; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 5
; to regenerate checks run following:
; $REPO/llvm/utils/update_pisa_test_checks.py --llc-binary $INSTALL/bin/llc ineg.ll
; RUN: llc < %s -march=pisa %disable_optional_optimizations -verify-machineinstrs | FileCheck --check-prefixes=CHECK,CHECK-LESS-OPT %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

define i1 @ineg_i1(i1 %arg0) {
; CHECK-LABEL: .16b @ineg_i1(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ineg.16b 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	and.16b 	[[R16_H2]], [[R16_H1]], 1;
; CHECK-NEXT: 	return [[R16_H2]];
;
; O0-LABEL: .16b @ineg_i1(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]];
; O0: 	ineg.16b 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	and.16b 	[[R16_H2]], [[R16_H1]], 1;
; O0-NEXT: 	return [[R16_H2]];
  %neg = sub i1 false, %arg0
  ret i1 %neg
}

define i8 @ineg_i8(i8 %arg0) {
; CHECK-LABEL: .8b @ineg_i8(
; CHECK-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .8b [[R8_B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	zext.16b.8b 	[[R16_H0]], [[R8_B0]];
; CHECK-NEXT: 	ineg.16b 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	trunc.8b.16b 	[[R8_B1]], [[R16_H1]];
; CHECK-NEXT: 	return [[R8_B1]];
;
; O0-LABEL: .8b @ineg_i8(
; O0-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .8b [[R8_B1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	zext.16b.8b 	[[R16_H0]], [[R8_B0]];
; O0-NEXT: 	ineg.16b 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B1]], [[R16_H1]];
; O0-NEXT: 	return [[R8_B1]];
  %neg = sub i8 0, %arg0
  ret i8 %neg
}

define i16 @ineg_i16(i16 %arg0) {
; CHECK-LABEL: .16b @ineg_i16(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ineg.16b 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	return [[R16_H1]];
;
; O0-LABEL: .16b @ineg_i16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	ineg.16b 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
  %neg = sub i16 0, %arg0
  ret i16 %neg
}

define i32 @ineg_i32(i32 %arg0) {
; CHECK-LABEL: .32b @ineg_i32(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ineg.32b 	[[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @ineg_i32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	ineg.32b 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	return [[R32_W1]];
  %neg = sub i32 0, %arg0
  ret i32 %neg
}

define i64 @ineg_i64(i64 %arg0) {
; CHECK-LABEL: .64b @ineg_i64(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ineg.64b 	[[R64_D1]], [[R64_D0]];
; CHECK-NEXT: 	return [[R64_D1]];
;
; O0-LABEL: .64b @ineg_i64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0: 	ineg.64b 	[[R64_D1]], [[R64_D0]];
; O0-NEXT: 	return [[R64_D1]];
  %neg = sub i64 0, %arg0
  ret i64 %neg
}

define <2 x i8> @ineg_v2i8(<2 x i8> %arg0) {
; CHECK-LABEL: .v2.8b @ineg_v2i8(
; CHECK-SAME: .reg .v2.8b [[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.8b [[VR2_8_V2B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; CHECK: 	zext.16b.8b 	[[R16_H0]], [[VR2_8_V2B0]].x;
; CHECK-NEXT: 	ineg.16b 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	trunc.8b.16b 	[[VR2_8_V2B1]].x, [[R16_H1]];
; CHECK-NEXT: 	zext.16b.8b 	[[R16_H2]], [[VR2_8_V2B0]].y;
; CHECK-NEXT: 	ineg.16b 	[[R16_H3]], [[R16_H2]];
; CHECK-NEXT: 	trunc.8b.16b 	[[VR2_8_V2B1]].y, [[R16_H3]];
; CHECK-NEXT: 	return [[VR2_8_V2B1]];
;
; O0-LABEL: .v2.8b @ineg_v2i8(
; O0-SAME: .reg .v2.8b [[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.8b [[VR2_8_V2B1:%[-a-zA-Z$._0-9]+]], [[VR2_8_V2B2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]], [[R8_B1:%[-a-zA-Z$._0-9]+]], [[R8_B2:%[-a-zA-Z$._0-9]+]], [[R8_B3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.8b 	[[R8_B0]], [[VR2_8_V2B0]].x;
; O0-NEXT: 	mov.8b 	[[R8_B1]], [[VR2_8_V2B0]].y;
; O0-NEXT: 	zext.16b.8b 	[[R16_H0]], [[R8_B0]];
; O0-NEXT: 	ineg.16b 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B2]], [[R16_H1]];
; O0-NEXT: 	zext.16b.8b 	[[R16_H2]], [[R8_B1]];
; O0-NEXT: 	ineg.16b 	[[R16_H3]], [[R16_H2]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B3]], [[R16_H3]];
; O0-NEXT: 	mov.8b 	[[VR2_8_V2B1]].x, [[R8_B2]];
; O0-NEXT: 	mov.16b 	[[VR2_8_V2B2]].xy, [[VR2_8_V2B1]].xy;
; O0-NEXT: 	mov.8b 	[[VR2_8_V2B2]].y, [[R8_B3]];
; O0-NEXT: 	return [[VR2_8_V2B2]];
  %neg = sub <2 x i8> zeroinitializer, %arg0
  ret <2 x i8> %neg
}

define <3 x i8> @ineg_v3i8(<3 x i8> %arg0) {
; CHECK-LABEL: .v3.8b @ineg_v3i8(
; CHECK-SAME: .reg .v3.8b [[VR3_8_V3B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v3.8b [[VR3_8_V3B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .16b %h<0~6>;
; CHECK: 	zext.16b.8b 	[[R16_H0:%[-a-zA-Z$._0-9]+]], [[VR3_8_V3B0]].x;
; CHECK-NEXT: 	ineg.16b 	[[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H0]];
; CHECK-NEXT: 	trunc.8b.16b 	[[VR3_8_V3B1]].x, [[R16_H1]];
; CHECK-NEXT: 	zext.16b.8b 	[[R16_H2:%[-a-zA-Z$._0-9]+]], [[VR3_8_V3B0]].y;
; CHECK-NEXT: 	ineg.16b 	[[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H2]];
; CHECK-NEXT: 	trunc.8b.16b 	[[VR3_8_V3B1]].y, [[R16_H3]];
; CHECK-NEXT: 	zext.16b.8b 	[[R16_H4:%[-a-zA-Z$._0-9]+]], [[VR3_8_V3B0]].z;
; CHECK-NEXT: 	ineg.16b 	[[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H4]];
; CHECK-NEXT: 	trunc.8b.16b 	[[VR3_8_V3B1]].z, [[R16_H5]];
; CHECK-NEXT: 	return [[VR3_8_V3B1]];
;
; O0-LABEL: .v3.8b @ineg_v3i8(
; O0-SAME: .reg .v3.8b [[VR3_8_V3B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.8b [[VR3_8_V3B1:%[-a-zA-Z$._0-9]+]], [[VR3_8_V3B2:%[-a-zA-Z$._0-9]+]], [[VR3_8_V3B3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .8b %b<0~6>;
; O0-NEXT: 	.reg .16b %h<0~6>;
; O0: 	mov.8b 	[[R8_B0:%[-a-zA-Z$._0-9]+]], [[VR3_8_V3B0]].x;
; O0-NEXT: 	mov.8b 	[[R8_B1:%[-a-zA-Z$._0-9]+]], [[VR3_8_V3B0]].y;
; O0-NEXT: 	mov.8b 	[[R8_B2:%[-a-zA-Z$._0-9]+]], [[VR3_8_V3B0]].z;
; O0-NEXT: 	zext.16b.8b 	[[R16_H0:%[-a-zA-Z$._0-9]+]], [[R8_B0]];
; O0-NEXT: 	ineg.16b 	[[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H0]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B3:%[-a-zA-Z$._0-9]+]], [[R16_H1]];
; O0-NEXT: 	zext.16b.8b 	[[R16_H2:%[-a-zA-Z$._0-9]+]], [[R8_B1]];
; O0-NEXT: 	ineg.16b 	[[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H2]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B4:%[-a-zA-Z$._0-9]+]], [[R16_H3]];
; O0-NEXT: 	zext.16b.8b 	[[R16_H4:%[-a-zA-Z$._0-9]+]], [[R8_B2]];
; O0-NEXT: 	ineg.16b 	[[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H4]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B5:%[-a-zA-Z$._0-9]+]], [[R16_H5]];
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B1]].x, [[R8_B3]];
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B2]].x, [[VR3_8_V3B1]].x;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B2]].y, [[VR3_8_V3B1]].y;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B2]].z, [[VR3_8_V3B1]].z;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B2]].y, [[R8_B4]];
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B3]].x, [[VR3_8_V3B2]].x;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B3]].y, [[VR3_8_V3B2]].y;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B3]].z, [[VR3_8_V3B2]].z;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B3]].z, [[R8_B5]];
; O0-NEXT: 	return [[VR3_8_V3B3]];
  %neg = sub <3 x i8> zeroinitializer, %arg0
  ret <3 x i8> %neg
}

define <4 x i8> @ineg_v4i8(<4 x i8> %arg0) {
; CHECK-LABEL: .v4.8b @ineg_v4i8(
; CHECK-SAME: .reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.8b [[VR4_8_V4B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .16b %h<0~8>;
; CHECK: 	zext.16b.8b 	[[R16_H0:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B0]].x;
; CHECK-NEXT: 	ineg.16b 	[[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H0]];
; CHECK-NEXT: 	trunc.8b.16b 	[[VR4_8_V4B1]].x, [[R16_H1]];
; CHECK-NEXT: 	zext.16b.8b 	[[R16_H2:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B0]].y;
; CHECK-NEXT: 	ineg.16b 	[[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H2]];
; CHECK-NEXT: 	trunc.8b.16b 	[[VR4_8_V4B1]].y, [[R16_H3]];
; CHECK-NEXT: 	zext.16b.8b 	[[R16_H4:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B0]].z;
; CHECK-NEXT: 	ineg.16b 	[[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H4]];
; CHECK-NEXT: 	trunc.8b.16b 	[[VR4_8_V4B1]].z, [[R16_H5]];
; CHECK-NEXT: 	zext.16b.8b 	[[R16_H6:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B0]].w;
; CHECK-NEXT: 	ineg.16b 	[[R16_H7:%[-a-zA-Z$._0-9]+]], [[R16_H6]];
; CHECK-NEXT: 	trunc.8b.16b 	[[VR4_8_V4B1]].w, [[R16_H7]];
; CHECK-NEXT: 	return [[VR4_8_V4B1]];
;
; O0-LABEL: .v4.8b @ineg_v4i8(
; O0-SAME: .reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.8b [[VR4_8_V4B1:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B2:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B3:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .8b %b<0~8>;
; O0-NEXT: 	.reg .16b %h<0~8>;
; O0: 	mov.8b 	[[R8_B0:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B0]].x;
; O0-NEXT: 	mov.8b 	[[R8_B1:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B0]].y;
; O0-NEXT: 	mov.8b 	[[R8_B2:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B0]].z;
; O0-NEXT: 	mov.8b 	[[R8_B3:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B0]].w;
; O0-NEXT: 	zext.16b.8b 	[[R16_H0:%[-a-zA-Z$._0-9]+]], [[R8_B0]];
; O0-NEXT: 	ineg.16b 	[[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H0]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B4:%[-a-zA-Z$._0-9]+]], [[R16_H1]];
; O0-NEXT: 	zext.16b.8b 	[[R16_H2:%[-a-zA-Z$._0-9]+]], [[R8_B1]];
; O0-NEXT: 	ineg.16b 	[[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H2]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B5:%[-a-zA-Z$._0-9]+]], [[R16_H3]];
; O0-NEXT: 	zext.16b.8b 	[[R16_H4:%[-a-zA-Z$._0-9]+]], [[R8_B2]];
; O0-NEXT: 	ineg.16b 	[[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H4]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B6:%[-a-zA-Z$._0-9]+]], [[R16_H5]];
; O0-NEXT: 	zext.16b.8b 	[[R16_H6:%[-a-zA-Z$._0-9]+]], [[R8_B3]];
; O0-NEXT: 	ineg.16b 	[[R16_H7:%[-a-zA-Z$._0-9]+]], [[R16_H6]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B7:%[-a-zA-Z$._0-9]+]], [[R16_H7]];
; O0-NEXT: 	mov.8b 	[[VR4_8_V4B1]].x, [[R8_B4]];
; O0-NEXT: 	mov.32b 	[[VR4_8_V4B2]].xyzw, [[VR4_8_V4B1]].xyzw;
; O0-NEXT: 	mov.8b 	[[VR4_8_V4B2]].y, [[R8_B5]];
; O0-NEXT: 	mov.32b 	[[VR4_8_V4B3]].xyzw, [[VR4_8_V4B2]].xyzw;
; O0-NEXT: 	mov.8b 	[[VR4_8_V4B3]].z, [[R8_B6]];
; O0-NEXT: 	mov.32b 	[[VR4_8_V4B4]].xyzw, [[VR4_8_V4B3]].xyzw;
; O0-NEXT: 	mov.8b 	[[VR4_8_V4B4]].w, [[R8_B7]];
; O0-NEXT: 	return [[VR4_8_V4B4]];
  %neg = sub <4 x i8> zeroinitializer, %arg0
  ret <4 x i8> %neg
}

define <2 x i16> @ineg_v2i16(<2 x i16> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v2.16b @ineg_v2i16(
; CHECK-LESS-OPT-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	ineg.16b 	[[VR2_16_V2H1]].x, [[VR2_16_V2H0]].x;
; CHECK-LESS-OPT-NEXT: 	ineg.16b 	[[VR2_16_V2H1]].y, [[VR2_16_V2H0]].y;
; CHECK-LESS-OPT-NEXT: 	return [[VR2_16_V2H1]];
;
; O0-LABEL: .v2.16b @ineg_v2i16(
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.16b 	[[R16_H0]], [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	[[R16_H1]], [[VR2_16_V2H0]].y;
; O0-NEXT: 	ineg.16b 	[[R16_H2]], [[R16_H0]];
; O0-NEXT: 	ineg.16b 	[[R16_H3]], [[R16_H1]];
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H1]].x, [[R16_H2]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H2]].xy, [[VR2_16_V2H1]].xy;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H2]].y, [[R16_H3]];
; O0-NEXT: 	return [[VR2_16_V2H2]];
  %neg = sub <2 x i16> zeroinitializer, %arg0
  ret <2 x i16> %neg
}

define <3 x i16> @ineg_v3i16(<3 x i16> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v3.16b @ineg_v3i16(
; CHECK-LESS-OPT-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	ineg.16b 	[[VR3_16_V3H1]].x, [[VR3_16_V3H0]].x;
; CHECK-LESS-OPT-NEXT: 	ineg.16b 	[[VR3_16_V3H1]].y, [[VR3_16_V3H0]].y;
; CHECK-LESS-OPT-NEXT: 	ineg.16b 	[[VR3_16_V3H1]].z, [[VR3_16_V3H0]].z;
; CHECK-LESS-OPT-NEXT: 	return [[VR3_16_V3H1]];
;
; O0-LABEL: .v3.16b @ineg_v3i16(
; O0-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H2:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~6>;
; O0: 	mov.16b 	[[R16_H0:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H0]].x;
; O0-NEXT: 	mov.16b 	[[R16_H1:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H0]].y;
; O0-NEXT: 	mov.16b 	[[R16_H2:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H0]].z;
; O0-NEXT: 	ineg.16b 	[[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H0]];
; O0-NEXT: 	ineg.16b 	[[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H1]];
; O0-NEXT: 	ineg.16b 	[[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H2]];
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H1]].x, [[R16_H3]];
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].x, [[VR3_16_V3H1]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, [[VR3_16_V3H1]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].z, [[VR3_16_V3H1]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, [[R16_H4]];
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].x, [[VR3_16_V3H2]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].y, [[VR3_16_V3H2]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, [[VR3_16_V3H2]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, [[R16_H5]];
; O0-NEXT: 	return [[VR3_16_V3H3]];
  %neg = sub <3 x i16> zeroinitializer, %arg0
  ret <3 x i16> %neg
}

define <4 x i16> @ineg_v4i16(<4 x i16> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v4.16b @ineg_v4i16(
; CHECK-LESS-OPT-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	ineg.16b 	[[VR4_16_V4H1]].x, [[VR4_16_V4H0]].x;
; CHECK-LESS-OPT-NEXT: 	ineg.16b 	[[VR4_16_V4H1]].y, [[VR4_16_V4H0]].y;
; CHECK-LESS-OPT-NEXT: 	ineg.16b 	[[VR4_16_V4H1]].z, [[VR4_16_V4H0]].z;
; CHECK-LESS-OPT-NEXT: 	ineg.16b 	[[VR4_16_V4H1]].w, [[VR4_16_V4H0]].w;
; CHECK-LESS-OPT-NEXT: 	return [[VR4_16_V4H1]];
;
; O0-LABEL: .v4.16b @ineg_v4i16(
; O0-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H2:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H3:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~8>;
; O0: 	mov.16b 	[[R16_H0:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	[[R16_H1:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	[[R16_H2:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	[[R16_H3:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H0]].w;
; O0-NEXT: 	ineg.16b 	[[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H0]];
; O0-NEXT: 	ineg.16b 	[[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H1]];
; O0-NEXT: 	ineg.16b 	[[R16_H6:%[-a-zA-Z$._0-9]+]], [[R16_H2]];
; O0-NEXT: 	ineg.16b 	[[R16_H7:%[-a-zA-Z$._0-9]+]], [[R16_H3]];
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H1]].x, [[R16_H4]];
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H2]].xyzw, [[VR4_16_V4H1]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H2]].y, [[R16_H5]];
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H3]].xyzw, [[VR4_16_V4H2]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H3]].z, [[R16_H6]];
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H4]].xyzw, [[VR4_16_V4H3]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H4]].w, [[R16_H7]];
; O0-NEXT: 	return [[VR4_16_V4H4]];
  %neg = sub <4 x i16> zeroinitializer, %arg0
  ret <4 x i16> %neg
}

define <2 x i32> @ineg_v2i32(<2 x i32> %arg0) {
; CHECK-LABEL: .v2.32b @ineg_v2i32(
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ineg.32b 	[[VR2_32_V2W1]].x, [[VR2_32_V2W0]].x;
; CHECK-NEXT: 	ineg.32b 	[[VR2_32_V2W1]].y, [[VR2_32_V2W0]].y;
; CHECK-NEXT: 	return [[VR2_32_V2W1]];
;
; O0-LABEL: .v2.32b @ineg_v2i32(
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.32b 	[[R32_W0]], [[VR2_32_V2W0]].x;
; O0-NEXT: 	mov.32b 	[[R32_W1]], [[VR2_32_V2W0]].y;
; O0-NEXT: 	ineg.32b 	[[R32_W2]], [[R32_W0]];
; O0-NEXT: 	ineg.32b 	[[R32_W3]], [[R32_W1]];
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W1]].x, [[R32_W2]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W2]].xy, [[VR2_32_V2W1]].xy;
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W2]].y, [[R32_W3]];
; O0-NEXT: 	return [[VR2_32_V2W2]];
  %neg = sub <2 x i32> zeroinitializer, %arg0
  ret <2 x i32> %neg
}

define <3 x i32> @ineg_v3i32(<3 x i32> %arg0) {
; CHECK-LABEL: .v3.32b @ineg_v3i32(
; CHECK-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v3.32b [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ineg.32b 	[[VR3_32_V3W1]].x, [[VR3_32_V3W0]].x;
; CHECK-NEXT: 	ineg.32b 	[[VR3_32_V3W1]].y, [[VR3_32_V3W0]].y;
; CHECK-NEXT: 	ineg.32b 	[[VR3_32_V3W1]].z, [[VR3_32_V3W0]].z;
; CHECK-NEXT: 	return [[VR3_32_V3W1]];
;
; O0-LABEL: .v3.32b @ineg_v3i32(
; O0-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.32b [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W2:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~6>;
; O0: 	mov.32b 	[[R32_W0:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W0]].x;
; O0-NEXT: 	mov.32b 	[[R32_W1:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W0]].y;
; O0-NEXT: 	mov.32b 	[[R32_W2:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W0]].z;
; O0-NEXT: 	ineg.32b 	[[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W0]];
; O0-NEXT: 	ineg.32b 	[[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W1]];
; O0-NEXT: 	ineg.32b 	[[R32_W5:%[-a-zA-Z$._0-9]+]], [[R32_W2]];
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W1]].x, [[R32_W3]];
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].x, [[VR3_32_V3W1]].x;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].y, [[VR3_32_V3W1]].y;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].z, [[VR3_32_V3W1]].z;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].y, [[R32_W4]];
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].x, [[VR3_32_V3W2]].x;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].y, [[VR3_32_V3W2]].y;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].z, [[VR3_32_V3W2]].z;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].z, [[R32_W5]];
; O0-NEXT: 	return [[VR3_32_V3W3]];
  %neg = sub <3 x i32> zeroinitializer, %arg0
  ret <3 x i32> %neg
}

define <4 x i32> @ineg_v4i32(<4 x i32> %arg0) {
; CHECK-LABEL: .v4.32b @ineg_v4i32(
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.32b [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ineg.32b 	[[VR4_32_V4W1]].x, [[VR4_32_V4W0]].x;
; CHECK-NEXT: 	ineg.32b 	[[VR4_32_V4W1]].y, [[VR4_32_V4W0]].y;
; CHECK-NEXT: 	ineg.32b 	[[VR4_32_V4W1]].z, [[VR4_32_V4W0]].z;
; CHECK-NEXT: 	ineg.32b 	[[VR4_32_V4W1]].w, [[VR4_32_V4W0]].w;
; CHECK-NEXT: 	return [[VR4_32_V4W1]];
;
; O0-LABEL: .v4.32b @ineg_v4i32(
; O0-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.32b [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W2:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W3:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~8>;
; O0: 	mov.32b 	[[R32_W0:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W0]].x;
; O0-NEXT: 	mov.32b 	[[R32_W1:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W0]].y;
; O0-NEXT: 	mov.32b 	[[R32_W2:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W0]].z;
; O0-NEXT: 	mov.32b 	[[R32_W3:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W0]].w;
; O0-NEXT: 	ineg.32b 	[[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W0]];
; O0-NEXT: 	ineg.32b 	[[R32_W5:%[-a-zA-Z$._0-9]+]], [[R32_W1]];
; O0-NEXT: 	ineg.32b 	[[R32_W6:%[-a-zA-Z$._0-9]+]], [[R32_W2]];
; O0-NEXT: 	ineg.32b 	[[R32_W7:%[-a-zA-Z$._0-9]+]], [[R32_W3]];
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W1]].x, [[R32_W4]];
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W2]].xyzw, [[VR4_32_V4W1]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W2]].y, [[R32_W5]];
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W3]].xyzw, [[VR4_32_V4W2]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W3]].z, [[R32_W6]];
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W4]].xyzw, [[VR4_32_V4W3]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W4]].w, [[R32_W7]];
; O0-NEXT: 	return [[VR4_32_V4W4]];
  %neg = sub <4 x i32> zeroinitializer, %arg0
  ret <4 x i32> %neg
}

define <2 x i64> @ineg_v2i64(<2 x i64> %arg0) {
; CHECK-LABEL: .v2.64b @ineg_v2i64(
; CHECK-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ineg.64b 	[[VR2_64_V2D1]].x, [[VR2_64_V2D0]].x;
; CHECK-NEXT: 	ineg.64b 	[[VR2_64_V2D1]].y, [[VR2_64_V2D0]].y;
; CHECK-NEXT: 	return [[VR2_64_V2D1]];
;
; O0-LABEL: .v2.64b @ineg_v2i64(
; O0-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]], [[VR2_64_V2D2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]], [[R64_D1:%[-a-zA-Z$._0-9]+]], [[R64_D2:%[-a-zA-Z$._0-9]+]], [[R64_D3:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.64b 	[[R64_D0]], [[VR2_64_V2D0]].x;
; O0-NEXT: 	mov.64b 	[[R64_D1]], [[VR2_64_V2D0]].y;
; O0-NEXT: 	ineg.64b 	[[R64_D2]], [[R64_D0]];
; O0-NEXT: 	ineg.64b 	[[R64_D3]], [[R64_D1]];
; O0-NEXT: 	mov.64b 	[[VR2_64_V2D1]].x, [[R64_D2]];
; O0-NEXT: 	mov.128b 	[[VR2_64_V2D2]].xy, [[VR2_64_V2D1]].xy;
; O0-NEXT: 	mov.64b 	[[VR2_64_V2D2]].y, [[R64_D3]];
; O0-NEXT: 	return [[VR2_64_V2D2]];
  %neg = sub <2 x i64> zeroinitializer, %arg0
  ret <2 x i64> %neg
}

define <3 x i64> @ineg_v3i64(<3 x i64> %arg0) {
; CHECK-LABEL: .v3.64b @ineg_v3i64(
; CHECK-SAME: .reg .v3.64b [[VR3_64_V3D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v3.64b [[VR3_64_V3D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ineg.64b 	[[VR3_64_V3D1]].x, [[VR3_64_V3D0]].x;
; CHECK-NEXT: 	ineg.64b 	[[VR3_64_V3D1]].y, [[VR3_64_V3D0]].y;
; CHECK-NEXT: 	ineg.64b 	[[VR3_64_V3D1]].z, [[VR3_64_V3D0]].z;
; CHECK-NEXT: 	return [[VR3_64_V3D1]];
;
; O0-LABEL: .v3.64b @ineg_v3i64(
; O0-SAME: .reg .v3.64b [[VR3_64_V3D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.64b [[VR3_64_V3D1:%[-a-zA-Z$._0-9]+]], [[VR3_64_V3D2:%[-a-zA-Z$._0-9]+]], [[VR3_64_V3D3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b %d<0~6>;
; O0: 	mov.64b 	[[R64_D0:%[-a-zA-Z$._0-9]+]], [[VR3_64_V3D0]].x;
; O0-NEXT: 	mov.64b 	[[R64_D1:%[-a-zA-Z$._0-9]+]], [[VR3_64_V3D0]].y;
; O0-NEXT: 	mov.64b 	[[R64_D2:%[-a-zA-Z$._0-9]+]], [[VR3_64_V3D0]].z;
; O0-NEXT: 	ineg.64b 	[[R64_D3:%[-a-zA-Z$._0-9]+]], [[R64_D0]];
; O0-NEXT: 	ineg.64b 	[[R64_D4:%[-a-zA-Z$._0-9]+]], [[R64_D1]];
; O0-NEXT: 	ineg.64b 	[[R64_D5:%[-a-zA-Z$._0-9]+]], [[R64_D2]];
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D1]].x, [[R64_D3]];
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D2]].x, [[VR3_64_V3D1]].x;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D2]].y, [[VR3_64_V3D1]].y;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D2]].z, [[VR3_64_V3D1]].z;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D2]].y, [[R64_D4]];
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D3]].x, [[VR3_64_V3D2]].x;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D3]].y, [[VR3_64_V3D2]].y;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D3]].z, [[VR3_64_V3D2]].z;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D3]].z, [[R64_D5]];
; O0-NEXT: 	return [[VR3_64_V3D3]];
  %neg = sub <3 x i64> zeroinitializer, %arg0
  ret <3 x i64> %neg
}

define <4 x i64> @ineg_v4i64(<4 x i64> %arg0) {
; CHECK-LABEL: .v4.64b @ineg_v4i64(
; CHECK-SAME: .reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.64b [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ineg.64b 	[[VR4_64_V4D1]].x, [[VR4_64_V4D0]].x;
; CHECK-NEXT: 	ineg.64b 	[[VR4_64_V4D1]].y, [[VR4_64_V4D0]].y;
; CHECK-NEXT: 	ineg.64b 	[[VR4_64_V4D1]].z, [[VR4_64_V4D0]].z;
; CHECK-NEXT: 	ineg.64b 	[[VR4_64_V4D1]].w, [[VR4_64_V4D0]].w;
; CHECK-NEXT: 	return [[VR4_64_V4D1]];
;
; O0-LABEL: .v4.64b @ineg_v4i64(
; O0-SAME: .reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.64b [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D2:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D3:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b %d<0~8>;
; O0: 	mov.64b 	[[R64_D0:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].x;
; O0-NEXT: 	mov.64b 	[[R64_D1:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].y;
; O0-NEXT: 	mov.64b 	[[R64_D2:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].z;
; O0-NEXT: 	mov.64b 	[[R64_D3:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].w;
; O0-NEXT: 	ineg.64b 	[[R64_D4:%[-a-zA-Z$._0-9]+]], [[R64_D0]];
; O0-NEXT: 	ineg.64b 	[[R64_D5:%[-a-zA-Z$._0-9]+]], [[R64_D1]];
; O0-NEXT: 	ineg.64b 	[[R64_D6:%[-a-zA-Z$._0-9]+]], [[R64_D2]];
; O0-NEXT: 	ineg.64b 	[[R64_D7:%[-a-zA-Z$._0-9]+]], [[R64_D3]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D1]].x, [[R64_D4]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].x, [[VR4_64_V4D1]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].y, [[VR4_64_V4D1]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].z, [[VR4_64_V4D1]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].w, [[VR4_64_V4D1]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].y, [[R64_D5]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].x, [[VR4_64_V4D2]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].y, [[VR4_64_V4D2]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].z, [[VR4_64_V4D2]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].w, [[VR4_64_V4D2]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].z, [[R64_D6]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].x, [[VR4_64_V4D3]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].y, [[VR4_64_V4D3]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].z, [[VR4_64_V4D3]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].w, [[VR4_64_V4D3]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].w, [[R64_D7]];
; O0-NEXT: 	return [[VR4_64_V4D4]];
  %neg = sub <4 x i64> zeroinitializer, %arg0
  ret <4 x i64> %neg
}
