; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; to regenerate checks run following:
; $REPO/llvm/utils/update_pisa_test_checks.py --llc-binary $INSTALL/bin/llc llvm.pisa.frsqrt.ll
; RUN: llc < %s -march=pisa %disable_optional_optimizations -verify-machineinstrs | FileCheck --check-prefixes=CHECK,CHECK-LESS-OPT %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

; Function Attrs: nounwind memory(none)
declare half @llvm.pisa.frsqrt.f16(half) #0

define half @pisa.frsqrt.llvm.pisa.frsqrt_half(half %arg0) {
; CHECK-LABEL: .16b @pisa.frsqrt.llvm.pisa.frsqrt_half(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.hf 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	return [[R16_H1]];
;
; O0-LABEL: .16b @pisa.frsqrt.llvm.pisa.frsqrt_half(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	frsqrt.fast.hf 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
  %call = call half @llvm.pisa.frsqrt.f16(half %arg0)
  ret half %call
}

; Function Attrs: nounwind memory(none)
declare bfloat @llvm.pisa.frsqrt.bf16(bfloat) #0

define bfloat @pisa.frsqrt.llvm.pisa.frsqrt_bfloat(bfloat %arg0) {
; CHECK-LABEL: .16b @pisa.frsqrt.llvm.pisa.frsqrt_bfloat(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.bf 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	return [[R16_H1]];
;
; O0-LABEL: .16b @pisa.frsqrt.llvm.pisa.frsqrt_bfloat(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	frsqrt.fast.bf 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
  %call = call bfloat @llvm.pisa.frsqrt.bf16(bfloat %arg0)
  ret bfloat %call
}

; Function Attrs: nounwind memory(none)
declare <2 x half> @llvm.pisa.frsqrt.v2f16(<2 x half>) #0

define <2 x half> @pisa.frsqrt.llvm.pisa.frsqrt_v2half(<2 x half> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v2.16b @pisa.frsqrt.llvm.pisa.frsqrt_v2half(
; CHECK-LESS-OPT-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	frsqrt.fast.hf 	[[VR2_16_V2H1]].x, [[VR2_16_V2H0]].x;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.hf 	[[VR2_16_V2H1]].y, [[VR2_16_V2H0]].y;
; CHECK-LESS-OPT-NEXT: 	return [[VR2_16_V2H1]];
;
; O0-LABEL: .v2.16b @pisa.frsqrt.llvm.pisa.frsqrt_v2half(
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~6>;
; O0: 	mov.16b 	%h0, [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR2_16_V2H0]].y;
; O0-NEXT: 	frsqrt.fast.hf 	%h2, %h0;
; O0-NEXT: 	mov.16b 	%h3, [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	%h4, [[VR2_16_V2H0]].y;
; O0-NEXT: 	frsqrt.fast.hf 	%h5, %h4;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H1]].x, %h2;
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H2]].xy, [[VR2_16_V2H1]].xy;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H2]].y, %h5;
; O0-NEXT: 	return [[VR2_16_V2H2]];
  %call = call <2 x half> @llvm.pisa.frsqrt.v2f16(<2 x half> %arg0)
  ret <2 x half> %call
}

; Function Attrs: nounwind memory(none)
declare <3 x half> @llvm.pisa.frsqrt.v3f16(<3 x half>) #0

define <3 x half> @pisa.frsqrt.llvm.pisa.frsqrt_v3half(<3 x half> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v3.16b @pisa.frsqrt.llvm.pisa.frsqrt_v3half(
; CHECK-LESS-OPT-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	frsqrt.fast.hf 	[[VR3_16_V3H1]].x, [[VR3_16_V3H0]].x;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.hf 	[[VR3_16_V3H1]].y, [[VR3_16_V3H0]].y;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.hf 	[[VR3_16_V3H1]].z, [[VR3_16_V3H0]].z;
; CHECK-LESS-OPT-NEXT: 	return [[VR3_16_V3H1]];
;
; O0-LABEL: .v3.16b @pisa.frsqrt.llvm.pisa.frsqrt_v3half(
; O0-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H2:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~12>;
; O0: 	mov.16b 	%h0, [[VR3_16_V3H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR3_16_V3H0]].y;
; O0-NEXT: 	mov.16b 	%h2, [[VR3_16_V3H0]].z;
; O0-NEXT: 	frsqrt.fast.hf 	%h3, %h0;
; O0-NEXT: 	mov.16b 	%h4, [[VR3_16_V3H0]].x;
; O0-NEXT: 	mov.16b 	%h5, [[VR3_16_V3H0]].y;
; O0-NEXT: 	mov.16b 	%h6, [[VR3_16_V3H0]].z;
; O0-NEXT: 	frsqrt.fast.hf 	%h7, %h5;
; O0-NEXT: 	mov.16b 	%h8, [[VR3_16_V3H0]].x;
; O0-NEXT: 	mov.16b 	%h9, [[VR3_16_V3H0]].y;
; O0-NEXT: 	mov.16b 	%h10, [[VR3_16_V3H0]].z;
; O0-NEXT: 	frsqrt.fast.hf 	%h11, %h10;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H1]].x, %h3;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].x, [[VR3_16_V3H1]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, [[VR3_16_V3H1]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].z, [[VR3_16_V3H1]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, %h7;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].x, [[VR3_16_V3H2]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].y, [[VR3_16_V3H2]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, [[VR3_16_V3H2]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, %h11;
; O0-NEXT: 	return [[VR3_16_V3H3]];
  %call = call <3 x half> @llvm.pisa.frsqrt.v3f16(<3 x half> %arg0)
  ret <3 x half> %call
}

; Function Attrs: nounwind memory(none)
declare <4 x half> @llvm.pisa.frsqrt.v4f16(<4 x half>) #0

define <4 x half> @pisa.frsqrt.llvm.pisa.frsqrt_v4half(<4 x half> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v4.16b @pisa.frsqrt.llvm.pisa.frsqrt_v4half(
; CHECK-LESS-OPT-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	frsqrt.fast.hf 	[[VR4_16_V4H1]].x, [[VR4_16_V4H0]].x;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.hf 	[[VR4_16_V4H1]].y, [[VR4_16_V4H0]].y;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.hf 	[[VR4_16_V4H1]].z, [[VR4_16_V4H0]].z;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.hf 	[[VR4_16_V4H1]].w, [[VR4_16_V4H0]].w;
; CHECK-LESS-OPT-NEXT: 	return [[VR4_16_V4H1]];
;
; O0-LABEL: .v4.16b @pisa.frsqrt.llvm.pisa.frsqrt_v4half(
; O0-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H2:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H3:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~20>;
; O0: 	mov.16b 	%h0, [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	%h2, [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	%h3, [[VR4_16_V4H0]].w;
; O0-NEXT: 	frsqrt.fast.hf 	%h4, %h0;
; O0-NEXT: 	mov.16b 	%h5, [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	%h6, [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	%h7, [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	%h8, [[VR4_16_V4H0]].w;
; O0-NEXT: 	frsqrt.fast.hf 	%h9, %h6;
; O0-NEXT: 	mov.16b 	%h10, [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	%h11, [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	%h12, [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	%h13, [[VR4_16_V4H0]].w;
; O0-NEXT: 	frsqrt.fast.hf 	%h14, %h12;
; O0-NEXT: 	mov.16b 	%h15, [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	%h16, [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	%h17, [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	%h18, [[VR4_16_V4H0]].w;
; O0-NEXT: 	frsqrt.fast.hf 	%h19, %h18;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H1]].x, %h4;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H2]].xyzw, [[VR4_16_V4H1]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H2]].y, %h9;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H3]].xyzw, [[VR4_16_V4H2]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H3]].z, %h14;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H4]].xyzw, [[VR4_16_V4H3]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H4]].w, %h19;
; O0-NEXT: 	return [[VR4_16_V4H4]];
  %call = call <4 x half> @llvm.pisa.frsqrt.v4f16(<4 x half> %arg0)
  ret <4 x half> %call
}

; Function Attrs: nounwind memory(none)
declare <2 x bfloat> @llvm.pisa.frsqrt.v2bf16(<2 x bfloat>) #0

define <2 x bfloat> @pisa.frsqrt.llvm.pisa.frsqrt_v2bfloat(<2 x bfloat> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v2.16b @pisa.frsqrt.llvm.pisa.frsqrt_v2bfloat(
; CHECK-LESS-OPT-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	frsqrt.fast.bf 	[[VR2_16_V2H1]].x, [[VR2_16_V2H0]].x;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.bf 	[[VR2_16_V2H1]].y, [[VR2_16_V2H0]].y;
; CHECK-LESS-OPT-NEXT: 	return [[VR2_16_V2H1]];
;
; O0-LABEL: .v2.16b @pisa.frsqrt.llvm.pisa.frsqrt_v2bfloat(
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~6>;
; O0: 	mov.16b 	%h0, [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR2_16_V2H0]].y;
; O0-NEXT: 	frsqrt.fast.bf 	%h2, %h0;
; O0-NEXT: 	mov.16b 	%h3, [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	%h4, [[VR2_16_V2H0]].y;
; O0-NEXT: 	frsqrt.fast.bf 	%h5, %h4;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H1]].x, %h2;
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H2]].xy, [[VR2_16_V2H1]].xy;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H2]].y, %h5;
; O0-NEXT: 	return [[VR2_16_V2H2]];
  %call = call <2 x bfloat> @llvm.pisa.frsqrt.v2bf16(<2 x bfloat> %arg0)
  ret <2 x bfloat> %call
}

; Function Attrs: nounwind memory(none)
declare <3 x bfloat> @llvm.pisa.frsqrt.v3bf16(<3 x bfloat>) #0

define <3 x bfloat> @pisa.frsqrt.llvm.pisa.frsqrt_v3bfloat(<3 x bfloat> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v3.16b @pisa.frsqrt.llvm.pisa.frsqrt_v3bfloat(
; CHECK-LESS-OPT-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	frsqrt.fast.bf 	[[VR3_16_V3H1]].x, [[VR3_16_V3H0]].x;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.bf 	[[VR3_16_V3H1]].y, [[VR3_16_V3H0]].y;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.bf 	[[VR3_16_V3H1]].z, [[VR3_16_V3H0]].z;
; CHECK-LESS-OPT-NEXT: 	return [[VR3_16_V3H1]];
;
; O0-LABEL: .v3.16b @pisa.frsqrt.llvm.pisa.frsqrt_v3bfloat(
; O0-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H2:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~12>;
; O0: 	mov.16b 	%h0, [[VR3_16_V3H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR3_16_V3H0]].y;
; O0-NEXT: 	mov.16b 	%h2, [[VR3_16_V3H0]].z;
; O0-NEXT: 	frsqrt.fast.bf 	%h3, %h0;
; O0-NEXT: 	mov.16b 	%h4, [[VR3_16_V3H0]].x;
; O0-NEXT: 	mov.16b 	%h5, [[VR3_16_V3H0]].y;
; O0-NEXT: 	mov.16b 	%h6, [[VR3_16_V3H0]].z;
; O0-NEXT: 	frsqrt.fast.bf 	%h7, %h5;
; O0-NEXT: 	mov.16b 	%h8, [[VR3_16_V3H0]].x;
; O0-NEXT: 	mov.16b 	%h9, [[VR3_16_V3H0]].y;
; O0-NEXT: 	mov.16b 	%h10, [[VR3_16_V3H0]].z;
; O0-NEXT: 	frsqrt.fast.bf 	%h11, %h10;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H1]].x, %h3;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].x, [[VR3_16_V3H1]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, [[VR3_16_V3H1]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].z, [[VR3_16_V3H1]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, %h7;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].x, [[VR3_16_V3H2]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].y, [[VR3_16_V3H2]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, [[VR3_16_V3H2]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, %h11;
; O0-NEXT: 	return [[VR3_16_V3H3]];
  %call = call <3 x bfloat> @llvm.pisa.frsqrt.v3bf16(<3 x bfloat> %arg0)
  ret <3 x bfloat> %call
}

; Function Attrs: nounwind memory(none)
declare <4 x bfloat> @llvm.pisa.frsqrt.v4bf16(<4 x bfloat>) #0

define <4 x bfloat> @pisa.frsqrt.llvm.pisa.frsqrt_v4bfloat(<4 x bfloat> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v4.16b @pisa.frsqrt.llvm.pisa.frsqrt_v4bfloat(
; CHECK-LESS-OPT-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	frsqrt.fast.bf 	[[VR4_16_V4H1]].x, [[VR4_16_V4H0]].x;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.bf 	[[VR4_16_V4H1]].y, [[VR4_16_V4H0]].y;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.bf 	[[VR4_16_V4H1]].z, [[VR4_16_V4H0]].z;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.bf 	[[VR4_16_V4H1]].w, [[VR4_16_V4H0]].w;
; CHECK-LESS-OPT-NEXT: 	return [[VR4_16_V4H1]];
;
; O0-LABEL: .v4.16b @pisa.frsqrt.llvm.pisa.frsqrt_v4bfloat(
; O0-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H2:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H3:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~20>;
; O0: 	mov.16b 	%h0, [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	%h2, [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	%h3, [[VR4_16_V4H0]].w;
; O0-NEXT: 	frsqrt.fast.bf 	%h4, %h0;
; O0-NEXT: 	mov.16b 	%h5, [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	%h6, [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	%h7, [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	%h8, [[VR4_16_V4H0]].w;
; O0-NEXT: 	frsqrt.fast.bf 	%h9, %h6;
; O0-NEXT: 	mov.16b 	%h10, [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	%h11, [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	%h12, [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	%h13, [[VR4_16_V4H0]].w;
; O0-NEXT: 	frsqrt.fast.bf 	%h14, %h12;
; O0-NEXT: 	mov.16b 	%h15, [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	%h16, [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	%h17, [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	%h18, [[VR4_16_V4H0]].w;
; O0-NEXT: 	frsqrt.fast.bf 	%h19, %h18;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H1]].x, %h4;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H2]].xyzw, [[VR4_16_V4H1]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H2]].y, %h9;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H3]].xyzw, [[VR4_16_V4H2]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H3]].z, %h14;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H4]].xyzw, [[VR4_16_V4H3]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H4]].w, %h19;
; O0-NEXT: 	return [[VR4_16_V4H4]];
  %call = call <4 x bfloat> @llvm.pisa.frsqrt.v4bf16(<4 x bfloat> %arg0)
  ret <4 x bfloat> %call
}

attributes #0 = { nounwind memory(none) }
