; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 5
; to regenerate checks run following:
; $REPO/llvm/utils/update_pisa_test_checks.py --llc-binary $INSTALL/bin/llc llvm.ctpop.ll
; RUN: llc < %s -march=pisa -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i8 @llvm.ctpop.i8(i8) #0

define i8 @ctpop.llvm.ctpop_i8(i8 %arg0) {
; CHECK-LABEL: .8b @ctpop.llvm.ctpop_i8(
; CHECK-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .8b [[R8_B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	zext.16b.8b 	[[R16_H0]], [[R8_B0]];
; CHECK-NEXT: 	cbit.16b 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	trunc.8b.16b 	[[R8_B1]], [[R16_H1]];
; CHECK-NEXT: 	return [[R8_B1]];
;
; O0-LABEL: .8b @ctpop.llvm.ctpop_i8(
; O0-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .8b [[R8_B1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	zext.16b.8b 	[[R16_H0]], [[R8_B0]];
; O0-NEXT: 	cbit.16b 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B1]], [[R16_H1]];
; O0-NEXT: 	return [[R8_B1]];
  %call = call i8 @llvm.ctpop.i8(i8 %arg0)
  ret i8 %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i16 @llvm.ctpop.i16(i16) #0

define i16 @ctpop.llvm.ctpop_i16(i16 %arg0) {
; CHECK-LABEL: .16b @ctpop.llvm.ctpop_i16(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	cbit.16b 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	return [[R16_H1]];
;
; O0-LABEL: .16b @ctpop.llvm.ctpop_i16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	cbit.16b 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
  %call = call i16 @llvm.ctpop.i16(i16 %arg0)
  ret i16 %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.ctpop.i32(i32) #0

define i32 @ctpop.llvm.ctpop_i32(i32 %arg0) {
; CHECK-LABEL: .32b @ctpop.llvm.ctpop_i32(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	cbit.32b 	[[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @ctpop.llvm.ctpop_i32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	cbit.32b 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	return [[R32_W1]];
  %call = call i32 @llvm.ctpop.i32(i32 %arg0)
  ret i32 %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i64 @llvm.ctpop.i64(i64) #0

define i64 @ctpop.llvm.ctpop_i64(i64 %arg0) {
; CHECK-LABEL: .64b @ctpop.llvm.ctpop_i64(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	mov.64b 	[[VR2_32_V2W0]].xy, [[R64_D0]];
; CHECK-NEXT: 	cbit.32b 	[[R32_W0]], [[VR2_32_V2W0]].x;
; CHECK-NEXT: 	cbit.32b 	[[R32_W1]], [[VR2_32_V2W0]].y;
; CHECK-NEXT: 	iadd.32b 	[[R32_W2]], [[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	zext.64b.32b 	[[R64_D1]], [[R32_W2]];
; CHECK-NEXT: 	return [[R64_D1]];
;
; O0-LABEL: .64b @ctpop.llvm.ctpop_i64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.64b 	[[VR2_32_V2W0]].xy, [[R64_D0]];
; O0-NEXT: 	mov.32b 	[[R32_W0]], [[VR2_32_V2W0]].x;
; O0-NEXT: 	mov.32b 	[[R32_W1]], [[VR2_32_V2W0]].y;
; O0-NEXT: 	cbit.32b 	[[R32_W2]], [[R32_W0]];
; O0-NEXT: 	cbit.32b 	[[R32_W3]], [[R32_W1]];
; O0-NEXT: 	iadd.32b 	[[R32_W4]], [[R32_W3]], [[R32_W2]];
; O0-NEXT: 	zext.64b.32b 	[[R64_D1]], [[R32_W4]];
; O0-NEXT: 	return [[R64_D1]];
  %call = call i64 @llvm.ctpop.i64(i64 %arg0)
  ret i64 %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <2 x i8> @llvm.ctpop.v2i8(<2 x i8>) #0

define <2 x i8> @ctpop.llvm.ctpop_v2i8(<2 x i8> %arg0) {
; CHECK-LABEL: .v2.8b @ctpop.llvm.ctpop_v2i8(
; CHECK-SAME: .reg .v2.8b [[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.8b [[VR2_8_V2B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; CHECK: 	zext.16b.8b 	[[R16_H0]], [[VR2_8_V2B0]].x;
; CHECK-NEXT: 	cbit.16b 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	trunc.8b.16b 	[[VR2_8_V2B1]].x, [[R16_H1]];
; CHECK-NEXT: 	zext.16b.8b 	[[R16_H2]], [[VR2_8_V2B0]].y;
; CHECK-NEXT: 	cbit.16b 	[[R16_H3]], [[R16_H2]];
; CHECK-NEXT: 	trunc.8b.16b 	[[VR2_8_V2B1]].y, [[R16_H3]];
; CHECK-NEXT: 	return [[VR2_8_V2B1]];
;
; O0-LABEL: .v2.8b @ctpop.llvm.ctpop_v2i8(
; O0-SAME: .reg .v2.8b [[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.8b [[VR2_8_V2B1:%[-a-zA-Z$._0-9]+]], [[VR2_8_V2B2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]], [[R8_B1:%[-a-zA-Z$._0-9]+]], [[R8_B2:%[-a-zA-Z$._0-9]+]], [[R8_B3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.8b 	[[R8_B0]], [[VR2_8_V2B0]].x;
; O0-NEXT: 	mov.8b 	[[R8_B1]], [[VR2_8_V2B0]].y;
; O0-NEXT: 	zext.16b.8b 	[[R16_H0]], [[R8_B0]];
; O0-NEXT: 	cbit.16b 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B2]], [[R16_H1]];
; O0-NEXT: 	zext.16b.8b 	[[R16_H2]], [[R8_B1]];
; O0-NEXT: 	cbit.16b 	[[R16_H3]], [[R16_H2]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B3]], [[R16_H3]];
; O0-NEXT: 	mov.8b 	[[VR2_8_V2B1]].x, [[R8_B2]];
; O0-NEXT: 	mov.16b 	[[VR2_8_V2B2]].xy, [[VR2_8_V2B1]].xy;
; O0-NEXT: 	mov.8b 	[[VR2_8_V2B2]].y, [[R8_B3]];
; O0-NEXT: 	return [[VR2_8_V2B2]];
  %call = call <2 x i8> @llvm.ctpop.v2i8(<2 x i8> %arg0)
  ret <2 x i8> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <3 x i8> @llvm.ctpop.v3i8(<3 x i8>) #0

define <3 x i8> @ctpop.llvm.ctpop_v3i8(<3 x i8> %arg0) {
; CHECK-LABEL: .v3.8b @ctpop.llvm.ctpop_v3i8(
; CHECK-SAME: .reg .v3.8b [[VR3_8_V3B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v3.8b [[VR3_8_V3B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .16b %h<0~6>;
; CHECK: 	zext.16b.8b 	%h0, [[VR3_8_V3B0]].x;
; CHECK-NEXT: 	cbit.16b 	%h1, %h0;
; CHECK-NEXT: 	trunc.8b.16b 	[[VR3_8_V3B1]].x, %h1;
; CHECK-NEXT: 	zext.16b.8b 	%h2, [[VR3_8_V3B0]].y;
; CHECK-NEXT: 	cbit.16b 	%h3, %h2;
; CHECK-NEXT: 	trunc.8b.16b 	[[VR3_8_V3B1]].y, %h3;
; CHECK-NEXT: 	zext.16b.8b 	%h4, [[VR3_8_V3B0]].z;
; CHECK-NEXT: 	cbit.16b 	%h5, %h4;
; CHECK-NEXT: 	trunc.8b.16b 	[[VR3_8_V3B1]].z, %h5;
; CHECK-NEXT: 	return [[VR3_8_V3B1]];
;
; O0-LABEL: .v3.8b @ctpop.llvm.ctpop_v3i8(
; O0-SAME: .reg .v3.8b [[VR3_8_V3B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.8b [[VR3_8_V3B1:%[-a-zA-Z$._0-9]+]], [[VR3_8_V3B2:%[-a-zA-Z$._0-9]+]], [[VR3_8_V3B3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .8b %b<0~6>;
; O0-NEXT: 	.reg .16b %h<0~6>;
; O0: 	mov.8b 	%b0, [[VR3_8_V3B0]].x;
; O0-NEXT: 	mov.8b 	%b1, [[VR3_8_V3B0]].y;
; O0-NEXT: 	mov.8b 	%b2, [[VR3_8_V3B0]].z;
; O0-NEXT: 	zext.16b.8b 	%h0, %b0;
; O0-NEXT: 	cbit.16b 	%h1, %h0;
; O0-NEXT: 	trunc.8b.16b 	%b3, %h1;
; O0-NEXT: 	zext.16b.8b 	%h2, %b1;
; O0-NEXT: 	cbit.16b 	%h3, %h2;
; O0-NEXT: 	trunc.8b.16b 	%b4, %h3;
; O0-NEXT: 	zext.16b.8b 	%h4, %b2;
; O0-NEXT: 	cbit.16b 	%h5, %h4;
; O0-NEXT: 	trunc.8b.16b 	%b5, %h5;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B1]].x, %b3;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B2]].x, [[VR3_8_V3B1]].x;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B2]].y, [[VR3_8_V3B1]].y;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B2]].z, [[VR3_8_V3B1]].z;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B2]].y, %b4;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B3]].x, [[VR3_8_V3B2]].x;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B3]].y, [[VR3_8_V3B2]].y;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B3]].z, [[VR3_8_V3B2]].z;
; O0-NEXT: 	mov.8b 	[[VR3_8_V3B3]].z, %b5;
; O0-NEXT: 	return [[VR3_8_V3B3]];
  %call = call <3 x i8> @llvm.ctpop.v3i8(<3 x i8> %arg0)
  ret <3 x i8> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <4 x i8> @llvm.ctpop.v4i8(<4 x i8>) #0

define <4 x i8> @ctpop.llvm.ctpop_v4i8(<4 x i8> %arg0) {
; CHECK-LABEL: .v4.8b @ctpop.llvm.ctpop_v4i8(
; CHECK-SAME: .reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.8b [[VR4_8_V4B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .16b %h<0~8>;
; CHECK: 	zext.16b.8b 	%h0, [[VR4_8_V4B0]].x;
; CHECK-NEXT: 	cbit.16b 	%h1, %h0;
; CHECK-NEXT: 	trunc.8b.16b 	[[VR4_8_V4B1]].x, %h1;
; CHECK-NEXT: 	zext.16b.8b 	%h2, [[VR4_8_V4B0]].y;
; CHECK-NEXT: 	cbit.16b 	%h3, %h2;
; CHECK-NEXT: 	trunc.8b.16b 	[[VR4_8_V4B1]].y, %h3;
; CHECK-NEXT: 	zext.16b.8b 	%h4, [[VR4_8_V4B0]].z;
; CHECK-NEXT: 	cbit.16b 	%h5, %h4;
; CHECK-NEXT: 	trunc.8b.16b 	[[VR4_8_V4B1]].z, %h5;
; CHECK-NEXT: 	zext.16b.8b 	%h6, [[VR4_8_V4B0]].w;
; CHECK-NEXT: 	cbit.16b 	%h7, %h6;
; CHECK-NEXT: 	trunc.8b.16b 	[[VR4_8_V4B1]].w, %h7;
; CHECK-NEXT: 	return [[VR4_8_V4B1]];
;
; O0-LABEL: .v4.8b @ctpop.llvm.ctpop_v4i8(
; O0-SAME: .reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.8b [[VR4_8_V4B1:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B2:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B3:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .8b %b<0~8>;
; O0-NEXT: 	.reg .16b %h<0~8>;
; O0: 	mov.8b 	%b0, [[VR4_8_V4B0]].x;
; O0-NEXT: 	mov.8b 	%b1, [[VR4_8_V4B0]].y;
; O0-NEXT: 	mov.8b 	%b2, [[VR4_8_V4B0]].z;
; O0-NEXT: 	mov.8b 	%b3, [[VR4_8_V4B0]].w;
; O0-NEXT: 	zext.16b.8b 	%h0, %b0;
; O0-NEXT: 	cbit.16b 	%h1, %h0;
; O0-NEXT: 	trunc.8b.16b 	%b4, %h1;
; O0-NEXT: 	zext.16b.8b 	%h2, %b1;
; O0-NEXT: 	cbit.16b 	%h3, %h2;
; O0-NEXT: 	trunc.8b.16b 	%b5, %h3;
; O0-NEXT: 	zext.16b.8b 	%h4, %b2;
; O0-NEXT: 	cbit.16b 	%h5, %h4;
; O0-NEXT: 	trunc.8b.16b 	%b6, %h5;
; O0-NEXT: 	zext.16b.8b 	%h6, %b3;
; O0-NEXT: 	cbit.16b 	%h7, %h6;
; O0-NEXT: 	trunc.8b.16b 	%b7, %h7;
; O0-NEXT: 	mov.8b 	[[VR4_8_V4B1]].x, %b4;
; O0-NEXT: 	mov.32b 	[[VR4_8_V4B2]].xyzw, [[VR4_8_V4B1]].xyzw;
; O0-NEXT: 	mov.8b 	[[VR4_8_V4B2]].y, %b5;
; O0-NEXT: 	mov.32b 	[[VR4_8_V4B3]].xyzw, [[VR4_8_V4B2]].xyzw;
; O0-NEXT: 	mov.8b 	[[VR4_8_V4B3]].z, %b6;
; O0-NEXT: 	mov.32b 	[[VR4_8_V4B4]].xyzw, [[VR4_8_V4B3]].xyzw;
; O0-NEXT: 	mov.8b 	[[VR4_8_V4B4]].w, %b7;
; O0-NEXT: 	return [[VR4_8_V4B4]];
  %call = call <4 x i8> @llvm.ctpop.v4i8(<4 x i8> %arg0)
  ret <4 x i8> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <2 x i16> @llvm.ctpop.v2i16(<2 x i16>) #0

define <2 x i16> @ctpop.llvm.ctpop_v2i16(<2 x i16> %arg0) {
; CHECK-LABEL: .v2.16b @ctpop.llvm.ctpop_v2i16(
; CHECK-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	cbit.16b 	[[VR2_16_V2H1]].x, [[VR2_16_V2H0]].x;
; CHECK-NEXT: 	cbit.16b 	[[VR2_16_V2H1]].y, [[VR2_16_V2H0]].y;
; CHECK-NEXT: 	return [[VR2_16_V2H1]];
;
; O0-LABEL: .v2.16b @ctpop.llvm.ctpop_v2i16(
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.16b 	[[R16_H0]], [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	[[R16_H1]], [[VR2_16_V2H0]].y;
; O0-NEXT: 	cbit.16b 	[[R16_H2]], [[R16_H0]];
; O0-NEXT: 	cbit.16b 	[[R16_H3]], [[R16_H1]];
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H1]].x, [[R16_H2]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H2]].xy, [[VR2_16_V2H1]].xy;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H2]].y, [[R16_H3]];
; O0-NEXT: 	return [[VR2_16_V2H2]];
  %call = call <2 x i16> @llvm.ctpop.v2i16(<2 x i16> %arg0)
  ret <2 x i16> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <3 x i16> @llvm.ctpop.v3i16(<3 x i16>) #0

define <3 x i16> @ctpop.llvm.ctpop_v3i16(<3 x i16> %arg0) {
; CHECK-LABEL: .v3.16b @ctpop.llvm.ctpop_v3i16(
; CHECK-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	cbit.16b 	[[VR3_16_V3H1]].x, [[VR3_16_V3H0]].x;
; CHECK-NEXT: 	cbit.16b 	[[VR3_16_V3H1]].y, [[VR3_16_V3H0]].y;
; CHECK-NEXT: 	cbit.16b 	[[VR3_16_V3H1]].z, [[VR3_16_V3H0]].z;
; CHECK-NEXT: 	return [[VR3_16_V3H1]];
;
; O0-LABEL: .v3.16b @ctpop.llvm.ctpop_v3i16(
; O0-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H2:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~6>;
; O0: 	mov.16b 	%h0, [[VR3_16_V3H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR3_16_V3H0]].y;
; O0-NEXT: 	mov.16b 	%h2, [[VR3_16_V3H0]].z;
; O0-NEXT: 	cbit.16b 	%h3, %h0;
; O0-NEXT: 	cbit.16b 	%h4, %h1;
; O0-NEXT: 	cbit.16b 	%h5, %h2;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H1]].x, %h3;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].x, [[VR3_16_V3H1]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, [[VR3_16_V3H1]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].z, [[VR3_16_V3H1]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, %h4;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].x, [[VR3_16_V3H2]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].y, [[VR3_16_V3H2]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, [[VR3_16_V3H2]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, %h5;
; O0-NEXT: 	return [[VR3_16_V3H3]];
  %call = call <3 x i16> @llvm.ctpop.v3i16(<3 x i16> %arg0)
  ret <3 x i16> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <4 x i16> @llvm.ctpop.v4i16(<4 x i16>) #0

define <4 x i16> @ctpop.llvm.ctpop_v4i16(<4 x i16> %arg0) {
; CHECK-LABEL: .v4.16b @ctpop.llvm.ctpop_v4i16(
; CHECK-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	cbit.16b 	[[VR4_16_V4H1]].x, [[VR4_16_V4H0]].x;
; CHECK-NEXT: 	cbit.16b 	[[VR4_16_V4H1]].y, [[VR4_16_V4H0]].y;
; CHECK-NEXT: 	cbit.16b 	[[VR4_16_V4H1]].z, [[VR4_16_V4H0]].z;
; CHECK-NEXT: 	cbit.16b 	[[VR4_16_V4H1]].w, [[VR4_16_V4H0]].w;
; CHECK-NEXT: 	return [[VR4_16_V4H1]];
;
; O0-LABEL: .v4.16b @ctpop.llvm.ctpop_v4i16(
; O0-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H2:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H3:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~8>;
; O0: 	mov.16b 	%h0, [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	%h2, [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	%h3, [[VR4_16_V4H0]].w;
; O0-NEXT: 	cbit.16b 	%h4, %h0;
; O0-NEXT: 	cbit.16b 	%h5, %h1;
; O0-NEXT: 	cbit.16b 	%h6, %h2;
; O0-NEXT: 	cbit.16b 	%h7, %h3;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H1]].x, %h4;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H2]].xyzw, [[VR4_16_V4H1]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H2]].y, %h5;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H3]].xyzw, [[VR4_16_V4H2]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H3]].z, %h6;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H4]].xyzw, [[VR4_16_V4H3]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H4]].w, %h7;
; O0-NEXT: 	return [[VR4_16_V4H4]];
  %call = call <4 x i16> @llvm.ctpop.v4i16(<4 x i16> %arg0)
  ret <4 x i16> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <2 x i32> @llvm.ctpop.v2i32(<2 x i32>) #0

define <2 x i32> @ctpop.llvm.ctpop_v2i32(<2 x i32> %arg0) {
; CHECK-LABEL: .v2.32b @ctpop.llvm.ctpop_v2i32(
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	cbit.32b 	[[VR2_32_V2W1]].x, [[VR2_32_V2W0]].x;
; CHECK-NEXT: 	cbit.32b 	[[VR2_32_V2W1]].y, [[VR2_32_V2W0]].y;
; CHECK-NEXT: 	return [[VR2_32_V2W1]];
;
; O0-LABEL: .v2.32b @ctpop.llvm.ctpop_v2i32(
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.32b 	[[R32_W0]], [[VR2_32_V2W0]].x;
; O0-NEXT: 	mov.32b 	[[R32_W1]], [[VR2_32_V2W0]].y;
; O0-NEXT: 	cbit.32b 	[[R32_W2]], [[R32_W0]];
; O0-NEXT: 	cbit.32b 	[[R32_W3]], [[R32_W1]];
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W1]].x, [[R32_W2]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W2]].xy, [[VR2_32_V2W1]].xy;
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W2]].y, [[R32_W3]];
; O0-NEXT: 	return [[VR2_32_V2W2]];
  %call = call <2 x i32> @llvm.ctpop.v2i32(<2 x i32> %arg0)
  ret <2 x i32> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <3 x i32> @llvm.ctpop.v3i32(<3 x i32>) #0

define <3 x i32> @ctpop.llvm.ctpop_v3i32(<3 x i32> %arg0) {
; CHECK-LABEL: .v3.32b @ctpop.llvm.ctpop_v3i32(
; CHECK-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v3.32b [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	cbit.32b 	[[VR3_32_V3W1]].x, [[VR3_32_V3W0]].x;
; CHECK-NEXT: 	cbit.32b 	[[VR3_32_V3W1]].y, [[VR3_32_V3W0]].y;
; CHECK-NEXT: 	cbit.32b 	[[VR3_32_V3W1]].z, [[VR3_32_V3W0]].z;
; CHECK-NEXT: 	return [[VR3_32_V3W1]];
;
; O0-LABEL: .v3.32b @ctpop.llvm.ctpop_v3i32(
; O0-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.32b [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W2:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~6>;
; O0: 	mov.32b 	%w0, [[VR3_32_V3W0]].x;
; O0-NEXT: 	mov.32b 	%w1, [[VR3_32_V3W0]].y;
; O0-NEXT: 	mov.32b 	%w2, [[VR3_32_V3W0]].z;
; O0-NEXT: 	cbit.32b 	%w3, %w0;
; O0-NEXT: 	cbit.32b 	%w4, %w1;
; O0-NEXT: 	cbit.32b 	%w5, %w2;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W1]].x, %w3;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].x, [[VR3_32_V3W1]].x;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].y, [[VR3_32_V3W1]].y;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].z, [[VR3_32_V3W1]].z;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].y, %w4;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].x, [[VR3_32_V3W2]].x;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].y, [[VR3_32_V3W2]].y;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].z, [[VR3_32_V3W2]].z;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].z, %w5;
; O0-NEXT: 	return [[VR3_32_V3W3]];
  %call = call <3 x i32> @llvm.ctpop.v3i32(<3 x i32> %arg0)
  ret <3 x i32> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <4 x i32> @llvm.ctpop.v4i32(<4 x i32>) #0

define <4 x i32> @ctpop.llvm.ctpop_v4i32(<4 x i32> %arg0) {
; CHECK-LABEL: .v4.32b @ctpop.llvm.ctpop_v4i32(
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.32b [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	cbit.32b 	[[VR4_32_V4W1]].x, [[VR4_32_V4W0]].x;
; CHECK-NEXT: 	cbit.32b 	[[VR4_32_V4W1]].y, [[VR4_32_V4W0]].y;
; CHECK-NEXT: 	cbit.32b 	[[VR4_32_V4W1]].z, [[VR4_32_V4W0]].z;
; CHECK-NEXT: 	cbit.32b 	[[VR4_32_V4W1]].w, [[VR4_32_V4W0]].w;
; CHECK-NEXT: 	return [[VR4_32_V4W1]];
;
; O0-LABEL: .v4.32b @ctpop.llvm.ctpop_v4i32(
; O0-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.32b [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W2:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W3:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~8>;
; O0: 	mov.32b 	%w0, [[VR4_32_V4W0]].x;
; O0-NEXT: 	mov.32b 	%w1, [[VR4_32_V4W0]].y;
; O0-NEXT: 	mov.32b 	%w2, [[VR4_32_V4W0]].z;
; O0-NEXT: 	mov.32b 	%w3, [[VR4_32_V4W0]].w;
; O0-NEXT: 	cbit.32b 	%w4, %w0;
; O0-NEXT: 	cbit.32b 	%w5, %w1;
; O0-NEXT: 	cbit.32b 	%w6, %w2;
; O0-NEXT: 	cbit.32b 	%w7, %w3;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W1]].x, %w4;
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W2]].xyzw, [[VR4_32_V4W1]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W2]].y, %w5;
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W3]].xyzw, [[VR4_32_V4W2]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W3]].z, %w6;
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W4]].xyzw, [[VR4_32_V4W3]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W4]].w, %w7;
; O0-NEXT: 	return [[VR4_32_V4W4]];
  %call = call <4 x i32> @llvm.ctpop.v4i32(<4 x i32> %arg0)
  ret <4 x i32> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <2 x i64> @llvm.ctpop.v2i64(<2 x i64>) #0

define <2 x i64> @ctpop.llvm.ctpop_v2i64(<2 x i64> %arg0) {
; CHECK-LABEL: .v2.64b @ctpop.llvm.ctpop_v2i64(
; CHECK-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .32b %w<0~6>;
; CHECK: 	mov.64b 	[[VR2_32_V2W0]].xy, [[VR2_64_V2D0]].x;
; CHECK-NEXT: 	cbit.32b 	%w0, [[VR2_32_V2W0]].x;
; CHECK-NEXT: 	cbit.32b 	%w1, [[VR2_32_V2W0]].y;
; CHECK-NEXT: 	iadd.32b 	%w2, %w1, %w0;
; CHECK-NEXT: 	zext.64b.32b 	[[VR2_64_V2D1]].x, %w2;
; CHECK-NEXT: 	mov.64b 	[[VR2_32_V2W1]].xy, [[VR2_64_V2D0]].y;
; CHECK-NEXT: 	cbit.32b 	%w3, [[VR2_32_V2W1]].x;
; CHECK-NEXT: 	cbit.32b 	%w4, [[VR2_32_V2W1]].y;
; CHECK-NEXT: 	iadd.32b 	%w5, %w4, %w3;
; CHECK-NEXT: 	zext.64b.32b 	[[VR2_64_V2D1]].y, %w5;
; CHECK-NEXT: 	return [[VR2_64_V2D1]];
;
; O0-LABEL: .v2.64b @ctpop.llvm.ctpop_v2i64(
; O0-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]], [[VR2_64_V2D2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]], [[R64_D1:%[-a-zA-Z$._0-9]+]], [[R64_D2:%[-a-zA-Z$._0-9]+]], [[R64_D3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~10>;
; O0: 	mov.64b 	[[R64_D0]], [[VR2_64_V2D0]].x;
; O0-NEXT: 	mov.64b 	[[R64_D1]], [[VR2_64_V2D0]].y;
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W0]].xy, [[R64_D0]];
; O0-NEXT: 	mov.32b 	%w0, [[VR2_32_V2W0]].x;
; O0-NEXT: 	mov.32b 	%w1, [[VR2_32_V2W0]].y;
; O0-NEXT: 	cbit.32b 	%w2, %w0;
; O0-NEXT: 	cbit.32b 	%w3, %w1;
; O0-NEXT: 	iadd.32b 	%w4, %w3, %w2;
; O0-NEXT: 	zext.64b.32b 	[[R64_D2]], %w4;
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W1]].xy, [[R64_D1]];
; O0-NEXT: 	mov.32b 	%w5, [[VR2_32_V2W1]].x;
; O0-NEXT: 	mov.32b 	%w6, [[VR2_32_V2W1]].y;
; O0-NEXT: 	cbit.32b 	%w7, %w5;
; O0-NEXT: 	cbit.32b 	%w8, %w6;
; O0-NEXT: 	iadd.32b 	%w9, %w8, %w7;
; O0-NEXT: 	zext.64b.32b 	[[R64_D3]], %w9;
; O0-NEXT: 	mov.64b 	[[VR2_64_V2D1]].x, [[R64_D2]];
; O0-NEXT: 	mov.128b 	[[VR2_64_V2D2]].xy, [[VR2_64_V2D1]].xy;
; O0-NEXT: 	mov.64b 	[[VR2_64_V2D2]].y, [[R64_D3]];
; O0-NEXT: 	return [[VR2_64_V2D2]];
  %call = call <2 x i64> @llvm.ctpop.v2i64(<2 x i64> %arg0)
  ret <2 x i64> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <3 x i64> @llvm.ctpop.v3i64(<3 x i64>) #0

define <3 x i64> @ctpop.llvm.ctpop_v3i64(<3 x i64> %arg0) {
; CHECK-LABEL: .v3.64b @ctpop.llvm.ctpop_v3i64(
; CHECK-SAME: .reg .v3.64b [[VR3_64_V3D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v3.64b [[VR3_64_V3D1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .32b %w<0~9>;
; CHECK: 	mov.64b 	[[VR2_32_V2W0]].xy, [[VR3_64_V3D0]].x;
; CHECK-NEXT: 	cbit.32b 	%w0, [[VR2_32_V2W0]].x;
; CHECK-NEXT: 	cbit.32b 	%w1, [[VR2_32_V2W0]].y;
; CHECK-NEXT: 	iadd.32b 	%w2, %w1, %w0;
; CHECK-NEXT: 	zext.64b.32b 	[[VR3_64_V3D1]].x, %w2;
; CHECK-NEXT: 	mov.64b 	[[VR2_32_V2W1]].xy, [[VR3_64_V3D0]].y;
; CHECK-NEXT: 	cbit.32b 	%w3, [[VR2_32_V2W1]].x;
; CHECK-NEXT: 	cbit.32b 	%w4, [[VR2_32_V2W1]].y;
; CHECK-NEXT: 	iadd.32b 	%w5, %w4, %w3;
; CHECK-NEXT: 	zext.64b.32b 	[[VR3_64_V3D1]].y, %w5;
; CHECK-NEXT: 	mov.64b 	[[VR2_32_V2W2]].xy, [[VR3_64_V3D0]].z;
; CHECK-NEXT: 	cbit.32b 	%w6, [[VR2_32_V2W2]].x;
; CHECK-NEXT: 	cbit.32b 	%w7, [[VR2_32_V2W2]].y;
; CHECK-NEXT: 	iadd.32b 	%w8, %w7, %w6;
; CHECK-NEXT: 	zext.64b.32b 	[[VR3_64_V3D1]].z, %w8;
; CHECK-NEXT: 	return [[VR3_64_V3D1]];
;
; O0-LABEL: .v3.64b @ctpop.llvm.ctpop_v3i64(
; O0-SAME: .reg .v3.64b [[VR3_64_V3D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.64b [[VR3_64_V3D1:%[-a-zA-Z$._0-9]+]], [[VR3_64_V3D2:%[-a-zA-Z$._0-9]+]], [[VR3_64_V3D3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b %d<0~6>;
; O0-NEXT: 	.reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~15>;
; O0: 	mov.64b 	%d0, [[VR3_64_V3D0]].x;
; O0-NEXT: 	mov.64b 	%d1, [[VR3_64_V3D0]].y;
; O0-NEXT: 	mov.64b 	%d2, [[VR3_64_V3D0]].z;
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W0]].xy, %d0;
; O0-NEXT: 	mov.32b 	%w0, [[VR2_32_V2W0]].x;
; O0-NEXT: 	mov.32b 	%w1, [[VR2_32_V2W0]].y;
; O0-NEXT: 	cbit.32b 	%w2, %w0;
; O0-NEXT: 	cbit.32b 	%w3, %w1;
; O0-NEXT: 	iadd.32b 	%w4, %w3, %w2;
; O0-NEXT: 	zext.64b.32b 	%d3, %w4;
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W1]].xy, %d1;
; O0-NEXT: 	mov.32b 	%w5, [[VR2_32_V2W1]].x;
; O0-NEXT: 	mov.32b 	%w6, [[VR2_32_V2W1]].y;
; O0-NEXT: 	cbit.32b 	%w7, %w5;
; O0-NEXT: 	cbit.32b 	%w8, %w6;
; O0-NEXT: 	iadd.32b 	%w9, %w8, %w7;
; O0-NEXT: 	zext.64b.32b 	%d4, %w9;
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W2]].xy, %d2;
; O0-NEXT: 	mov.32b 	%w10, [[VR2_32_V2W2]].x;
; O0-NEXT: 	mov.32b 	%w11, [[VR2_32_V2W2]].y;
; O0-NEXT: 	cbit.32b 	%w12, %w10;
; O0-NEXT: 	cbit.32b 	%w13, %w11;
; O0-NEXT: 	iadd.32b 	%w14, %w13, %w12;
; O0-NEXT: 	zext.64b.32b 	%d5, %w14;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D1]].x, %d3;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D2]].x, [[VR3_64_V3D1]].x;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D2]].y, [[VR3_64_V3D1]].y;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D2]].z, [[VR3_64_V3D1]].z;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D2]].y, %d4;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D3]].x, [[VR3_64_V3D2]].x;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D3]].y, [[VR3_64_V3D2]].y;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D3]].z, [[VR3_64_V3D2]].z;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D3]].z, %d5;
; O0-NEXT: 	return [[VR3_64_V3D3]];
  %call = call <3 x i64> @llvm.ctpop.v3i64(<3 x i64> %arg0)
  ret <3 x i64> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <4 x i64> @llvm.ctpop.v4i64(<4 x i64>) #0

define <4 x i64> @ctpop.llvm.ctpop_v4i64(<4 x i64> %arg0) {
; CHECK-LABEL: .v4.64b @ctpop.llvm.ctpop_v4i64(
; CHECK-SAME: .reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.64b [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .32b %w<0~12>;
; CHECK: 	mov.64b 	[[VR2_32_V2W0]].xy, [[VR4_64_V4D0]].x;
; CHECK-NEXT: 	cbit.32b 	%w0, [[VR2_32_V2W0]].x;
; CHECK-NEXT: 	cbit.32b 	%w1, [[VR2_32_V2W0]].y;
; CHECK-NEXT: 	iadd.32b 	%w2, %w1, %w0;
; CHECK-NEXT: 	zext.64b.32b 	[[VR4_64_V4D1]].x, %w2;
; CHECK-NEXT: 	mov.64b 	[[VR2_32_V2W1]].xy, [[VR4_64_V4D0]].y;
; CHECK-NEXT: 	cbit.32b 	%w3, [[VR2_32_V2W1]].x;
; CHECK-NEXT: 	cbit.32b 	%w4, [[VR2_32_V2W1]].y;
; CHECK-NEXT: 	iadd.32b 	%w5, %w4, %w3;
; CHECK-NEXT: 	zext.64b.32b 	[[VR4_64_V4D1]].y, %w5;
; CHECK-NEXT: 	mov.64b 	[[VR2_32_V2W2]].xy, [[VR4_64_V4D0]].z;
; CHECK-NEXT: 	cbit.32b 	%w6, [[VR2_32_V2W2]].x;
; CHECK-NEXT: 	cbit.32b 	%w7, [[VR2_32_V2W2]].y;
; CHECK-NEXT: 	iadd.32b 	%w8, %w7, %w6;
; CHECK-NEXT: 	zext.64b.32b 	[[VR4_64_V4D1]].z, %w8;
; CHECK-NEXT: 	mov.64b 	[[VR2_32_V2W3]].xy, [[VR4_64_V4D0]].w;
; CHECK-NEXT: 	cbit.32b 	%w9, [[VR2_32_V2W3]].x;
; CHECK-NEXT: 	cbit.32b 	%w10, [[VR2_32_V2W3]].y;
; CHECK-NEXT: 	iadd.32b 	%w11, %w10, %w9;
; CHECK-NEXT: 	zext.64b.32b 	[[VR4_64_V4D1]].w, %w11;
; CHECK-NEXT: 	return [[VR4_64_V4D1]];
;
; O0-LABEL: .v4.64b @ctpop.llvm.ctpop_v4i64(
; O0-SAME: .reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.64b [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D2:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D3:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b %d<0~8>;
; O0-NEXT: 	.reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~20>;
; O0: 	mov.64b 	%d0, [[VR4_64_V4D0]].x;
; O0-NEXT: 	mov.64b 	%d1, [[VR4_64_V4D0]].y;
; O0-NEXT: 	mov.64b 	%d2, [[VR4_64_V4D0]].z;
; O0-NEXT: 	mov.64b 	%d3, [[VR4_64_V4D0]].w;
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W0]].xy, %d0;
; O0-NEXT: 	mov.32b 	%w0, [[VR2_32_V2W0]].x;
; O0-NEXT: 	mov.32b 	%w1, [[VR2_32_V2W0]].y;
; O0-NEXT: 	cbit.32b 	%w2, %w0;
; O0-NEXT: 	cbit.32b 	%w3, %w1;
; O0-NEXT: 	iadd.32b 	%w4, %w3, %w2;
; O0-NEXT: 	zext.64b.32b 	%d4, %w4;
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W1]].xy, %d1;
; O0-NEXT: 	mov.32b 	%w5, [[VR2_32_V2W1]].x;
; O0-NEXT: 	mov.32b 	%w6, [[VR2_32_V2W1]].y;
; O0-NEXT: 	cbit.32b 	%w7, %w5;
; O0-NEXT: 	cbit.32b 	%w8, %w6;
; O0-NEXT: 	iadd.32b 	%w9, %w8, %w7;
; O0-NEXT: 	zext.64b.32b 	%d5, %w9;
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W2]].xy, %d2;
; O0-NEXT: 	mov.32b 	%w10, [[VR2_32_V2W2]].x;
; O0-NEXT: 	mov.32b 	%w11, [[VR2_32_V2W2]].y;
; O0-NEXT: 	cbit.32b 	%w12, %w10;
; O0-NEXT: 	cbit.32b 	%w13, %w11;
; O0-NEXT: 	iadd.32b 	%w14, %w13, %w12;
; O0-NEXT: 	zext.64b.32b 	%d6, %w14;
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W3]].xy, %d3;
; O0-NEXT: 	mov.32b 	%w15, [[VR2_32_V2W3]].x;
; O0-NEXT: 	mov.32b 	%w16, [[VR2_32_V2W3]].y;
; O0-NEXT: 	cbit.32b 	%w17, %w15;
; O0-NEXT: 	cbit.32b 	%w18, %w16;
; O0-NEXT: 	iadd.32b 	%w19, %w18, %w17;
; O0-NEXT: 	zext.64b.32b 	%d7, %w19;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D1]].x, %d4;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].x, [[VR4_64_V4D1]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].y, [[VR4_64_V4D1]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].z, [[VR4_64_V4D1]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].w, [[VR4_64_V4D1]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].y, %d5;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].x, [[VR4_64_V4D2]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].y, [[VR4_64_V4D2]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].z, [[VR4_64_V4D2]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].w, [[VR4_64_V4D2]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].z, %d6;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].x, [[VR4_64_V4D3]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].y, [[VR4_64_V4D3]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].z, [[VR4_64_V4D3]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].w, [[VR4_64_V4D3]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].w, %d7;
; O0-NEXT: 	return [[VR4_64_V4D4]];
  %call = call <4 x i64> @llvm.ctpop.v4i64(<4 x i64> %arg0)
  ret <4 x i64> %call
}

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
