; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; to regenerate checks run following:
; $REPO/llvm/utils/update_pisa_test_checks.py --llc-binary $INSTALL/bin/llc llvm.log2.ll
; RUN: llc < %s -march=pisa %disable_optional_optimizations -verify-machineinstrs | FileCheck --check-prefixes=CHECK,CHECK-LESS-OPT %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare half @llvm.log2.f16(half) #0

define half @log2.llvm.log2_half(half %arg0) {
; CHECK-LABEL: .16b @log2.llvm.log2_half(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	flog2.hf 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	return [[R16_H1]];
;
; O0-LABEL: .16b @log2.llvm.log2_half(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	flog2.hf 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
  %call = call half @llvm.log2.f16(half %arg0)
  ret half %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare bfloat @llvm.log2.bf16(bfloat) #0

define bfloat @log2.llvm.log2_bfloat(bfloat %arg0) {
; CHECK-LABEL: .16b @log2.llvm.log2_bfloat(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	flog2.bf 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	return [[R16_H1]];
;
; O0-LABEL: .16b @log2.llvm.log2_bfloat(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	flog2.bf 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
  %call = call bfloat @llvm.log2.bf16(bfloat %arg0)
  ret bfloat %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare float @llvm.log2.f32(float) #0

define float @log2.llvm.log2_float(float %arg0) {
; CHECK-LABEL: .32b @log2.llvm.log2_float(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	flog2.f 	[[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @log2.llvm.log2_float(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	flog2.f 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	return [[R32_W1]];
  %call = call float @llvm.log2.f32(float %arg0)
  ret float %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <2 x half> @llvm.log2.v2f16(<2 x half>) #0

define <2 x half> @log2.llvm.log2_v2half(<2 x half> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v2.16b @log2.llvm.log2_v2half(
; CHECK-LESS-OPT-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	flog2.hf 	[[VR2_16_V2H1]].x, [[VR2_16_V2H0]].x;
; CHECK-LESS-OPT-NEXT: 	flog2.hf 	[[VR2_16_V2H1]].y, [[VR2_16_V2H0]].y;
; CHECK-LESS-OPT-NEXT: 	return [[VR2_16_V2H1]];
;
; O0-LABEL: .v2.16b @log2.llvm.log2_v2half(
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.16b 	[[R16_H0]], [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	[[R16_H1]], [[VR2_16_V2H0]].y;
; O0-NEXT: 	flog2.hf 	[[R16_H2]], [[R16_H0]];
; O0-NEXT: 	flog2.hf 	[[R16_H3]], [[R16_H1]];
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H1]].x, [[R16_H2]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H2]].xy, [[VR2_16_V2H1]].xy;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H2]].y, [[R16_H3]];
; O0-NEXT: 	return [[VR2_16_V2H2]];
  %call = call <2 x half> @llvm.log2.v2f16(<2 x half> %arg0)
  ret <2 x half> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <3 x half> @llvm.log2.v3f16(<3 x half>) #0

define <3 x half> @log2.llvm.log2_v3half(<3 x half> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v3.16b @log2.llvm.log2_v3half(
; CHECK-LESS-OPT-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	flog2.hf 	[[VR3_16_V3H1]].x, [[VR3_16_V3H0]].x;
; CHECK-LESS-OPT-NEXT: 	flog2.hf 	[[VR3_16_V3H1]].y, [[VR3_16_V3H0]].y;
; CHECK-LESS-OPT-NEXT: 	flog2.hf 	[[VR3_16_V3H1]].z, [[VR3_16_V3H0]].z;
; CHECK-LESS-OPT-NEXT: 	return [[VR3_16_V3H1]];
;
; O0-LABEL: .v3.16b @log2.llvm.log2_v3half(
; O0-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H2:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~6>;
; O0: 	mov.16b 	%h0, [[VR3_16_V3H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR3_16_V3H0]].y;
; O0-NEXT: 	mov.16b 	%h2, [[VR3_16_V3H0]].z;
; O0-NEXT: 	flog2.hf 	%h3, %h0;
; O0-NEXT: 	flog2.hf 	%h4, %h1;
; O0-NEXT: 	flog2.hf 	%h5, %h2;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H1]].x, %h3;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].x, [[VR3_16_V3H1]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, [[VR3_16_V3H1]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].z, [[VR3_16_V3H1]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, %h4;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].x, [[VR3_16_V3H2]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].y, [[VR3_16_V3H2]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, [[VR3_16_V3H2]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, %h5;
; O0-NEXT: 	return [[VR3_16_V3H3]];
  %call = call <3 x half> @llvm.log2.v3f16(<3 x half> %arg0)
  ret <3 x half> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <4 x half> @llvm.log2.v4f16(<4 x half>) #0

define <4 x half> @log2.llvm.log2_v4half(<4 x half> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v4.16b @log2.llvm.log2_v4half(
; CHECK-LESS-OPT-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	flog2.hf 	[[VR4_16_V4H1]].x, [[VR4_16_V4H0]].x;
; CHECK-LESS-OPT-NEXT: 	flog2.hf 	[[VR4_16_V4H1]].y, [[VR4_16_V4H0]].y;
; CHECK-LESS-OPT-NEXT: 	flog2.hf 	[[VR4_16_V4H1]].z, [[VR4_16_V4H0]].z;
; CHECK-LESS-OPT-NEXT: 	flog2.hf 	[[VR4_16_V4H1]].w, [[VR4_16_V4H0]].w;
; CHECK-LESS-OPT-NEXT: 	return [[VR4_16_V4H1]];
;
; O0-LABEL: .v4.16b @log2.llvm.log2_v4half(
; O0-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H2:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H3:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~8>;
; O0: 	mov.16b 	%h0, [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	%h2, [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	%h3, [[VR4_16_V4H0]].w;
; O0-NEXT: 	flog2.hf 	%h4, %h0;
; O0-NEXT: 	flog2.hf 	%h5, %h1;
; O0-NEXT: 	flog2.hf 	%h6, %h2;
; O0-NEXT: 	flog2.hf 	%h7, %h3;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H1]].x, %h4;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H2]].xyzw, [[VR4_16_V4H1]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H2]].y, %h5;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H3]].xyzw, [[VR4_16_V4H2]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H3]].z, %h6;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H4]].xyzw, [[VR4_16_V4H3]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H4]].w, %h7;
; O0-NEXT: 	return [[VR4_16_V4H4]];
  %call = call <4 x half> @llvm.log2.v4f16(<4 x half> %arg0)
  ret <4 x half> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <2 x bfloat> @llvm.log2.v2bf16(<2 x bfloat>) #0

define <2 x bfloat> @log2.llvm.log2_v2bfloat(<2 x bfloat> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v2.16b @log2.llvm.log2_v2bfloat(
; CHECK-LESS-OPT-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	flog2.bf 	[[VR2_16_V2H1]].x, [[VR2_16_V2H0]].x;
; CHECK-LESS-OPT-NEXT: 	flog2.bf 	[[VR2_16_V2H1]].y, [[VR2_16_V2H0]].y;
; CHECK-LESS-OPT-NEXT: 	return [[VR2_16_V2H1]];
;
; O0-LABEL: .v2.16b @log2.llvm.log2_v2bfloat(
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.16b 	[[R16_H0]], [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	[[R16_H1]], [[VR2_16_V2H0]].y;
; O0-NEXT: 	flog2.bf 	[[R16_H2]], [[R16_H0]];
; O0-NEXT: 	flog2.bf 	[[R16_H3]], [[R16_H1]];
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H1]].x, [[R16_H2]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H2]].xy, [[VR2_16_V2H1]].xy;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H2]].y, [[R16_H3]];
; O0-NEXT: 	return [[VR2_16_V2H2]];
  %call = call <2 x bfloat> @llvm.log2.v2bf16(<2 x bfloat> %arg0)
  ret <2 x bfloat> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <3 x bfloat> @llvm.log2.v3bf16(<3 x bfloat>) #0

define <3 x bfloat> @log2.llvm.log2_v3bfloat(<3 x bfloat> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v3.16b @log2.llvm.log2_v3bfloat(
; CHECK-LESS-OPT-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	flog2.bf 	[[VR3_16_V3H1]].x, [[VR3_16_V3H0]].x;
; CHECK-LESS-OPT-NEXT: 	flog2.bf 	[[VR3_16_V3H1]].y, [[VR3_16_V3H0]].y;
; CHECK-LESS-OPT-NEXT: 	flog2.bf 	[[VR3_16_V3H1]].z, [[VR3_16_V3H0]].z;
; CHECK-LESS-OPT-NEXT: 	return [[VR3_16_V3H1]];
;
; O0-LABEL: .v3.16b @log2.llvm.log2_v3bfloat(
; O0-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H2:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~6>;
; O0: 	mov.16b 	%h0, [[VR3_16_V3H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR3_16_V3H0]].y;
; O0-NEXT: 	mov.16b 	%h2, [[VR3_16_V3H0]].z;
; O0-NEXT: 	flog2.bf 	%h3, %h0;
; O0-NEXT: 	flog2.bf 	%h4, %h1;
; O0-NEXT: 	flog2.bf 	%h5, %h2;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H1]].x, %h3;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].x, [[VR3_16_V3H1]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, [[VR3_16_V3H1]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].z, [[VR3_16_V3H1]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, %h4;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].x, [[VR3_16_V3H2]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].y, [[VR3_16_V3H2]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, [[VR3_16_V3H2]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, %h5;
; O0-NEXT: 	return [[VR3_16_V3H3]];
  %call = call <3 x bfloat> @llvm.log2.v3bf16(<3 x bfloat> %arg0)
  ret <3 x bfloat> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <4 x bfloat> @llvm.log2.v4bf16(<4 x bfloat>) #0

define <4 x bfloat> @log2.llvm.log2_v4bfloat(<4 x bfloat> %arg0) {
;
; CHECK-LESS-OPT-LABEL: .v4.16b @log2.llvm.log2_v4bfloat(
; CHECK-LESS-OPT-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	flog2.bf 	[[VR4_16_V4H1]].x, [[VR4_16_V4H0]].x;
; CHECK-LESS-OPT-NEXT: 	flog2.bf 	[[VR4_16_V4H1]].y, [[VR4_16_V4H0]].y;
; CHECK-LESS-OPT-NEXT: 	flog2.bf 	[[VR4_16_V4H1]].z, [[VR4_16_V4H0]].z;
; CHECK-LESS-OPT-NEXT: 	flog2.bf 	[[VR4_16_V4H1]].w, [[VR4_16_V4H0]].w;
; CHECK-LESS-OPT-NEXT: 	return [[VR4_16_V4H1]];
;
; O0-LABEL: .v4.16b @log2.llvm.log2_v4bfloat(
; O0-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H2:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H3:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~8>;
; O0: 	mov.16b 	%h0, [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	%h2, [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	%h3, [[VR4_16_V4H0]].w;
; O0-NEXT: 	flog2.bf 	%h4, %h0;
; O0-NEXT: 	flog2.bf 	%h5, %h1;
; O0-NEXT: 	flog2.bf 	%h6, %h2;
; O0-NEXT: 	flog2.bf 	%h7, %h3;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H1]].x, %h4;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H2]].xyzw, [[VR4_16_V4H1]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H2]].y, %h5;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H3]].xyzw, [[VR4_16_V4H2]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H3]].z, %h6;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H4]].xyzw, [[VR4_16_V4H3]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H4]].w, %h7;
; O0-NEXT: 	return [[VR4_16_V4H4]];
  %call = call <4 x bfloat> @llvm.log2.v4bf16(<4 x bfloat> %arg0)
  ret <4 x bfloat> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <2 x float> @llvm.log2.v2f32(<2 x float>) #0

define <2 x float> @log2.llvm.log2_v2float(<2 x float> %arg0) {
; CHECK-LABEL: .v2.32b @log2.llvm.log2_v2float(
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	flog2.f 	[[VR2_32_V2W1]].x, [[VR2_32_V2W0]].x;
; CHECK-NEXT: 	flog2.f 	[[VR2_32_V2W1]].y, [[VR2_32_V2W0]].y;
; CHECK-NEXT: 	return [[VR2_32_V2W1]];
;
; O0-LABEL: .v2.32b @log2.llvm.log2_v2float(
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.32b 	[[R32_W0]], [[VR2_32_V2W0]].x;
; O0-NEXT: 	mov.32b 	[[R32_W1]], [[VR2_32_V2W0]].y;
; O0-NEXT: 	flog2.f 	[[R32_W2]], [[R32_W0]];
; O0-NEXT: 	flog2.f 	[[R32_W3]], [[R32_W1]];
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W1]].x, [[R32_W2]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W2]].xy, [[VR2_32_V2W1]].xy;
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W2]].y, [[R32_W3]];
; O0-NEXT: 	return [[VR2_32_V2W2]];
  %call = call <2 x float> @llvm.log2.v2f32(<2 x float> %arg0)
  ret <2 x float> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <3 x float> @llvm.log2.v3f32(<3 x float>) #0

define <3 x float> @log2.llvm.log2_v3float(<3 x float> %arg0) {
; CHECK-LABEL: .v3.32b @log2.llvm.log2_v3float(
; CHECK-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v3.32b [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	flog2.f 	[[VR3_32_V3W1]].x, [[VR3_32_V3W0]].x;
; CHECK-NEXT: 	flog2.f 	[[VR3_32_V3W1]].y, [[VR3_32_V3W0]].y;
; CHECK-NEXT: 	flog2.f 	[[VR3_32_V3W1]].z, [[VR3_32_V3W0]].z;
; CHECK-NEXT: 	return [[VR3_32_V3W1]];
;
; O0-LABEL: .v3.32b @log2.llvm.log2_v3float(
; O0-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.32b [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W2:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~6>;
; O0: 	mov.32b 	%w0, [[VR3_32_V3W0]].x;
; O0-NEXT: 	mov.32b 	%w1, [[VR3_32_V3W0]].y;
; O0-NEXT: 	mov.32b 	%w2, [[VR3_32_V3W0]].z;
; O0-NEXT: 	flog2.f 	%w3, %w0;
; O0-NEXT: 	flog2.f 	%w4, %w1;
; O0-NEXT: 	flog2.f 	%w5, %w2;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W1]].x, %w3;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].x, [[VR3_32_V3W1]].x;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].y, [[VR3_32_V3W1]].y;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].z, [[VR3_32_V3W1]].z;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].y, %w4;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].x, [[VR3_32_V3W2]].x;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].y, [[VR3_32_V3W2]].y;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].z, [[VR3_32_V3W2]].z;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].z, %w5;
; O0-NEXT: 	return [[VR3_32_V3W3]];
  %call = call <3 x float> @llvm.log2.v3f32(<3 x float> %arg0)
  ret <3 x float> %call
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <4 x float> @llvm.log2.v4f32(<4 x float>) #0

define <4 x float> @log2.llvm.log2_v4float(<4 x float> %arg0) {
; CHECK-LABEL: .v4.32b @log2.llvm.log2_v4float(
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.32b [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	flog2.f 	[[VR4_32_V4W1]].x, [[VR4_32_V4W0]].x;
; CHECK-NEXT: 	flog2.f 	[[VR4_32_V4W1]].y, [[VR4_32_V4W0]].y;
; CHECK-NEXT: 	flog2.f 	[[VR4_32_V4W1]].z, [[VR4_32_V4W0]].z;
; CHECK-NEXT: 	flog2.f 	[[VR4_32_V4W1]].w, [[VR4_32_V4W0]].w;
; CHECK-NEXT: 	return [[VR4_32_V4W1]];
;
; O0-LABEL: .v4.32b @log2.llvm.log2_v4float(
; O0-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.32b [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W2:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W3:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~8>;
; O0: 	mov.32b 	%w0, [[VR4_32_V4W0]].x;
; O0-NEXT: 	mov.32b 	%w1, [[VR4_32_V4W0]].y;
; O0-NEXT: 	mov.32b 	%w2, [[VR4_32_V4W0]].z;
; O0-NEXT: 	mov.32b 	%w3, [[VR4_32_V4W0]].w;
; O0-NEXT: 	flog2.f 	%w4, %w0;
; O0-NEXT: 	flog2.f 	%w5, %w1;
; O0-NEXT: 	flog2.f 	%w6, %w2;
; O0-NEXT: 	flog2.f 	%w7, %w3;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W1]].x, %w4;
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W2]].xyzw, [[VR4_32_V4W1]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W2]].y, %w5;
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W3]].xyzw, [[VR4_32_V4W2]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W3]].z, %w6;
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W4]].xyzw, [[VR4_32_V4W3]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W4]].w, %w7;
; O0-NEXT: 	return [[VR4_32_V4W4]];
  %call = call <4 x float> @llvm.log2.v4f32(<4 x float> %arg0)
  ret <4 x float> %call
}

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
