; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s
; RUN: llc < %s -march=pisa -verify-machineinstrs -o %t.pisa
; RUN: FileCheck %s < %t.pisa

%s4 = type { i8* }
@c1 = internal unnamed_addr addrspace(1) constant [1 x i8] zeroinitializer
@c2 = internal unnamed_addr addrspace(2) constant [1 x i8] zeroinitializer
@t1 = internal addrspace(1) global %s4 { i8* addrspacecast (i8 addrspace(1)* getelementptr ([1 x i8], [1 x i8] addrspace(1)* @c1, i32 0, i32 0) to i8*) }
@t2 = internal addrspace(2) global %s4 { i8* addrspacecast (i8 addrspace(2)* getelementptr ([1 x i8], [1 x i8] addrspace(2)* @c2, i32 0, i32 0) to i8*) }


; CHECK: .global  .align 1 [[$GLOB_C1:@[-a-zA-Z$._0-9]+]] = { .zero 1 };
; CHECK-NEXT: .const  .align 1 [[$CONST_C2:@[-a-zA-Z$._0-9]+]] = { .zero 1 };
; CHECK-NEXT: .global  .align 8 [[$GLOB_T1:@[-a-zA-Z$._0-9]+]] = { .64b @c1 };
; CHECK-NEXT: .const  .align 8 [[$CONST_T2:@[-a-zA-Z$._0-9]+]] = { .64b @c2 };
define i32 @private_to_generic(ptr addrspace(4) noundef nonnull %ptr) {
; CHECK-LABEL: .32b @private_to_generic(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	addrcast.generic.private 	[[R64_D0]], [[R32_W0]];
; CHECK-NEXT: 	ld.generic.32b	 [[R32_W1]], [[[R64_D0]]];
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @private_to_generic(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; O0: 	addrcast.generic.private 	[[R64_D0]], [[R32_W0]];
; O0-NEXT: 	ld.generic.32b	 [[R32_W1]], [[[R64_D0]]];
; O0-NEXT: 	return [[R32_W1]];
  %genptr = addrspacecast ptr addrspace(4) %ptr to ptr
  %val = load i32, ptr %genptr
  ret i32 %val
}

define i32 @global_to_generic(ptr addrspace(1) %ptr) {
; CHECK-LABEL: .32b @global_to_generic(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	addrcast.generic.global 	[[R64_D1]], [[R64_D0]];
; CHECK-NEXT: 	ld.generic.32b	 [[R32_W0]], [[[R64_D1]]];
; CHECK-NEXT: 	return [[R32_W0]];
;
; O0-LABEL: .32b @global_to_generic(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0: 	addrcast.generic.global 	[[R64_D1]], [[R64_D0]];
; O0-NEXT: 	ld.generic.32b	 [[R32_W0]], [[[R64_D1]]];
; O0-NEXT: 	return [[R32_W0]];
  %genptr = addrspacecast ptr addrspace (1) %ptr to ptr
  %val = load i32, ptr %genptr
  ret i32 %val
}

define i32 @const_to_generic(ptr addrspace (2) %ptr) {
; CHECK-LABEL: .32b @const_to_generic(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	addrcast.generic.const 	[[R64_D1]], [[R64_D0]];
; CHECK-NEXT: 	ld.generic.32b	 [[R32_W0]], [[[R64_D1]]];
; CHECK-NEXT: 	return [[R32_W0]];
;
; O0-LABEL: .32b @const_to_generic(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0: 	addrcast.generic.const 	[[R64_D1]], [[R64_D0]];
; O0-NEXT: 	ld.generic.32b	 [[R32_W0]], [[[R64_D1]]];
; O0-NEXT: 	return [[R32_W0]];
  %genptr = addrspacecast ptr addrspace (2) %ptr to ptr
  %val = load i32, ptr %genptr
  ret i32 %val
}

define i32 @shared_to_generic(ptr addrspace (3) noundef nonnull %ptr) {
; CHECK-LABEL: .32b @shared_to_generic(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	addrcast.generic.shared 	[[R64_D0]], [[R32_W0]];
; CHECK-NEXT: 	ld.generic.32b	 [[R32_W1]], [[[R64_D0]]];
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @shared_to_generic(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; O0: 	addrcast.generic.shared 	[[R64_D0]], [[R32_W0]];
; O0-NEXT: 	ld.generic.32b	 [[R32_W1]], [[[R64_D0]]];
; O0-NEXT: 	return [[R32_W1]];
  %genptr = addrspacecast ptr addrspace (3) %ptr to ptr
  %val = load i32, ptr %genptr
  ret i32 %val
}

define i32 @generic_to_private(ptr noundef nonnull %gen) {
; CHECK-LABEL: .32b @generic_to_private(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	addrcast.private.generic 	[[R32_W0]], [[R64_D0]];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W1]], [[[R32_W0]]];
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @generic_to_private(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	addrcast.private.generic 	[[R32_W0]], [[R64_D0]];
; O0-NEXT: 	ld.private.32b	 [[R32_W1]], [[[R32_W0]]];
; O0-NEXT: 	return [[R32_W1]];
  %ptr = addrspacecast ptr %gen to ptr addrspace(4)
  %val = load i32, ptr addrspace(4) %ptr
  ret i32 %val
}

define i32 @generic_to_global(ptr %gen) {
; CHECK-LABEL: .32b @generic_to_global(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	addrcast.global.generic 	[[R64_D1]], [[R64_D0]];
; CHECK-NEXT: 	ld.global.32b	 [[R32_W0]], [[[R64_D1]]];
; CHECK-NEXT: 	return [[R32_W0]];
;
; O0-LABEL: .32b @generic_to_global(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0: 	addrcast.global.generic 	[[R64_D1]], [[R64_D0]];
; O0-NEXT: 	ld.global.32b	 [[R32_W0]], [[[R64_D1]]];
; O0-NEXT: 	return [[R32_W0]];
  %ptr = addrspacecast ptr %gen to ptr addrspace(1)
  %val = load i32, ptr addrspace(1) %ptr
  ret i32 %val
}

define i32 @generic_to_shared(ptr noundef nonnull %gen) {
; CHECK-LABEL: .32b @generic_to_shared(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	addrcast.shared.generic 	[[R32_W0]], [[R64_D0]];
; CHECK-NEXT: 	ld.shared.32b	 [[R32_W1]], [[[R32_W0]]];
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @generic_to_shared(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	addrcast.shared.generic 	[[R32_W0]], [[R64_D0]];
; O0-NEXT: 	ld.shared.32b	 [[R32_W1]], [[[R32_W0]]];
; O0-NEXT: 	return [[R32_W1]];
  %ptr = addrspacecast ptr %gen to ptr addrspace(3)
  %val = load i32, ptr addrspace(3) %ptr
  ret i32 %val
}

define <2 x ptr addrspace (3)> @generic_to_shared_vector(<2 x ptr> %gen) {
; CHECK-LABEL: .v2.32b @generic_to_shared_vector(
; CHECK-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	addrcast.shared.generic 	[[VR2_32_V2W0]].x, [[VR2_64_V2D0]].x;
; CHECK-NEXT: 	addrcast.shared.generic 	[[VR2_32_V2W0]].y, [[VR2_64_V2D0]].y;
; CHECK-NEXT: 	return [[VR2_32_V2W0]];
;
; O0-LABEL: .v2.32b @generic_to_shared_vector(
; O0-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]], [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.64b 	[[R64_D0]], [[VR2_64_V2D0]].x;
; O0-NEXT: 	mov.64b 	[[R64_D1]], [[VR2_64_V2D0]].y;
; O0-NEXT: 	addrcast.shared.generic 	[[R32_W0]], [[R64_D0]];
; O0-NEXT: 	addrcast.shared.generic 	[[R32_W1]], [[R64_D1]];
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W0]].x, [[R32_W0]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W1]].xy, [[VR2_32_V2W0]].xy;
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W1]].y, [[R32_W1]];
; O0-NEXT: 	return [[VR2_32_V2W1]];
  %ptr = addrspacecast <2 x ptr> %gen to <2 x ptr addrspace(3)>
  ret <2 x ptr addrspace(3)> %ptr
}
