; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -verify-machineinstrs -march=pisa | FileCheck %s
; RUN: llc < %s -verify-machineinstrs -march=pisa > %t.pisa
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

; CHECK-LABEL: @iatom_add_hint
; CHECK: iatom.global.acq_rel.system.add.16b
; CHECK: iatom.global.acq_rel.system.uc.add.16b
; CHECK: iatom.global.acq_rel.system.L3wb.add.16b
; CHECK: iatom.global.acq_rel.system.L2wb.add.16b
define i16 @iatom_add_hint(ptr addrspace(1) %ptr, i16 %a) {
; O0-LABEL: .16b @iatom_add_hint(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; O0: 	iatom.global.acq_rel.system.add.16b	 [[R16_H1]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	iatom.global.acq_rel.system.uc.add.16b	 [[R16_H2]], [[[R64_D0]]], [[R16_H1]];
; O0-NEXT: 	iatom.global.acq_rel.system.L3wb.add.16b	 [[R16_H3]], [[[R64_D0]]], [[R16_H2]];
; O0-NEXT: 	iatom.global.acq_rel.system.L2wb.add.16b	 [[R16_H4]], [[[R64_D0]]], [[R16_H3]];
; O0-NEXT: 	return [[R16_H4]];
  %b = atomicrmw add ptr addrspace(1) %ptr, i16 %a acq_rel, align 2, !mmra !0
  %c = atomicrmw add ptr addrspace(1) %ptr, i16 %b acq_rel, align 2, !mmra !2
  %d = atomicrmw add ptr addrspace(1) %ptr, i16 %c acq_rel, align 2, !mmra !3
  %e = atomicrmw add ptr addrspace(1) %ptr, i16 %d acq_rel, align 2, !mmra !4
  ret i16 %e
}

; CHECK-LABEL: @fatom_add_hint
; CHECK: fatom.global.acq_rel.system.add.f
; CHECK: fatom.global.acq_rel.system.uc.add.f
; CHECK: fatom.global.acq_rel.system.L3wb.add.f
; CHECK: fatom.global.acq_rel.system.L2wb.add.f
define float @fatom_add_hint(ptr addrspace(1) %ptr, float %a) {
; O0-LABEL: .32b @fatom_add_hint(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.acq_rel.system.add.f	 [[R32_W1]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.global.acq_rel.system.uc.add.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W1]];
; O0-NEXT: 	fatom.global.acq_rel.system.L3wb.add.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W2]];
; O0-NEXT: 	fatom.global.acq_rel.system.L2wb.add.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W3]];
; O0-NEXT: 	return [[R32_W4]];
  %b = atomicrmw fadd ptr addrspace(1) %ptr, float %a acq_rel, align 4, !mmra !0
  %c = atomicrmw fadd ptr addrspace(1) %ptr, float %b acq_rel, align 4, !mmra !2
  %d = atomicrmw fadd ptr addrspace(1) %ptr, float %c acq_rel, align 4, !mmra !3
  %e = atomicrmw fadd ptr addrspace(1) %ptr, float %d acq_rel, align 4, !mmra !4
  ret float %e
}

; CHECK-LABEL: @fatom_cas_hint
; CHECK: fatom.global.acq_rel.system.cas.f
; CHECK: fatom.global.acq_rel.system.uc.cas.f
; CHECK: fatom.global.acq_rel.system.L3wb.cas.f
; CHECK: fatom.global.acq_rel.system.L2wb.cas.f
define float @fatom_cas_hint(ptr addrspace(1) %ptr, float %a, float %b) {
; O0-LABEL: .32b @fatom_cas_hint(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.acq_rel.system.cas.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	fatom.global.acq_rel.system.uc.cas.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W1]], [[R32_W2]];
; O0-NEXT: 	fatom.global.acq_rel.system.L3wb.cas.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W2]], [[R32_W3]];
; O0-NEXT: 	fatom.global.acq_rel.system.L2wb.cas.f	 [[R32_W5]], [[[R64_D0]]], [[R32_W3]], [[R32_W4]];
; O0-NEXT: 	return [[R32_W5]];
  %c = call float @llvm.pisa.cas.fatom.f32.p1(ptr addrspace(1) %ptr, float %a, float %b, i8 6), !mmra !0
  %d = call float @llvm.pisa.cas.fatom.f32.p1(ptr addrspace(1) %ptr, float %b, float %c, i8 6), !mmra !2
  %e = call float @llvm.pisa.cas.fatom.f32.p1(ptr addrspace(1) %ptr, float %c, float %d, i8 6), !mmra !3
  %f = call float @llvm.pisa.cas.fatom.f32.p1(ptr addrspace(1) %ptr, float %d, float %e, i8 6), !mmra !4
  ret float %f
}

; CHECK-LABEL: @fatom_cas_hint_bf
; CHECK: fatom.global.acq_rel.system.cas.bf
; CHECK: fatom.global.acq_rel.system.uc.cas.bf
; CHECK: fatom.global.acq_rel.system.L3wb.cas.bf
; CHECK: fatom.global.acq_rel.system.L2wb.cas.bf
define bfloat @fatom_cas_hint_bf(ptr addrspace(1) %ptr, bfloat %a, bfloat %b) {
; O0-LABEL: .16b @fatom_cas_hint_bf(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H5:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.acq_rel.system.cas.bf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]], [[R16_H1]];
; O0-NEXT: 	fatom.global.acq_rel.system.uc.cas.bf	 [[R16_H3]], [[[R64_D0]]], [[R16_H1]], [[R16_H2]];
; O0-NEXT: 	fatom.global.acq_rel.system.L3wb.cas.bf	 [[R16_H4]], [[[R64_D0]]], [[R16_H2]], [[R16_H3]];
; O0-NEXT: 	fatom.global.acq_rel.system.L2wb.cas.bf	 [[R16_H5]], [[[R64_D0]]], [[R16_H3]], [[R16_H4]];
; O0-NEXT: 	return [[R16_H5]];
  %c = call bfloat @llvm.pisa.cas.fatom.bf16.p1(ptr addrspace(1) %ptr, bfloat %a, bfloat %b, i8 6), !mmra !0
  %d = call bfloat @llvm.pisa.cas.fatom.bf16.p1(ptr addrspace(1) %ptr, bfloat %b, bfloat %c, i8 6), !mmra !2
  %e = call bfloat @llvm.pisa.cas.fatom.bf16.p1(ptr addrspace(1) %ptr, bfloat %c, bfloat %d, i8 6), !mmra !3
  %f = call bfloat @llvm.pisa.cas.fatom.bf16.p1(ptr addrspace(1) %ptr, bfloat %d, bfloat %e, i8 6), !mmra !4
  ret bfloat %f
}

; CHECK-LABEL: @iatom_cas_hint
; CHECK: iatom.global.acq_rel.system.cas.32b
; CHECK: iatom.global.acq_rel.system.uc.cas.32b
; CHECK: iatom.global.acq_rel.system.L3wb.cas.32b
; CHECK: iatom.global.acq_rel.system.L2wb.cas.32b
define i32 @iatom_cas_hint(ptr addrspace(1) %ptr, i32 %a, i32 %b) {
; O0-LABEL: .32b @iatom_cas_hint(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]];
; O0: 	iatom.global.acq_rel.system.cas.32b	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	iatom.global.acq_rel.system.uc.cas.32b	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	iatom.global.acq_rel.system.L3wb.cas.32b	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	iatom.global.acq_rel.system.L2wb.cas.32b	 [[R32_W5]], [[[R64_D0]]], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	return [[R32_W0]];
  %c = cmpxchg ptr addrspace(1) %ptr, i32 %a, i32 %b acq_rel monotonic, !mmra !0
  %d = cmpxchg ptr addrspace(1) %ptr, i32 %a, i32 %b acq_rel monotonic, !mmra !2
  %e = cmpxchg ptr addrspace(1) %ptr, i32 %a, i32 %b acq_rel monotonic, !mmra !3
  %f = cmpxchg ptr addrspace(1) %ptr, i32 %a, i32 %b acq_rel monotonic, !mmra !4
  ret i32 %a
}

!0 = !{!"pisa.cache.ctrl", !"0"}
!1 = !{i32 1}
!2 = !{!"pisa.cache.ctrl", !"2"}
!3 = !{!"pisa.cache.ctrl", !"3"}
!4 = !{!"pisa.cache.ctrl", !"4"}
