; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -verify-machineinstrs -march=pisa | FileCheck %s
; RUN: llc < %s -verify-machineinstrs -march=pisa > %t.pisa
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

define void @fatom_global_16b_relaxed(ptr addrspace(1) %ptr, half %a)
; CHECK-LABEL: void @fatom_global_16b_relaxed(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.global.relaxed.add.hf	 [[R16_H1]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.global.relaxed.sub.hf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.global.relaxed.min.hf	 [[R16_H3]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.global.relaxed.max.hf	 [[R16_H4]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_global_16b_relaxed(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.relaxed.add.hf	 [[R16_H1]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.global.relaxed.sub.hf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.global.relaxed.min.hf	 [[R16_H3]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.global.relaxed.max.hf	 [[R16_H4]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(1) %ptr, half %a monotonic
  %res8 = atomicrmw fsub ptr addrspace(1) %ptr, half %a monotonic
  %res9 = atomicrmw fmin ptr addrspace(1) %ptr, half %a monotonic
  %res10 = atomicrmw fmax ptr addrspace(1) %ptr, half %a monotonic

  ret void
}

define void @fatom_shared_16b_relaxed(ptr addrspace(3) %ptr, half %a)
; CHECK-LABEL: void @fatom_shared_16b_relaxed(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.shared.relaxed.add.hf	 [[R16_H1]], [[[R32_W0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.shared.relaxed.sub.hf	 [[R16_H2]], [[[R32_W0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.shared.relaxed.min.hf	 [[R16_H3]], [[[R32_W0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.shared.relaxed.max.hf	 [[R16_H4]], [[[R32_W0]]], [[R16_H0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_shared_16b_relaxed(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.shared.relaxed.add.hf	 [[R16_H1]], [[[R32_W0]]], [[R16_H0]];
; O0-NEXT: 	fatom.shared.relaxed.sub.hf	 [[R16_H2]], [[[R32_W0]]], [[R16_H0]];
; O0-NEXT: 	fatom.shared.relaxed.min.hf	 [[R16_H3]], [[[R32_W0]]], [[R16_H0]];
; O0-NEXT: 	fatom.shared.relaxed.max.hf	 [[R16_H4]], [[[R32_W0]]], [[R16_H0]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(3) %ptr, half %a monotonic
  %res8 = atomicrmw fsub ptr addrspace(3) %ptr, half %a monotonic
  %res9 = atomicrmw fmin ptr addrspace(3) %ptr, half %a monotonic
  %res10 = atomicrmw fmax ptr addrspace(3) %ptr, half %a monotonic

  ret void
}

define void @fatom_generic_16b_relaxed(ptr %ptr, half %a)
; CHECK-LABEL: void @fatom_generic_16b_relaxed(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.generic.relaxed.add.hf	 [[R16_H1]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.generic.relaxed.sub.hf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.generic.relaxed.min.hf	 [[R16_H3]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.generic.relaxed.max.hf	 [[R16_H4]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_generic_16b_relaxed(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.generic.relaxed.add.hf	 [[R16_H1]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.generic.relaxed.sub.hf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.generic.relaxed.min.hf	 [[R16_H3]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.generic.relaxed.max.hf	 [[R16_H4]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr %ptr, half %a monotonic
  %res8 = atomicrmw fsub ptr %ptr, half %a monotonic
  %res9 = atomicrmw fmin ptr %ptr, half %a monotonic
  %res10 = atomicrmw fmax ptr %ptr, half %a monotonic

  ret void
}

define void @fatom_global_16b_acq_rel(ptr addrspace(1) %ptr, half %a, half %b)
; CHECK-LABEL: void @fatom_global_16b_acq_rel(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H6:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.global.acq_rel.system.add.hf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.global.acq_rel.system.sub.hf	 [[R16_H3]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.global.acq_rel.system.min.hf	 [[R16_H4]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.global.acq_rel.system.max.hf	 [[R16_H5]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.global.relaxed.cas.hf	 [[R16_H6]], [[[R64_D0]]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_global_16b_acq_rel(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H6:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.acq_rel.system.add.hf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.global.acq_rel.system.sub.hf	 [[R16_H3]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.global.acq_rel.system.min.hf	 [[R16_H4]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.global.acq_rel.system.max.hf	 [[R16_H5]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.global.relaxed.cas.hf	 [[R16_H6]], [[[R64_D0]]], [[R16_H0]], [[R16_H1]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(1) %ptr, half %a acq_rel
  %res8 = atomicrmw fsub ptr addrspace(1) %ptr, half %a acq_rel
  %res9 = atomicrmw fmin ptr addrspace(1) %ptr, half %a acq_rel
  %res10 = atomicrmw fmax ptr addrspace(1) %ptr, half %a acq_rel
  %res11 = call half @llvm.pisa.cas.fatom.f16.p1(ptr addrspace(1) %ptr, half %a, half %b, i8 2)

  ret void
}

define void @fatom_shared_16b_acq_rel(ptr addrspace(3) %ptr, half %a, half %b)
; CHECK-LABEL: void @fatom_shared_16b_acq_rel(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H6:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.shared.acq_rel.system.add.hf	 [[R16_H2]], [[[R32_W0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.shared.acq_rel.system.sub.hf	 [[R16_H3]], [[[R32_W0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.shared.acq_rel.system.min.hf	 [[R16_H4]], [[[R32_W0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.shared.acq_rel.system.max.hf	 [[R16_H5]], [[[R32_W0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.shared.acquire.system.cas.hf	 [[R16_H6]], [[[R32_W0]]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_shared_16b_acq_rel(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H6:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.shared.acq_rel.system.add.hf	 [[R16_H2]], [[[R32_W0]]], [[R16_H0]];
; O0-NEXT: 	fatom.shared.acq_rel.system.sub.hf	 [[R16_H3]], [[[R32_W0]]], [[R16_H0]];
; O0-NEXT: 	fatom.shared.acq_rel.system.min.hf	 [[R16_H4]], [[[R32_W0]]], [[R16_H0]];
; O0-NEXT: 	fatom.shared.acq_rel.system.max.hf	 [[R16_H5]], [[[R32_W0]]], [[R16_H0]];
; O0-NEXT: 	fatom.shared.acquire.system.cas.hf	 [[R16_H6]], [[[R32_W0]]], [[R16_H0]], [[R16_H1]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(3) %ptr, half %a acq_rel
  %res8 = atomicrmw fsub ptr addrspace(3) %ptr, half %a acq_rel
  %res9 = atomicrmw fmin ptr addrspace(3) %ptr, half %a acq_rel
  %res10 = atomicrmw fmax ptr addrspace(3) %ptr, half %a acq_rel
  %res11 = call half @llvm.pisa.cas.fatom.f16.p3(ptr addrspace(3) %ptr, half %a, half %b, i8 4)

  ret void
}

define void @fatom_generic_16b_acq_rel(ptr %ptr, half %a, half %b)
; CHECK-LABEL: void @fatom_generic_16b_acq_rel(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H6:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.generic.acq_rel.system.add.hf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.generic.acq_rel.system.sub.hf	 [[R16_H3]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.generic.acq_rel.system.min.hf	 [[R16_H4]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.generic.acq_rel.system.max.hf	 [[R16_H5]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.generic.release.system.cas.hf	 [[R16_H6]], [[[R64_D0]]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_generic_16b_acq_rel(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H6:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.generic.acq_rel.system.add.hf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.generic.acq_rel.system.sub.hf	 [[R16_H3]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.generic.acq_rel.system.min.hf	 [[R16_H4]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.generic.acq_rel.system.max.hf	 [[R16_H5]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.generic.release.system.cas.hf	 [[R16_H6]], [[[R64_D0]]], [[R16_H0]], [[R16_H1]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr %ptr, half %a acq_rel
  %res8 = atomicrmw fsub ptr %ptr, half %a acq_rel
  %res9 = atomicrmw fmin ptr %ptr, half %a acq_rel
  %res10 = atomicrmw fmax ptr %ptr, half %a acq_rel
  %res11 = call half @llvm.pisa.cas.fatom.f16.p4(ptr %ptr, half %a, half %b, i8 5)

  ret void
}

define void @fatom_global_acq_rel_bf(ptr addrspace(1) %ptr, bfloat %a, bfloat %b) {
; CHECK-LABEL: void @fatom_global_acq_rel_bf(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.global.acq_rel.system.cas.bf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_global_acq_rel_bf(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.acq_rel.system.cas.bf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]], [[R16_H1]];
; O0-NEXT: 	return;
  %res0 = call bfloat @llvm.pisa.cas.fatom.bf16.p1(ptr addrspace(1) %ptr, bfloat %a, bfloat %b, i8 6)
  ret void
}

define void @fatom_shared_acq_rel_bf(ptr addrspace(3) %ptr, bfloat %a, bfloat %b) {
; CHECK-LABEL: void @fatom_shared_acq_rel_bf(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.shared.acq_rel.system.cas.bf	 [[R16_H2]], [[[R32_W0]]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_shared_acq_rel_bf(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.shared.acq_rel.system.cas.bf	 [[R16_H2]], [[[R32_W0]]], [[R16_H0]], [[R16_H1]];
; O0-NEXT: 	return;
  %res0 = call bfloat @llvm.pisa.cas.fatom.bf16.p3(ptr addrspace(3) %ptr, bfloat %a, bfloat %b, i8 6)
  ret void
}

define void @fatom_generic_acq_rel_bf(ptr %ptr, bfloat %a, bfloat %b) {
; CHECK-LABEL: void @fatom_generic_acq_rel_bf(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.generic.acq_rel.system.cas.bf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_generic_acq_rel_bf(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.generic.acq_rel.system.cas.bf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]], [[R16_H1]];
; O0-NEXT: 	return;
  %res0 = call bfloat @llvm.pisa.cas.fatom.bf16.p4(ptr %ptr, bfloat %a, bfloat %b, i8 6)
  ret void
}

define void @fatom_global_32b_relaxed(ptr addrspace(1) %ptr, float %a)
; CHECK-LABEL: void @fatom_global_32b_relaxed(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.global.relaxed.add.f	 [[R32_W1]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.global.relaxed.sub.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.global.relaxed.min.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.global.relaxed.max.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_global_32b_relaxed(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.relaxed.add.f	 [[R32_W1]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.global.relaxed.sub.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.global.relaxed.min.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.global.relaxed.max.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(1) %ptr, float %a monotonic
  %res8 = atomicrmw fsub ptr addrspace(1) %ptr, float %a monotonic
  %res9 = atomicrmw fmin ptr addrspace(1) %ptr, float %a monotonic
  %res10 = atomicrmw fmax ptr addrspace(1) %ptr, float %a monotonic

  ret void
}

define void @fatom_shared_32b_relaxed(ptr addrspace(3) %ptr, float %a)
; CHECK-LABEL: void @fatom_shared_32b_relaxed(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.shared.relaxed.add.f	 [[R32_W2]], [[[R32_W0]]], [[R32_W1]];
; CHECK-NEXT: 	fatom.shared.relaxed.sub.f	 [[R32_W3]], [[[R32_W0]]], [[R32_W1]];
; CHECK-NEXT: 	fatom.shared.relaxed.min.f	 [[R32_W4]], [[[R32_W0]]], [[R32_W1]];
; CHECK-NEXT: 	fatom.shared.relaxed.max.f	 [[R32_W5]], [[[R32_W0]]], [[R32_W1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_shared_32b_relaxed(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.shared.relaxed.add.f	 [[R32_W2]], [[[R32_W0]]], [[R32_W1]];
; O0-NEXT: 	fatom.shared.relaxed.sub.f	 [[R32_W3]], [[[R32_W0]]], [[R32_W1]];
; O0-NEXT: 	fatom.shared.relaxed.min.f	 [[R32_W4]], [[[R32_W0]]], [[R32_W1]];
; O0-NEXT: 	fatom.shared.relaxed.max.f	 [[R32_W5]], [[[R32_W0]]], [[R32_W1]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(3) %ptr, float %a monotonic
  %res8 = atomicrmw fsub ptr addrspace(3) %ptr, float %a monotonic
  %res9 = atomicrmw fmin ptr addrspace(3) %ptr, float %a monotonic
  %res10 = atomicrmw fmax ptr addrspace(3) %ptr, float %a monotonic

  ret void
}

define void @fatom_generic_32b_relaxed(ptr %ptr, float %a)
; CHECK-LABEL: void @fatom_generic_32b_relaxed(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.generic.relaxed.add.f	 [[R32_W1]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.generic.relaxed.sub.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.generic.relaxed.min.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.generic.relaxed.max.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_generic_32b_relaxed(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.generic.relaxed.add.f	 [[R32_W1]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.generic.relaxed.sub.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.generic.relaxed.min.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.generic.relaxed.max.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr %ptr, float %a monotonic
  %res8 = atomicrmw fsub ptr %ptr, float %a monotonic
  %res9 = atomicrmw fmin ptr %ptr, float %a monotonic
  %res10 = atomicrmw fmax ptr %ptr, float %a monotonic

  ret void
}

define void @fatom_global_32b_acq_rel(ptr addrspace(1) %ptr, float %a, float %b)
; CHECK-LABEL: void @fatom_global_32b_acq_rel(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]], [[R32_W6:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.global.acq_rel.system.add.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.global.acq_rel.system.sub.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.global.acq_rel.system.min.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.global.acq_rel.system.max.f	 [[R32_W5]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.global.release.system.cas.f	 [[R32_W6]], [[[R64_D0]]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_global_32b_acq_rel(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]], [[R32_W6:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.acq_rel.system.add.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.global.acq_rel.system.sub.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.global.acq_rel.system.min.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.global.acq_rel.system.max.f	 [[R32_W5]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.global.release.system.cas.f	 [[R32_W6]], [[[R64_D0]]], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(1) %ptr, float %a acq_rel
  %res8 = atomicrmw fsub ptr addrspace(1) %ptr, float %a acq_rel
  %res9 = atomicrmw fmin ptr addrspace(1) %ptr, float %a acq_rel
  %res10 = atomicrmw fmax ptr addrspace(1) %ptr, float %a acq_rel
  %res11 = call float @llvm.pisa.cas.fatom.f32.p1(ptr addrspace(1) %ptr, float %a, float %b, i8 5)

  ret void
}

define void @fatom_shared_32b_acq_rel(ptr addrspace(3) %ptr, float %a, float %b)
; CHECK-LABEL: void @fatom_shared_32b_acq_rel(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]], [[R32_W6:%[-a-zA-Z$._0-9]+]], [[R32_W7:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.shared.acq_rel.system.add.f	 [[R32_W3]], [[[R32_W0]]], [[R32_W1]];
; CHECK-NEXT: 	fatom.shared.acq_rel.system.sub.f	 [[R32_W4]], [[[R32_W0]]], [[R32_W1]];
; CHECK-NEXT: 	fatom.shared.acq_rel.system.min.f	 [[R32_W5]], [[[R32_W0]]], [[R32_W1]];
; CHECK-NEXT: 	fatom.shared.acq_rel.system.max.f	 [[R32_W6]], [[[R32_W0]]], [[R32_W1]];
; CHECK-NEXT: 	fatom.shared.acquire.system.cas.f	 [[R32_W7]], [[[R32_W0]]], [[R32_W1]], [[R32_W2]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_shared_32b_acq_rel(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]], [[R32_W6:%[-a-zA-Z$._0-9]+]], [[R32_W7:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.shared.acq_rel.system.add.f	 [[R32_W3]], [[[R32_W0]]], [[R32_W1]];
; O0-NEXT: 	fatom.shared.acq_rel.system.sub.f	 [[R32_W4]], [[[R32_W0]]], [[R32_W1]];
; O0-NEXT: 	fatom.shared.acq_rel.system.min.f	 [[R32_W5]], [[[R32_W0]]], [[R32_W1]];
; O0-NEXT: 	fatom.shared.acq_rel.system.max.f	 [[R32_W6]], [[[R32_W0]]], [[R32_W1]];
; O0-NEXT: 	fatom.shared.acquire.system.cas.f	 [[R32_W7]], [[[R32_W0]]], [[R32_W1]], [[R32_W2]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(3) %ptr, float %a acq_rel
  %res8 = atomicrmw fsub ptr addrspace(3) %ptr, float %a acq_rel
  %res9 = atomicrmw fmin ptr addrspace(3) %ptr, float %a acq_rel
  %res10 = atomicrmw fmax ptr addrspace(3) %ptr, float %a acq_rel
  %res11 = call float @llvm.pisa.cas.fatom.f32.p3(ptr addrspace(3) %ptr, float %a, float %b, i8 4)

  ret void
}

define void @fatom_generic_32b_acq_rel(ptr %ptr, float %a, float %b)
; CHECK-LABEL: void @fatom_generic_32b_acq_rel(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]], [[R32_W6:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.generic.acq_rel.system.add.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.generic.acq_rel.system.sub.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.generic.acq_rel.system.min.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.generic.acq_rel.system.max.f	 [[R32_W5]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.generic.relaxed.cas.f	 [[R32_W6]], [[[R64_D0]]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_generic_32b_acq_rel(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]], [[R32_W6:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.generic.acq_rel.system.add.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.generic.acq_rel.system.sub.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.generic.acq_rel.system.min.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.generic.acq_rel.system.max.f	 [[R32_W5]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.generic.relaxed.cas.f	 [[R32_W6]], [[[R64_D0]]], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr %ptr, float %a acq_rel
  %res8 = atomicrmw fsub ptr %ptr, float %a acq_rel
  %res9 = atomicrmw fmin ptr %ptr, float %a acq_rel
  %res10 = atomicrmw fmax ptr %ptr, float %a acq_rel
  %res11 = call float @llvm.pisa.cas.fatom.f32.p4(ptr %ptr, float %a, float %b, i8 2)

  ret void
}

define void @fatom_global_32b_seq_cst(ptr addrspace(1) %ptr, float %a, float %b)
; CHECK-LABEL: void @fatom_global_32b_seq_cst(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fence.global.seq_cst.gpu;
; CHECK-NEXT: 	fatom.global.relaxed.add.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fence.global.seq_cst.gpu;
; CHECK-NEXT: 	fatom.global.relaxed.sub.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fence.global.seq_cst.gpu;
; CHECK-NEXT: 	fatom.global.relaxed.min.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fence.global.seq_cst.gpu;
; CHECK-NEXT: 	fatom.global.relaxed.max.f	 [[R32_W5]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fence.global.seq_cst.gpu;
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_global_32b_seq_cst(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]];
; O0: 	fence.global.seq_cst.gpu;
; O0-NEXT: 	fatom.global.relaxed.add.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fence.global.seq_cst.gpu;
; O0-NEXT: 	fence.global.seq_cst.gpu;
; O0-NEXT: 	fatom.global.relaxed.sub.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fence.global.seq_cst.gpu;
; O0-NEXT: 	fence.global.seq_cst.gpu;
; O0-NEXT: 	fatom.global.relaxed.min.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fence.global.seq_cst.gpu;
; O0-NEXT: 	fence.global.seq_cst.gpu;
; O0-NEXT: 	fatom.global.relaxed.max.f	 [[R32_W5]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fence.global.seq_cst.gpu;
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(1) %ptr, float %a seq_cst
  %res8 = atomicrmw fsub ptr addrspace(1) %ptr, float %a seq_cst
  %res9 = atomicrmw fmin ptr addrspace(1) %ptr, float %a seq_cst
  %res10 = atomicrmw fmax ptr addrspace(1) %ptr, float %a seq_cst

  ret void
}

define void @fatom_shared_32b_seq_cst(ptr addrspace(3) %ptr, float %a, float %b)
; CHECK-LABEL: void @fatom_shared_32b_seq_cst(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]], [[R32_W6:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fence.shared.seq_cst.gpu;
; CHECK-NEXT: 	fatom.shared.relaxed.add.f	 [[R32_W3]], [[[R32_W0]]], [[R32_W1]];
; CHECK-NEXT: 	fence.shared.seq_cst.gpu;
; CHECK-NEXT: 	fatom.shared.relaxed.sub.f	 [[R32_W4]], [[[R32_W0]]], [[R32_W1]];
; CHECK-NEXT: 	fence.shared.seq_cst.gpu;
; CHECK-NEXT: 	fatom.shared.relaxed.min.f	 [[R32_W5]], [[[R32_W0]]], [[R32_W1]];
; CHECK-NEXT: 	fence.shared.seq_cst.gpu;
; CHECK-NEXT: 	fatom.shared.relaxed.max.f	 [[R32_W6]], [[[R32_W0]]], [[R32_W1]];
; CHECK-NEXT: 	fence.shared.seq_cst.gpu;
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_shared_32b_seq_cst(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]], [[R32_W6:%[-a-zA-Z$._0-9]+]];
; O0: 	fence.shared.seq_cst.gpu;
; O0-NEXT: 	fatom.shared.relaxed.add.f	 [[R32_W3]], [[[R32_W0]]], [[R32_W1]];
; O0-NEXT: 	fence.shared.seq_cst.gpu;
; O0-NEXT: 	fence.shared.seq_cst.gpu;
; O0-NEXT: 	fatom.shared.relaxed.sub.f	 [[R32_W4]], [[[R32_W0]]], [[R32_W1]];
; O0-NEXT: 	fence.shared.seq_cst.gpu;
; O0-NEXT: 	fence.shared.seq_cst.gpu;
; O0-NEXT: 	fatom.shared.relaxed.min.f	 [[R32_W5]], [[[R32_W0]]], [[R32_W1]];
; O0-NEXT: 	fence.shared.seq_cst.gpu;
; O0-NEXT: 	fence.shared.seq_cst.gpu;
; O0-NEXT: 	fatom.shared.relaxed.max.f	 [[R32_W6]], [[[R32_W0]]], [[R32_W1]];
; O0-NEXT: 	fence.shared.seq_cst.gpu;
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(3) %ptr, float %a seq_cst
  %res8 = atomicrmw fsub ptr addrspace(3) %ptr, float %a seq_cst
  %res9 = atomicrmw fmin ptr addrspace(3) %ptr, float %a seq_cst
  %res10 = atomicrmw fmax ptr addrspace(3) %ptr, float %a seq_cst

  ret void
}

define void @fatom_generic_32b_seq_cst(ptr %ptr, float %a, float %b)
; CHECK-LABEL: void @fatom_generic_32b_seq_cst(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fence.generic.seq_cst.gpu;
; CHECK-NEXT: 	fatom.generic.relaxed.add.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fence.generic.seq_cst.gpu;
; CHECK-NEXT: 	fatom.generic.relaxed.sub.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fence.generic.seq_cst.gpu;
; CHECK-NEXT: 	fatom.generic.relaxed.min.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fence.generic.seq_cst.gpu;
; CHECK-NEXT: 	fatom.generic.relaxed.max.f	 [[R32_W5]], [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fence.generic.seq_cst.gpu;
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_generic_32b_seq_cst(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]];
; O0: 	fence.generic.seq_cst.gpu;
; O0-NEXT: 	fatom.generic.relaxed.add.f	 [[R32_W2]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fence.generic.seq_cst.gpu;
; O0-NEXT: 	fence.generic.seq_cst.gpu;
; O0-NEXT: 	fatom.generic.relaxed.sub.f	 [[R32_W3]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fence.generic.seq_cst.gpu;
; O0-NEXT: 	fence.generic.seq_cst.gpu;
; O0-NEXT: 	fatom.generic.relaxed.min.f	 [[R32_W4]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fence.generic.seq_cst.gpu;
; O0-NEXT: 	fence.generic.seq_cst.gpu;
; O0-NEXT: 	fatom.generic.relaxed.max.f	 [[R32_W5]], [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fence.generic.seq_cst.gpu;
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr %ptr, float %a seq_cst
  %res8 = atomicrmw fsub ptr %ptr, float %a seq_cst
  %res9 = atomicrmw fmin ptr %ptr, float %a seq_cst
  %res10 = atomicrmw fmax ptr %ptr, float %a seq_cst

  ret void
}


define void @fatom_global_64b_relaxed(ptr addrspace(1) %ptr, double %a)
; CHECK-LABEL: void @fatom_global_64b_relaxed(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]], [[R64_D3:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.global.relaxed.add.df	 [[R64_D2]], [[[R64_D0]]], [[R64_D1]];
; CHECK-NEXT: 	fatom.global.relaxed.sub.df	 [[R64_D3]], [[[R64_D0]]], [[R64_D1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_global_64b_relaxed(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]], [[R64_D3:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.relaxed.add.df	 [[R64_D2]], [[[R64_D0]]], [[R64_D1]];
; O0-NEXT: 	fatom.global.relaxed.sub.df	 [[R64_D3]], [[[R64_D0]]], [[R64_D1]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(1) %ptr, double %a monotonic
  %res8 = atomicrmw fsub ptr addrspace(1) %ptr, double %a monotonic

  ret void
}

define void @fatom_global_64b_acq_rel(ptr addrspace(1) %ptr, double %a, double %b)
; CHECK-LABEL: void @fatom_global_64b_acq_rel(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D3:%[-a-zA-Z$._0-9]+]], [[R64_D4:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.global.acq_rel.system.add.df	 [[R64_D3]], [[[R64_D0]]], [[R64_D1]];
; CHECK-NEXT: 	fatom.global.acq_rel.system.sub.df	 [[R64_D4]], [[[R64_D0]]], [[R64_D1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_global_64b_acq_rel(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D3:%[-a-zA-Z$._0-9]+]], [[R64_D4:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.acq_rel.system.add.df	 [[R64_D3]], [[[R64_D0]]], [[R64_D1]];
; O0-NEXT: 	fatom.global.acq_rel.system.sub.df	 [[R64_D4]], [[[R64_D0]]], [[R64_D1]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(1) %ptr, double %a acq_rel
  %res8 = atomicrmw fsub ptr addrspace(1) %ptr, double %a acq_rel

  ret void
}

define float @fatom_global_reg_imm(ptr addrspace(1) %ptr, float %a)
; CHECK-LABEL: .32b @fatom_global_reg_imm(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.global.relaxed.add.f	 [[R32_W1]], [[[R64_D0]] + 8], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @fatom_global_reg_imm(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.relaxed.add.f	 [[R32_W1]], [[[R64_D0]] + 8], [[R32_W0]];
; O0-NEXT: 	return [[R32_W1]];
{
  %ptraddr1 = getelementptr [4 x i32], ptr addrspace(1) %ptr, i64 0, i64 2
  %res1 = atomicrmw fadd ptr addrspace(1) %ptraddr1, float %a monotonic

  ret float %res1
}

define float @fatom_cas_global_reg_imm(ptr addrspace(1) %ptr, float %a, float %b)
; CHECK-LABEL: .32b @fatom_cas_global_reg_imm(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.global.acq_rel.system.cas.f	 [[R32_W2]], [[[R64_D0]] + 8], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	return [[R32_W2]];
;
; O0-LABEL: .32b @fatom_cas_global_reg_imm(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.acq_rel.system.cas.f	 [[R32_W2]], [[[R64_D0]] + 8], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	return [[R32_W2]];
{
  %ptraddr1 = getelementptr [4 x i32], ptr addrspace(1) %ptr, i64 0, i64 2
  %res1 = call float @llvm.pisa.cas.fatom.f32.p1(ptr addrspace(1) %ptraddr1, float %a, float %b, i8 6)

  ret float %res1
}

define float @fatom_global_reg_reg(ptr addrspace(1) %ptr, i64 %a, float %b)
; CHECK-LABEL: .32b @fatom_global_reg_reg(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	shl.64b 	[[R64_D2]], [[R64_D1]], 2;
; CHECK-NEXT: 	fatom.global.relaxed.add.f	 [[R32_W1]], [[[R64_D0]] + [[R64_D2]]], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @fatom_global_reg_reg(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	smul.64b 	[[R64_D2]], [[R64_D1]], 4;
; O0-NEXT: 	fatom.global.relaxed.add.f	 [[R32_W1]], [[[R64_D0]] + [[R64_D2]]], [[R32_W0]];
; O0-NEXT: 	return [[R32_W1]];
{
  %ptraddr1 = getelementptr [4 x i32], ptr addrspace(1) %ptr, i64 0, i64 %a
  %res1 = atomicrmw fadd ptr addrspace(1) %ptraddr1, float %b monotonic

  ret float %res1
}

define pisa_kernel void @fatom_shared_var(float %a)
; CHECK-LABEL: @fatom_shared_var(
; CHECK-SAME: .param[4] .align(4) [[PARAM_ARG0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.shared .align 8 [[SHARED_R0:@[-a-zA-Z$._0-9]+]][8];
; CHECK: 	ld.param.32b [[R32_W0]], [[[PARAM_ARG0]]];
; CHECK-NEXT: 	fatom.shared.relaxed.add.f	 [[R32_W1]], [[[SHARED_R0]]], [[R32_W0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: @fatom_shared_var(
; O0-SAME: .param[4] .align(4) [[PARAM_ARG0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.shared .align 8 [[SHARED_R0:@[-a-zA-Z$._0-9]+]][8];
; O0: 	ld.param.32b [[R32_W0]], [[[PARAM_ARG0]]];
; O0-NEXT: 	fatom.shared.relaxed.add.f	 [[R32_W1]], [[[SHARED_R0]]], [[R32_W0]];
; O0-NEXT: 	return;
{
  %ptr1 = alloca ptr addrspace(1), addrspace(3)
  %res1 = atomicrmw fadd ptr addrspace(3) %ptr1, float %a monotonic

  ret void
}

define pisa_kernel void @fatom_cas_shared_var(float %a, float %b)
; CHECK-LABEL: @fatom_cas_shared_var(
; CHECK-SAME: .param[4] .align(4) [[PARAM_ARG0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .param[4] .align(4) [[PARAM_ARG1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.shared .align 8 [[SHARED_R0:@[-a-zA-Z$._0-9]+]][8];
; CHECK: 	ld.param.32b [[R32_W0]], [[[PARAM_ARG0]]];
; CHECK-NEXT: 	ld.param.32b [[R32_W1]], [[[PARAM_ARG1]]];
; CHECK-NEXT: 	fatom.shared.acq_rel.system.cas.f	 [[R32_W2]], [[[SHARED_R0]]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: @fatom_cas_shared_var(
; O0-SAME: .param[4] .align(4) [[PARAM_ARG0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .param[4] .align(4) [[PARAM_ARG1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.shared .align 8 [[SHARED_R0:@[-a-zA-Z$._0-9]+]][8];
; O0: 	ld.param.32b [[R32_W0]], [[[PARAM_ARG0]]];
; O0-NEXT: 	ld.param.32b [[R32_W1]], [[[PARAM_ARG1]]];
; O0-NEXT: 	fatom.shared.acq_rel.system.cas.f	 [[R32_W2]], [[[SHARED_R0]]], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	return;
{
  %ptr1 = alloca ptr addrspace(1), addrspace(3)
  %res1 = call float @llvm.pisa.cas.fatom.f32.p3(ptr addrspace(3) %ptr1, float %a, float %b, i8 6)

  ret void
}

define pisa_kernel void @fatom_shared_var_imm(float %a)
; CHECK-LABEL: @fatom_shared_var_imm(
; CHECK-SAME: .param[4] .align(4) [[PARAM_ARG0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.shared .align 8 [[SHARED_R0:@[-a-zA-Z$._0-9]+]][8];
; CHECK: 	ld.param.32b [[R32_W0]], [[[PARAM_ARG0]]];
; CHECK-NEXT: 	fatom.shared.relaxed.min.f	 [[R32_W1]], [[[SHARED_R0]] + 8], [[R32_W0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: @fatom_shared_var_imm(
; O0-SAME: .param[4] .align(4) [[PARAM_ARG0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.shared .align 8 [[SHARED_R0:@[-a-zA-Z$._0-9]+]][8];
; O0: 	ld.param.32b [[R32_W0]], [[[PARAM_ARG0]]];
; O0-NEXT: 	fatom.shared.relaxed.min.f	 [[R32_W1]], [[[SHARED_R0]] + 8], [[R32_W0]];
; O0-NEXT: 	return;
{
  %ptr1 = alloca ptr addrspace(1), addrspace(3)
  %ptraddr1 = getelementptr [4 x i32], ptr addrspace(3) %ptr1, i64 0, i64 2
  %res1 = atomicrmw fmin ptr addrspace(3) %ptraddr1, float %a monotonic

  ret void
}

define pisa_kernel void @fatom_cas_shared_var_imm(float %a, float %b)
; CHECK-LABEL: @fatom_cas_shared_var_imm(
; CHECK-SAME: .param[4] .align(4) [[PARAM_ARG0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .param[4] .align(4) [[PARAM_ARG1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.shared .align 8 [[SHARED_R0:@[-a-zA-Z$._0-9]+]][8];
; CHECK: 	ld.param.32b [[R32_W0]], [[[PARAM_ARG0]]];
; CHECK-NEXT: 	ld.param.32b [[R32_W1]], [[[PARAM_ARG1]]];
; CHECK-NEXT: 	fatom.shared.acq_rel.system.cas.f	 [[R32_W2]], [[[SHARED_R0]] + 8], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: @fatom_cas_shared_var_imm(
; O0-SAME: .param[4] .align(4) [[PARAM_ARG0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .param[4] .align(4) [[PARAM_ARG1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.shared .align 8 [[SHARED_R0:@[-a-zA-Z$._0-9]+]][8];
; O0: 	ld.param.32b [[R32_W0]], [[[PARAM_ARG0]]];
; O0-NEXT: 	ld.param.32b [[R32_W1]], [[[PARAM_ARG1]]];
; O0-NEXT: 	fatom.shared.acq_rel.system.cas.f	 [[R32_W2]], [[[SHARED_R0]] + 8], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	return;
{
  %ptr1 = alloca ptr addrspace(1), addrspace(3)
  %ptraddr1 = getelementptr [4 x i32], ptr addrspace(3) %ptr1, i64 0, i64 2
  %res1 = call float @llvm.pisa.cas.fatom.f32.p3(ptr addrspace(3) %ptraddr1, float %a, float %b, i8 6)

  ret void
}

define pisa_kernel void @fatom_shared_var_reg(float %a, i64 %b)
; CHECK-LABEL: @fatom_shared_var_reg(
; CHECK-SAME: .param[4] .align(4) [[PARAM_ARG0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .param[8] [[PARAM_ARG1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.shared .align 8 [[SHARED_R0:@[-a-zA-Z$._0-9]+]][8];
; CHECK: 	ld.param.32b [[R32_W0]], [[[PARAM_ARG0]]];
; CHECK-NEXT: 	ld.param.64b [[R64_D0]], [[[PARAM_ARG1]]];
; CHECK-NEXT: 	trunc.32b.64b 	[[R32_W1]], [[R64_D0]];
; CHECK-NEXT: 	shl.32b 	[[R32_W2]], [[R32_W1]], 2;
; CHECK-NEXT: 	fatom.shared.relaxed.sub.f	 [[R32_W3]], [[[SHARED_R0]] + [[R32_W2]]], [[R32_W0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: @fatom_shared_var_reg(
; O0-SAME: .param[4] .align(4) [[PARAM_ARG0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .param[8] [[PARAM_ARG1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.shared .align 8 [[SHARED_R0:@[-a-zA-Z$._0-9]+]][8];
; O0: 	ld.param.32b [[R32_W0]], [[[PARAM_ARG0]]];
; O0-NEXT: 	ld.param.64b [[R64_D0]], [[[PARAM_ARG1]]];
; O0-NEXT: 	trunc.32b.64b 	[[R32_W1]], [[R64_D0]];
; O0-NEXT: 	smul.32b 	[[R32_W2]], [[R32_W1]], 4;
; O0-NEXT: 	fatom.shared.relaxed.sub.f	 [[R32_W3]], [[[SHARED_R0]] + [[R32_W2]]], [[R32_W0]];
; O0-NEXT: 	return;
{
  %ptr1 = alloca ptr addrspace(1), addrspace(3)
  %ptraddr1 = getelementptr [4 x i32], ptr addrspace(3) %ptr1, i64 0, i64 %b
  %res1 = atomicrmw fsub ptr addrspace(3) %ptraddr1, float %a monotonic

  ret void
}

define pisa_kernel void @fatom_cas_shared_var_reg(float %a, i64 %b, float %c)
; CHECK-LABEL: @fatom_cas_shared_var_reg(
; CHECK-SAME: .param[4] .align(4) [[PARAM_ARG0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .param[8] [[PARAM_ARG1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .param[4] .align(4) [[PARAM_ARG2:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.shared .align 8 [[SHARED_R0:@[-a-zA-Z$._0-9]+]][8];
; CHECK: 	ld.param.32b [[R32_W0]], [[[PARAM_ARG0]]];
; CHECK-NEXT: 	ld.param.64b [[R64_D0]], [[[PARAM_ARG1]]];
; CHECK-NEXT: 	ld.param.32b [[R32_W1]], [[[PARAM_ARG2]]];
; CHECK-NEXT: 	trunc.32b.64b 	[[R32_W2]], [[R64_D0]];
; CHECK-NEXT: 	shl.32b 	[[R32_W3]], [[R32_W2]], 2;
; CHECK-NEXT: 	fatom.shared.acq_rel.system.cas.f	 [[R32_W4]], [[[SHARED_R0]] + [[R32_W3]]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: @fatom_cas_shared_var_reg(
; O0-SAME: .param[4] .align(4) [[PARAM_ARG0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .param[8] [[PARAM_ARG1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .param[4] .align(4) [[PARAM_ARG2:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.shared .align 8 [[SHARED_R0:@[-a-zA-Z$._0-9]+]][8];
; O0: 	ld.param.32b [[R32_W0]], [[[PARAM_ARG0]]];
; O0-NEXT: 	ld.param.64b [[R64_D0]], [[[PARAM_ARG1]]];
; O0-NEXT: 	ld.param.32b [[R32_W1]], [[[PARAM_ARG2]]];
; O0-NEXT: 	trunc.32b.64b 	[[R32_W2]], [[R64_D0]];
; O0-NEXT: 	smul.32b 	[[R32_W3]], [[R32_W2]], 4;
; O0-NEXT: 	fatom.shared.acq_rel.system.cas.f	 [[R32_W4]], [[[SHARED_R0]] + [[R32_W3]]], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	return;
{
  %ptr1 = alloca ptr addrspace(1), addrspace(3)
  %ptraddr1 = getelementptr [4 x i32], ptr addrspace(3) %ptr1, i64 0, i64 %b
  %res1 = call float @llvm.pisa.cas.fatom.f32.p3(ptr addrspace(3) %ptraddr1, float %a, float %c, i8 6)

  ret void
}

; - check for bf16 support
define void @fatom_global_16bf_relaxed(ptr addrspace(1) %ptr, bfloat %a)
; CHECK-LABEL: void @fatom_global_16bf_relaxed(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.global.relaxed.add.bf	 [[R16_H1]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.global.relaxed.sub.bf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.global.relaxed.min.bf	 [[R16_H3]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.global.relaxed.max.bf	 [[R16_H4]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_global_16bf_relaxed(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.global.relaxed.add.bf	 [[R16_H1]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.global.relaxed.sub.bf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.global.relaxed.min.bf	 [[R16_H3]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.global.relaxed.max.bf	 [[R16_H4]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(1) %ptr, bfloat %a monotonic
  %res8 = atomicrmw fsub ptr addrspace(1) %ptr, bfloat %a monotonic
  %res9 = atomicrmw fmin ptr addrspace(1) %ptr, bfloat %a monotonic
  %res10 = atomicrmw fmax ptr addrspace(1) %ptr, bfloat %a monotonic

  ret void
}

define void @fatom_shared_16bf_relaxed(ptr addrspace(3) %ptr, bfloat %a)
; CHECK-LABEL: void @fatom_shared_16bf_relaxed(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.shared.relaxed.add.bf	 [[R16_H1]], [[[R32_W0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.shared.relaxed.sub.bf	 [[R16_H2]], [[[R32_W0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.shared.relaxed.min.bf	 [[R16_H3]], [[[R32_W0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.shared.relaxed.max.bf	 [[R16_H4]], [[[R32_W0]]], [[R16_H0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_shared_16bf_relaxed(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.shared.relaxed.add.bf	 [[R16_H1]], [[[R32_W0]]], [[R16_H0]];
; O0-NEXT: 	fatom.shared.relaxed.sub.bf	 [[R16_H2]], [[[R32_W0]]], [[R16_H0]];
; O0-NEXT: 	fatom.shared.relaxed.min.bf	 [[R16_H3]], [[[R32_W0]]], [[R16_H0]];
; O0-NEXT: 	fatom.shared.relaxed.max.bf	 [[R16_H4]], [[[R32_W0]]], [[R16_H0]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr addrspace(3) %ptr, bfloat %a monotonic
  %res8 = atomicrmw fsub ptr addrspace(3) %ptr, bfloat %a monotonic
  %res9 = atomicrmw fmin ptr addrspace(3) %ptr, bfloat %a monotonic
  %res10 = atomicrmw fmax ptr addrspace(3) %ptr, bfloat %a monotonic

  ret void
}

define void @fatom_generic_16bf_relaxed(ptr %ptr, bfloat %a)
; CHECK-LABEL: void @fatom_generic_16bf_relaxed(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fatom.generic.relaxed.add.bf	 [[R16_H1]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.generic.relaxed.sub.bf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.generic.relaxed.min.bf	 [[R16_H3]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	fatom.generic.relaxed.max.bf	 [[R16_H4]], [[[R64_D0]]], [[R16_H0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_generic_16bf_relaxed(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; O0: 	fatom.generic.relaxed.add.bf	 [[R16_H1]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.generic.relaxed.sub.bf	 [[R16_H2]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.generic.relaxed.min.bf	 [[R16_H3]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	fatom.generic.relaxed.max.bf	 [[R16_H4]], [[[R64_D0]]], [[R16_H0]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr %ptr, bfloat %a monotonic
  %res8 = atomicrmw fsub ptr %ptr, bfloat %a monotonic
  %res9 = atomicrmw fmin ptr %ptr, bfloat %a monotonic
  %res10 = atomicrmw fmax ptr %ptr, bfloat %a monotonic

  ret void
}

define void @fatom_scope(ptr %ptr, float %a)
; CHECK-LABEL: void @fatom_scope(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b %w<1~7>;
; CHECK: 	fatom.generic.relaxed.add.f	 %w1, [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.generic.relaxed.add.f	 %w2, [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.generic.acq_rel.system.add.f	 %w3, [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.generic.acq_rel.workgroup.add.f	 %w4, [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.generic.acq_rel.workgroup.add.f	 %w5, [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	fatom.generic.acq_rel.workgroup.add.f	 %w6, [[[R64_D0]]], [[R32_W0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @fatom_scope(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b %w<1~7>;
; O0: 	fatom.generic.relaxed.add.f	 %w1, [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.generic.relaxed.add.f	 %w2, [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.generic.acq_rel.system.add.f	 %w3, [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.generic.acq_rel.workgroup.add.f	 %w4, [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.generic.acq_rel.workgroup.add.f	 %w5, [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	fatom.generic.acq_rel.workgroup.add.f	 %w6, [[[R64_D0]]], [[R32_W0]];
; O0-NEXT: 	return;
{
  %res7 = atomicrmw fadd ptr %ptr, float %a monotonic
  %res8 = atomicrmw fadd ptr %ptr, float %a syncscope("workgroup") monotonic
  %res9 = atomicrmw fadd ptr %ptr, float %a acq_rel
  %res10 = atomicrmw fadd ptr %ptr, float %a syncscope("workgroup") acq_rel
  %res11 = atomicrmw fadd ptr %ptr, float %a syncscope("workitem") acq_rel
  %res12 = atomicrmw fadd ptr %ptr, float %a syncscope("subgroup") acq_rel

  ret void
}
