; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

define half @test_fneg16(half %a) {
; CHECK-LABEL: .16b @test_fneg16(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fneg.hf 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	return [[R16_H1]];
;
; O0-LABEL: .16b @test_fneg16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	fneg.hf 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
  %result = fneg half %a
  ret half %result
}

define float @test_fneg32(float %a) {
; CHECK-LABEL: .32b @test_fneg32(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fneg.f 	[[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @test_fneg32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	fneg.f 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	return [[R32_W1]];
  %result = fneg float %a
  ret float %result
}

define double @test_fneg64(double %a) {
; CHECK-LABEL: .64b @test_fneg64(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fneg.df 	[[R64_D1]], [[R64_D0]];
; CHECK-NEXT: 	return [[R64_D1]];
;
; O0-LABEL: .64b @test_fneg64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0: 	fneg.df 	[[R64_D1]], [[R64_D0]];
; O0-NEXT: 	return [[R64_D1]];
  %result = fneg double %a
  ret double %result
}
