; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s
; RUN: llc < %s -march=pisa %disable_optional_optimizations -verify-machineinstrs | FileCheck --check-prefixes=CHECK,CHECK-LESS-OPT %s

declare bfloat @llvm.pisa.frsqrt.bf16(bfloat)
declare half   @llvm.pisa.frsqrt.f16(half)
declare float  @llvm.pisa.frsqrt.f32(float)
declare double @llvm.pisa.frsqrt.f64(double)

declare float @llvm.sqrt.f32(float)
declare float @llvm.pisa.frcp.f32(float)
declare float @llvm.fabs.f32(float)
declare half  @llvm.fabs.f16(half)

define half @test_frsqrt_half(half %a) {
; O0-LABEL: .16b @test_frsqrt_half(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	frsqrt.fast.hf 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
;
; CHECK-LABEL: .16b @test_frsqrt_half(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.hf 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	return [[R16_H1]];
  %res = call afn half @llvm.pisa.frsqrt.f16(half %a)
  ret half %res
}

define bfloat @frsqrt_bf16(bfloat %a) {
; O0-LABEL: .16b @frsqrt_bf16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	frsqrt.fast.bf 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
;
; CHECK-LABEL: .16b @frsqrt_bf16(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.bf 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	return [[R16_H1]];
  %res = call afn bfloat @llvm.pisa.frsqrt.bf16(bfloat %a)
  ret bfloat %res
}

define float @test_frsqrt_float(float %a) {
; O0-LABEL: .32b @test_frsqrt_float(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	frsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	return [[R32_W1]];
;
; CHECK-LABEL: .32b @test_frsqrt_float(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W1]];
  %res = call afn float @llvm.pisa.frsqrt.f32(float %a)
  ret float %res
}

define double @test_frsqrt_double(double %a) {
; O0-LABEL: .64b @test_frsqrt_double(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0: 	frsqrt.fast.df 	[[R64_D1]], [[R64_D0]];
; O0-NEXT: 	return [[R64_D1]];
;
; CHECK-LABEL: .64b @test_frsqrt_double(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.df 	[[R64_D1]], [[R64_D0]];
; CHECK-NEXT: 	return [[R64_D1]];
  %res = call afn double @llvm.pisa.frsqrt.f64(double %a)
  ret double %res
}

define <2 x bfloat> @test_frsqrt_v2bf16(<2 x bfloat> %a) {
; O0-LABEL: .v2.16b @test_frsqrt_v2bf16(
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~6>;
; O0: 	mov.16b 	[[R16_H0:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	[[R16_H1:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H0]].y;
; O0-NEXT: 	frsqrt.fast.bf 	[[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H0]];
; O0-NEXT: 	mov.16b 	[[R16_H3:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	[[R16_H4:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H0]].y;
; O0-NEXT: 	frsqrt.fast.bf 	[[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H4]];
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H1]].x, [[R16_H2]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H2]].xy, [[VR2_16_V2H1]].xy;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H2]].y, [[R16_H5]];
; O0-NEXT: 	return [[VR2_16_V2H2]];
;
;
; CHECK-LESS-OPT-LABEL: .v2.16b @test_frsqrt_v2bf16(
; CHECK-LESS-OPT-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	frsqrt.fast.bf 	[[VR2_16_V2H1]].x, [[VR2_16_V2H0]].x;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.bf 	[[VR2_16_V2H1]].y, [[VR2_16_V2H0]].y;
; CHECK-LESS-OPT-NEXT: 	return [[VR2_16_V2H1]];
  %result = call afn <2 x bfloat> @llvm.pisa.frsqrt.v2bf16(<2 x bfloat> %a)
  ret <2 x bfloat> %result
}

define <2 x half> @test_frsqrt_v2f16(<2 x half> %a) {
; O0-LABEL: .v2.16b @test_frsqrt_v2f16(
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~6>;
; O0: 	mov.16b 	[[R16_H0:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	[[R16_H1:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H0]].y;
; O0-NEXT: 	frsqrt.fast.hf 	[[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H0]];
; O0-NEXT: 	mov.16b 	[[R16_H3:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	[[R16_H4:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H0]].y;
; O0-NEXT: 	frsqrt.fast.hf 	[[R16_H5:%[-a-zA-Z$._0-9]+]], [[R16_H4]];
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H1]].x, [[R16_H2]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H2]].xy, [[VR2_16_V2H1]].xy;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H2]].y, [[R16_H5]];
; O0-NEXT: 	return [[VR2_16_V2H2]];
;
;
; CHECK-LESS-OPT-LABEL: .v2.16b @test_frsqrt_v2f16(
; CHECK-LESS-OPT-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; CHECK-LESS-OPT: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]];
; CHECK-LESS-OPT: 	frsqrt.fast.hf 	[[VR2_16_V2H1]].x, [[VR2_16_V2H0]].x;
; CHECK-LESS-OPT-NEXT: 	frsqrt.fast.hf 	[[VR2_16_V2H1]].y, [[VR2_16_V2H0]].y;
; CHECK-LESS-OPT-NEXT: 	return [[VR2_16_V2H1]];
  %result = call afn <2 x half> @llvm.pisa.frsqrt.v2f16(<2 x half> %a)
  ret <2 x half> %result
}

define <2 x float> @test_frsqrt_v2f32(<2 x float> %a) {
; O0-LABEL: .v2.32b @test_frsqrt_v2f32(
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.32b 	[[R32_W0]], [[VR2_32_V2W0]].x;
; O0-NEXT: 	frsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	mov.32b 	[[R32_W2]], [[VR2_32_V2W0]].y;
; O0-NEXT: 	frsqrt.fast.f 	[[R32_W3]], [[R32_W2]];
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W1]].x, [[R32_W1]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W2]].xy, [[VR2_32_V2W1]].xy;
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W2]].y, [[R32_W3]];
; O0-NEXT: 	return [[VR2_32_V2W2]];
;
; CHECK-LABEL: .v2.32b @test_frsqrt_v2f32(
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.f 	[[VR2_32_V2W1]].x, [[VR2_32_V2W0]].x;
; CHECK-NEXT: 	frsqrt.fast.f 	[[VR2_32_V2W1]].y, [[VR2_32_V2W0]].y;
; CHECK-NEXT: 	return [[VR2_32_V2W1]];
  %result = call afn <2 x float> @llvm.pisa.frsqrt.v2f32(<2 x float> %a)
  ret <2 x float> %result
}

define <2 x double> @test_frsqrt_v2f64(<2 x double> %a) {
; O0-LABEL: .v2.64b @test_frsqrt_v2f64(
; O0-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]], [[VR2_64_V2D2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b %d<0~6>;
; O0: 	mov.64b 	[[R64_D0:%[-a-zA-Z$._0-9]+]], [[VR2_64_V2D0]].x;
; O0-NEXT: 	mov.64b 	[[R64_D1:%[-a-zA-Z$._0-9]+]], [[VR2_64_V2D0]].y;
; O0-NEXT: 	frsqrt.fast.df 	[[R64_D2:%[-a-zA-Z$._0-9]+]], [[R64_D0]];
; O0-NEXT: 	mov.64b 	[[R64_D3:%[-a-zA-Z$._0-9]+]], [[VR2_64_V2D0]].x;
; O0-NEXT: 	mov.64b 	[[R64_D4:%[-a-zA-Z$._0-9]+]], [[VR2_64_V2D0]].y;
; O0-NEXT: 	frsqrt.fast.df 	[[R64_D5:%[-a-zA-Z$._0-9]+]], [[R64_D4]];
; O0-NEXT: 	mov.64b 	[[VR2_64_V2D1]].x, [[R64_D2]];
; O0-NEXT: 	mov.128b 	[[VR2_64_V2D2]].xy, [[VR2_64_V2D1]].xy;
; O0-NEXT: 	mov.64b 	[[VR2_64_V2D2]].y, [[R64_D5]];
; O0-NEXT: 	return [[VR2_64_V2D2]];
;
; CHECK-LABEL: .v2.64b @test_frsqrt_v2f64(
; CHECK-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.df 	[[VR2_64_V2D1]].x, [[VR2_64_V2D0]].x;
; CHECK-NEXT: 	frsqrt.fast.df 	[[VR2_64_V2D1]].y, [[VR2_64_V2D0]].y;
; CHECK-NEXT: 	return [[VR2_64_V2D1]];
  %result = call afn <2 x double> @llvm.pisa.frsqrt.v2f64(<2 x double> %a)
  ret <2 x double> %result
}

define bfloat @test_frsqrt_pattern_bf(bfloat %a) {
; O0-LABEL: .16b @test_frsqrt_pattern_bf(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]];
; O0: 	fsqrt.fast.bf 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	frcp.bf 	[[R16_H2]], [[R16_H1]];
; O0-NEXT: 	return [[R16_H2]];
;
; CHECK-LABEL: .16b @test_frsqrt_pattern_bf(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.bf 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	return [[R16_H1]];
  %b = call afn contract bfloat @llvm.sqrt.bf(bfloat %a)
  %res = call afn contract bfloat @llvm.pisa.frcp.bf(bfloat %b)
  ret bfloat %res
}

define half @test_frsqrt_pattern_h(half %a) {
; O0-LABEL: .16b @test_frsqrt_pattern_h(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]];
; O0: 	fsqrt.fast.hf 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	frcp.hf 	[[R16_H2]], [[R16_H1]];
; O0-NEXT: 	return [[R16_H2]];
;
; CHECK-LABEL: .16b @test_frsqrt_pattern_h(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.hf 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	return [[R16_H1]];
  %b = call afn contract half @llvm.sqrt.f16(half %a)
  %res = call afn contract half @llvm.pisa.frcp.f16(half %b)
  ret half %res
}

define float @test_frsqrt_pattern_f(float %a) {
; O0-LABEL: .32b @test_frsqrt_pattern_f(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; O0: 	fsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	frcp.f 	[[R32_W2]], [[R32_W1]];
; O0-NEXT: 	return [[R32_W2]];
;
; CHECK-LABEL: .32b @test_frsqrt_pattern_f(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W1]];
  %b = call afn contract float @llvm.sqrt.f32(float %a)
  %res = call afn contract float @llvm.pisa.frcp.f32(float %b)
  ret float %res
}

define double @test_frsqrt_pattern_d(double %a) {
; O0-LABEL: .64b @test_frsqrt_pattern_d(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]], [[R64_D2:%[-a-zA-Z$._0-9]+]];
; O0: 	fsqrt.fast.df 	[[R64_D1]], [[R64_D0]];
; O0-NEXT: 	fdiv.df 	[[R64_D2]], {{0x3FF0000000000000|4607182418800017408}}, [[R64_D1]];
; O0-NEXT: 	return [[R64_D2]];
;
; CHECK-LABEL: .64b @test_frsqrt_pattern_d(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.df 	[[R64_D1]], [[R64_D0]];
; CHECK-NEXT: 	return [[R64_D1]];
  %b = call afn contract double @llvm.sqrt.f64(double %a)
  %res = fdiv afn contract double 1.0, %b
  ret double %res
}

define float @test_frsqrt_pattern_rev(float %a) {
; O0-LABEL: .32b @test_frsqrt_pattern_rev(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; O0: 	frcp.f 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	fsqrt.fast.f 	[[R32_W2]], [[R32_W1]];
; O0-NEXT: 	return [[R32_W2]];
;
; CHECK-LABEL: .32b @test_frsqrt_pattern_rev(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W1]];
  %b = call afn contract float @llvm.pisa.frcp.f32(float %a)
  %res = call afn contract float @llvm.sqrt.f32(float %b)
  ret float %res
}

define float @test_frsqrt_pattern_div(float %a) {
; O0-LABEL: .32b @test_frsqrt_pattern_div(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; O0: 	fsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	fdiv.f 	[[R32_W2]], {{0x3F800000|1065353216}}, [[R32_W1]];
; O0-NEXT: 	return [[R32_W2]];
;
; CHECK-LABEL: .32b @test_frsqrt_pattern_div(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W1]];
  %b = call afn contract float @llvm.sqrt.f32(float %a)
  %res = fdiv afn contract float 1.0, %b
  ret float %res
}

define float @test_frsqrt_pattern_div_rev(float %a) {
; O0-LABEL: .32b @test_frsqrt_pattern_div_rev(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; O0: 	fdiv.f 	[[R32_W1]], {{0x3F800000|1065353216}}, [[R32_W0]];
; O0-NEXT: 	fsqrt.fast.f 	[[R32_W2]], [[R32_W1]];
; O0-NEXT: 	return [[R32_W2]];
;
; CHECK-LABEL: .32b @test_frsqrt_pattern_div_rev(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W1]];
  %b = fdiv afn contract float 1.0, %a
  %res = call afn contract float @llvm.sqrt.f32(float %b)
  ret float %res
}

; 1 / fabs(sqrt(x)) == fabs(frsqrt(x))
define float @test_frsqrt_pattern_fabs_div(float %a) {
; O0-LABEL: .32b @test_frsqrt_pattern_fabs_div(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0: 	fsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	fabs.f 	[[R32_W2]], [[R32_W1]];
; O0-NEXT: 	fdiv.f 	[[R32_W3]], {{0x3F800000|1065353216}}, [[R32_W2]];
; O0-NEXT: 	return [[R32_W3]];
;
; CHECK-LABEL: .32b @test_frsqrt_pattern_fabs_div(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	fabs.f 	[[R32_W2]], [[R32_W1]];
; CHECK-NEXT: 	return [[R32_W2]];
  %b = call afn contract float @llvm.sqrt.f32(float %a)
  %c = call float @llvm.fabs.f32(float %b)
  %res = fdiv afn contract float 1.0, %c
  ret float %res
}

; frcp(fabs(sqrt(x))) == fabs(frsqrt(x))
define float @test_frsqrt_pattern_fabs_frcp(float %a) {
; O0-LABEL: .32b @test_frsqrt_pattern_fabs_frcp(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0: 	fsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	fabs.f 	[[R32_W2]], [[R32_W1]];
; O0-NEXT: 	frcp.f 	[[R32_W3]], [[R32_W2]];
; O0-NEXT: 	return [[R32_W3]];
;
; CHECK-LABEL: .32b @test_frsqrt_pattern_fabs_frcp(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.f 	[[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	fabs.f 	[[R32_W2]], [[R32_W1]];
; CHECK-NEXT: 	return [[R32_W2]];
  %b = call afn contract float @llvm.sqrt.f32(float %a)
  %c = call float @llvm.fabs.f32(float %b)
  %res = call afn contract float @llvm.pisa.frcp.f32(float %c)
  ret float %res
}

; half variant: 1 / fabs(sqrt(x)) == fabs(frsqrt(x))
define half @test_frsqrt_pattern_fabs_div_h(half %a) {
; O0-LABEL: .16b @test_frsqrt_pattern_fabs_div_h(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; O0: 	fsqrt.fast.hf 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	fabs.hf 	[[R16_H2]], [[R16_H1]];
; O0-NEXT: 	fext.f.hf 	[[R32_W0]], {{0x3C00|15360}};
; O0-NEXT: 	fext.f.hf 	[[R32_W1]], [[R16_H2]];
; O0-NEXT: 	fdiv.f 	[[R32_W2]], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	ftrunc.hf.f 	[[R16_H3]], [[R32_W2]];
; O0-NEXT: 	return [[R16_H3]];
;
; CHECK-LABEL: .16b @test_frsqrt_pattern_fabs_div_h(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	frsqrt.fast.hf 	[[R16_H1]], [[R16_H0]];
; CHECK-NEXT: 	fabs.hf 	[[R16_H2]], [[R16_H1]];
; CHECK-NEXT: 	return [[R16_H2]];
  %b = call afn contract half @llvm.sqrt.f16(half %a)
  %c = call half @llvm.fabs.f16(half %b)
  %res = fdiv afn contract half 1.0, %c
  ret half %res
}
