; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa | FileCheck %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

declare double @llvm.experimental.constrained.sqrt.f64(double, metadata, metadata) #1
declare float @llvm.experimental.constrained.sqrt.f32(float, metadata, metadata) #1

define double @test_fsqrt64_rnd(double %a) {
; CHECK-LABEL: .64b @test_fsqrt64_rnd(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fsqrt.rz.df 	[[R64_D1]], [[R64_D0]];
; CHECK-NEXT: 	return [[R64_D1]];
;
; O0-LABEL: .64b @test_fsqrt64_rnd(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0: 	fsqrt.rz.df 	[[R64_D1]], [[R64_D0]];
; O0-NEXT: 	return [[R64_D1]];
  %result = call double @llvm.experimental.constrained.sqrt.f64(
                        double %a,
                        metadata !"round.towardzero",
                        metadata !"fpexcept.ignore") #1
  ret double %result
}

define float @test_fsqrt32_rnd(float %a) {
; CHECK-LABEL: .32b @test_fsqrt32_rnd(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fsqrt.re.f 	[[R32_W1]], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @test_fsqrt32_rnd(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	fsqrt.re.f 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	return [[R32_W1]];
  %result = call float @llvm.experimental.constrained.sqrt.f32(
                        float %a,
                        metadata !"round.tonearest",
                        metadata !"fpexcept.ignore") #1
  ret float %result
}

define <2 x float> @test_fsqrtv2f32_rnd(<2 x float> %a) {
; CHECK-LABEL: .v2.32b @test_fsqrtv2f32_rnd(
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fsqrt.re.f 	[[VR2_32_V2W1]].x, [[VR2_32_V2W0]].x;
; CHECK-NEXT: 	fsqrt.re.f 	[[VR2_32_V2W1]].y, [[VR2_32_V2W0]].y;
; CHECK-NEXT: 	return [[VR2_32_V2W1]];
;
; O0-LABEL: .v2.32b @test_fsqrtv2f32_rnd(
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.32b 	[[R32_W0]], [[VR2_32_V2W0]].x;
; O0-NEXT: 	fsqrt.re.f 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	mov.32b 	[[R32_W2]], [[VR2_32_V2W0]].y;
; O0-NEXT: 	fsqrt.re.f 	[[R32_W3]], [[R32_W2]];
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W1]].x, [[R32_W1]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W2]].xy, [[VR2_32_V2W1]].xy;
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W2]].y, [[R32_W3]];
; O0-NEXT: 	return [[VR2_32_V2W2]];
  %result = call <2 x float> @llvm.experimental.constrained.sqrt.v2f32(
                        <2 x float> %a,
                        metadata !"round.tonearest",
                        metadata !"fpexcept.ignore") #1
  ret <2 x float> %result
}

attributes #1 = { strictfp }


