; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -verify-machineinstrs > %t.pisa
; RUN: FileCheck < %t.pisa %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

; FUNCARGS:    .function .v2.8b @test_v2_8b(.reg .v2.8b [[ARG:%r[0-9]+]])
; FUNCARGS:    return [[ARG]]
define <2 x i8> @test_v2_8b(<2 x i8> %vec) {
; CHECK-LABEL: .v2.8b @test_v2_8b(
; CHECK-SAME: .reg .v2.8b [[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	return [[VR2_8_V2B0]];
;
; O0-LABEL: .v2.8b @test_v2_8b(
; O0-SAME: .reg .v2.8b [[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]]
; O0: 	return [[VR2_8_V2B0]];
  ret <2 x i8> %vec
}

; FUNCARGS:    .function .v3.8b @test_v3_8b(.reg .v3.8b [[ARG:%r[0-9]+]])
; FUNCARGS:    return [[ARG]]
define <3 x i8> @test_v3_8b(<3 x i8> %vec) {
; CHECK-LABEL: .v3.8b @test_v3_8b(
; CHECK-SAME: .reg .v3.8b [[VR3_8_V3B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	return [[VR3_8_V3B0]];
;
; O0-LABEL: .v3.8b @test_v3_8b(
; O0-SAME: .reg .v3.8b [[VR3_8_V3B0:%[-a-zA-Z$._0-9]+]]
; O0: 	return [[VR3_8_V3B0]];
  ret <3 x i8> %vec
}

; FUNCARGS:    .function .v4.8b @test_v4_8b(.reg .v4.8b [[ARG:%r[0-9]+]])
; FUNCARGS:    return [[ARG]]
define <4 x i8> @test_v4_8b(<4 x i8> %vec) {
; CHECK-LABEL: .v4.8b @test_v4_8b(
; CHECK-SAME: .reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	return [[VR4_8_V4B0]];
;
; O0-LABEL: .v4.8b @test_v4_8b(
; O0-SAME: .reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]]
; O0: 	return [[VR4_8_V4B0]];
  ret <4 x i8> %vec
}

; FUNCARGS:    .function .v2.16b @test_v2_16b(.reg .v2.16b [[ARG:%r[0-9]+]])
; FUNCARGS:    return [[ARG]]
define <2 x i16> @test_v2_16b(<2 x i16> %vec) {
; CHECK-LABEL: .v2.16b @test_v2_16b(
; CHECK-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	return [[VR2_16_V2H0]];
;
; O0-LABEL: .v2.16b @test_v2_16b(
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0: 	return [[VR2_16_V2H0]];
  ret <2 x i16> %vec
}

; FUNCARGS:    .function .v3.16b @test_v3_16b(.reg .v3.16b [[ARG:%r[0-9]+]])
; FUNCARGS:    return [[ARG]]
define <3 x i16> @test_v3_16b(<3 x i16> %vec) {
; CHECK-LABEL: .v3.16b @test_v3_16b(
; CHECK-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	return [[VR3_16_V3H0]];
;
; O0-LABEL: .v3.16b @test_v3_16b(
; O0-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; O0: 	return [[VR3_16_V3H0]];
  ret <3 x i16> %vec
}

; FUNCARGS:    .function .v4.16b @test_v4_16b(.reg .v4.16b [[ARG:%r[0-9]+]])
; FUNCARGS:    return [[ARG]]
define <4 x i16> @test_v4_16b(<4 x i16> %vec) {
; CHECK-LABEL: .v4.16b @test_v4_16b(
; CHECK-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	return [[VR4_16_V4H0]];
;
; O0-LABEL: .v4.16b @test_v4_16b(
; O0-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; O0: 	return [[VR4_16_V4H0]];
  ret <4 x i16> %vec
}

; FUNCARGS:    .function .v2.32b @test_v2_32b(.reg .v2.32b [[ARG:%r[0-9]+]])
; FUNCARGS:    return [[ARG]]
define <2 x i32> @test_v2_32b(<2 x i32> %vec) {
; CHECK-LABEL: .v2.32b @test_v2_32b(
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	return [[VR2_32_V2W0]];
;
; O0-LABEL: .v2.32b @test_v2_32b(
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	return [[VR2_32_V2W0]];
  ret <2 x i32> %vec
}

; FUNCARGS:    .function .v3.32b @test_v3_32b(.reg .v3.32b [[ARG:%r[0-9]+]])
; FUNCARGS:    return [[ARG]]
define <3 x i32> @test_v3_32b(<3 x i32> %vec) {
; CHECK-LABEL: .v3.32b @test_v3_32b(
; CHECK-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	return [[VR3_32_V3W0]];
;
; O0-LABEL: .v3.32b @test_v3_32b(
; O0-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; O0: 	return [[VR3_32_V3W0]];
  ret <3 x i32> %vec
}

; FUNCARGS:    .function .v4.32b @test_v4_32b(.reg .v4.32b [[ARG:%r[0-9]+]])
; FUNCARGS:    return [[ARG]]
define <4 x i32> @test_v4_32b(<4 x i32> %vec) {
; CHECK-LABEL: .v4.32b @test_v4_32b(
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	return [[VR4_32_V4W0]];
;
; O0-LABEL: .v4.32b @test_v4_32b(
; O0-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; O0: 	return [[VR4_32_V4W0]];
  ret <4 x i32> %vec
}

; FUNCARGS:    .function .v2.64b @test_v2_64b(.reg .v2.64b [[ARG:%r[0-9]+]])
; FUNCARGS:    return [[ARG]]
define <2 x i64> @test_v2_64b(<2 x i64> %vec) {
; CHECK-LABEL: .v2.64b @test_v2_64b(
; CHECK-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	return [[VR2_64_V2D0]];
;
; O0-LABEL: .v2.64b @test_v2_64b(
; O0-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; O0: 	return [[VR2_64_V2D0]];
  ret <2 x i64> %vec
}

; FUNCARGS:    .function .v3.64b @test_v3_64b(.reg .v3.64b [[ARG:%r[0-9]+]])
; FUNCARGS:    return [[ARG]]
define <3 x i64> @test_v3_64b(<3 x i64> %vec) {
; CHECK-LABEL: .v3.64b @test_v3_64b(
; CHECK-SAME: .reg .v3.64b [[VR3_64_V3D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	return [[VR3_64_V3D0]];
;
; O0-LABEL: .v3.64b @test_v3_64b(
; O0-SAME: .reg .v3.64b [[VR3_64_V3D0:%[-a-zA-Z$._0-9]+]]
; O0: 	return [[VR3_64_V3D0]];
  ret <3 x i64> %vec
}

; FUNCARGS:    .function .v4.64b @test_v4_64b(.reg .v4.64b [[ARG:%r[0-9]+]])
; FUNCARGS:    return [[ARG]]
define <4 x i64> @test_v4_64b(<4 x i64> %vec) {
; CHECK-LABEL: .v4.64b @test_v4_64b(
; CHECK-SAME: .reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	return [[VR4_64_V4D0]];
;
; O0-LABEL: .v4.64b @test_v4_64b(
; O0-SAME: .reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]]
; O0: 	return [[VR4_64_V4D0]];
  ret <4 x i64> %vec
}
