; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa | FileCheck %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

define i64 @test_iadd64(i64 %a, i64 %b) {
; CHECK-LABEL: .64b @test_iadd64(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	iadd.64b 	[[R64_D2]], [[R64_D0]], [[R64_D1]];
; CHECK-NEXT: 	return [[R64_D2]];
;
; O0-LABEL: .64b @test_iadd64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]];
; O0: 	iadd.64b 	[[R64_D2]], [[R64_D0]], [[R64_D1]];
; O0-NEXT: 	return [[R64_D2]];
  %result = add i64 %a, %b
  ret i64 %result
}

define i32 @test_iadd32(i32 %a, i32 %b) {
; CHECK-LABEL: .32b @test_iadd32(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	iadd.32b 	[[R32_W2]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	return [[R32_W2]];
;
; O0-LABEL: .32b @test_iadd32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]];
; O0: 	iadd.32b 	[[R32_W2]], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	return [[R32_W2]];
  %result = add i32 %a, %b
  ret i32 %result
}

define i16 @test_iadd16(i16 %a, i16 %b) {
; CHECK-LABEL: .16b @test_iadd16(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	iadd.16b 	[[R16_H2]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	return [[R16_H2]];
;
; O0-LABEL: .16b @test_iadd16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]];
; O0: 	iadd.16b 	[[R16_H2]], [[R16_H0]], [[R16_H1]];
; O0-NEXT: 	return [[R16_H2]];
  %result = add i16 %a, %b
  ret i16 %result
}

define i64 @test_iadd64imm(i64 %a) {
; CHECK-LABEL: .64b @test_iadd64imm(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	iadd.64b 	[[R64_D1]], [[R64_D0]], 5;
; CHECK-NEXT: 	return [[R64_D1]];
;
; O0-LABEL: .64b @test_iadd64imm(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0: 	iadd.64b 	[[R64_D1]], [[R64_D0]], 5;
; O0-NEXT: 	return [[R64_D1]];
  %result = add i64 %a, 5
  ret i64 %result
}

define i32 @test_iadd32imm(i32 %a) {
; CHECK-LABEL: .32b @test_iadd32imm(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	iadd.32b 	[[R32_W1]], [[R32_W0]], 5;
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @test_iadd32imm(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	iadd.32b 	[[R32_W1]], [[R32_W0]], 5;
; O0-NEXT: 	return [[R32_W1]];
  %result = add i32 %a, 5
  ret i32 %result
}

define i16 @test_iadd16imm(i16 %a) {
; CHECK-LABEL: .16b @test_iadd16imm(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	iadd.16b 	[[R16_H1]], [[R16_H0]], 5;
; CHECK-NEXT: 	return [[R16_H1]];
;
; O0-LABEL: .16b @test_iadd16imm(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	iadd.16b 	[[R16_H1]], [[R16_H0]], 5;
; O0-NEXT: 	return [[R16_H1]];
  %result = add i16 %a, 5
  ret i16 %result
}

