; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

define <2 x i32> @insert_v2_32b_v2_32b(<2 x i32> %v0, <2 x i32> %v) {
; CHECK-LABEL: .v2.32b @insert_v2_32b_v2_32b(
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	insert.0.v2.32b 	[[VR2_32_V2W0]], [[VR2_32_V2W1]];
; CHECK-NEXT: 	return [[VR2_32_V2W0]];
;
; O0-LABEL: .v2.32b @insert_v2_32b_v2_32b(
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.32b [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.64b 	[[VR2_32_V2W2]].xy, [[VR2_32_V2W0]].xy;
; O0-NEXT: 	insert.0.v2.32b 	[[VR2_32_V2W2]], [[VR2_32_V2W1]];
; O0-NEXT: 	return [[VR2_32_V2W2]];
  %a = call <2 x i32> @llvm.vector.insert.v2i32.v2i32(<2 x i32> %v0, <2 x i32> %v, i64 0)
  ret <2 x i32> %a
}

define <4 x i16> @insert_v2_32b_v2_32b_copy(<4 x i16> %v0, <2 x i32> %v) {
; CHECK-LABEL: .v4.16b @insert_v2_32b_v2_32b_copy(
; CHECK-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	mov.64b 	[[VR2_32_V2W1]].xy, [[VR4_16_V4H0]].xyzw;
; CHECK-NEXT: 	insert.0.v2.32b 	[[VR2_32_V2W1]], [[VR2_32_V2W0]];
; CHECK-NEXT: 	mov.64b 	[[VR4_16_V4H1]].xyzw, [[VR2_32_V2W1]].xy;
; CHECK-NEXT: 	return [[VR4_16_V4H1]];
;
; O0-LABEL: .v4.16b @insert_v2_32b_v2_32b_copy(
; O0-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.64b 	[[VR2_32_V2W1]].xy, [[VR4_16_V4H0]].xyzw;
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W2]].xy, [[VR2_32_V2W1]].xy;
; O0-NEXT: 	insert.0.v2.32b 	[[VR2_32_V2W2]], [[VR2_32_V2W0]];
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H1]].xyzw, [[VR2_32_V2W2]].xy;
; O0-NEXT: 	return [[VR4_16_V4H1]];
  %cast = bitcast <4 x i16> %v0 to <2 x i32>
  %a = call <2 x i32> @llvm.vector.insert.v2i32.v1i32(<2 x i32> %cast, <2 x i32> %v, i64 0)
  %res = bitcast <2 x i32> %a to <4 x i16>
  ret <4 x i16> %res
}

define <4 x i32> @insert_v2_32b_v4_32b(<4 x i32> %v0, <2 x i32> %v) {
; CHECK-LABEL: .v4.32b @insert_v2_32b_v4_32b(
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	insert.2.v2.32b 	[[VR4_32_V4W0]], [[VR2_32_V2W0]];
; CHECK-NEXT: 	return [[VR4_32_V4W0]];
;
; O0-LABEL: .v4.32b @insert_v2_32b_v4_32b(
; O0-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.32b [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.128b 	[[VR4_32_V4W1]].xyzw, [[VR4_32_V4W0]].xyzw;
; O0-NEXT: 	insert.2.v2.32b 	[[VR4_32_V4W1]], [[VR2_32_V2W0]];
; O0-NEXT: 	return [[VR4_32_V4W1]];
  %a = call <4 x i32> @llvm.vector.insert.v4i32.v2i32(<4 x i32> %v0, <2 x i32> %v, i64 2)
  ret <4 x i32> %a
}

define <8 x i32> @insert_v2_32b_v8_32b(<8 x i32> %v0, <2 x i32> %v) {
; CHECK-LABEL: .v8.32b @insert_v2_32b_v8_32b(
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	insert.6.v2.32b 	[[VR8_32_V8W0]], [[VR2_32_V2W0]];
; CHECK-NEXT: 	return [[VR8_32_V8W0]];
;
; O0-LABEL: .v8.32b @insert_v2_32b_v8_32b(
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]];
; O0: 	extract.0.v8.32b 	[[VR8_32_V8W1]], [[VR8_32_V8W0]];
; O0-NEXT: 	insert.6.v2.32b 	[[VR8_32_V8W1]], [[VR2_32_V2W0]];
; O0-NEXT: 	return [[VR8_32_V8W1]];
  %a = call <8 x i32> @llvm.vector.insert.v8i32.v2i32(<8 x i32> %v0, <2 x i32> %v, i64 6)
  ret <8 x i32> %a
}

define <16 x i32> @insert_v4_32b_v16_32b(<16 x i32> %v0, <4 x i32> %v) {
; CHECK-LABEL: .v16.32b @insert_v4_32b_v16_32b(
; CHECK-SAME: .reg .v16.32b [[VR16_32_V16W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	insert.12.v4.32b 	[[VR16_32_V16W0]], [[VR4_32_V4W0]];
; CHECK-NEXT: 	return [[VR16_32_V16W0]];
;
; O0-LABEL: .v16.32b @insert_v4_32b_v16_32b(
; O0-SAME: .reg .v16.32b [[VR16_32_V16W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v16.32b [[VR16_32_V16W1:%[-a-zA-Z$._0-9]+]];
; O0: 	extract.0.v16.32b 	[[VR16_32_V16W1]], [[VR16_32_V16W0]];
; O0-NEXT: 	insert.12.v4.32b 	[[VR16_32_V16W1]], [[VR4_32_V4W0]];
; O0-NEXT: 	return [[VR16_32_V16W1]];
  %a = call <16 x i32> @llvm.vector.insert.v16i32.v4i32(<16 x i32> %v0, <4 x i32> %v, i64 12)
  ret <16 x i32> %a
}

define <64 x i32> @insert_v2_32b_v64_32b_idx_0(<64 x i32> %arg0, <2 x i32> %arg1) {
; CHECK-LABEL: .v64.32b @insert_v2_32b_v64_32b_idx_0(
; CHECK-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	insert.0.v2.32b 	[[VR64_32_V64W0]], [[VR2_32_V2W0]];
; CHECK-NEXT: 	return [[VR64_32_V64W0]];
;
; O0-LABEL: .v64.32b @insert_v2_32b_v64_32b_idx_0(
; O0-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v64.32b [[VR64_32_V64W1:%[-a-zA-Z$._0-9]+]];
; O0: 	extract.0.v64.32b 	[[VR64_32_V64W1]], [[VR64_32_V64W0]];
; O0-NEXT: 	insert.0.v2.32b 	[[VR64_32_V64W1]], [[VR2_32_V2W0]];
; O0-NEXT: 	return [[VR64_32_V64W1]];
  %insert = call <64 x i32> @llvm.vector.insert.v64i32.v2i32(<64 x i32> %arg0, <2 x i32> %arg1, i64 0)
  ret <64 x i32> %insert
}

define <64 x i32> @insert_v2_32b_v64_32b_idx_30(<64 x i32> %arg0, <2 x i32> %arg1) {
; CHECK-LABEL: .v64.32b @insert_v2_32b_v64_32b_idx_30(
; CHECK-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	insert.30.v2.32b 	[[VR64_32_V64W0]], [[VR2_32_V2W0]];
; CHECK-NEXT: 	return [[VR64_32_V64W0]];
;
; O0-LABEL: .v64.32b @insert_v2_32b_v64_32b_idx_30(
; O0-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v64.32b [[VR64_32_V64W1:%[-a-zA-Z$._0-9]+]];
; O0: 	extract.0.v64.32b 	[[VR64_32_V64W1]], [[VR64_32_V64W0]];
; O0-NEXT: 	insert.30.v2.32b 	[[VR64_32_V64W1]], [[VR2_32_V2W0]];
; O0-NEXT: 	return [[VR64_32_V64W1]];
  %insert = call <64 x i32> @llvm.vector.insert.v64i32.v2i32(<64 x i32> %arg0, <2 x i32> %arg1, i64 30)
  ret <64 x i32> %insert
}

define <64 x i32> @insert_v2_32b_v64_32b_idx_32(<64 x i32> %arg0, <2 x i32> %arg1) {
; CHECK-LABEL: .v64.32b @insert_v2_32b_v64_32b_idx_32(
; CHECK-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	insert.32.v2.32b 	[[VR64_32_V64W0]], [[VR2_32_V2W0]];
; CHECK-NEXT: 	return [[VR64_32_V64W0]];
;
; O0-LABEL: .v64.32b @insert_v2_32b_v64_32b_idx_32(
; O0-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v64.32b [[VR64_32_V64W1:%[-a-zA-Z$._0-9]+]];
; O0: 	extract.0.v64.32b 	[[VR64_32_V64W1]], [[VR64_32_V64W0]];
; O0-NEXT: 	insert.32.v2.32b 	[[VR64_32_V64W1]], [[VR2_32_V2W0]];
; O0-NEXT: 	return [[VR64_32_V64W1]];
  %insert = call <64 x i32> @llvm.vector.insert.v64i32.v2i32(<64 x i32> %arg0, <2 x i32> %arg1, i64 32)
  ret <64 x i32> %insert
}

define <64 x i32> @insert_v4_32b_v64_32b_idx_0(<64 x i32> %arg0, <4 x i32> %arg1) {
; CHECK-LABEL: .v64.32b @insert_v4_32b_v64_32b_idx_0(
; CHECK-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	insert.0.v4.32b 	[[VR64_32_V64W0]], [[VR4_32_V4W0]];
; CHECK-NEXT: 	return [[VR64_32_V64W0]];
;
; O0-LABEL: .v64.32b @insert_v4_32b_v64_32b_idx_0(
; O0-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v64.32b [[VR64_32_V64W1:%[-a-zA-Z$._0-9]+]];
; O0: 	extract.0.v64.32b 	[[VR64_32_V64W1]], [[VR64_32_V64W0]];
; O0-NEXT: 	insert.0.v4.32b 	[[VR64_32_V64W1]], [[VR4_32_V4W0]];
; O0-NEXT: 	return [[VR64_32_V64W1]];
  %insert = call <64 x i32> @llvm.vector.insert.v64i32.v4i32(<64 x i32> %arg0, <4 x i32> %arg1, i64 0)
  ret <64 x i32> %insert
}

define <64 x i32> @insert_v4_32b_v64_32b_idx_28(<64 x i32> %arg0, <4 x i32> %arg1) {
; CHECK-LABEL: .v64.32b @insert_v4_32b_v64_32b_idx_28(
; CHECK-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	insert.28.v4.32b 	[[VR64_32_V64W0]], [[VR4_32_V4W0]];
; CHECK-NEXT: 	return [[VR64_32_V64W0]];
;
; O0-LABEL: .v64.32b @insert_v4_32b_v64_32b_idx_28(
; O0-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v64.32b [[VR64_32_V64W1:%[-a-zA-Z$._0-9]+]];
; O0: 	extract.0.v64.32b 	[[VR64_32_V64W1]], [[VR64_32_V64W0]];
; O0-NEXT: 	insert.28.v4.32b 	[[VR64_32_V64W1]], [[VR4_32_V4W0]];
; O0-NEXT: 	return [[VR64_32_V64W1]];
  %insert = call <64 x i32> @llvm.vector.insert.v64i32.v4i32(<64 x i32> %arg0, <4 x i32> %arg1, i64 28)
  ret <64 x i32> %insert
}

define <64 x i32> @insert_v4_32b_v64_32b(<64 x i32> %arg0, <4 x i32> %arg1) {
; CHECK-LABEL: .v64.32b @insert_v4_32b_v64_32b(
; CHECK-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	insert.60.v4.32b 	[[VR64_32_V64W0]], [[VR4_32_V4W0]];
; CHECK-NEXT: 	return [[VR64_32_V64W0]];
;
; O0-LABEL: .v64.32b @insert_v4_32b_v64_32b(
; O0-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v64.32b [[VR64_32_V64W1:%[-a-zA-Z$._0-9]+]];
; O0: 	extract.0.v64.32b 	[[VR64_32_V64W1]], [[VR64_32_V64W0]];
; O0-NEXT: 	insert.60.v4.32b 	[[VR64_32_V64W1]], [[VR4_32_V4W0]];
; O0-NEXT: 	return [[VR64_32_V64W1]];
  %insert = call <64 x i32> @llvm.vector.insert.v64i32.v4i32(<64 x i32> %arg0, <4 x i32> %arg1, i64 60)
  ret <64 x i32> %insert
}

define <64 x i32> @insert_v8_32b_v64_32b_idx_0(<64 x i32> %arg0, <8 x i32> %arg1) {
; CHECK-LABEL: .v64.32b @insert_v8_32b_v64_32b_idx_0(
; CHECK-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	insert.0.v8.32b 	[[VR64_32_V64W0]], [[VR8_32_V8W0]];
; CHECK-NEXT: 	return [[VR64_32_V64W0]];
;
; O0-LABEL: .v64.32b @insert_v8_32b_v64_32b_idx_0(
; O0-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v64.32b [[VR64_32_V64W1:%[-a-zA-Z$._0-9]+]];
; O0: 	extract.0.v64.32b 	[[VR64_32_V64W1]], [[VR64_32_V64W0]];
; O0-NEXT: 	insert.0.v8.32b 	[[VR64_32_V64W1]], [[VR8_32_V8W0]];
; O0-NEXT: 	return [[VR64_32_V64W1]];
  %insert = call <64 x i32> @llvm.vector.insert.v64i32.v8i32(<64 x i32> %arg0, <8 x i32> %arg1, i64 0)
  ret <64 x i32> %insert
}

define <64 x i32> @insert_v8_32b_v64_32b_idx_56(<64 x i32> %arg0, <8 x i32> %arg1) {
; CHECK-LABEL: .v64.32b @insert_v8_32b_v64_32b_idx_56(
; CHECK-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	insert.56.v8.32b 	[[VR64_32_V64W0]], [[VR8_32_V8W0]];
; CHECK-NEXT: 	return [[VR64_32_V64W0]];
;
; O0-LABEL: .v64.32b @insert_v8_32b_v64_32b_idx_56(
; O0-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v64.32b [[VR64_32_V64W1:%[-a-zA-Z$._0-9]+]];
; O0: 	extract.0.v64.32b 	[[VR64_32_V64W1]], [[VR64_32_V64W0]];
; O0-NEXT: 	insert.56.v8.32b 	[[VR64_32_V64W1]], [[VR8_32_V8W0]];
; O0-NEXT: 	return [[VR64_32_V64W1]];
  %insert = call <64 x i32> @llvm.vector.insert.v64i32.v8i32(<64 x i32> %arg0, <8 x i32> %arg1, i64 56)
  ret <64 x i32> %insert
}
