; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -verify-machineinstrs > %t.pisa
; RUN: FileCheck < %t.pisa %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

; Following types are legal, according to OpenCL spec:
; - scalars of 1,2,4,8 bytes in size
; - vectors of above with 2,3,4,8,16 elements

%struct.small = type { i8, i16, i32 }
%struct.large = type { [13 x i32] }


; // extend/trunc
declare i1 @test_call_i1(i1 %arg)
declare signext i1 @test_call_i1_sext(i1 signext %arg)
declare i4 @test_call_i4(i4 %arg)
declare signext i4 @test_call_i4_sext(i4 signext %arg)
; // pass as is
declare <2 x i8> @test_call_i8_2(<2 x i8> %arg)
declare <3 x i8> @test_call_i8_3(<3 x i8> %arg)
declare <4 x i8> @test_call_i8_4(<4 x i8> %arg)
declare <2 x i16> @test_call_i16_2(<2 x i16> %arg)
declare <3 x i16> @test_call_i16_3(<3 x i16> %arg)
declare <4 x i16> @test_call_i16_4(<4 x i16> %arg)
declare <2 x i32> @test_call_i32_2(<2 x i32> %arg)
declare <3 x i32> @test_call_i32_3(<3 x i32> %arg)
declare <4 x i32> @test_call_i32_4(<4 x i32> %arg)
declare <5 x i32> @test_call_i32_5(<5 x i32> %arg)
declare <6 x i32> @test_call_i32_6(<6 x i32> %arg)
declare <7 x i32> @test_call_i32_7(<7 x i32> %arg)
declare <8 x i32> @test_call_i32_8(<8 x i32> %arg)
declare <16 x i32> @test_call_i32_16(<16 x i32> %arg)
declare <32 x i32> @test_call_i32_32(<32 x i32> %arg)
declare <64 x i32> @test_call_i32_64(<64 x i32> %arg)
declare <2 x i64> @test_call_i64_2(<2 x i64> %arg)
declare <3 x i64> @test_call_i64_3(<3 x i64> %arg)
declare <4 x i64> @test_call_i64_4(<4 x i64> %arg)
; // memory
declare <5 x i8> @test_call_i8_5(<5 x i8> %arg)
declare <5 x i16> @test_call_i16_5(<5 x i16> %arg)
declare <11 x i32> @test_call_i32_11(<11 x i32> %arg)
declare <5 x i64> @test_call_i64_5(<5 x i64> %arg)
declare %struct.small @test_call_struct_small(%struct.small %arg)
declare %struct.large @test_call_struct_large(%struct.large %arg)
; // scalarize
declare <1 x i16> @test_call_single_vector(<1 x i16> %arg)
; // pointers
declare ptr addrspace(2) @test_call_pointer2(ptr addrspace(2) %arg)
declare ptr addrspace(3) @test_call_pointer3(ptr addrspace(3) %arg)
declare <8 x ptr addrspace(2)> @test_call_pointer2_vector(<8 x ptr addrspace(2)> %arg)
declare <8 x ptr addrspace(3)> @test_call_pointer3_vector(<8 x ptr addrspace(3)> %arg)
declare <11 x ptr addrspace(3)> @test_call_pointer3_vector_odd(<11 x ptr addrspace(3)> %arg)
declare i1 @test_call_complex(i1, i8, i16, i32, i64, half, bfloat, float, double, <2 x i8>, <3 x i8>, <4 x i8>, <5 x i8>, <8 x i8>, <2 x i16>, <3 x i16>, <4 x i16>, <5 x i16>, <8 x i16>, <2 x i32>, <3 x i32>, <4 x i32>, <5 x i32>, <8 x i32>, <2 x i64>, <3 x i64>, <4 x i64>, <5 x i64>, <8 x i64>, <2 x half>, <3 x half>, <4 x half>, <5 x half>, <8 x half>, <2 x bfloat>, <3 x bfloat>, <4 x bfloat>, <5 x bfloat>, <8 x bfloat>, <2 x float>, <3 x float>, <4 x float>, <5 x float>, <8 x float>, <2 x double>, <3 x double>, <4 x double>, <5 x double>, <8 x double>)

define i1 @test_i1(i1 %arg) {
; CHECK-LABEL: .16b @test_i1(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; CHECK: 	and.16b 	[[R16_H1]], [[R16_H0]], 1;
; CHECK-NEXT: 	call [[R16_H2]], @test_call_i1 ([[R16_H1]]);
; CHECK-NEXT: 	and.16b 	[[R16_H3]], [[R16_H2]], 1;
; CHECK-NEXT: 	return [[R16_H3]];
;
; O0-LABEL: .16b @test_i1(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; O0: 	and.16b 	[[R16_H1]], [[R16_H0]], 1;
; O0-NEXT: 	call [[R16_H2]], @test_call_i1 ([[R16_H1]]);
; O0-NEXT: 	and.16b 	[[R16_H3]], [[R16_H2]], 1;
; O0-NEXT: 	return [[R16_H3]];
  %res = call i1 @test_call_i1(i1 %arg)
  ret i1 %res
}

define signext i1 @test_i1_sext(i1 signext %arg) {
; CHECK-LABEL: .16b @test_i1_sext(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H5:%[-a-zA-Z$._0-9]+]];
; CHECK: 	shl.16b 	[[R16_H1]], [[R16_H0]], 15;
; CHECK-NEXT: 	asr.16b 	[[R16_H2]], [[R16_H1]], 15;
; CHECK-NEXT: 	call [[R16_H3]], @test_call_i1_sext ([[R16_H2]]);
; CHECK-NEXT: 	shl.16b 	[[R16_H4]], [[R16_H3]], 15;
; CHECK-NEXT: 	asr.16b 	[[R16_H5]], [[R16_H4]], 15;
; CHECK-NEXT: 	return [[R16_H5]];
;
; O0-LABEL: .16b @test_i1_sext(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H5:%[-a-zA-Z$._0-9]+]];
; O0: 	shl.16b 	[[R16_H1]], [[R16_H0]], 15;
; O0-NEXT: 	asr.16b 	[[R16_H2]], [[R16_H1]], 15;
; O0-NEXT: 	call [[R16_H3]], @test_call_i1_sext ([[R16_H2]]);
; O0-NEXT: 	shl.16b 	[[R16_H4]], [[R16_H3]], 15;
; O0-NEXT: 	asr.16b 	[[R16_H5]], [[R16_H4]], 15;
; O0-NEXT: 	return [[R16_H5]];
  %res = call signext i1 @test_call_i1_sext(i1 signext %arg)
  ret i1 %res
}

define i4 @test_i4(i4 %arg) {
; CHECK-LABEL: .16b @test_i4(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; CHECK: 	and.16b 	[[R16_H1]], [[R16_H0]], 15;
; CHECK-NEXT: 	call [[R16_H2]], @test_call_i4 ([[R16_H1]]);
; CHECK-NEXT: 	and.16b 	[[R16_H3]], [[R16_H2]], 15;
; CHECK-NEXT: 	return [[R16_H3]];
;
; O0-LABEL: .16b @test_i4(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; O0: 	and.16b 	[[R16_H1]], [[R16_H0]], 15;
; O0-NEXT: 	call [[R16_H2]], @test_call_i4 ([[R16_H1]]);
; O0-NEXT: 	and.16b 	[[R16_H3]], [[R16_H2]], 15;
; O0-NEXT: 	return [[R16_H3]];
  %res = call i4 @test_call_i4(i4 %arg)
  ret i4 %res
}

define signext i4 @test_i4_sext(i4 signext %arg) {
; CHECK-LABEL: .16b @test_i4_sext(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H5:%[-a-zA-Z$._0-9]+]];
; CHECK: 	shl.16b 	[[R16_H1]], [[R16_H0]], 12;
; CHECK-NEXT: 	asr.16b 	[[R16_H2]], [[R16_H1]], 12;
; CHECK-NEXT: 	call [[R16_H3]], @test_call_i4_sext ([[R16_H2]]);
; CHECK-NEXT: 	shl.16b 	[[R16_H4]], [[R16_H3]], 12;
; CHECK-NEXT: 	asr.16b 	[[R16_H5]], [[R16_H4]], 12;
; CHECK-NEXT: 	return [[R16_H5]];
;
; O0-LABEL: .16b @test_i4_sext(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]], [[R16_H5:%[-a-zA-Z$._0-9]+]];
; O0: 	shl.16b 	[[R16_H1]], [[R16_H0]], 12;
; O0-NEXT: 	asr.16b 	[[R16_H2]], [[R16_H1]], 12;
; O0-NEXT: 	call [[R16_H3]], @test_call_i4_sext ([[R16_H2]]);
; O0-NEXT: 	shl.16b 	[[R16_H4]], [[R16_H3]], 12;
; O0-NEXT: 	asr.16b 	[[R16_H5]], [[R16_H4]], 12;
; O0-NEXT: 	return [[R16_H5]];
  %res = call signext i4 @test_call_i4_sext(i4 signext %arg)
  ret i4 %res
}

define <2 x i8> @test_i8_2(<2 x i8> %arg) {
; CHECK-LABEL: .v2.8b @test_i8_2(
; CHECK-SAME: .reg .v2.8b [[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.8b [[VR2_8_V2B1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR2_8_V2B1]], @test_call_i8_2 ([[VR2_8_V2B0]]);
; CHECK-NEXT: 	return [[VR2_8_V2B1]];
;
; O0-LABEL: .v2.8b @test_i8_2(
; O0-SAME: .reg .v2.8b [[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.8b [[VR2_8_V2B1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR2_8_V2B1]], @test_call_i8_2 ([[VR2_8_V2B0]]);
; O0-NEXT: 	return [[VR2_8_V2B1]];
  %res = call <2 x i8> @test_call_i8_2(<2 x i8> %arg)
  ret <2 x i8> %res
}

define <3 x i8> @test_i8_3(<3 x i8> %arg) {
; CHECK-LABEL: .v3.8b @test_i8_3(
; CHECK-SAME: .reg .v3.8b [[VR3_8_V3B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v3.8b [[VR3_8_V3B1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR3_8_V3B1]], @test_call_i8_3 ([[VR3_8_V3B0]]);
; CHECK-NEXT: 	return [[VR3_8_V3B1]];
;
; O0-LABEL: .v3.8b @test_i8_3(
; O0-SAME: .reg .v3.8b [[VR3_8_V3B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.8b [[VR3_8_V3B1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR3_8_V3B1]], @test_call_i8_3 ([[VR3_8_V3B0]]);
; O0-NEXT: 	return [[VR3_8_V3B1]];
  %res = call <3 x i8> @test_call_i8_3(<3 x i8> %arg)
  ret <3 x i8> %res
}

define <4 x i8> @test_i8_4(<4 x i8> %arg) {
; CHECK-LABEL: .v4.8b @test_i8_4(
; CHECK-SAME: .reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.8b [[VR4_8_V4B1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR4_8_V4B1]], @test_call_i8_4 ([[VR4_8_V4B0]]);
; CHECK-NEXT: 	return [[VR4_8_V4B1]];
;
; O0-LABEL: .v4.8b @test_i8_4(
; O0-SAME: .reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.8b [[VR4_8_V4B1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR4_8_V4B1]], @test_call_i8_4 ([[VR4_8_V4B0]]);
; O0-NEXT: 	return [[VR4_8_V4B1]];
  %res = call <4 x i8> @test_call_i8_4(<4 x i8> %arg)
  ret <4 x i8> %res
}

define <2 x i16> @test_i16_2(<2 x i16> %arg) {
; CHECK-LABEL: .v2.16b @test_i16_2(
; CHECK-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR2_16_V2H1]], @test_call_i16_2 ([[VR2_16_V2H0]]);
; CHECK-NEXT: 	return [[VR2_16_V2H1]];
;
; O0-LABEL: .v2.16b @test_i16_2(
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR2_16_V2H1]], @test_call_i16_2 ([[VR2_16_V2H0]]);
; O0-NEXT: 	return [[VR2_16_V2H1]];
  %res = call <2 x i16> @test_call_i16_2(<2 x i16> %arg)
  ret <2 x i16> %res
}

define <3 x i16> @test_i16_3(<3 x i16> %arg) {
; CHECK-LABEL: .v3.16b @test_i16_3(
; CHECK-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR3_16_V3H1]], @test_call_i16_3 ([[VR3_16_V3H0]]);
; CHECK-NEXT: 	return [[VR3_16_V3H1]];
;
; O0-LABEL: .v3.16b @test_i16_3(
; O0-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR3_16_V3H1]], @test_call_i16_3 ([[VR3_16_V3H0]]);
; O0-NEXT: 	return [[VR3_16_V3H1]];
  %res = call <3 x i16> @test_call_i16_3(<3 x i16> %arg)
  ret <3 x i16> %res
}

define <4 x i16> @test_i16_4(<4 x i16> %arg) {
; CHECK-LABEL: .v4.16b @test_i16_4(
; CHECK-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR4_16_V4H1]], @test_call_i16_4 ([[VR4_16_V4H0]]);
; CHECK-NEXT: 	return [[VR4_16_V4H1]];
;
; O0-LABEL: .v4.16b @test_i16_4(
; O0-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR4_16_V4H1]], @test_call_i16_4 ([[VR4_16_V4H0]]);
; O0-NEXT: 	return [[VR4_16_V4H1]];
  %res = call <4 x i16> @test_call_i16_4(<4 x i16> %arg)
  ret <4 x i16> %res
}

define <2 x i32> @test_i32_2(<2 x i32> %arg) {
; CHECK-LABEL: .v2.32b @test_i32_2(
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR2_32_V2W1]], @test_call_i32_2 ([[VR2_32_V2W0]]);
; CHECK-NEXT: 	return [[VR2_32_V2W1]];
;
; O0-LABEL: .v2.32b @test_i32_2(
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR2_32_V2W1]], @test_call_i32_2 ([[VR2_32_V2W0]]);
; O0-NEXT: 	return [[VR2_32_V2W1]];
  %res = call <2 x i32> @test_call_i32_2(<2 x i32> %arg)
  ret <2 x i32> %res
}

define <3 x i32> @test_i32_3(<3 x i32> %arg) {
; CHECK-LABEL: .v3.32b @test_i32_3(
; CHECK-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v3.32b [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR3_32_V3W1]], @test_call_i32_3 ([[VR3_32_V3W0]]);
; CHECK-NEXT: 	return [[VR3_32_V3W1]];
;
; O0-LABEL: .v3.32b @test_i32_3(
; O0-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.32b [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR3_32_V3W1]], @test_call_i32_3 ([[VR3_32_V3W0]]);
; O0-NEXT: 	return [[VR3_32_V3W1]];
  %res = call <3 x i32> @test_call_i32_3(<3 x i32> %arg)
  ret <3 x i32> %res
}

define <4 x i32> @test_i32_4(<4 x i32> %arg) {
; CHECK-LABEL: .v4.32b @test_i32_4(
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.32b [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR4_32_V4W1]], @test_call_i32_4 ([[VR4_32_V4W0]]);
; CHECK-NEXT: 	return [[VR4_32_V4W1]];
;
; O0-LABEL: .v4.32b @test_i32_4(
; O0-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.32b [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR4_32_V4W1]], @test_call_i32_4 ([[VR4_32_V4W0]]);
; O0-NEXT: 	return [[VR4_32_V4W1]];
  %res = call <4 x i32> @test_call_i32_4(<4 x i32> %arg)
  ret <4 x i32> %res
}

define <5 x i32> @test_i32_5(<5 x i32> %arg) {
; CHECK-LABEL: .v5.32b @test_i32_5(
; CHECK-SAME: .reg .v5.32b [[VR5_32_V5W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v5.32b [[VR5_32_V5W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR5_32_V5W1]], @test_call_i32_5 ([[VR5_32_V5W0]]);
; CHECK-NEXT: 	return [[VR5_32_V5W1]];
;
; O0-LABEL: .v5.32b @test_i32_5(
; O0-SAME: .reg .v5.32b [[VR5_32_V5W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v5.32b [[VR5_32_V5W1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR5_32_V5W1]], @test_call_i32_5 ([[VR5_32_V5W0]]);
; O0-NEXT: 	return [[VR5_32_V5W1]];
  %res = call <5 x i32> @test_call_i32_5(<5 x i32> %arg)
  ret <5 x i32> %res
}

define <6 x i32> @test_i32_6(<6 x i32> %arg) {
; CHECK-LABEL: .v6.32b @test_i32_6(
; CHECK-SAME: .reg .v6.32b [[VR6_32_V6W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v6.32b [[VR6_32_V6W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR6_32_V6W1]], @test_call_i32_6 ([[VR6_32_V6W0]]);
; CHECK-NEXT: 	return [[VR6_32_V6W1]];
;
; O0-LABEL: .v6.32b @test_i32_6(
; O0-SAME: .reg .v6.32b [[VR6_32_V6W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v6.32b [[VR6_32_V6W1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR6_32_V6W1]], @test_call_i32_6 ([[VR6_32_V6W0]]);
; O0-NEXT: 	return [[VR6_32_V6W1]];
  %res = call <6 x i32> @test_call_i32_6(<6 x i32> %arg)
  ret <6 x i32> %res
}

define <7 x i32> @test_i32_7(<7 x i32> %arg) {
; CHECK-LABEL: .v7.32b @test_i32_7(
; CHECK-SAME: .reg .v7.32b [[VR7_32_V7W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v7.32b [[VR7_32_V7W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR7_32_V7W1]], @test_call_i32_7 ([[VR7_32_V7W0]]);
; CHECK-NEXT: 	return [[VR7_32_V7W1]];
;
; O0-LABEL: .v7.32b @test_i32_7(
; O0-SAME: .reg .v7.32b [[VR7_32_V7W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v7.32b [[VR7_32_V7W1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR7_32_V7W1]], @test_call_i32_7 ([[VR7_32_V7W0]]);
; O0-NEXT: 	return [[VR7_32_V7W1]];
  %res = call <7 x i32> @test_call_i32_7(<7 x i32> %arg)
  ret <7 x i32> %res
}

define <8 x i32> @test_i32_8(<8 x i32> %arg) {
; CHECK-LABEL: .v8.32b @test_i32_8(
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR8_32_V8W1]], @test_call_i32_8 ([[VR8_32_V8W0]]);
; CHECK-NEXT: 	return [[VR8_32_V8W1]];
;
; O0-LABEL: .v8.32b @test_i32_8(
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR8_32_V8W1]], @test_call_i32_8 ([[VR8_32_V8W0]]);
; O0-NEXT: 	return [[VR8_32_V8W1]];
  %res = call <8 x i32> @test_call_i32_8(<8 x i32> %arg)
  ret <8 x i32> %res
}

define <16 x i32> @test_i32_16(<16 x i32> %arg) {
; CHECK-LABEL: .v16.32b @test_i32_16(
; CHECK-SAME: .reg .v16.32b [[VR16_32_V16W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v16.32b [[VR16_32_V16W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR16_32_V16W1]], @test_call_i32_16 ([[VR16_32_V16W0]]);
; CHECK-NEXT: 	return [[VR16_32_V16W1]];
;
; O0-LABEL: .v16.32b @test_i32_16(
; O0-SAME: .reg .v16.32b [[VR16_32_V16W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v16.32b [[VR16_32_V16W1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR16_32_V16W1]], @test_call_i32_16 ([[VR16_32_V16W0]]);
; O0-NEXT: 	return [[VR16_32_V16W1]];
  %res = call <16 x i32> @test_call_i32_16(<16 x i32> %arg)
  ret <16 x i32> %res
}

define <32 x i32> @test_i32_32(<32 x i32> %arg) {
; CHECK-LABEL: .v32.32b @test_i32_32(
; CHECK-SAME: .reg .v32.32b [[VR32_32_V32W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v32.32b [[VR32_32_V32W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR32_32_V32W1]], @test_call_i32_32 ([[VR32_32_V32W0]]);
; CHECK-NEXT: 	return [[VR32_32_V32W1]];
;
; O0-LABEL: .v32.32b @test_i32_32(
; O0-SAME: .reg .v32.32b [[VR32_32_V32W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v32.32b [[VR32_32_V32W1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR32_32_V32W1]], @test_call_i32_32 ([[VR32_32_V32W0]]);
; O0-NEXT: 	return [[VR32_32_V32W1]];
  %res = call <32 x i32> @test_call_i32_32(<32 x i32> %arg)
  ret <32 x i32> %res
}

define <64 x i32> @test_i32_64(<64 x i32> %arg) {
; CHECK-LABEL: .v64.32b @test_i32_64(
; CHECK-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v64.32b [[VR64_32_V64W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR64_32_V64W1]], @test_call_i32_64 ([[VR64_32_V64W0]]);
; CHECK-NEXT: 	return [[VR64_32_V64W1]];
;
; O0-LABEL: .v64.32b @test_i32_64(
; O0-SAME: .reg .v64.32b [[VR64_32_V64W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v64.32b [[VR64_32_V64W1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR64_32_V64W1]], @test_call_i32_64 ([[VR64_32_V64W0]]);
; O0-NEXT: 	return [[VR64_32_V64W1]];
  %res = call <64 x i32> @test_call_i32_64(<64 x i32> %arg)
  ret <64 x i32> %res
}

define <2 x i64> @test_i64_2(<2 x i64> %arg) {
; CHECK-LABEL: .v2.64b @test_i64_2(
; CHECK-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR2_64_V2D1]], @test_call_i64_2 ([[VR2_64_V2D0]]);
; CHECK-NEXT: 	return [[VR2_64_V2D1]];
;
; O0-LABEL: .v2.64b @test_i64_2(
; O0-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR2_64_V2D1]], @test_call_i64_2 ([[VR2_64_V2D0]]);
; O0-NEXT: 	return [[VR2_64_V2D1]];
  %res = call <2 x i64> @test_call_i64_2(<2 x i64> %arg)
  ret <2 x i64> %res
}

define <3 x i64> @test_i64_3(<3 x i64> %arg) {
; CHECK-LABEL: .v3.64b @test_i64_3(
; CHECK-SAME: .reg .v3.64b [[VR3_64_V3D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v3.64b [[VR3_64_V3D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR3_64_V3D1]], @test_call_i64_3 ([[VR3_64_V3D0]]);
; CHECK-NEXT: 	return [[VR3_64_V3D1]];
;
; O0-LABEL: .v3.64b @test_i64_3(
; O0-SAME: .reg .v3.64b [[VR3_64_V3D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.64b [[VR3_64_V3D1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR3_64_V3D1]], @test_call_i64_3 ([[VR3_64_V3D0]]);
; O0-NEXT: 	return [[VR3_64_V3D1]];
  %res = call <3 x i64> @test_call_i64_3(<3 x i64> %arg)
  ret <3 x i64> %res
}

define <4 x i64> @test_i64_4(<4 x i64> %arg) {
; CHECK-LABEL: .v4.64b @test_i64_4(
; CHECK-SAME: .reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.64b [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR4_64_V4D1]], @test_call_i64_4 ([[VR4_64_V4D0]]);
; CHECK-NEXT: 	return [[VR4_64_V4D1]];
;
; O0-LABEL: .v4.64b @test_i64_4(
; O0-SAME: .reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.64b [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR4_64_V4D1]], @test_call_i64_4 ([[VR4_64_V4D0]]);
; O0-NEXT: 	return [[VR4_64_V4D1]];
  %res = call <4 x i64> @test_call_i64_4(<4 x i64> %arg)
  ret <4 x i64> %res
}

define <5 x i8> @test_i8_5(<5 x i8> %arg) {
; CHECK-LABEL: void @test_i8_5(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]], [[R8_B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 8 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][8];
; CHECK-NEXT: 	.private .align 8 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][8];
; CHECK: 	ld.private.v4.8b	 [[VR4_8_V4B0]], [[[R32_W0]]];
; CHECK-NEXT: 	ld.private.8b	 [[R8_B0]], [[[R32_W0]] + 4];
; CHECK-NEXT: 	addrof.32b [[R32_W2]], [[PRIVATE_R0]];
; CHECK-NEXT: 	st.private.v4.8b	 [[[PRIVATE_R0]]], [[VR4_8_V4B0]];
; CHECK-NEXT: 	st.private.8b	 [[[PRIVATE_R0]] + 4], [[R8_B0]];
; CHECK-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R1]];
; CHECK-NEXT: 	call void, @test_call_i8_5 ([[R32_W2]], [[R32_W3]]);
; CHECK-NEXT: 	ld.private.v4.8b	 [[VR4_8_V4B1]], [[[PRIVATE_R1]]];
; CHECK-NEXT: 	ld.private.8b	 [[R8_B1]], [[[PRIVATE_R1]] + 4];
; CHECK-NEXT: 	st.private.v4.8b	 [[[R32_W1]]], [[VR4_8_V4B1]];
; CHECK-NEXT: 	st.private.8b	 [[[R32_W1]] + 4], [[R8_B1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @test_i8_5(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]], [[R8_B1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.private .align 8 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][8];
; O0-NEXT: 	.private .align 8 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][8];
; O0: 	ld.private.v4.8b	 [[VR4_8_V4B0]], [[[R32_W0]]];
; O0-NEXT: 	ld.private.8b	 [[R8_B0]], [[[R32_W0]] + 4];
; O0-NEXT: 	addrof.32b [[R32_W2]], [[PRIVATE_R0]];
; O0-NEXT: 	st.private.v4.8b	 [[[PRIVATE_R0]]], [[VR4_8_V4B0]];
; O0-NEXT: 	st.private.8b	 [[[PRIVATE_R0]] + 4], [[R8_B0]];
; O0-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R1]];
; O0-NEXT: 	call void, @test_call_i8_5 ([[R32_W2]], [[R32_W3]]);
; O0-NEXT: 	ld.private.v4.8b	 [[VR4_8_V4B1]], [[[PRIVATE_R1]]];
; O0-NEXT: 	ld.private.8b	 [[R8_B1]], [[[PRIVATE_R1]] + 4];
; O0-NEXT: 	st.private.v4.8b	 [[[R32_W1]]], [[VR4_8_V4B1]];
; O0-NEXT: 	st.private.8b	 [[[R32_W1]] + 4], [[R8_B1]];
; O0-NEXT: 	return;
  %res = call <5 x i8> @test_call_i8_5(<5 x i8> %arg)
  ret <5 x i8> %res
}

define <5 x i16> @test_i16_5(<5 x i16> %arg) {
; CHECK-LABEL: void @test_i16_5(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 16 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][16];
; CHECK-NEXT: 	.private .align 16 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][16];
; CHECK: 	ld.private.v4.16b	 [[VR4_16_V4H0]], [[[R32_W0]]];
; CHECK-NEXT: 	ld.private.16b	 [[R16_H0]], [[[R32_W0]] + 8];
; CHECK-NEXT: 	addrof.32b [[R32_W2]], [[PRIVATE_R0]];
; CHECK-NEXT: 	st.private.v4.16b	 [[[PRIVATE_R0]]], [[VR4_16_V4H0]];
; CHECK-NEXT: 	st.private.16b	 [[[PRIVATE_R0]] + 8], [[R16_H0]];
; CHECK-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R1]];
; CHECK-NEXT: 	call void, @test_call_i16_5 ([[R32_W2]], [[R32_W3]]);
; CHECK-NEXT: 	ld.private.v4.16b	 [[VR4_16_V4H1]], [[[PRIVATE_R1]]];
; CHECK-NEXT: 	ld.private.16b	 [[R16_H1]], [[[PRIVATE_R1]] + 8];
; CHECK-NEXT: 	st.private.v4.16b	 [[[R32_W1]]], [[VR4_16_V4H1]];
; CHECK-NEXT: 	st.private.16b	 [[[R32_W1]] + 8], [[R16_H1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @test_i16_5(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.private .align 16 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][16];
; O0-NEXT: 	.private .align 16 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][16];
; O0: 	ld.private.v4.16b	 [[VR4_16_V4H0]], [[[R32_W0]]];
; O0-NEXT: 	ld.private.16b	 [[R16_H0]], [[[R32_W0]] + 8];
; O0-NEXT: 	addrof.32b [[R32_W2]], [[PRIVATE_R0]];
; O0-NEXT: 	st.private.v4.16b	 [[[PRIVATE_R0]]], [[VR4_16_V4H0]];
; O0-NEXT: 	st.private.16b	 [[[PRIVATE_R0]] + 8], [[R16_H0]];
; O0-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R1]];
; O0-NEXT: 	call void, @test_call_i16_5 ([[R32_W2]], [[R32_W3]]);
; O0-NEXT: 	ld.private.v4.16b	 [[VR4_16_V4H1]], [[[PRIVATE_R1]]];
; O0-NEXT: 	ld.private.16b	 [[R16_H1]], [[[PRIVATE_R1]] + 8];
; O0-NEXT: 	st.private.v4.16b	 [[[R32_W1]]], [[VR4_16_V4H1]];
; O0-NEXT: 	st.private.16b	 [[[R32_W1]] + 8], [[R16_H1]];
; O0-NEXT: 	return;
  %res = call <5 x i16> @test_call_i16_5(<5 x i16> %arg)
  ret <5 x i16> %res
}

define <11 x i32> @test_i32_11(<11 x i32> %arg) {
; CHECK-LABEL: void @test_i32_11(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 64 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][64];
; CHECK-NEXT: 	.private .align 64 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][64];
; CHECK: 	ld.private.v8.32b	 [[VR8_32_V8W0]], [[[R32_W0]]];
; CHECK-NEXT: 	ld.private.v3.32b	 [[VR3_32_V3W0]], [[[R32_W0]] + 32];
; CHECK-NEXT: 	addrof.32b [[R32_W2]], [[PRIVATE_R0]];
; CHECK-NEXT: 	st.private.v8.32b	 [[[PRIVATE_R0]]], [[VR8_32_V8W0]];
; CHECK-NEXT: 	st.private.v3.32b	 [[[PRIVATE_R0]] + 32], [[VR3_32_V3W0]];
; CHECK-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R1]];
; CHECK-NEXT: 	call void, @test_call_i32_11 ([[R32_W2]], [[R32_W3]]);
; CHECK-NEXT: 	ld.private.v8.32b	 [[VR8_32_V8W1]], [[[PRIVATE_R1]]];
; CHECK-NEXT: 	ld.private.v3.32b	 [[VR3_32_V3W1]], [[[PRIVATE_R1]] + 32];
; CHECK-NEXT: 	st.private.v8.32b	 [[[R32_W1]]], [[VR8_32_V8W1]];
; CHECK-NEXT: 	st.private.v3.32b	 [[[R32_W1]] + 32], [[VR3_32_V3W1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @test_i32_11(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.private .align 64 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][64];
; O0-NEXT: 	.private .align 64 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][64];
; O0: 	ld.private.v8.32b	 [[VR8_32_V8W0]], [[[R32_W0]]];
; O0-NEXT: 	ld.private.v3.32b	 [[VR3_32_V3W0]], [[[R32_W0]] + 32];
; O0-NEXT: 	addrof.32b [[R32_W2]], [[PRIVATE_R0]];
; O0-NEXT: 	st.private.v8.32b	 [[[PRIVATE_R0]]], [[VR8_32_V8W0]];
; O0-NEXT: 	st.private.v3.32b	 [[[PRIVATE_R0]] + 32], [[VR3_32_V3W0]];
; O0-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R1]];
; O0-NEXT: 	call void, @test_call_i32_11 ([[R32_W2]], [[R32_W3]]);
; O0-NEXT: 	ld.private.v8.32b	 [[VR8_32_V8W1]], [[[PRIVATE_R1]]];
; O0-NEXT: 	ld.private.v3.32b	 [[VR3_32_V3W1]], [[[PRIVATE_R1]] + 32];
; O0-NEXT: 	st.private.v8.32b	 [[[R32_W1]]], [[VR8_32_V8W1]];
; O0-NEXT: 	st.private.v3.32b	 [[[R32_W1]] + 32], [[VR3_32_V3W1]];
; O0-NEXT: 	return;
  %res = call <11 x i32> @test_call_i32_11(<11 x i32> %arg)
  ret <11 x i32> %res
}

define <5 x i64> @test_i64_5(<5 x i64> %arg) {
; CHECK-LABEL: void @test_i64_5(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]], [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 64 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][64];
; CHECK-NEXT: 	.private .align 64 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][64];
; CHECK: 	ld.private.v4.64b	 [[VR4_64_V4D0]], [[[R32_W0]]];
; CHECK-NEXT: 	ld.private.64b	 [[R64_D0]], [[[R32_W0]] + 32];
; CHECK-NEXT: 	addrof.32b [[R32_W2]], [[PRIVATE_R0]];
; CHECK-NEXT: 	st.private.v4.64b	 [[[PRIVATE_R0]]], [[VR4_64_V4D0]];
; CHECK-NEXT: 	st.private.64b	 [[[PRIVATE_R0]] + 32], [[R64_D0]];
; CHECK-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R1]];
; CHECK-NEXT: 	call void, @test_call_i64_5 ([[R32_W2]], [[R32_W3]]);
; CHECK-NEXT: 	ld.private.v4.64b	 [[VR4_64_V4D1]], [[[PRIVATE_R1]]];
; CHECK-NEXT: 	ld.private.64b	 [[R64_D1]], [[[PRIVATE_R1]] + 32];
; CHECK-NEXT: 	st.private.v4.64b	 [[[R32_W1]]], [[VR4_64_V4D1]];
; CHECK-NEXT: 	st.private.64b	 [[[R32_W1]] + 32], [[R64_D1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @test_i64_5(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]], [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.private .align 64 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][64];
; O0-NEXT: 	.private .align 64 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][64];
; O0: 	ld.private.v4.64b	 [[VR4_64_V4D0]], [[[R32_W0]]];
; O0-NEXT: 	ld.private.64b	 [[R64_D0]], [[[R32_W0]] + 32];
; O0-NEXT: 	addrof.32b [[R32_W2]], [[PRIVATE_R0]];
; O0-NEXT: 	st.private.v4.64b	 [[[PRIVATE_R0]]], [[VR4_64_V4D0]];
; O0-NEXT: 	st.private.64b	 [[[PRIVATE_R0]] + 32], [[R64_D0]];
; O0-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R1]];
; O0-NEXT: 	call void, @test_call_i64_5 ([[R32_W2]], [[R32_W3]]);
; O0-NEXT: 	ld.private.v4.64b	 [[VR4_64_V4D1]], [[[PRIVATE_R1]]];
; O0-NEXT: 	ld.private.64b	 [[R64_D1]], [[[PRIVATE_R1]] + 32];
; O0-NEXT: 	st.private.v4.64b	 [[[R32_W1]]], [[VR4_64_V4D1]];
; O0-NEXT: 	st.private.64b	 [[[R32_W1]] + 32], [[R64_D1]];
; O0-NEXT: 	return;
  %res = call <5 x i64> @test_call_i64_5(<5 x i64> %arg)
  ret <5 x i64> %res
}

define %struct.small @test_struct_small(%struct.small %arg) {
; CHECK-LABEL: void @test_struct_small(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]], [[R8_B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 8 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][8];
; CHECK-NEXT: 	.private .align 8 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][8];
; CHECK: 	ld.private.8b	 [[R8_B0]], [[[R32_W0]]];
; CHECK-NEXT: 	ld.private.16b	 [[R16_H0]], [[[R32_W0]] + 2];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W2]], [[[R32_W0]] + 4];
; CHECK-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R0]];
; CHECK-NEXT: 	st.private.8b	 [[[PRIVATE_R0]]], [[R8_B0]];
; CHECK-NEXT: 	st.private.16b	 [[[PRIVATE_R0]] + 2], [[R16_H0]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 4], [[R32_W2]];
; CHECK-NEXT: 	addrof.32b [[R32_W4]], [[PRIVATE_R1]];
; CHECK-NEXT: 	call void, @test_call_struct_small ([[R32_W3]], [[R32_W4]]);
; CHECK-NEXT: 	ld.private.8b	 [[R8_B1]], [[[PRIVATE_R1]]];
; CHECK-NEXT: 	ld.private.16b	 [[R16_H1]], [[[PRIVATE_R1]] + 2];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W5]], [[[PRIVATE_R1]] + 4];
; CHECK-NEXT: 	st.private.8b	 [[[R32_W1]]], [[R8_B1]];
; CHECK-NEXT: 	st.private.16b	 [[[R32_W1]] + 2], [[R16_H1]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 4], [[R32_W5]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @test_struct_small(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]], [[R8_B1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.private .align 8 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][8];
; O0-NEXT: 	.private .align 8 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][8];
; O0: 	ld.private.8b	 [[R8_B0]], [[[R32_W0]]];
; O0-NEXT: 	ld.private.16b	 [[R16_H0]], [[[R32_W0]] + 2];
; O0-NEXT: 	ld.private.32b	 [[R32_W2]], [[[R32_W0]] + 4];
; O0-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R0]];
; O0-NEXT: 	st.private.8b	 [[[PRIVATE_R0]]], [[R8_B0]];
; O0-NEXT: 	st.private.16b	 [[[PRIVATE_R0]] + 2], [[R16_H0]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 4], [[R32_W2]];
; O0-NEXT: 	addrof.32b [[R32_W4]], [[PRIVATE_R1]];
; O0-NEXT: 	call void, @test_call_struct_small ([[R32_W3]], [[R32_W4]]);
; O0-NEXT: 	ld.private.8b	 [[R8_B1]], [[[PRIVATE_R1]]];
; O0-NEXT: 	ld.private.16b	 [[R16_H1]], [[[PRIVATE_R1]] + 2];
; O0-NEXT: 	ld.private.32b	 [[R32_W5]], [[[PRIVATE_R1]] + 4];
; O0-NEXT: 	st.private.8b	 [[[R32_W1]]], [[R8_B1]];
; O0-NEXT: 	st.private.16b	 [[[R32_W1]] + 2], [[R16_H1]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 4], [[R32_W5]];
; O0-NEXT: 	return;
  %res = call %struct.small @test_call_struct_small(%struct.small %arg)
  ret %struct.small %res
}

define %struct.large @test_struct_large(%struct.large %arg) {
; CHECK-LABEL: void @test_struct_large(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b %w<2~30>;
; CHECK-NEXT: 	.private .align 8 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][52];
; CHECK-NEXT: 	.private .align 8 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][52];
; CHECK: 	ld.private.32b	 [[R32_W2:%[-a-zA-Z$._0-9]+]], [[[R32_W0]]];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W3:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 4];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W4:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 8];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W5:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 12];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W6:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 16];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W7:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 20];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W8:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 24];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W9:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 28];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W10:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 32];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W11:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 36];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W12:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 40];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W13:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 44];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W14:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 48];
; CHECK-NEXT: 	addrof.32b [[R32_W15:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R0]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]]], [[R32_W2]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 4], [[R32_W3]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 8], [[R32_W4]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 12], [[R32_W5]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 16], [[R32_W6]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 20], [[R32_W7]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 24], [[R32_W8]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 28], [[R32_W9]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 32], [[R32_W10]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 36], [[R32_W11]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 40], [[R32_W12]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 44], [[R32_W13]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 48], [[R32_W14]];
; CHECK-NEXT: 	addrof.32b [[R32_W16:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R1]];
; CHECK-NEXT: 	call void, @test_call_struct_large ([[R32_W15]], [[R32_W16]]);
; CHECK-NEXT: 	ld.private.32b	 [[R32_W17:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]]];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W18:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 4];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W19:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 8];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W20:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 12];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W21:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 16];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W22:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 20];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W23:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 24];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W24:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 28];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W25:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 32];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W26:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 36];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W27:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 40];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W28:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 44];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W29:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 48];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]]], [[R32_W17]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 4], [[R32_W18]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 8], [[R32_W19]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 12], [[R32_W20]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 16], [[R32_W21]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 20], [[R32_W22]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 24], [[R32_W23]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 28], [[R32_W24]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 32], [[R32_W25]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 36], [[R32_W26]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 40], [[R32_W27]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 44], [[R32_W28]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W1]] + 48], [[R32_W29]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @test_struct_large(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b %w<2~30>;
; O0-NEXT: 	.private .align 8 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][52];
; O0-NEXT: 	.private .align 8 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][52];
; O0: 	ld.private.32b	 [[R32_W2:%[-a-zA-Z$._0-9]+]], [[[R32_W0]]];
; O0-NEXT: 	ld.private.32b	 [[R32_W3:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 4];
; O0-NEXT: 	ld.private.32b	 [[R32_W4:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 8];
; O0-NEXT: 	ld.private.32b	 [[R32_W5:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 12];
; O0-NEXT: 	ld.private.32b	 [[R32_W6:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 16];
; O0-NEXT: 	ld.private.32b	 [[R32_W7:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 20];
; O0-NEXT: 	ld.private.32b	 [[R32_W8:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 24];
; O0-NEXT: 	ld.private.32b	 [[R32_W9:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 28];
; O0-NEXT: 	ld.private.32b	 [[R32_W10:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 32];
; O0-NEXT: 	ld.private.32b	 [[R32_W11:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 36];
; O0-NEXT: 	ld.private.32b	 [[R32_W12:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 40];
; O0-NEXT: 	ld.private.32b	 [[R32_W13:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 44];
; O0-NEXT: 	ld.private.32b	 [[R32_W14:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 48];
; O0-NEXT: 	addrof.32b [[R32_W15:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R0]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]]], [[R32_W2]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 4], [[R32_W3]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 8], [[R32_W4]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 12], [[R32_W5]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 16], [[R32_W6]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 20], [[R32_W7]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 24], [[R32_W8]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 28], [[R32_W9]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 32], [[R32_W10]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 36], [[R32_W11]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 40], [[R32_W12]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 44], [[R32_W13]];
; O0-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 48], [[R32_W14]];
; O0-NEXT: 	addrof.32b [[R32_W16:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R1]];
; O0-NEXT: 	call void, @test_call_struct_large ([[R32_W15]], [[R32_W16]]);
; O0-NEXT: 	ld.private.32b	 [[R32_W17:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]]];
; O0-NEXT: 	ld.private.32b	 [[R32_W18:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 4];
; O0-NEXT: 	ld.private.32b	 [[R32_W19:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 8];
; O0-NEXT: 	ld.private.32b	 [[R32_W20:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 12];
; O0-NEXT: 	ld.private.32b	 [[R32_W21:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 16];
; O0-NEXT: 	ld.private.32b	 [[R32_W22:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 20];
; O0-NEXT: 	ld.private.32b	 [[R32_W23:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 24];
; O0-NEXT: 	ld.private.32b	 [[R32_W24:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 28];
; O0-NEXT: 	ld.private.32b	 [[R32_W25:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 32];
; O0-NEXT: 	ld.private.32b	 [[R32_W26:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 36];
; O0-NEXT: 	ld.private.32b	 [[R32_W27:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 40];
; O0-NEXT: 	ld.private.32b	 [[R32_W28:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 44];
; O0-NEXT: 	ld.private.32b	 [[R32_W29:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 48];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]]], [[R32_W17]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 4], [[R32_W18]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 8], [[R32_W19]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 12], [[R32_W20]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 16], [[R32_W21]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 20], [[R32_W22]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 24], [[R32_W23]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 28], [[R32_W24]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 32], [[R32_W25]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 36], [[R32_W26]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 40], [[R32_W27]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 44], [[R32_W28]];
; O0-NEXT: 	st.private.32b	 [[[R32_W1]] + 48], [[R32_W29]];
; O0-NEXT: 	return;
  %res = call %struct.large @test_call_struct_large(%struct.large %arg)
  ret %struct.large %res
}

define <1 x i16> @test_single_vector(<1 x i16> %arg) {
; CHECK-LABEL: .16b @test_single_vector(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[R16_H1]], @test_call_single_vector ([[R16_H0]]);
; CHECK-NEXT: 	return [[R16_H1]];
;
; O0-LABEL: .16b @test_single_vector(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[R16_H1]], @test_call_single_vector ([[R16_H0]]);
; O0-NEXT: 	return [[R16_H1]];
  %res = call <1 x i16> @test_call_single_vector(<1 x i16> %arg)
  ret <1 x i16> %res
}

define ptr addrspace(2) @test_pointer2(ptr addrspace(2) %arg) {
; CHECK-LABEL: .64b @test_pointer2(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[R64_D1]], @test_call_pointer2 ([[R64_D0]]);
; CHECK-NEXT: 	return [[R64_D1]];
;
; O0-LABEL: .64b @test_pointer2(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[R64_D1]], @test_call_pointer2 ([[R64_D0]]);
; O0-NEXT: 	return [[R64_D1]];
  %res = call ptr addrspace(2) @test_call_pointer2(ptr addrspace(2) %arg)
  ret ptr addrspace(2) %res
}

define ptr addrspace(3) @test_pointer3(ptr addrspace(3) %arg) {
; CHECK-LABEL: .32b @test_pointer3(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[R32_W1]], @test_call_pointer3 ([[R32_W0]]);
; CHECK-NEXT: 	return [[R32_W1]];
;
; O0-LABEL: .32b @test_pointer3(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[R32_W1]], @test_call_pointer3 ([[R32_W0]]);
; O0-NEXT: 	return [[R32_W1]];
  %res = call ptr addrspace(3) @test_call_pointer3(ptr addrspace(3) %arg)
  ret ptr addrspace(3) %res
}

define <8 x ptr addrspace(2)> @test_pointer2_vector(<8 x ptr addrspace(2)> %arg) {
; CHECK-LABEL: void @test_pointer2_vector(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D2:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 64 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][64];
; CHECK-NEXT: 	.private .align 64 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][64];
; CHECK: 	ld.private.v4.64b	 [[VR4_64_V4D0]], [[[R32_W0]]];
; CHECK-NEXT: 	ld.private.v4.64b	 [[VR4_64_V4D1]], [[[R32_W0]] + 32];
; CHECK-NEXT: 	addrof.32b [[R32_W2]], [[PRIVATE_R0]];
; CHECK-NEXT: 	st.private.v4.64b	 [[[PRIVATE_R0]]], [[VR4_64_V4D0]];
; CHECK-NEXT: 	st.private.v4.64b	 [[[PRIVATE_R0]] + 32], [[VR4_64_V4D1]];
; CHECK-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R1]];
; CHECK-NEXT: 	call void, @test_call_pointer2_vector ([[R32_W2]], [[R32_W3]]);
; CHECK-NEXT: 	ld.private.v4.64b	 [[VR4_64_V4D2]], [[[PRIVATE_R1]]];
; CHECK-NEXT: 	ld.private.v4.64b	 [[VR4_64_V4D3]], [[[PRIVATE_R1]] + 32];
; CHECK-NEXT: 	st.private.v4.64b	 [[[R32_W1]]], [[VR4_64_V4D2]];
; CHECK-NEXT: 	st.private.v4.64b	 [[[R32_W1]] + 32], [[VR4_64_V4D3]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @test_pointer2_vector(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v4.64b %v4d<0~20>;
; O0-NEXT: 	.reg .64b %d<0~16>;
; O0-NEXT: 	.private .align 64 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][64];
; O0-NEXT: 	.private .align 64 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][64];
; O0: 	ld.private.v4.64b	 [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]], [[[R32_W0]]];
; O0-NEXT: 	mov.64b 	[[R64_D0:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].x;
; O0-NEXT: 	mov.64b 	[[R64_D1:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].y;
; O0-NEXT: 	mov.64b 	[[R64_D2:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].z;
; O0-NEXT: 	mov.64b 	[[R64_D3:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].w;
; O0-NEXT: 	ld.private.v4.64b	 [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 32];
; O0-NEXT: 	mov.64b 	[[R64_D4:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D1]].x;
; O0-NEXT: 	mov.64b 	[[R64_D5:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D1]].y;
; O0-NEXT: 	mov.64b 	[[R64_D6:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D1]].z;
; O0-NEXT: 	mov.64b 	[[R64_D7:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D1]].w;
; O0-NEXT: 	addrof.32b [[R32_W2]], [[PRIVATE_R0]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2:%[-a-zA-Z$._0-9]+]].x, [[R64_D0]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D2]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].y, [[VR4_64_V4D2]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].z, [[VR4_64_V4D2]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].w, [[VR4_64_V4D2]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].y, [[R64_D1]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D3]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].y, [[VR4_64_V4D3]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].z, [[VR4_64_V4D3]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].w, [[VR4_64_V4D3]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].z, [[R64_D2]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D5:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D4]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D5]].y, [[VR4_64_V4D4]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D5]].z, [[VR4_64_V4D4]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D5]].w, [[VR4_64_V4D4]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D5]].w, [[R64_D3]];
; O0-NEXT: 	st.private.v4.64b	 [[[PRIVATE_R0]]], [[VR4_64_V4D5]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D6:%[-a-zA-Z$._0-9]+]].x, [[R64_D4]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D7:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D6]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D7]].y, [[VR4_64_V4D6]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D7]].z, [[VR4_64_V4D6]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D7]].w, [[VR4_64_V4D6]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D7]].y, [[R64_D5]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D8:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D7]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D8]].y, [[VR4_64_V4D7]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D8]].z, [[VR4_64_V4D7]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D8]].w, [[VR4_64_V4D7]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D8]].z, [[R64_D6]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D9:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D8]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D9]].y, [[VR4_64_V4D8]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D9]].z, [[VR4_64_V4D8]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D9]].w, [[VR4_64_V4D8]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D9]].w, [[R64_D7]];
; O0-NEXT: 	st.private.v4.64b	 [[[PRIVATE_R0]] + 32], [[VR4_64_V4D9]];
; O0-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R1]];
; O0-NEXT: 	call void, @test_call_pointer2_vector ([[R32_W2]], [[R32_W3]]);
; O0-NEXT: 	ld.private.v4.64b	 [[VR4_64_V4D10:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]]];
; O0-NEXT: 	mov.64b 	[[R64_D8:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D10]].x;
; O0-NEXT: 	mov.64b 	[[R64_D9:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D10]].y;
; O0-NEXT: 	mov.64b 	[[R64_D10:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D10]].z;
; O0-NEXT: 	mov.64b 	[[R64_D11:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D10]].w;
; O0-NEXT: 	ld.private.v4.64b	 [[VR4_64_V4D11:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 32];
; O0-NEXT: 	mov.64b 	[[R64_D12:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D11]].x;
; O0-NEXT: 	mov.64b 	[[R64_D13:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D11]].y;
; O0-NEXT: 	mov.64b 	[[R64_D14:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D11]].z;
; O0-NEXT: 	mov.64b 	[[R64_D15:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D11]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D12:%[-a-zA-Z$._0-9]+]].x, [[R64_D8]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D13:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D12]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D13]].y, [[VR4_64_V4D12]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D13]].z, [[VR4_64_V4D12]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D13]].w, [[VR4_64_V4D12]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D13]].y, [[R64_D9]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D14:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D13]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D14]].y, [[VR4_64_V4D13]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D14]].z, [[VR4_64_V4D13]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D14]].w, [[VR4_64_V4D13]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D14]].z, [[R64_D10]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D15:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D14]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D15]].y, [[VR4_64_V4D14]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D15]].z, [[VR4_64_V4D14]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D15]].w, [[VR4_64_V4D14]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D15]].w, [[R64_D11]];
; O0-NEXT: 	st.private.v4.64b	 [[[R32_W1]]], [[VR4_64_V4D15]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D16:%[-a-zA-Z$._0-9]+]].x, [[R64_D12]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D17:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D16]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D17]].y, [[VR4_64_V4D16]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D17]].z, [[VR4_64_V4D16]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D17]].w, [[VR4_64_V4D16]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D17]].y, [[R64_D13]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D18:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D17]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D18]].y, [[VR4_64_V4D17]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D18]].z, [[VR4_64_V4D17]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D18]].w, [[VR4_64_V4D17]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D18]].z, [[R64_D14]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D19:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D18]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D19]].y, [[VR4_64_V4D18]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D19]].z, [[VR4_64_V4D18]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D19]].w, [[VR4_64_V4D18]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D19]].w, [[R64_D15]];
; O0-NEXT: 	st.private.v4.64b	 [[[R32_W1]] + 32], [[VR4_64_V4D19]];
; O0-NEXT: 	return;
  %res = call <8 x ptr addrspace(2)> @test_call_pointer2_vector(<8 x ptr addrspace(2)> %arg)
  ret <8 x ptr addrspace(2)> %res
}

define <8 x ptr addrspace(3)> @test_pointer3_vector(<8 x ptr addrspace(3)> %arg) {
; CHECK-LABEL: .v8.32b @test_pointer3_vector(
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	call [[VR8_32_V8W1]], @test_call_pointer3_vector ([[VR8_32_V8W0]]);
; CHECK-NEXT: 	return [[VR8_32_V8W1]];
;
; O0-LABEL: .v8.32b @test_pointer3_vector(
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]];
; O0: 	call [[VR8_32_V8W1]], @test_call_pointer3_vector ([[VR8_32_V8W0]]);
; O0-NEXT: 	return [[VR8_32_V8W1]];
  %res = call <8 x ptr addrspace(3)> @test_call_pointer3_vector(<8 x ptr addrspace(3)> %arg)
  ret <8 x ptr addrspace(3)> %res
}

define <11 x ptr addrspace(3)> @test_pointer3_vector_odd(<11 x ptr addrspace(3)> %arg) {
; CHECK-LABEL: void @test_pointer3_vector_odd(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 64 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][64];
; CHECK-NEXT: 	.private .align 64 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][64];
; CHECK: 	ld.private.v8.32b	 [[VR8_32_V8W0]], [[[R32_W0]]];
; CHECK-NEXT: 	ld.private.v3.32b	 [[VR3_32_V3W0]], [[[R32_W0]] + 32];
; CHECK-NEXT: 	addrof.32b [[R32_W2]], [[PRIVATE_R0]];
; CHECK-NEXT: 	st.private.v8.32b	 [[[PRIVATE_R0]]], [[VR8_32_V8W0]];
; CHECK-NEXT: 	st.private.v3.32b	 [[[PRIVATE_R0]] + 32], [[VR3_32_V3W0]];
; CHECK-NEXT: 	addrof.32b [[R32_W3]], [[PRIVATE_R1]];
; CHECK-NEXT: 	call void, @test_call_pointer3_vector_odd ([[R32_W2]], [[R32_W3]]);
; CHECK-NEXT: 	ld.private.v8.32b	 [[VR8_32_V8W1]], [[[PRIVATE_R1]]];
; CHECK-NEXT: 	ld.private.v3.32b	 [[VR3_32_V3W1]], [[[PRIVATE_R1]] + 32];
; CHECK-NEXT: 	st.private.v8.32b	 [[[R32_W1]]], [[VR8_32_V8W1]];
; CHECK-NEXT: 	st.private.v3.32b	 [[[R32_W1]] + 32], [[VR3_32_V3W1]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @test_pointer3_vector_odd(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b %w<2~26>;
; O0-NEXT: 	.reg .v8.32b %v8w<0~18>;
; O0-NEXT: 	.reg .v3.32b %v3w<0~8>;
; O0-NEXT: 	.private .align 64 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][64];
; O0-NEXT: 	.private .align 64 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][64];
; O0: 	ld.private.v8.32b	 [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]], [[[R32_W0]]];
; O0-NEXT: 	mov.32b 	[[R32_W2:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W0]].x;
; O0-NEXT: 	mov.32b 	[[R32_W3:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W0]].y;
; O0-NEXT: 	mov.32b 	[[R32_W4:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W0]].z;
; O0-NEXT: 	mov.32b 	[[R32_W5:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W0]].w;
; O0-NEXT: 	extract.4.32b 	[[R32_W6:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W0]];
; O0-NEXT: 	extract.5.32b 	[[R32_W7:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W0]];
; O0-NEXT: 	extract.6.32b 	[[R32_W8:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W0]];
; O0-NEXT: 	extract.7.32b 	[[R32_W9:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W0]];
; O0-NEXT: 	ld.private.v3.32b	 [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]], [[[R32_W0]] + 32];
; O0-NEXT: 	mov.32b 	[[R32_W10:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W0]].x;
; O0-NEXT: 	mov.32b 	[[R32_W11:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W0]].y;
; O0-NEXT: 	mov.32b 	[[R32_W12:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W0]].z;
; O0-NEXT: 	addrof.32b [[R32_W13:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R0]];
; O0-NEXT: 	insert.0.32b 	[[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]], [[R32_W2]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W1]];
; O0-NEXT: 	insert.1.32b 	[[VR8_32_V8W2]], [[R32_W3]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W3:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W2]];
; O0-NEXT: 	insert.2.32b 	[[VR8_32_V8W3]], [[R32_W4]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W4:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W3]];
; O0-NEXT: 	insert.3.32b 	[[VR8_32_V8W4]], [[R32_W5]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W5:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W4]];
; O0-NEXT: 	insert.4.32b 	[[VR8_32_V8W5]], [[R32_W6]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W6:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W5]];
; O0-NEXT: 	insert.5.32b 	[[VR8_32_V8W6]], [[R32_W7]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W7:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W6]];
; O0-NEXT: 	insert.6.32b 	[[VR8_32_V8W7]], [[R32_W8]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W8:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W7]];
; O0-NEXT: 	insert.7.32b 	[[VR8_32_V8W8]], [[R32_W9]];
; O0-NEXT: 	st.private.v8.32b	 [[[PRIVATE_R0]]], [[VR8_32_V8W8]];
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]].x, [[R32_W10]];
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2:%[-a-zA-Z$._0-9]+]].x, [[VR3_32_V3W1]].x;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].y, [[VR3_32_V3W1]].y;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].z, [[VR3_32_V3W1]].z;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].y, [[R32_W11]];
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3:%[-a-zA-Z$._0-9]+]].x, [[VR3_32_V3W2]].x;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].y, [[VR3_32_V3W2]].y;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].z, [[VR3_32_V3W2]].z;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].z, [[R32_W12]];
; O0-NEXT: 	st.private.v3.32b	 [[[PRIVATE_R0]] + 32], [[VR3_32_V3W3]];
; O0-NEXT: 	addrof.32b [[R32_W14:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R1]];
; O0-NEXT: 	call void, @test_call_pointer3_vector_odd ([[R32_W13]], [[R32_W14]]);
; O0-NEXT: 	ld.private.v8.32b	 [[VR8_32_V8W9:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]]];
; O0-NEXT: 	mov.32b 	[[R32_W15:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W9]].x;
; O0-NEXT: 	mov.32b 	[[R32_W16:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W9]].y;
; O0-NEXT: 	mov.32b 	[[R32_W17:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W9]].z;
; O0-NEXT: 	mov.32b 	[[R32_W18:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W9]].w;
; O0-NEXT: 	extract.4.32b 	[[R32_W19:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W9]];
; O0-NEXT: 	extract.5.32b 	[[R32_W20:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W9]];
; O0-NEXT: 	extract.6.32b 	[[R32_W21:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W9]];
; O0-NEXT: 	extract.7.32b 	[[R32_W22:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W9]];
; O0-NEXT: 	ld.private.v3.32b	 [[VR3_32_V3W4:%[-a-zA-Z$._0-9]+]], [[[PRIVATE_R1]] + 32];
; O0-NEXT: 	mov.32b 	[[R32_W23:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W4]].x;
; O0-NEXT: 	mov.32b 	[[R32_W24:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W4]].y;
; O0-NEXT: 	mov.32b 	[[R32_W25:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W4]].z;
; O0-NEXT: 	insert.0.32b 	[[VR8_32_V8W10:%[-a-zA-Z$._0-9]+]], [[R32_W15]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W11:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W10]];
; O0-NEXT: 	insert.1.32b 	[[VR8_32_V8W11]], [[R32_W16]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W12:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W11]];
; O0-NEXT: 	insert.2.32b 	[[VR8_32_V8W12]], [[R32_W17]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W13:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W12]];
; O0-NEXT: 	insert.3.32b 	[[VR8_32_V8W13]], [[R32_W18]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W14:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W13]];
; O0-NEXT: 	insert.4.32b 	[[VR8_32_V8W14]], [[R32_W19]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W15:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W14]];
; O0-NEXT: 	insert.5.32b 	[[VR8_32_V8W15]], [[R32_W20]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W16:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W15]];
; O0-NEXT: 	insert.6.32b 	[[VR8_32_V8W16]], [[R32_W21]];
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W17:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W16]];
; O0-NEXT: 	insert.7.32b 	[[VR8_32_V8W17]], [[R32_W22]];
; O0-NEXT: 	st.private.v8.32b	 [[[R32_W1]]], [[VR8_32_V8W17]];
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W5:%[-a-zA-Z$._0-9]+]].x, [[R32_W23]];
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W6:%[-a-zA-Z$._0-9]+]].x, [[VR3_32_V3W5]].x;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W6]].y, [[VR3_32_V3W5]].y;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W6]].z, [[VR3_32_V3W5]].z;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W6]].y, [[R32_W24]];
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W7:%[-a-zA-Z$._0-9]+]].x, [[VR3_32_V3W6]].x;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W7]].y, [[VR3_32_V3W6]].y;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W7]].z, [[VR3_32_V3W6]].z;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W7]].z, [[R32_W25]];
; O0-NEXT: 	st.private.v3.32b	 [[[R32_W1]] + 32], [[VR3_32_V3W7]];
; O0-NEXT: 	return;
  %res = call <11 x ptr addrspace(3)> @test_call_pointer3_vector_odd(<11 x ptr addrspace(3)> %arg)
  ret <11 x ptr addrspace(3)> %res
}

define <6 x i8> @test_trunc_v6i64(<6 x i64> %arg0) {
; CHECK-LABEL: void @test_trunc_v6i64(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v2.8b [[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ld.private.v4.64b	 [[VR4_64_V4D0]], [[[R32_W0]]];
; CHECK-NEXT: 	ld.private.v2.64b	 [[VR2_64_V2D0]], [[[R32_W0]] + 32];
; CHECK-NEXT: 	trunc.8b.64b 	[[VR4_8_V4B0]].x, [[VR4_64_V4D0]].x;
; CHECK-NEXT: 	trunc.8b.64b 	[[VR4_8_V4B0]].y, [[VR4_64_V4D0]].y;
; CHECK-NEXT: 	trunc.8b.64b 	[[VR4_8_V4B0]].z, [[VR4_64_V4D0]].z;
; CHECK-NEXT: 	trunc.8b.64b 	[[VR4_8_V4B0]].w, [[VR4_64_V4D0]].w;
; CHECK-NEXT: 	trunc.8b.64b 	[[VR2_8_V2B0]].x, [[VR2_64_V2D0]].x;
; CHECK-NEXT: 	trunc.8b.64b 	[[VR2_8_V2B0]].y, [[VR2_64_V2D0]].y;
; CHECK-NEXT: 	st.private.v4.8b	 [[[R32_W1]]], [[VR4_8_V4B0]];
; CHECK-NEXT: 	st.private.v2.8b	 [[[R32_W1]] + 4], [[VR2_8_V2B0]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @test_trunc_v6i64(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b %d<0~10>;
; O0-NEXT: 	.reg .8b %b<0~6>;
; O0-NEXT: 	.reg .v2.8b %v2b<0~6>;
; O0-NEXT: 	.reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B1:%[-a-zA-Z$._0-9]+]];
; O0: 	ld.private.v4.64b	 [[VR4_64_V4D0]], [[[R32_W0]]];
; O0-NEXT: 	ld.private.v2.64b	 [[VR2_64_V2D0]], [[[R32_W0]] + 32];
; O0-NEXT: 	mov.64b 	[[R64_D0:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].x;
; O0-NEXT: 	mov.64b 	[[R64_D1:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].y;
; O0-NEXT: 	mov.64b 	[[R64_D2:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].z;
; O0-NEXT: 	mov.64b 	[[R64_D3:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].w;
; O0-NEXT: 	trunc.8b.64b 	[[R8_B0:%[-a-zA-Z$._0-9]+]], [[R64_D0]];
; O0-NEXT: 	trunc.8b.64b 	[[R8_B1:%[-a-zA-Z$._0-9]+]], [[R64_D1]];
; O0-NEXT: 	mov.8b 	[[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]].x, [[R8_B0]];
; O0-NEXT: 	mov.16b 	[[VR2_8_V2B1:%[-a-zA-Z$._0-9]+]].xy, [[VR2_8_V2B0]].xy;
; O0-NEXT: 	mov.8b 	[[VR2_8_V2B1]].y, [[R8_B1]];
; O0-NEXT: 	mov.64b 	[[R64_D4:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].x;
; O0-NEXT: 	mov.64b 	[[R64_D5:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].y;
; O0-NEXT: 	mov.64b 	[[R64_D6:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].z;
; O0-NEXT: 	mov.64b 	[[R64_D7:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D0]].w;
; O0-NEXT: 	trunc.8b.64b 	[[R8_B2:%[-a-zA-Z$._0-9]+]], [[R64_D6]];
; O0-NEXT: 	trunc.8b.64b 	[[R8_B3:%[-a-zA-Z$._0-9]+]], [[R64_D7]];
; O0-NEXT: 	mov.8b 	[[VR2_8_V2B2:%[-a-zA-Z$._0-9]+]].x, [[R8_B2]];
; O0-NEXT: 	mov.16b 	[[VR2_8_V2B3:%[-a-zA-Z$._0-9]+]].xy, [[VR2_8_V2B2]].xy;
; O0-NEXT: 	mov.8b 	[[VR2_8_V2B3]].y, [[R8_B3]];
; O0-NEXT: 	mov.64b 	[[R64_D8:%[-a-zA-Z$._0-9]+]], [[VR2_64_V2D0]].x;
; O0-NEXT: 	mov.64b 	[[R64_D9:%[-a-zA-Z$._0-9]+]], [[VR2_64_V2D0]].y;
; O0-NEXT: 	trunc.8b.64b 	[[R8_B4:%[-a-zA-Z$._0-9]+]], [[R64_D8]];
; O0-NEXT: 	trunc.8b.64b 	[[R8_B5:%[-a-zA-Z$._0-9]+]], [[R64_D9]];
; O0-NEXT: 	mov.8b 	[[VR2_8_V2B4:%[-a-zA-Z$._0-9]+]].x, [[R8_B4]];
; O0-NEXT: 	mov.16b 	[[VR2_8_V2B5:%[-a-zA-Z$._0-9]+]].xy, [[VR2_8_V2B4]].xy;
; O0-NEXT: 	mov.8b 	[[VR2_8_V2B5]].y, [[R8_B5]];
; O0-NEXT: 	mov.16b 	[[VR4_8_V4B0]].xy, [[VR2_8_V2B1]].xy;
; O0-NEXT: 	mov.32b 	[[VR4_8_V4B1]].xyzw, [[VR4_8_V4B0]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_8_V4B1]].zw, [[VR2_8_V2B3]].xy;
; O0-NEXT: 	st.private.v4.8b	 [[[R32_W1]]], [[VR4_8_V4B1]];
; O0-NEXT: 	st.private.v2.8b	 [[[R32_W1]] + 4], [[VR2_8_V2B5]];
; O0-NEXT: 	return;
  %trunc = trunc <6 x i64> %arg0 to <6 x i8>
  ret <6 x i8> %trunc
}

define void @test_complex(i1 %arg0, i8 %arg1, i16 %arg2, i32 %arg3, i64 %arg4, half %arg5, bfloat %arg6, float %arg7, double %arg8, <2 x i8> %arg9, <3 x i8> %arg10, <4 x i8> %arg11, <5 x i8> %arg12, <8 x i8> %arg13, <2 x i16> %arg14, <3 x i16> %arg15, <4 x i16> %arg16, <5 x i16> %arg17, <8 x i16> %arg18, <2 x i32> %arg19, <3 x i32> %arg20, <4 x i32> %arg21, <5 x i32> %arg22, <8 x i32> %arg23, <2 x i64> %arg24, <3 x i64> %arg25, <4 x i64> %arg26, <5 x i64> %arg27, <8 x i64> %arg28, <2 x half> %arg29, <3 x half> %arg30, <4 x half> %arg31, <5 x half> %arg32, <8 x half> %arg33, <2 x bfloat> %arg34, <3 x bfloat> %arg35, <4 x bfloat> %arg36, <5 x bfloat> %arg37, <8 x bfloat> %arg38, <2 x float> %arg39, <3 x float> %arg40, <4 x float> %arg41, <5 x float> %arg42, <8 x float> %arg43, <2 x double> %arg44, <3 x double> %arg45, <4 x double> %arg46, <5 x double> %arg47, <8 x double> %arg48) {
; CHECK-LABEL: void @test_complex(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H3:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.8b [[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v3.8b [[VR3_8_V3B0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W3:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v5.32b [[VR5_32_V5W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v3.64b [[VR3_64_V3D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W4:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v16.32b [[VR16_32_V16W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W5:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W2:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.16b [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v3.16b [[VR3_16_V3H2:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.16b [[VR4_16_V4H2:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W6:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W3:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v3.32b [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.32b [[VR4_32_V4W4:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v5.32b [[VR5_32_V5W1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v3.64b [[VR3_64_V3D1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v4.64b [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W7:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v16.32b [[VR16_32_V16W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b %h<4~10>;
; CHECK-NEXT: 	.reg .8b [[R8_B1:%[-a-zA-Z$._0-9]+]], [[R8_B2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .32b %w<8~14>;
; CHECK-NEXT: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]], [[R64_D3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.8b [[VR4_8_V4B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.16b [[VR4_16_V4H3:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H4:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H5:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.64b [[VR4_64_V4D2:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 4 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][4];
; CHECK-NEXT: 	.private .align 8 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][8];
; CHECK-NEXT: 	.private .align 16 [[PRIVATE_R2:@[-a-zA-Z$._0-9]+]][16];
; CHECK-NEXT: 	.private .align 64 [[PRIVATE_R3:@[-a-zA-Z$._0-9]+]][64];
; CHECK-NEXT: 	.private .align 16 [[PRIVATE_R4:@[-a-zA-Z$._0-9]+]][16];
; CHECK-NEXT: 	.private .align 16 [[PRIVATE_R5:@[-a-zA-Z$._0-9]+]][16];
; CHECK-NEXT: 	.private .align 64 [[PRIVATE_R6:@[-a-zA-Z$._0-9]+]][64];
; CHECK: 	ld.private.v4.8b	 [[VR4_8_V4B1]], [[[R32_W2]]];
; CHECK-NEXT: 	ld.private.8b	 [[R8_B1]], [[[R32_W2]] + 4];
; CHECK-NEXT: 	ld.private.v4.16b	 [[VR4_16_V4H3]], [[[R32_W3]]];
; CHECK-NEXT: 	ld.private.16b	 [[R16_H4:%[-a-zA-Z$._0-9]+]], [[[R32_W3]] + 8];
; CHECK-NEXT: 	ld.private.v4.64b	 [[VR4_64_V4D2]], [[[R32_W4]]];
; CHECK-NEXT: 	ld.private.64b	 [[R64_D2]], [[[R32_W4]] + 32];
; CHECK-NEXT: 	ld.private.v4.16b	 [[VR4_16_V4H4]], [[[R32_W5]]];
; CHECK-NEXT: 	ld.private.16b	 [[R16_H5:%[-a-zA-Z$._0-9]+]], [[[R32_W5]] + 8];
; CHECK-NEXT: 	ld.private.v4.16b	 [[VR4_16_V4H5]], [[[R32_W6]]];
; CHECK-NEXT: 	ld.private.16b	 [[R16_H6:%[-a-zA-Z$._0-9]+]], [[[R32_W6]] + 8];
; CHECK-NEXT: 	ld.private.v4.64b	 [[VR4_64_V4D3]], [[[R32_W7]]];
; CHECK-NEXT: 	ld.private.64b	 [[R64_D3]], [[[R32_W7]] + 32];
; CHECK-NEXT: 	and.16b 	[[R16_H7:%[-a-zA-Z$._0-9]+]], [[R16_H0]], 1;
; CHECK-NEXT: 	addrof.32b [[R32_W8:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R1]];
; CHECK-NEXT: 	st.private.v4.8b	 [[[PRIVATE_R1]]], [[VR4_8_V4B1]];
; CHECK-NEXT: 	st.private.8b	 [[[PRIVATE_R1]] + 4], [[R8_B1]];
; CHECK-NEXT: 	addrof.32b [[R32_W9:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R2]];
; CHECK-NEXT: 	st.private.v4.16b	 [[[PRIVATE_R2]]], [[VR4_16_V4H3]];
; CHECK-NEXT: 	st.private.16b	 [[[PRIVATE_R2]] + 8], [[R16_H4]];
; CHECK-NEXT: 	addrof.32b [[R32_W10:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R3]];
; CHECK-NEXT: 	st.private.v4.64b	 [[[PRIVATE_R3]]], [[VR4_64_V4D2]];
; CHECK-NEXT: 	st.private.64b	 [[[PRIVATE_R3]] + 32], [[R64_D2]];
; CHECK-NEXT: 	addrof.32b [[R32_W11:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R4]];
; CHECK-NEXT: 	st.private.v4.16b	 [[[PRIVATE_R4]]], [[VR4_16_V4H4]];
; CHECK-NEXT: 	st.private.16b	 [[[PRIVATE_R4]] + 8], [[R16_H5]];
; CHECK-NEXT: 	addrof.32b [[R32_W12:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R5]];
; CHECK-NEXT: 	st.private.v4.16b	 [[[PRIVATE_R5]]], [[VR4_16_V4H5]];
; CHECK-NEXT: 	st.private.16b	 [[[PRIVATE_R5]] + 8], [[R16_H6]];
; CHECK-NEXT: 	addrof.32b [[R32_W13:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R6]];
; CHECK-NEXT: 	st.private.v4.64b	 [[[PRIVATE_R6]]], [[VR4_64_V4D3]];
; CHECK-NEXT: 	st.private.64b	 [[[PRIVATE_R6]] + 32], [[R64_D3]];
; CHECK-NEXT: 	call [[R16_H8:%[-a-zA-Z$._0-9]+]], @test_call_complex ([[R16_H7]], [[R8_B0]], [[R16_H1]], [[R32_W0]], [[R64_D0]], [[R16_H2]], [[R16_H3]], [[R32_W1]], [[R64_D1]], [[VR2_8_V2B0]], [[VR3_8_V3B0]], [[VR4_8_V4B0]], [[R32_W8]], [[VR2_32_V2W0]], [[VR2_16_V2H0]], [[VR3_16_V3H0]], [[VR4_16_V4H0]], [[R32_W9]], [[VR4_32_V4W0]], [[VR2_32_V2W1]], [[VR3_32_V3W0]], [[VR4_32_V4W1]], [[VR5_32_V5W0]], [[VR8_32_V8W0]], [[VR2_64_V2D0]], [[VR3_64_V3D0]], [[VR4_64_V4D0]], [[R32_W10]], [[VR16_32_V16W0]], [[VR2_16_V2H1]], [[VR3_16_V3H1]], [[VR4_16_V4H1]], [[R32_W11]], [[VR4_32_V4W2]], [[VR2_16_V2H2]], [[VR3_16_V3H2]], [[VR4_16_V4H2]], [[R32_W12]], [[VR4_32_V4W3]], [[VR2_32_V2W2]], [[VR3_32_V3W1]], [[VR4_32_V4W4]], [[VR5_32_V5W1]], [[VR8_32_V8W1]], [[VR2_64_V2D1]], [[VR3_64_V3D1]], [[VR4_64_V4D1]], [[R32_W13]], [[VR16_32_V16W1]]);
; CHECK-NEXT: 	and.16b 	[[R16_H9:%[-a-zA-Z$._0-9]+]], [[R16_H8]], 1;
; CHECK-NEXT: 	trunc.8b.16b 	[[R8_B2]], [[R16_H9]];
; CHECK-NEXT: 	st.private.8b	 [[[PRIVATE_R0]]], [[R8_B2]];
; CHECK-NEXT: 	return;
;
; O0-LABEL: void @test_complex(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H3:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.8b [[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v3.8b [[VR3_8_V3B0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W3:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.32b [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v5.32b [[VR5_32_V5W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v3.64b [[VR3_64_V3D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W4:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v16.32b [[VR16_32_V16W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W5:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.32b [[VR4_32_V4W2:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.16b [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v3.16b [[VR3_16_V3H2:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.16b [[VR4_16_V4H2:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W6:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.32b [[VR4_32_V4W3:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.32b [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v3.32b [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.32b [[VR4_32_V4W4:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v5.32b [[VR5_32_V5W1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v3.64b [[VR3_64_V3D1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v4.64b [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W7:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v16.32b [[VR16_32_V16W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b %h<4~18>;
; O0-NEXT: 	.reg .8b [[R8_B1:%[-a-zA-Z$._0-9]+]], [[R8_B2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<8~42>;
; O0-NEXT: 	.reg .64b %d<2~24>;
; O0-NEXT: 	.reg .v4.8b [[VR4_8_V4B1:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B2:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v2.32b %v2w<3~37>;
; O0-NEXT: 	.reg .v2.16b %v2h<3~15>;
; O0-NEXT: 	.reg .v4.16b %v4h<3~14>;
; O0-NEXT: 	.reg .v4.32b %v4w<5~17>;
; O0-NEXT: 	.reg .v4.64b %v4d<2~8>;
; O0-NEXT: 	.reg .v16.32b %v16w<2~18>;
; O0-NEXT: 	.private .align 4 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][4];
; O0-NEXT: 	.private .align 8 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][8];
; O0-NEXT: 	.private .align 16 [[PRIVATE_R2:@[-a-zA-Z$._0-9]+]][16];
; O0-NEXT: 	.private .align 64 [[PRIVATE_R3:@[-a-zA-Z$._0-9]+]][64];
; O0-NEXT: 	.private .align 16 [[PRIVATE_R4:@[-a-zA-Z$._0-9]+]][16];
; O0-NEXT: 	.private .align 16 [[PRIVATE_R5:@[-a-zA-Z$._0-9]+]][16];
; O0-NEXT: 	.private .align 64 [[PRIVATE_R6:@[-a-zA-Z$._0-9]+]][64];
; O0: 	ld.private.v4.8b	 [[VR4_8_V4B1]], [[[R32_W2]]];
; O0-NEXT: 	ld.private.8b	 [[R8_B1]], [[[R32_W2]] + 4];
; O0-NEXT: 	mov.32b 	[[R32_W8:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W0]].x;
; O0-NEXT: 	mov.32b 	[[R32_W9:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W0]].y;
; O0-NEXT: 	mov.32b 	[[VR4_8_V4B2]].xyzw, [[R32_W8]];
; O0-NEXT: 	mov.32b 	[[VR4_8_V4B3]].xyzw, [[R32_W9]];
; O0-NEXT: 	ld.private.v4.16b	 [[VR4_16_V4H3:%[-a-zA-Z$._0-9]+]], [[[R32_W3]]];
; O0-NEXT: 	ld.private.16b	 [[R16_H4:%[-a-zA-Z$._0-9]+]], [[[R32_W3]] + 8];
; O0-NEXT: 	mov.32b 	[[R32_W10:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W0]].x;
; O0-NEXT: 	mov.32b 	[[R32_W11:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W0]].y;
; O0-NEXT: 	mov.32b 	[[R32_W12:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W0]].z;
; O0-NEXT: 	mov.32b 	[[R32_W13:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W0]].w;
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H3:%[-a-zA-Z$._0-9]+]].xy, [[R32_W10]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H4:%[-a-zA-Z$._0-9]+]].xy, [[R32_W11]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H5:%[-a-zA-Z$._0-9]+]].xy, [[R32_W12]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H6:%[-a-zA-Z$._0-9]+]].xy, [[R32_W13]];
; O0-NEXT: 	ld.private.v4.64b	 [[VR4_64_V4D2:%[-a-zA-Z$._0-9]+]], [[[R32_W4]]];
; O0-NEXT: 	ld.private.64b	 [[R64_D2:%[-a-zA-Z$._0-9]+]], [[[R32_W4]] + 32];
; O0-NEXT: 	extract.0.v2.32b 	[[VR2_32_V2W3:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W0]];
; O0-NEXT: 	extract.2.v2.32b 	[[VR2_32_V2W4:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W0]];
; O0-NEXT: 	extract.4.v2.32b 	[[VR2_32_V2W5:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W0]];
; O0-NEXT: 	extract.6.v2.32b 	[[VR2_32_V2W6:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W0]];
; O0-NEXT: 	extract.8.v2.32b 	[[VR2_32_V2W7:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W0]];
; O0-NEXT: 	extract.10.v2.32b 	[[VR2_32_V2W8:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W0]];
; O0-NEXT: 	extract.12.v2.32b 	[[VR2_32_V2W9:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W0]];
; O0-NEXT: 	extract.14.v2.32b 	[[VR2_32_V2W10:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W0]];
; O0-NEXT: 	mov.64b 	[[R64_D3:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W3]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D4:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W4]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D5:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W5]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D6:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W6]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D7:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W7]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D8:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W8]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D9:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W9]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D10:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W10]].xy;
; O0-NEXT: 	ld.private.v4.16b	 [[VR4_16_V4H4:%[-a-zA-Z$._0-9]+]], [[[R32_W5]]];
; O0-NEXT: 	ld.private.16b	 [[R16_H5:%[-a-zA-Z$._0-9]+]], [[[R32_W5]] + 8];
; O0-NEXT: 	mov.16b 	[[R16_H6:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H4]].x;
; O0-NEXT: 	mov.16b 	[[R16_H7:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H4]].y;
; O0-NEXT: 	mov.16b 	[[R16_H8:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H4]].z;
; O0-NEXT: 	mov.16b 	[[R16_H9:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H4]].w;
; O0-NEXT: 	mov.32b 	[[R32_W14:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W2]].x;
; O0-NEXT: 	mov.32b 	[[R32_W15:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W2]].y;
; O0-NEXT: 	mov.32b 	[[R32_W16:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W2]].z;
; O0-NEXT: 	mov.32b 	[[R32_W17:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W2]].w;
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H7:%[-a-zA-Z$._0-9]+]].xy, [[R32_W14]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H8:%[-a-zA-Z$._0-9]+]].xy, [[R32_W15]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H9:%[-a-zA-Z$._0-9]+]].xy, [[R32_W16]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H10:%[-a-zA-Z$._0-9]+]].xy, [[R32_W17]];
; O0-NEXT: 	ld.private.v4.16b	 [[VR4_16_V4H5:%[-a-zA-Z$._0-9]+]], [[[R32_W6]]];
; O0-NEXT: 	ld.private.16b	 [[R16_H10:%[-a-zA-Z$._0-9]+]], [[[R32_W6]] + 8];
; O0-NEXT: 	mov.16b 	[[R16_H11:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H5]].x;
; O0-NEXT: 	mov.16b 	[[R16_H12:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H5]].y;
; O0-NEXT: 	mov.16b 	[[R16_H13:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H5]].z;
; O0-NEXT: 	mov.16b 	[[R16_H14:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H5]].w;
; O0-NEXT: 	mov.32b 	[[R32_W18:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W3]].x;
; O0-NEXT: 	mov.32b 	[[R32_W19:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W3]].y;
; O0-NEXT: 	mov.32b 	[[R32_W20:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W3]].z;
; O0-NEXT: 	mov.32b 	[[R32_W21:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W3]].w;
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H11:%[-a-zA-Z$._0-9]+]].xy, [[R32_W18]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H12:%[-a-zA-Z$._0-9]+]].xy, [[R32_W19]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H13:%[-a-zA-Z$._0-9]+]].xy, [[R32_W20]];
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H14:%[-a-zA-Z$._0-9]+]].xy, [[R32_W21]];
; O0-NEXT: 	ld.private.v4.64b	 [[VR4_64_V4D3:%[-a-zA-Z$._0-9]+]], [[[R32_W7]]];
; O0-NEXT: 	ld.private.64b	 [[R64_D11:%[-a-zA-Z$._0-9]+]], [[[R32_W7]] + 32];
; O0-NEXT: 	mov.64b 	[[R64_D12:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D3]].x;
; O0-NEXT: 	mov.64b 	[[R64_D13:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D3]].y;
; O0-NEXT: 	mov.64b 	[[R64_D14:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D3]].z;
; O0-NEXT: 	mov.64b 	[[R64_D15:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D3]].w;
; O0-NEXT: 	extract.0.v2.32b 	[[VR2_32_V2W11:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W1]];
; O0-NEXT: 	extract.2.v2.32b 	[[VR2_32_V2W12:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W1]];
; O0-NEXT: 	extract.4.v2.32b 	[[VR2_32_V2W13:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W1]];
; O0-NEXT: 	extract.6.v2.32b 	[[VR2_32_V2W14:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W1]];
; O0-NEXT: 	extract.8.v2.32b 	[[VR2_32_V2W15:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W1]];
; O0-NEXT: 	extract.10.v2.32b 	[[VR2_32_V2W16:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W1]];
; O0-NEXT: 	extract.12.v2.32b 	[[VR2_32_V2W17:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W1]];
; O0-NEXT: 	extract.14.v2.32b 	[[VR2_32_V2W18:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W1]];
; O0-NEXT: 	mov.64b 	[[R64_D16:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W11]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D17:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W12]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D18:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W13]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D19:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W14]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D20:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W15]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D21:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W16]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D22:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W17]].xy;
; O0-NEXT: 	mov.64b 	[[R64_D23:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W18]].xy;
; O0-NEXT: 	and.16b 	[[R16_H15:%[-a-zA-Z$._0-9]+]], [[R16_H0]], 1;
; O0-NEXT: 	addrof.32b [[R32_W22:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R1]];
; O0-NEXT: 	st.private.v4.8b	 [[[PRIVATE_R1]]], [[VR4_8_V4B1]];
; O0-NEXT: 	st.private.8b	 [[[PRIVATE_R1]] + 4], [[R8_B1]];
; O0-NEXT: 	mov.32b 	[[R32_W23:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B2]].xyzw;
; O0-NEXT: 	mov.32b 	[[R32_W24:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B3]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W19:%[-a-zA-Z$._0-9]+]].x, [[R32_W23]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W20:%[-a-zA-Z$._0-9]+]].xy, [[VR2_32_V2W19]].xy;
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W20]].y, [[R32_W24]];
; O0-NEXT: 	addrof.32b [[R32_W25:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R2]];
; O0-NEXT: 	st.private.v4.16b	 [[[PRIVATE_R2]]], [[VR4_16_V4H3]];
; O0-NEXT: 	st.private.16b	 [[[PRIVATE_R2]] + 8], [[R16_H4]];
; O0-NEXT: 	mov.32b 	[[R32_W26:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H3]].xy;
; O0-NEXT: 	mov.32b 	[[R32_W27:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H4]].xy;
; O0-NEXT: 	mov.32b 	[[R32_W28:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H5]].xy;
; O0-NEXT: 	mov.32b 	[[R32_W29:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H6]].xy;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W5:%[-a-zA-Z$._0-9]+]].x, [[R32_W26]];
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W6:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_32_V4W5]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W6]].y, [[R32_W27]];
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W7:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_32_V4W6]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W7]].z, [[R32_W28]];
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W8:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_32_V4W7]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W8]].w, [[R32_W29]];
; O0-NEXT: 	addrof.32b [[R32_W30:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R3]];
; O0-NEXT: 	st.private.v4.64b	 [[[PRIVATE_R3]]], [[VR4_64_V4D2]];
; O0-NEXT: 	st.private.64b	 [[[PRIVATE_R3]] + 32], [[R64_D2]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W21:%[-a-zA-Z$._0-9]+]].xy, [[R64_D3]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W22:%[-a-zA-Z$._0-9]+]].xy, [[R64_D4]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W23:%[-a-zA-Z$._0-9]+]].xy, [[R64_D5]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W24:%[-a-zA-Z$._0-9]+]].xy, [[R64_D6]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W25:%[-a-zA-Z$._0-9]+]].xy, [[R64_D7]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W26:%[-a-zA-Z$._0-9]+]].xy, [[R64_D8]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W27:%[-a-zA-Z$._0-9]+]].xy, [[R64_D9]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W28:%[-a-zA-Z$._0-9]+]].xy, [[R64_D10]];
; O0-NEXT: 	insert.0.v2.32b 	[[VR16_32_V16W2:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W21]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W3:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W2]];
; O0-NEXT: 	insert.2.v2.32b 	[[VR16_32_V16W3]], [[VR2_32_V2W22]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W4:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W3]];
; O0-NEXT: 	insert.4.v2.32b 	[[VR16_32_V16W4]], [[VR2_32_V2W23]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W5:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W4]];
; O0-NEXT: 	insert.6.v2.32b 	[[VR16_32_V16W5]], [[VR2_32_V2W24]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W6:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W5]];
; O0-NEXT: 	insert.8.v2.32b 	[[VR16_32_V16W6]], [[VR2_32_V2W25]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W7:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W6]];
; O0-NEXT: 	insert.10.v2.32b 	[[VR16_32_V16W7]], [[VR2_32_V2W26]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W8:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W7]];
; O0-NEXT: 	insert.12.v2.32b 	[[VR16_32_V16W8]], [[VR2_32_V2W27]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W9:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W8]];
; O0-NEXT: 	insert.14.v2.32b 	[[VR16_32_V16W9]], [[VR2_32_V2W28]];
; O0-NEXT: 	addrof.32b [[R32_W31:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R4]];
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H6:%[-a-zA-Z$._0-9]+]].x, [[R16_H6]];
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H7:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_16_V4H6]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H7]].y, [[R16_H7]];
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H8:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_16_V4H7]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H8]].z, [[R16_H8]];
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H9:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_16_V4H8]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H9]].w, [[R16_H9]];
; O0-NEXT: 	st.private.v4.16b	 [[[PRIVATE_R4]]], [[VR4_16_V4H9]];
; O0-NEXT: 	st.private.16b	 [[[PRIVATE_R4]] + 8], [[R16_H5]];
; O0-NEXT: 	mov.32b 	[[R32_W32:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H7]].xy;
; O0-NEXT: 	mov.32b 	[[R32_W33:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H8]].xy;
; O0-NEXT: 	mov.32b 	[[R32_W34:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H9]].xy;
; O0-NEXT: 	mov.32b 	[[R32_W35:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H10]].xy;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W9:%[-a-zA-Z$._0-9]+]].x, [[R32_W32]];
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W10:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_32_V4W9]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W10]].y, [[R32_W33]];
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W11:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_32_V4W10]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W11]].z, [[R32_W34]];
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W12:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_32_V4W11]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W12]].w, [[R32_W35]];
; O0-NEXT: 	addrof.32b [[R32_W36:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R5]];
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H10:%[-a-zA-Z$._0-9]+]].x, [[R16_H11]];
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H11:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_16_V4H10]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H11]].y, [[R16_H12]];
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H12:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_16_V4H11]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H12]].z, [[R16_H13]];
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H13:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_16_V4H12]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H13]].w, [[R16_H14]];
; O0-NEXT: 	st.private.v4.16b	 [[[PRIVATE_R5]]], [[VR4_16_V4H13]];
; O0-NEXT: 	st.private.16b	 [[[PRIVATE_R5]] + 8], [[R16_H10]];
; O0-NEXT: 	mov.32b 	[[R32_W37:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H11]].xy;
; O0-NEXT: 	mov.32b 	[[R32_W38:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H12]].xy;
; O0-NEXT: 	mov.32b 	[[R32_W39:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H13]].xy;
; O0-NEXT: 	mov.32b 	[[R32_W40:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H14]].xy;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W13:%[-a-zA-Z$._0-9]+]].x, [[R32_W37]];
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W14:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_32_V4W13]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W14]].y, [[R32_W38]];
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W15:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_32_V4W14]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W15]].z, [[R32_W39]];
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W16:%[-a-zA-Z$._0-9]+]].xyzw, [[VR4_32_V4W15]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W16]].w, [[R32_W40]];
; O0-NEXT: 	addrof.32b [[R32_W41:%[-a-zA-Z$._0-9]+]], [[PRIVATE_R6]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4:%[-a-zA-Z$._0-9]+]].x, [[R64_D12]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D5:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D4]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D5]].y, [[VR4_64_V4D4]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D5]].z, [[VR4_64_V4D4]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D5]].w, [[VR4_64_V4D4]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D5]].y, [[R64_D13]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D6:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D5]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D6]].y, [[VR4_64_V4D5]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D6]].z, [[VR4_64_V4D5]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D6]].w, [[VR4_64_V4D5]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D6]].z, [[R64_D14]];
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D7:%[-a-zA-Z$._0-9]+]].x, [[VR4_64_V4D6]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D7]].y, [[VR4_64_V4D6]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D7]].z, [[VR4_64_V4D6]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D7]].w, [[VR4_64_V4D6]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D7]].w, [[R64_D15]];
; O0-NEXT: 	st.private.v4.64b	 [[[PRIVATE_R6]]], [[VR4_64_V4D7]];
; O0-NEXT: 	st.private.64b	 [[[PRIVATE_R6]] + 32], [[R64_D11]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W29:%[-a-zA-Z$._0-9]+]].xy, [[R64_D16]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W30:%[-a-zA-Z$._0-9]+]].xy, [[R64_D17]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W31:%[-a-zA-Z$._0-9]+]].xy, [[R64_D18]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W32:%[-a-zA-Z$._0-9]+]].xy, [[R64_D19]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W33:%[-a-zA-Z$._0-9]+]].xy, [[R64_D20]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W34:%[-a-zA-Z$._0-9]+]].xy, [[R64_D21]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W35:%[-a-zA-Z$._0-9]+]].xy, [[R64_D22]];
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W36:%[-a-zA-Z$._0-9]+]].xy, [[R64_D23]];
; O0-NEXT: 	insert.0.v2.32b 	[[VR16_32_V16W10:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W29]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W11:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W10]];
; O0-NEXT: 	insert.2.v2.32b 	[[VR16_32_V16W11]], [[VR2_32_V2W30]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W12:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W11]];
; O0-NEXT: 	insert.4.v2.32b 	[[VR16_32_V16W12]], [[VR2_32_V2W31]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W13:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W12]];
; O0-NEXT: 	insert.6.v2.32b 	[[VR16_32_V16W13]], [[VR2_32_V2W32]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W14:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W13]];
; O0-NEXT: 	insert.8.v2.32b 	[[VR16_32_V16W14]], [[VR2_32_V2W33]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W15:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W14]];
; O0-NEXT: 	insert.10.v2.32b 	[[VR16_32_V16W15]], [[VR2_32_V2W34]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W16:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W15]];
; O0-NEXT: 	insert.12.v2.32b 	[[VR16_32_V16W16]], [[VR2_32_V2W35]];
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W17:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W16]];
; O0-NEXT: 	insert.14.v2.32b 	[[VR16_32_V16W17]], [[VR2_32_V2W36]];
; O0-NEXT: 	call [[R16_H16:%[-a-zA-Z$._0-9]+]], @test_call_complex ([[R16_H15]], [[R8_B0]], [[R16_H1]], [[R32_W0]], [[R64_D0]], [[R16_H2]], [[R16_H3]], [[R32_W1]], [[R64_D1]], [[VR2_8_V2B0]], [[VR3_8_V3B0]], [[VR4_8_V4B0]], [[R32_W22]], [[VR2_32_V2W20]], [[VR2_16_V2H0]], [[VR3_16_V3H0]], [[VR4_16_V4H0]], [[R32_W25]], [[VR4_32_V4W8]], [[VR2_32_V2W1]], [[VR3_32_V3W0]], [[VR4_32_V4W1]], [[VR5_32_V5W0]], [[VR8_32_V8W0]], [[VR2_64_V2D0]], [[VR3_64_V3D0]], [[VR4_64_V4D0]], [[R32_W30]], [[VR16_32_V16W9]], [[VR2_16_V2H1]], [[VR3_16_V3H1]], [[VR4_16_V4H1]], [[R32_W31]], [[VR4_32_V4W12]], [[VR2_16_V2H2]], [[VR3_16_V3H2]], [[VR4_16_V4H2]], [[R32_W36]], [[VR4_32_V4W16]], [[VR2_32_V2W2]], [[VR3_32_V3W1]], [[VR4_32_V4W4]], [[VR5_32_V5W1]], [[VR8_32_V8W1]], [[VR2_64_V2D1]], [[VR3_64_V3D1]], [[VR4_64_V4D1]], [[R32_W41]], [[VR16_32_V16W17]]);
; O0-NEXT: 	and.16b 	[[R16_H17:%[-a-zA-Z$._0-9]+]], [[R16_H16]], 1;
; O0-NEXT: 	trunc.8b.16b 	[[R8_B2]], [[R16_H17]];
; O0-NEXT: 	st.private.8b	 [[[PRIVATE_R0]]], [[R8_B2]];
; O0-NEXT: 	return;
  %alloca = alloca i32, align 4, addrspace(4)
  %call = call i1 @test_call_complex(i1 %arg0, i8 %arg1, i16 %arg2, i32 %arg3, i64 %arg4, half %arg5, bfloat %arg6, float %arg7, double %arg8, <2 x i8> %arg9, <3 x i8> %arg10, <4 x i8> %arg11, <5 x i8> %arg12, <8 x i8> %arg13, <2 x i16> %arg14, <3 x i16> %arg15, <4 x i16> %arg16, <5 x i16> %arg17, <8 x i16> %arg18, <2 x i32> %arg19, <3 x i32> %arg20, <4 x i32> %arg21, <5 x i32> %arg22, <8 x i32> %arg23, <2 x i64> %arg24, <3 x i64> %arg25, <4 x i64> %arg26, <5 x i64> %arg27, <8 x i64> %arg28, <2 x half> %arg29, <3 x half> %arg30, <4 x half> %arg31, <5 x half> %arg32, <8 x half> %arg33, <2 x bfloat> %arg34, <3 x bfloat> %arg35, <4 x bfloat> %arg36, <5 x bfloat> %arg37, <8 x bfloat> %arg38, <2 x float> %arg39, <3 x float> %arg40, <4 x float> %arg41, <5 x float> %arg42, <8 x float> %arg43, <2 x double> %arg44, <3 x double> %arg45, <4 x double> %arg46, <5 x double> %arg47, <8 x double> %arg48)
  store i1 %call, ptr addrspace(4) %alloca, align 1
  ret void
}
