; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -print-after=pisa-legalize-calls 2>&1 | FileCheck %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs

define <5 x i16> @test(<5 x i16> returned %1) {
; CHECK-LABEL: .export .function void @test(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.16b [[VR4_16_R2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .16b [[R16_R3:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ld.private.v4.16b	 [[VR4_16_R2]], [[[R32_R0]]];
; CHECK-NEXT: 	ld.private.16b	 [[R16_R3]], [[[R32_R0]] + 8];
; CHECK-NEXT: 	st.private.v4.16b	 [[[R32_R1]]], [[VR4_16_R2]];
; CHECK-NEXT: 	st.private.16b	 [[[R32_R1]] + 8], [[R16_R3]];
; CHECK-NEXT: 	return;
BB:
  ret <5 x i16> %1
}
