; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

declare i16 @llvm.usub.sat.i16(i16, i16)
declare i32 @llvm.usub.sat.i32(i32, i32)
declare i64 @llvm.usub.sat.i64(i64, i64)
declare <2 x i16> @llvm.usub.sat.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i32> @llvm.usub.sat.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.usub.sat.v2i64(<2 x i64>, <2 x i64>)

define i16 @test_usubsat16(i16 %a, i16 %b) {
; O0-LABEL: .16b @test_usubsat16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; O0: 	umin.16b 	[[R16_H2]], [[R16_H0]], [[R16_H1]];
; O0-NEXT: 	isub.16b 	[[R16_H3]], [[R16_H0]], [[R16_H2]];
; O0-NEXT: 	return [[R16_H3]];
;
; CHECK-LABEL: .16b @test_usubsat16(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; CHECK: 	umin.16b 	[[R16_H2]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	isub.16b 	[[R16_H3]], [[R16_H0]], [[R16_H2]];
; CHECK-NEXT: 	return [[R16_H3]];
  %result = call i16 @llvm.usub.sat.i16(i16 %a, i16 %b)
  ret i16 %result
}

define i32 @test_usubsat32(i32 %a, i32 %b) {
; O0-LABEL: .32b @test_usubsat32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; O0: 	umin.32b 	[[R32_W2]], [[R32_W0]], [[R32_W1]];
; O0-NEXT: 	isub.32b 	[[R32_W3]], [[R32_W0]], [[R32_W2]];
; O0-NEXT: 	return [[R32_W3]];
;
; CHECK-LABEL: .32b @test_usubsat32(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; CHECK: 	umin.32b 	[[R32_W2]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	isub.32b 	[[R32_W3]], [[R32_W0]], [[R32_W2]];
; CHECK-NEXT: 	return [[R32_W3]];
  %result = call i32 @llvm.usub.sat.i32(i32 %a, i32 %b)
  ret i32 %result
}

define i64 @test_usubsat64(i64 %a, i64 %b) {
; O0-LABEL: .64b @test_usubsat64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]], [[R64_D3:%[-a-zA-Z$._0-9]+]];
; O0: 	umin.64b 	[[R64_D2]], [[R64_D0]], [[R64_D1]];
; O0-NEXT: 	isub.64b 	[[R64_D3]], [[R64_D0]], [[R64_D2]];
; O0-NEXT: 	return [[R64_D3]];
;
; CHECK-LABEL: .64b @test_usubsat64(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]], [[R64_D3:%[-a-zA-Z$._0-9]+]];
; CHECK: 	umin.64b 	[[R64_D2]], [[R64_D0]], [[R64_D1]];
; CHECK-NEXT: 	isub.64b 	[[R64_D3]], [[R64_D0]], [[R64_D2]];
; CHECK-NEXT: 	return [[R64_D3]];
  %result = call i64 @llvm.usub.sat.i64(i64 %a, i64 %b)
  ret i64 %result
}

define <2 x i16> @test_usubsatv2i16(<2 x i16> %a, <2 x i16> %b) {
; O0-LABEL: .v2.16b @test_usubsatv2i16(
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.16b [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~8>;
; O0: 	mov.16b 	%h0, [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	%h1, [[VR2_16_V2H0]].y;
; O0-NEXT: 	mov.16b 	%h2, [[VR2_16_V2H1]].x;
; O0-NEXT: 	mov.16b 	%h3, [[VR2_16_V2H1]].y;
; O0-NEXT: 	umin.16b 	%h4, %h0, %h2;
; O0-NEXT: 	isub.16b 	%h5, %h0, %h4;
; O0-NEXT: 	umin.16b 	%h6, %h1, %h3;
; O0-NEXT: 	isub.16b 	%h7, %h1, %h6;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H2]].x, %h5;
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H3]].xy, [[VR2_16_V2H2]].xy;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H3]].y, %h7;
; O0-NEXT: 	return [[VR2_16_V2H3]];
;
; CHECK-LABEL: .v2.16b @test_usubsatv2i16(
; CHECK-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.16b [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	umin.16b 	[[R16_H0]], [[VR2_16_V2H0]].x, [[VR2_16_V2H1]].x;
; CHECK-NEXT: 	isub.16b 	[[VR2_16_V2H2]].x, [[VR2_16_V2H0]].x, [[R16_H0]];
; CHECK-NEXT: 	umin.16b 	[[R16_H1]], [[VR2_16_V2H0]].y, [[VR2_16_V2H1]].y;
; CHECK-NEXT: 	isub.16b 	[[VR2_16_V2H2]].y, [[VR2_16_V2H0]].y, [[R16_H1]];
; CHECK-NEXT: 	return [[VR2_16_V2H2]];
  %result = call <2 x i16> @llvm.usub.sat.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %result
}

define <2 x i32> @test_usubsatv2i32(<2 x i32> %a, <2 x i32> %b) {
; O0-LABEL: .v2.32b @test_usubsatv2i32(
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.32b [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~8>;
; O0: 	mov.32b 	%w0, [[VR2_32_V2W0]].x;
; O0-NEXT: 	mov.32b 	%w1, [[VR2_32_V2W0]].y;
; O0-NEXT: 	mov.32b 	%w2, [[VR2_32_V2W1]].x;
; O0-NEXT: 	mov.32b 	%w3, [[VR2_32_V2W1]].y;
; O0-NEXT: 	umin.32b 	%w4, %w0, %w2;
; O0-NEXT: 	isub.32b 	%w5, %w0, %w4;
; O0-NEXT: 	umin.32b 	%w6, %w1, %w3;
; O0-NEXT: 	isub.32b 	%w7, %w1, %w6;
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W2]].x, %w5;
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W3]].xy, [[VR2_32_V2W2]].xy;
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W3]].y, %w7;
; O0-NEXT: 	return [[VR2_32_V2W3]];
;
; CHECK-LABEL: .v2.32b @test_usubsatv2i32(
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.32b [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]], [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	umin.32b 	[[R32_W0]], [[VR2_32_V2W0]].x, [[VR2_32_V2W1]].x;
; CHECK-NEXT: 	isub.32b 	[[VR2_32_V2W2]].x, [[VR2_32_V2W0]].x, [[R32_W0]];
; CHECK-NEXT: 	umin.32b 	[[R32_W1]], [[VR2_32_V2W0]].y, [[VR2_32_V2W1]].y;
; CHECK-NEXT: 	isub.32b 	[[VR2_32_V2W2]].y, [[VR2_32_V2W0]].y, [[R32_W1]];
; CHECK-NEXT: 	return [[VR2_32_V2W2]];
  %result = call <2 x i32> @llvm.usub.sat.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %result
}

define <2 x i64> @test_usubsatv2i64(<2 x i64> %a, <2 x i64> %b) {
; O0-LABEL: .v2.64b @test_usubsatv2i64(
; O0-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.64b [[VR2_64_V2D2:%[-a-zA-Z$._0-9]+]], [[VR2_64_V2D3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b %d<0~8>;
; O0: 	mov.64b 	%d0, [[VR2_64_V2D0]].x;
; O0-NEXT: 	mov.64b 	%d1, [[VR2_64_V2D0]].y;
; O0-NEXT: 	mov.64b 	%d2, [[VR2_64_V2D1]].x;
; O0-NEXT: 	mov.64b 	%d3, [[VR2_64_V2D1]].y;
; O0-NEXT: 	umin.64b 	%d4, %d0, %d2;
; O0-NEXT: 	isub.64b 	%d5, %d0, %d4;
; O0-NEXT: 	umin.64b 	%d6, %d1, %d3;
; O0-NEXT: 	isub.64b 	%d7, %d1, %d6;
; O0-NEXT: 	mov.64b 	[[VR2_64_V2D2]].x, %d5;
; O0-NEXT: 	mov.128b 	[[VR2_64_V2D3]].xy, [[VR2_64_V2D2]].xy;
; O0-NEXT: 	mov.64b 	[[VR2_64_V2D3]].y, %d7;
; O0-NEXT: 	return [[VR2_64_V2D3]];
;
; CHECK-LABEL: .v2.64b @test_usubsatv2i64(
; CHECK-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.64b [[VR2_64_V2D2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]], [[R64_D1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	umin.64b 	[[R64_D0]], [[VR2_64_V2D0]].x, [[VR2_64_V2D1]].x;
; CHECK-NEXT: 	isub.64b 	[[VR2_64_V2D2]].x, [[VR2_64_V2D0]].x, [[R64_D0]];
; CHECK-NEXT: 	umin.64b 	[[R64_D1]], [[VR2_64_V2D0]].y, [[VR2_64_V2D1]].y;
; CHECK-NEXT: 	isub.64b 	[[VR2_64_V2D2]].y, [[VR2_64_V2D0]].y, [[R64_D1]];
; CHECK-NEXT: 	return [[VR2_64_V2D2]];
  %result = call <2 x i64> @llvm.usub.sat.v2i64(<2 x i64> %a, <2 x i64> %b)
  ret <2 x i64> %result
}

