; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

define i8 @i8_private(ptr addrspace(4) noundef %0) {
; O0-LABEL: .8b @i8_private(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]];
; O0: 	ld.private.8b	 [[R8_B0]], [[[R32_W0]]];
; O0-NEXT: 	return [[R8_B0]];
;
; CHECK-LABEL: .8b @i8_private(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ld.private.8b	 [[R8_B0]], [[[R32_W0]]];
; CHECK-NEXT: 	return [[R8_B0]];
  %2 = load i8, ptr addrspace(4) %0, align 1
  ret i8 %2
}

define i8 @i8_global(ptr addrspace(1) noundef %0) {
; O0-LABEL: .8b @i8_global(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]];
; O0: 	ld.global.8b	 [[R8_B0]], [[[R64_D0]]];
; O0-NEXT: 	return [[R8_B0]];
;
; CHECK-LABEL: .8b @i8_global(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ld.global.8b	 [[R8_B0]], [[[R64_D0]]];
; CHECK-NEXT: 	return [[R8_B0]];
  %2 = load i8, ptr addrspace(1) %0, align 1
  ret i8 %2
}

define i8 @i8_const(ptr addrspace(2) noundef %0) {
; O0-LABEL: .8b @i8_const(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]];
; O0: 	ld.const.8b	 [[R8_B0]], [[[R64_D0]]];
; O0-NEXT: 	return [[R8_B0]];
;
; CHECK-LABEL: .8b @i8_const(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ld.const.8b	 [[R8_B0]], [[[R64_D0]]];
; CHECK-NEXT: 	return [[R8_B0]];
  %2 = load i8, ptr addrspace(2) %0, align 1
  ret i8 %2
}

define i8 @i8_shared(ptr addrspace(3) noundef %0) {
; O0-LABEL: .8b @i8_shared(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]];
; O0: 	ld.shared.8b	 [[R8_B0]], [[[R32_W0]]];
; O0-NEXT: 	return [[R8_B0]];
;
; CHECK-LABEL: .8b @i8_shared(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ld.shared.8b	 [[R8_B0]], [[[R32_W0]]];
; CHECK-NEXT: 	return [[R8_B0]];
  %2 = load i8, ptr addrspace(3) %0, align 1
  ret i8 %2
}

define i8 @i8_generic(ptr noundef %0) {
; O0-LABEL: .8b @i8_generic(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]];
; O0: 	ld.generic.8b	 [[R8_B0]], [[[R64_D0]]];
; O0-NEXT: 	return [[R8_B0]];
;
; CHECK-LABEL: .8b @i8_generic(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ld.generic.8b	 [[R8_B0]], [[[R64_D0]]];
; CHECK-NEXT: 	return [[R8_B0]];
  %2 = load i8, ptr %0, align 1
  ret i8 %2
}
