; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -stop-after=register-coalescer | FileCheck %s --check-prefixes=CHECK-MIR
; RUN: llc < %s -march=pisa | FileCheck %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

declare i32 @check_char(i8)
declare i32 @check_char2(<2 x i8>)
declare i32 @check_char4(<4 x i8>)
declare i32 @check_short(i16)
declare i32 @check_short2(<2 x i16>)
declare i32 @check_short3(<3 x i16>)
declare i32 @check_short4(<4 x i16>)
declare i32 @check_int(i32)
declare i32 @check_int2(<2 x i32>)
declare i32 @check_int3(<3 x i32>)
declare i32 @check_int4(<4 x i32>)
declare i32 @check_long(i64)
declare i32 @check_long2(<2 x i64>)
declare i32 @check_long3(<3 x i64>)
declare i32 @check_long4(<4 x i64>)

; CHECK-MIR-LABEL: {{^}}name: foo_char
; CHECK-LABEL: @foo_char
define  i8 @foo_char(i8 %i) {
; O0-LABEL: .8b @foo_char(
; O0-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .8b [[R8_B1:%[-a-zA-Z$._0-9]+]], [[R8_B2:%[-a-zA-Z$._0-9]+]], [[R8_B3:%[-a-zA-Z$._0-9]+]], [[R8_B4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.8b 	[[R8_B1]], 0;
; O0-NEXT: 	mov.8b 	[[R8_B2]], [[R8_B1]];
; O0-NEXT: 	goto [[LBB0_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB0_2]]:
; O0: 	mov.8b 	[[R8_B3]], [[R8_B2]];
; O0-NEXT: 	call [[R32_W0]], @check_char ([[R8_B3]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], [[R32_W0]], 11;
; O0-NEXT: 	zext.16b.8b 	[[R16_H0]], [[R8_B3]];
; O0-NEXT: 	zext.16b.8b 	[[R16_H1]], [[R8_B0]];
; O0-NEXT: 	iadd.16b 	[[R16_H2]], [[R16_H0]], [[R16_H1]];
; O0-NEXT: 	trunc.8b.16b 	[[R8_B4]], [[R16_H2]];
; O0-NEXT: 	mov.8b 	[[R8_B2]], [[R8_B4]];
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB0_2]];
; O0-NEXT: 	goto [[LBB0_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB0_3]]:
; O0-NEXT: 	return [[R8_B3]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi i8 [ 0, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:reg8b = COPY %{{[0-9]+}}
; CHECK:     mov.8b %b{{[0-9]+}}, %b{{[0-9]+}}
  %call = tail call i32 @check_char(i8 %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add i8 %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret i8 %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_char2
; CHECK-LABEL: @foo_char2
define <2 x i8> @foo_char2(<2 x i8> %i) {
; O0-LABEL: .v2.8b @foo_char2(
; O0-SAME: .reg .v2.8b [[VR2_8_V2B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.8b [[VR2_8_V2B1:%[-a-zA-Z$._0-9]+]], [[VR2_8_V2B2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .8b %b<0~9>;
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~6>;
; O0: 	mov.8b 	%b0, 0;
; O0-NEXT: 	mov.8b 	%b1, %b0;
; O0-NEXT: 	mov.8b 	%b2, %b0;
; O0-NEXT: 	goto [[LBB1_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB1_2]]:
; O0: 	mov.8b 	%b3, %b2;
; O0-NEXT: 	mov.8b 	%b4, %b1;
; O0-NEXT: 	mov.8b 	[[VR2_8_V2B1]].x, %b4;
; O0-NEXT: 	mov.16b 	[[VR2_8_V2B2]].xy, [[VR2_8_V2B1]].xy;
; O0-NEXT: 	mov.8b 	[[VR2_8_V2B2]].y, %b3;
; O0-NEXT: 	call [[R32_W0]], @check_char2 ([[VR2_8_V2B2]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], [[R32_W0]], 11;
; O0-NEXT: 	mov.8b 	%b5, [[VR2_8_V2B0]].x;
; O0-NEXT: 	mov.8b 	%b6, [[VR2_8_V2B0]].y;
; O0-NEXT: 	zext.16b.8b 	%h0, %b4;
; O0-NEXT: 	zext.16b.8b 	%h1, %b5;
; O0-NEXT: 	iadd.16b 	%h2, %h0, %h1;
; O0-NEXT: 	trunc.8b.16b 	%b7, %h2;
; O0-NEXT: 	zext.16b.8b 	%h3, %b3;
; O0-NEXT: 	zext.16b.8b 	%h4, %b6;
; O0-NEXT: 	iadd.16b 	%h5, %h3, %h4;
; O0-NEXT: 	trunc.8b.16b 	%b8, %h5;
; O0-NEXT: 	mov.8b 	%b1, %b7;
; O0-NEXT: 	mov.8b 	%b2, %b8;
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB1_2]];
; O0-NEXT: 	goto [[LBB1_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB1_3]]:
; O0-NEXT: 	return [[VR2_8_V2B2]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi <2 x i8> [ zeroinitializer, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:regv2_8b{{[a-z_0-9]*}} = COPY %{{[0-9]+}}
; CHECK:     mov.16b %v2b{{[0-9]+}}.xy, %v2b{{[0-9]+}}.xy
  %call = tail call i32 @check_char2(<2 x i8> %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add <2 x i8> %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret <2 x i8> %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_char4
; CHECK-LABEL: @foo_char4
define <4 x i8> @foo_char4(<4 x i8> %i) {
; O0-LABEL: .v4.8b @foo_char4(
; O0-SAME: .reg .v4.8b [[VR4_8_V4B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.8b [[VR4_8_V4B1:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B2:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B3:%[-a-zA-Z$._0-9]+]], [[VR4_8_V4B4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .8b %b<0~17>;
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~12>;
; O0: 	mov.8b 	%b0, 0;
; O0-NEXT: 	mov.8b 	%b1, %b0;
; O0-NEXT: 	mov.8b 	%b2, %b0;
; O0-NEXT: 	mov.8b 	%b3, %b0;
; O0-NEXT: 	mov.8b 	%b4, %b0;
; O0-NEXT: 	goto [[LBB2_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB2_2]]:
; O0: 	mov.8b 	%b5, %b4;
; O0-NEXT: 	mov.8b 	%b6, %b3;
; O0-NEXT: 	mov.8b 	%b7, %b2;
; O0-NEXT: 	mov.8b 	%b8, %b1;
; O0-NEXT: 	mov.8b 	[[VR4_8_V4B1]].x, %b8;
; O0-NEXT: 	mov.32b 	[[VR4_8_V4B2]].xyzw, [[VR4_8_V4B1]].xyzw;
; O0-NEXT: 	mov.8b 	[[VR4_8_V4B2]].y, %b7;
; O0-NEXT: 	mov.32b 	[[VR4_8_V4B3]].xyzw, [[VR4_8_V4B2]].xyzw;
; O0-NEXT: 	mov.8b 	[[VR4_8_V4B3]].z, %b6;
; O0-NEXT: 	mov.32b 	[[VR4_8_V4B4]].xyzw, [[VR4_8_V4B3]].xyzw;
; O0-NEXT: 	mov.8b 	[[VR4_8_V4B4]].w, %b5;
; O0-NEXT: 	call [[R32_W0]], @check_char4 ([[VR4_8_V4B4]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], [[R32_W0]], 11;
; O0-NEXT: 	mov.8b 	%b9, [[VR4_8_V4B0]].x;
; O0-NEXT: 	mov.8b 	%b10, [[VR4_8_V4B0]].y;
; O0-NEXT: 	mov.8b 	%b11, [[VR4_8_V4B0]].z;
; O0-NEXT: 	mov.8b 	%b12, [[VR4_8_V4B0]].w;
; O0-NEXT: 	zext.16b.8b 	%h0, %b8;
; O0-NEXT: 	zext.16b.8b 	%h1, %b9;
; O0-NEXT: 	iadd.16b 	%h2, %h0, %h1;
; O0-NEXT: 	trunc.8b.16b 	%b13, %h2;
; O0-NEXT: 	zext.16b.8b 	%h3, %b7;
; O0-NEXT: 	zext.16b.8b 	%h4, %b10;
; O0-NEXT: 	iadd.16b 	%h5, %h3, %h4;
; O0-NEXT: 	trunc.8b.16b 	%b14, %h5;
; O0-NEXT: 	zext.16b.8b 	%h6, %b6;
; O0-NEXT: 	zext.16b.8b 	%h7, %b11;
; O0-NEXT: 	iadd.16b 	%h8, %h6, %h7;
; O0-NEXT: 	trunc.8b.16b 	%b15, %h8;
; O0-NEXT: 	zext.16b.8b 	%h9, %b5;
; O0-NEXT: 	zext.16b.8b 	%h10, %b12;
; O0-NEXT: 	iadd.16b 	%h11, %h9, %h10;
; O0-NEXT: 	trunc.8b.16b 	%b16, %h11;
; O0-NEXT: 	mov.8b 	%b1, %b13;
; O0-NEXT: 	mov.8b 	%b2, %b14;
; O0-NEXT: 	mov.8b 	%b3, %b15;
; O0-NEXT: 	mov.8b 	%b4, %b16;
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB2_2]];
; O0-NEXT: 	goto [[LBB2_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB2_3]]:
; O0-NEXT: 	return [[VR4_8_V4B4]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi <4 x i8> [ zeroinitializer, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:regv4_8b{{[a-z_0-9]*}} = COPY %{{[0-9]+}}
; CHECK:     mov.32b %v4b{{[0-9]+}}.xyzw, %v4b{{[0-9]+}}.xyzw
  %call = tail call i32 @check_char4(<4 x i8> %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add <4 x i8> %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret <4 x i8> %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_short
; CHECK-LABEL: @foo_short
define  i16 @foo_short(i16 %i) {
; O0-LABEL: .16b @foo_short(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]], [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]], [[R16_H4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.16b 	[[R16_H1]], 0;
; O0-NEXT: 	mov.16b 	[[R16_H2]], [[R16_H1]];
; O0-NEXT: 	goto [[LBB3_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB3_2]]:
; O0: 	mov.16b 	[[R16_H3]], [[R16_H2]];
; O0-NEXT: 	call [[R32_W0]], @check_short ([[R16_H3]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], [[R32_W0]], 11;
; O0-NEXT: 	iadd.16b 	[[R16_H4]], [[R16_H3]], [[R16_H0]];
; O0-NEXT: 	mov.16b 	[[R16_H2]], [[R16_H4]];
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB3_2]];
; O0-NEXT: 	goto [[LBB3_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB3_3]]:
; O0-NEXT: 	return [[R16_H3]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi i16 [ 0, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:reg16b = COPY %{{[0-9]+}}
; CHECK:     mov.16b %h{{[0-9]+}}, %h{{[0-9]+}}
  %call = tail call i32 @check_short(i16 %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add i16 %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret i16 %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_short2
; CHECK-LABEL: @foo_short2
define <2 x i16> @foo_short2(<2 x i16> %i) {
; O0-LABEL: .v2.16b @foo_short2(
; O0-SAME: .reg .v2.16b [[VR2_16_V2H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.16b [[VR2_16_V2H1:%[-a-zA-Z$._0-9]+]], [[VR2_16_V2H2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~9>;
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.16b 	%h0, 0;
; O0-NEXT: 	mov.16b 	%h1, %h0;
; O0-NEXT: 	mov.16b 	%h2, %h0;
; O0-NEXT: 	goto [[LBB4_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB4_2]]:
; O0: 	mov.16b 	%h3, %h2;
; O0-NEXT: 	mov.16b 	%h4, %h1;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H1]].x, %h4;
; O0-NEXT: 	mov.32b 	[[VR2_16_V2H2]].xy, [[VR2_16_V2H1]].xy;
; O0-NEXT: 	mov.16b 	[[VR2_16_V2H2]].y, %h3;
; O0-NEXT: 	call [[R32_W0]], @check_short2 ([[VR2_16_V2H2]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], [[R32_W0]], 11;
; O0-NEXT: 	mov.16b 	%h5, [[VR2_16_V2H0]].x;
; O0-NEXT: 	mov.16b 	%h6, [[VR2_16_V2H0]].y;
; O0-NEXT: 	iadd.16b 	%h7, %h4, %h5;
; O0-NEXT: 	iadd.16b 	%h8, %h3, %h6;
; O0-NEXT: 	mov.16b 	%h1, %h7;
; O0-NEXT: 	mov.16b 	%h2, %h8;
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB4_2]];
; O0-NEXT: 	goto [[LBB4_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB4_3]]:
; O0-NEXT: 	return [[VR2_16_V2H2]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi <2 x i16> [ zeroinitializer, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:regv2_16b{{[a-z_0-9]*}} = COPY %{{[0-9]+}}
; CHECK:     mov.32b %v2h{{[0-9]+}}.xy, %v2h{{[0-9]+}}.xy
  %call = tail call i32 @check_short2(<2 x i16> %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add <2 x i16> %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret <2 x i16> %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_short3
; CHECK-LABEL: @foo_short3
define <3 x i16> @foo_short3(<3 x i16> %i) {
; O0-LABEL: .v3.16b @foo_short3(
; O0-SAME: .reg .v3.16b [[VR3_16_V3H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.16b [[VR3_16_V3H1:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H2:%[-a-zA-Z$._0-9]+]], [[VR3_16_V3H3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~13>;
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.16b 	%h0, 0;
; O0-NEXT: 	mov.16b 	%h1, %h0;
; O0-NEXT: 	mov.16b 	%h2, %h0;
; O0-NEXT: 	mov.16b 	%h3, %h0;
; O0-NEXT: 	goto [[LBB5_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB5_2]]:
; O0: 	mov.16b 	%h4, %h3;
; O0-NEXT: 	mov.16b 	%h5, %h2;
; O0-NEXT: 	mov.16b 	%h6, %h1;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H1]].x, %h6;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].x, [[VR3_16_V3H1]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, [[VR3_16_V3H1]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].z, [[VR3_16_V3H1]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H2]].y, %h5;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].x, [[VR3_16_V3H2]].x;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].y, [[VR3_16_V3H2]].y;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, [[VR3_16_V3H2]].z;
; O0-NEXT: 	mov.16b 	[[VR3_16_V3H3]].z, %h4;
; O0-NEXT: 	call [[R32_W0]], @check_short2 ([[VR3_16_V3H3]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], [[R32_W0]], 11;
; O0-NEXT: 	mov.16b 	%h7, [[VR3_16_V3H0]].x;
; O0-NEXT: 	mov.16b 	%h8, [[VR3_16_V3H0]].y;
; O0-NEXT: 	mov.16b 	%h9, [[VR3_16_V3H0]].z;
; O0-NEXT: 	iadd.16b 	%h10, %h6, %h7;
; O0-NEXT: 	iadd.16b 	%h11, %h5, %h8;
; O0-NEXT: 	iadd.16b 	%h12, %h4, %h9;
; O0-NEXT: 	mov.16b 	%h1, %h10;
; O0-NEXT: 	mov.16b 	%h2, %h11;
; O0-NEXT: 	mov.16b 	%h3, %h12;
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB5_2]];
; O0-NEXT: 	goto [[LBB5_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB5_3]]:
; O0-NEXT: 	return [[VR3_16_V3H3]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi <3 x i16> [ zeroinitializer, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:regv3_16b = COPY %{{[0-9]+}}
; CHECK:     mov.32b [[DST:%v3h[0-9]+]].xy, [[SRC:%v3h[0-9]+]].xy
; CHECK:     mov.16b [[DST]].z, [[SRC]].z
  %call = tail call i32 @check_short2(<3 x i16> %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add <3 x i16> %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret <3 x i16> %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_short4
; CHECK-LABEL: @foo_short4
define <4 x i16> @foo_short4(<4 x i16> %i) {
; O0-LABEL: .v4.16b @foo_short4(
; O0-SAME: .reg .v4.16b [[VR4_16_V4H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.16b [[VR4_16_V4H1:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H2:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H3:%[-a-zA-Z$._0-9]+]], [[VR4_16_V4H4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b %h<0~17>;
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.16b 	%h0, 0;
; O0-NEXT: 	mov.16b 	%h1, %h0;
; O0-NEXT: 	mov.16b 	%h2, %h0;
; O0-NEXT: 	mov.16b 	%h3, %h0;
; O0-NEXT: 	mov.16b 	%h4, %h0;
; O0-NEXT: 	goto [[LBB6_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB6_2]]:
; O0: 	mov.16b 	%h5, %h4;
; O0-NEXT: 	mov.16b 	%h6, %h3;
; O0-NEXT: 	mov.16b 	%h7, %h2;
; O0-NEXT: 	mov.16b 	%h8, %h1;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H1]].x, %h8;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H2]].xyzw, [[VR4_16_V4H1]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H2]].y, %h7;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H3]].xyzw, [[VR4_16_V4H2]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H3]].z, %h6;
; O0-NEXT: 	mov.64b 	[[VR4_16_V4H4]].xyzw, [[VR4_16_V4H3]].xyzw;
; O0-NEXT: 	mov.16b 	[[VR4_16_V4H4]].w, %h5;
; O0-NEXT: 	call [[R32_W0]], @check_short4 ([[VR4_16_V4H4]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], [[R32_W0]], 11;
; O0-NEXT: 	mov.16b 	%h9, [[VR4_16_V4H0]].x;
; O0-NEXT: 	mov.16b 	%h10, [[VR4_16_V4H0]].y;
; O0-NEXT: 	mov.16b 	%h11, [[VR4_16_V4H0]].z;
; O0-NEXT: 	mov.16b 	%h12, [[VR4_16_V4H0]].w;
; O0-NEXT: 	iadd.16b 	%h13, %h8, %h9;
; O0-NEXT: 	iadd.16b 	%h14, %h7, %h10;
; O0-NEXT: 	iadd.16b 	%h15, %h6, %h11;
; O0-NEXT: 	iadd.16b 	%h16, %h5, %h12;
; O0-NEXT: 	mov.16b 	%h1, %h13;
; O0-NEXT: 	mov.16b 	%h2, %h14;
; O0-NEXT: 	mov.16b 	%h3, %h15;
; O0-NEXT: 	mov.16b 	%h4, %h16;
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB6_2]];
; O0-NEXT: 	goto [[LBB6_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB6_3]]:
; O0-NEXT: 	return [[VR4_16_V4H4]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi <4 x i16> [ zeroinitializer, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:regv4_16b = COPY %{{[0-9]+}}
; CHECK:     mov.64b %v4h{{[0-9]+}}.xyzw, %v4h{{[0-9]+}}.xyzw
  %call = tail call i32 @check_short4(<4 x i16> %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add <4 x i16> %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret <4 x i16> %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_int
; CHECK-LABEL: @foo_int
define i32 @foo_int(i32 %i) {
; O0-LABEL: .32b @foo_int(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]], [[R32_W5:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.32b 	[[R32_W1]], 0;
; O0-NEXT: 	mov.32b 	[[R32_W2]], [[R32_W1]];
; O0-NEXT: 	goto [[LBB7_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB7_2]]:
; O0: 	mov.32b 	[[R32_W3]], [[R32_W2]];
; O0-NEXT: 	call [[R32_W4]], @check_int ([[R32_W3]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], [[R32_W4]], 11;
; O0-NEXT: 	iadd.32b 	[[R32_W5]], [[R32_W3]], [[R32_W0]];
; O0-NEXT: 	mov.32b 	[[R32_W2]], [[R32_W5]];
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB7_2]];
; O0-NEXT: 	goto [[LBB7_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB7_3]]:
; O0-NEXT: 	return [[R32_W3]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi i32 [ 0, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:reg32b = COPY %{{[0-9]+}}
; CHECK:     mov.32b %w{{[0-9]+}}, %w{{[0-9]+}}
  %call = tail call i32 @check_int(i32 %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add nsw i32 %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret i32 %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_int2
; CHECK-LABEL: @foo_int2
define <2 x i32> @foo_int2(<2 x i32> %i) {
; O0-LABEL: .v2.32b @foo_int2(
; O0-SAME: .reg .v2.32b [[VR2_32_V2W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.32b [[VR2_32_V2W1:%[-a-zA-Z$._0-9]+]], [[VR2_32_V2W2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~10>;
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.32b 	%w0, 0;
; O0-NEXT: 	mov.32b 	%w1, %w0;
; O0-NEXT: 	mov.32b 	%w2, %w0;
; O0-NEXT: 	goto [[LBB8_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB8_2]]:
; O0: 	mov.32b 	%w3, %w2;
; O0-NEXT: 	mov.32b 	%w4, %w1;
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W1]].x, %w4;
; O0-NEXT: 	mov.64b 	[[VR2_32_V2W2]].xy, [[VR2_32_V2W1]].xy;
; O0-NEXT: 	mov.32b 	[[VR2_32_V2W2]].y, %w3;
; O0-NEXT: 	call %w5, @check_int2 ([[VR2_32_V2W2]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], %w5, 11;
; O0-NEXT: 	mov.32b 	%w6, [[VR2_32_V2W0]].x;
; O0-NEXT: 	mov.32b 	%w7, [[VR2_32_V2W0]].y;
; O0-NEXT: 	iadd.32b 	%w8, %w4, %w6;
; O0-NEXT: 	iadd.32b 	%w9, %w3, %w7;
; O0-NEXT: 	mov.32b 	%w1, %w8;
; O0-NEXT: 	mov.32b 	%w2, %w9;
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB8_2]];
; O0-NEXT: 	goto [[LBB8_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB8_3]]:
; O0-NEXT: 	return [[VR2_32_V2W2]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi <2 x i32> [ zeroinitializer, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:regv2_32b = COPY %{{[0-9]+}}
; CHECK:     mov.64b %v2w{{[0-9]+}}.xy, %v2w{{[0-9]+}}.xy
  %call = tail call i32 @check_int2(<2 x i32> %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add <2 x i32> %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret <2 x i32> %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_int3
; CHECK-LABEL: @foo_int3
define <3 x i32> @foo_int3(<3 x i32> %i) {
; O0-LABEL: .v3.32b @foo_int3(
; O0-SAME: .reg .v3.32b [[VR3_32_V3W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.32b [[VR3_32_V3W1:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W2:%[-a-zA-Z$._0-9]+]], [[VR3_32_V3W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~14>;
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.32b 	%w0, 0;
; O0-NEXT: 	mov.32b 	%w1, %w0;
; O0-NEXT: 	mov.32b 	%w2, %w0;
; O0-NEXT: 	mov.32b 	%w3, %w0;
; O0-NEXT: 	goto [[LBB9_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB9_2]]:
; O0: 	mov.32b 	%w4, %w3;
; O0-NEXT: 	mov.32b 	%w5, %w2;
; O0-NEXT: 	mov.32b 	%w6, %w1;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W1]].x, %w6;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].x, [[VR3_32_V3W1]].x;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].y, [[VR3_32_V3W1]].y;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].z, [[VR3_32_V3W1]].z;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W2]].y, %w5;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].x, [[VR3_32_V3W2]].x;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].y, [[VR3_32_V3W2]].y;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].z, [[VR3_32_V3W2]].z;
; O0-NEXT: 	mov.32b 	[[VR3_32_V3W3]].z, %w4;
; O0-NEXT: 	call %w7, @check_int2 ([[VR3_32_V3W3]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], %w7, 11;
; O0-NEXT: 	mov.32b 	%w8, [[VR3_32_V3W0]].x;
; O0-NEXT: 	mov.32b 	%w9, [[VR3_32_V3W0]].y;
; O0-NEXT: 	mov.32b 	%w10, [[VR3_32_V3W0]].z;
; O0-NEXT: 	iadd.32b 	%w11, %w6, %w8;
; O0-NEXT: 	iadd.32b 	%w12, %w5, %w9;
; O0-NEXT: 	iadd.32b 	%w13, %w4, %w10;
; O0-NEXT: 	mov.32b 	%w1, %w11;
; O0-NEXT: 	mov.32b 	%w2, %w12;
; O0-NEXT: 	mov.32b 	%w3, %w13;
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB9_2]];
; O0-NEXT: 	goto [[LBB9_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB9_3]]:
; O0-NEXT: 	return [[VR3_32_V3W3]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi <3 x i32> [ zeroinitializer, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:regv3_32b = COPY %{{[0-9]+}}
; CHECK:     mov.64b [[DST:%v3w[0-9]+]].xy, [[SRC:%v3w[0-9]+]].xy
; CHECK:     mov.32b [[DST]].z, [[SRC]].z
  %call = tail call i32 @check_int2(<3 x i32> %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add <3 x i32> %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret <3 x i32> %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_int4
; CHECK-LABEL: @foo_int4
define <4 x i32> @foo_int4(<4 x i32> %i) {
; O0-LABEL: .v4.32b @foo_int4(
; O0-SAME: .reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.32b [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W2:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W3:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~18>;
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.32b 	%w0, 0;
; O0-NEXT: 	mov.32b 	%w1, %w0;
; O0-NEXT: 	mov.32b 	%w2, %w0;
; O0-NEXT: 	mov.32b 	%w3, %w0;
; O0-NEXT: 	mov.32b 	%w4, %w0;
; O0-NEXT: 	goto [[LBB10_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB10_2]]:
; O0: 	mov.32b 	%w5, %w4;
; O0-NEXT: 	mov.32b 	%w6, %w3;
; O0-NEXT: 	mov.32b 	%w7, %w2;
; O0-NEXT: 	mov.32b 	%w8, %w1;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W1]].x, %w8;
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W2]].xyzw, [[VR4_32_V4W1]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W2]].y, %w7;
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W3]].xyzw, [[VR4_32_V4W2]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W3]].z, %w6;
; O0-NEXT: 	mov.128b 	[[VR4_32_V4W4]].xyzw, [[VR4_32_V4W3]].xyzw;
; O0-NEXT: 	mov.32b 	[[VR4_32_V4W4]].w, %w5;
; O0-NEXT: 	call %w9, @check_int4 ([[VR4_32_V4W4]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], %w9, 11;
; O0-NEXT: 	mov.32b 	%w10, [[VR4_32_V4W0]].x;
; O0-NEXT: 	mov.32b 	%w11, [[VR4_32_V4W0]].y;
; O0-NEXT: 	mov.32b 	%w12, [[VR4_32_V4W0]].z;
; O0-NEXT: 	mov.32b 	%w13, [[VR4_32_V4W0]].w;
; O0-NEXT: 	iadd.32b 	%w14, %w8, %w10;
; O0-NEXT: 	iadd.32b 	%w15, %w7, %w11;
; O0-NEXT: 	iadd.32b 	%w16, %w6, %w12;
; O0-NEXT: 	iadd.32b 	%w17, %w5, %w13;
; O0-NEXT: 	mov.32b 	%w1, %w14;
; O0-NEXT: 	mov.32b 	%w2, %w15;
; O0-NEXT: 	mov.32b 	%w3, %w16;
; O0-NEXT: 	mov.32b 	%w4, %w17;
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB10_2]];
; O0-NEXT: 	goto [[LBB10_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB10_3]]:
; O0-NEXT: 	return [[VR4_32_V4W4]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi <4 x i32> [ zeroinitializer, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:regv4_32b = COPY %{{[0-9]+}}
; CHECK:       mov.128b [[DST:%v4w[0-9]+]].xyzw, [[SRC:%v4w[0-9]+]].xyzw
  %call = tail call i32 @check_int4(<4 x i32>  %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add <4 x i32> %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret <4 x i32> %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_long
; CHECK-LABEL: @foo_long
define i64 @foo_long(i64 %i) {
; O0-LABEL: .64b @foo_long(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]], [[R64_D2:%[-a-zA-Z$._0-9]+]], [[R64_D3:%[-a-zA-Z$._0-9]+]], [[R64_D4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.64b 	[[R64_D1]], 0;
; O0-NEXT: 	mov.64b 	[[R64_D2]], [[R64_D1]];
; O0-NEXT: 	goto [[LBB11_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB11_2]]:
; O0: 	mov.64b 	[[R64_D3]], [[R64_D2]];
; O0-NEXT: 	call [[R32_W0]], @check_long ([[R64_D3]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], [[R32_W0]], 11;
; O0-NEXT: 	iadd.64b 	[[R64_D4]], [[R64_D3]], [[R64_D0]];
; O0-NEXT: 	mov.64b 	[[R64_D2]], [[R64_D4]];
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB11_2]];
; O0-NEXT: 	goto [[LBB11_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB11_3]]:
; O0-NEXT: 	return [[R64_D3]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi i64 [ 0, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:reg64b = COPY %{{[0-9]+}}
; CHECK:     mov.64b %d{{[0-9]+}}, %d{{[0-9]+}}
  %call = tail call i32 @check_long(i64 %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add nsw i64 %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret i64 %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_long2
; CHECK-LABEL: @foo_long2
define <2 x i64> @foo_long2(<2 x i64> %i) {
; O0-LABEL: .v2.64b @foo_long2(
; O0-SAME: .reg .v2.64b [[VR2_64_V2D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.64b [[VR2_64_V2D1:%[-a-zA-Z$._0-9]+]], [[VR2_64_V2D2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b %d<0~9>;
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.64b 	%d0, 0;
; O0-NEXT: 	mov.64b 	%d1, %d0;
; O0-NEXT: 	mov.64b 	%d2, %d0;
; O0-NEXT: 	goto [[LBB12_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB12_2]]:
; O0: 	mov.64b 	%d3, %d2;
; O0-NEXT: 	mov.64b 	%d4, %d1;
; O0-NEXT: 	mov.64b 	[[VR2_64_V2D1]].x, %d4;
; O0-NEXT: 	mov.128b 	[[VR2_64_V2D2]].xy, [[VR2_64_V2D1]].xy;
; O0-NEXT: 	mov.64b 	[[VR2_64_V2D2]].y, %d3;
; O0-NEXT: 	call [[R32_W0]], @check_long2 ([[VR2_64_V2D2]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], [[R32_W0]], 11;
; O0-NEXT: 	mov.64b 	%d5, [[VR2_64_V2D0]].x;
; O0-NEXT: 	mov.64b 	%d6, [[VR2_64_V2D0]].y;
; O0-NEXT: 	iadd.64b 	%d7, %d4, %d5;
; O0-NEXT: 	iadd.64b 	%d8, %d3, %d6;
; O0-NEXT: 	mov.64b 	%d1, %d7;
; O0-NEXT: 	mov.64b 	%d2, %d8;
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB12_2]];
; O0-NEXT: 	goto [[LBB12_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB12_3]]:
; O0-NEXT: 	return [[VR2_64_V2D2]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi <2 x i64> [ zeroinitializer, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:regv2_64b = COPY %{{[0-9]+}}
; CHECK:       mov.128b [[DST:%v2d[0-9]+]].xy, [[SRC:%v2d[0-9]+]].xy
  %call = tail call i32 @check_long2(<2 x i64> %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add <2 x i64> %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret <2 x i64> %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_long3
; CHECK-LABEL: @foo_long3
define <3 x i64> @foo_long3(<3 x i64> %i) {
; O0-LABEL: .v3.64b @foo_long3(
; O0-SAME: .reg .v3.64b [[VR3_64_V3D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v3.64b [[VR3_64_V3D1:%[-a-zA-Z$._0-9]+]], [[VR3_64_V3D2:%[-a-zA-Z$._0-9]+]], [[VR3_64_V3D3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b %d<0~13>;
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.64b 	%d0, 0;
; O0-NEXT: 	mov.64b 	%d1, %d0;
; O0-NEXT: 	mov.64b 	%d2, %d0;
; O0-NEXT: 	mov.64b 	%d3, %d0;
; O0-NEXT: 	goto [[LBB13_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB13_2]]:
; O0: 	mov.64b 	%d4, %d3;
; O0-NEXT: 	mov.64b 	%d5, %d2;
; O0-NEXT: 	mov.64b 	%d6, %d1;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D1]].x, %d6;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D2]].x, [[VR3_64_V3D1]].x;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D2]].y, [[VR3_64_V3D1]].y;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D2]].z, [[VR3_64_V3D1]].z;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D2]].y, %d5;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D3]].x, [[VR3_64_V3D2]].x;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D3]].y, [[VR3_64_V3D2]].y;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D3]].z, [[VR3_64_V3D2]].z;
; O0-NEXT: 	mov.64b 	[[VR3_64_V3D3]].z, %d4;
; O0-NEXT: 	call [[R32_W0]], @check_long2 ([[VR3_64_V3D3]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], [[R32_W0]], 11;
; O0-NEXT: 	mov.64b 	%d7, [[VR3_64_V3D0]].x;
; O0-NEXT: 	mov.64b 	%d8, [[VR3_64_V3D0]].y;
; O0-NEXT: 	mov.64b 	%d9, [[VR3_64_V3D0]].z;
; O0-NEXT: 	iadd.64b 	%d10, %d6, %d7;
; O0-NEXT: 	iadd.64b 	%d11, %d5, %d8;
; O0-NEXT: 	iadd.64b 	%d12, %d4, %d9;
; O0-NEXT: 	mov.64b 	%d1, %d10;
; O0-NEXT: 	mov.64b 	%d2, %d11;
; O0-NEXT: 	mov.64b 	%d3, %d12;
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB13_2]];
; O0-NEXT: 	goto [[LBB13_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB13_3]]:
; O0-NEXT: 	return [[VR3_64_V3D3]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi <3 x i64> [ zeroinitializer, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:regv3_64b = COPY %{{[0-9]+}}
; CHECK:     mov.128b [[DST:%v3d[0-9]+]].xy, [[SRC:%v3d[0-9]+]].xy
; CHECK:     mov.64b [[DST]].z, [[SRC]].z
  %call = tail call i32 @check_long2(<3 x i64> %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add <3 x i64> %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret <3 x i64> %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_long4
; CHECK-LABEL: @foo_long4
define <4 x i64> @foo_long4(<4 x i64> %i) {
; O0-LABEL: .v4.64b @foo_long4(
; O0-SAME: .reg .v4.64b [[VR4_64_V4D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.64b [[VR4_64_V4D1:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D2:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D3:%[-a-zA-Z$._0-9]+]], [[VR4_64_V4D4:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .64b %d<0~17>;
; O0-NEXT: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; O0: 	mov.64b 	%d0, 0;
; O0-NEXT: 	mov.64b 	%d1, %d0;
; O0-NEXT: 	mov.64b 	%d2, %d0;
; O0-NEXT: 	mov.64b 	%d3, %d0;
; O0-NEXT: 	mov.64b 	%d4, %d0;
; O0-NEXT: 	goto [[LBB14_2:LBB[0-9_]+]];
; O0-NEXT: [[LBB14_2]]:
; O0: 	mov.64b 	%d5, %d4;
; O0-NEXT: 	mov.64b 	%d6, %d3;
; O0-NEXT: 	mov.64b 	%d7, %d2;
; O0-NEXT: 	mov.64b 	%d8, %d1;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D1]].x, %d8;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].x, [[VR4_64_V4D1]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].y, [[VR4_64_V4D1]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].z, [[VR4_64_V4D1]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].w, [[VR4_64_V4D1]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D2]].y, %d7;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].x, [[VR4_64_V4D2]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].y, [[VR4_64_V4D2]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].z, [[VR4_64_V4D2]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].w, [[VR4_64_V4D2]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D3]].z, %d6;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].x, [[VR4_64_V4D3]].x;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].y, [[VR4_64_V4D3]].y;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].z, [[VR4_64_V4D3]].z;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].w, [[VR4_64_V4D3]].w;
; O0-NEXT: 	mov.64b 	[[VR4_64_V4D4]].w, %d5;
; O0-NEXT: 	call [[R32_W0]], @check_long4 ([[VR4_64_V4D4]]);
; O0-NEXT: 	scmp.lt.32b 	[[P_P0]], [[R32_W0]], 11;
; O0-NEXT: 	mov.64b 	%d9, [[VR4_64_V4D0]].x;
; O0-NEXT: 	mov.64b 	%d10, [[VR4_64_V4D0]].y;
; O0-NEXT: 	mov.64b 	%d11, [[VR4_64_V4D0]].z;
; O0-NEXT: 	mov.64b 	%d12, [[VR4_64_V4D0]].w;
; O0-NEXT: 	iadd.64b 	%d13, %d8, %d9;
; O0-NEXT: 	iadd.64b 	%d14, %d7, %d10;
; O0-NEXT: 	iadd.64b 	%d15, %d6, %d11;
; O0-NEXT: 	iadd.64b 	%d16, %d5, %d12;
; O0-NEXT: 	mov.64b 	%d1, %d13;
; O0-NEXT: 	mov.64b 	%d2, %d14;
; O0-NEXT: 	mov.64b 	%d3, %d15;
; O0-NEXT: 	mov.64b 	%d4, %d16;
; O0-NEXT: 	goto.cond [[P_P0]], [[LBB14_2]];
; O0-NEXT: 	goto [[LBB14_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB14_3]]:
; O0-NEXT: 	return [[VR4_64_V4D4]];
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %x.0 = phi <4 x i64> [ zeroinitializer, %entry ], [ %add, %while.cond ]
; CHECK-MIR: %{{[0-9]+}}:regv4_64b = COPY %{{[0-9]+}}
; CHECK:     mov.128b [[DST:%v4d[0-9]+]].xy, [[SRC:%v4d[0-9]+]].xy
; CHECK:     mov.128b [[DST]].zw, [[SRC]].zw
  %call = tail call i32 @check_long4(<4 x i64> %x.0)
  %cmp = icmp slt i32 %call, 11
  %add = add <4 x i64> %x.0, %i
  br i1 %cmp, label %while.cond, label %while.end

while.end:                                        ; preds = %while.cond
  ret <4 x i64> %x.0
}

; CHECK-MIR-LABEL: {{^}}name: foo_undef
; CHECK-LABEL: @foo_undef
define float @foo_undef(i32 %a, i32 %b) {
; O0-LABEL: .32b @foo_undef(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]], [[P_P1:%[-a-zA-Z$._0-9]+]], [[P_P2:%[-a-zA-Z$._0-9]+]], [[P_P3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]], [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	scmp.lt.32b 	[[P_P0]], [[R32_W0]], 1024;
; O0: 	goto.cond [[P_P0]], [[LBB15_2:LBB[0-9_]+]];
; O0-NEXT: 	goto [[LBB15_3:LBB[0-9_]+]];
; O0-NEXT: [[LBB15_2]]:
; O0-NEXT: 	ucmp.eq.32b 	[[P_P2]], [[R32_W1]], -100;
; O0-NEXT: 	sel.16b 	[[R16_H0]], 1, 0, [[P_P2]];
; O0-NEXT: 	ucmp.ne.16b 	[[P_P1]], [[R16_H0]], 0;
; O0-NEXT: 	goto [[LBB15_3]];
; O0-NEXT: [[LBB15_3]]:
; O0-NEXT: 	sel.16b 	[[R16_H1]], 1, 0, [[P_P1]];
; O0-NEXT: 	ucmp.ne.16b 	[[P_P3]], [[R16_H1]], 0;
; O0-NEXT: 	sel.32b 	[[R32_W2]], {{0x00000000|0}}, {{0x3F800000|1065353216}}, [[P_P3]];
; O0-NEXT: 	goto [[LBB15_4:LBB[0-9_]+]];
; O0-NEXT: [[LBB15_4]]:
; O0-NEXT: 	return [[R32_W2]];
entry:
; CHECK-MIR: [[PRED:%[0-9]+]]:pred = IMPLICIT_DEF
; CHECK-MIR: [[PRED]]:pred = ucmp_eq_32b_pri %{{[0-9]+}}, -100
; CHECK-MIR: %{{[0-9]+}}:reg32b = sel_f_iip [[PRED]], float 0.000000e+00, float 1.000000e+00

; CHECK:      .pred %p0, [[PRED:%p[0-9]+]]
; CHECK:      ucmp.eq.32b   [[PRED]], %w1, -100
; CHECK:      sel.32b   %w{{[0-9]+}}, {{0x00000000|0}}, {{0x3F800000|1065353216}}, [[PRED]]
  %c0 = icmp slt i32 %a, 1024
  br i1 %c0, label %_if, label %_else

_if:
  %icmp = icmp eq i32 %b, -100
  br label %_else

_else:
  %.not = phi i1 [ %icmp, %_if ], [ undef, %entry ]
  %rv = select i1 %.not, float 0.000000e+00, float 1.000000e+00
  br label %_ret

_ret:
  ret float %rv
}
