; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -verify-machineinstrs -o %t.pisa
; RUN: FileCheck %s < %t.pisa
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs

; A non-kernel function with a static alloca forces a frame-index operand in
; the st.private / ld.private instructions.  PISAMCInstLower::lower()
; handles MO_FrameIndex by calling setVariableRef(OutMI, OpNo), which
; must insert a brand-new entry into PISAMCInst::Opnds (the
; It == MC->Opnds.end() branch).

define i32 @variable_ref_new_entry(i32 %a, i32 %b) {
; CHECK-LABEL: .32b @variable_ref_new_entry(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]], [[R32_W4:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 4 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][4];
; CHECK-NEXT: 	.private .align 4 [[PRIVATE_R1:@[-a-zA-Z$._0-9]+]][4];
; CHECK: 	st.private.32b	 [[[PRIVATE_R0]]], [[R32_W0]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R1]]], [[R32_W1]];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W2]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W3]], [[[PRIVATE_R1]]];
; CHECK-NEXT: 	iadd.32b 	[[R32_W4]], [[R32_W2]], [[R32_W3]];
; CHECK-NEXT: 	return [[R32_W4]];
entry:
  %slot_a = alloca i32, align 4, addrspace(4)
  %slot_b = alloca i32, align 4, addrspace(4)
  store i32 %a, ptr addrspace(4) %slot_a
  store i32 %b, ptr addrspace(4) %slot_b
  %va = load i32, ptr addrspace(4) %slot_a
  %vb = load i32, ptr addrspace(4) %slot_b
  %sum = add i32 %va, %vb
  ret i32 %sum
}

; A second function ensures setVariableRef is called for operands that
; are fresh (not previously swizzled), covering the new-entry path a
; second time with a different frame index.

define i32 @variable_ref_single_slot(i32 %x) {
; CHECK-LABEL: .32b @variable_ref_single_slot(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 4 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][4];
; CHECK: 	st.private.32b	 [[[PRIVATE_R0]]], [[R32_W0]];
; CHECK-NEXT: 	ld.private.32b	 [[R32_W1]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	return [[R32_W1]];
entry:
  %slot = alloca i32, align 4, addrspace(4)
  store i32 %x, ptr addrspace(4) %slot
  %v = load i32, ptr addrspace(4) %slot
  ret i32 %v
}
