; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -verify-machineinstrs -march=pisa | FileCheck %s
; RUN: llc < %s -verify-machineinstrs -march=pisa > %t.pisa
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs

define ptr addrspace(4) @alloca_addrof() {
; CHECK-LABEL: .32b @alloca_addrof(
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 1 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][1];
; CHECK: 	addrof.32b [[R32_W0]], [[PRIVATE_R0]];
; CHECK-NEXT: 	return [[R32_W0]];
  %1 = alloca i8, align 1, addrspace(4)
  ret ptr addrspace(4) %1
}

define i8 @alloca_i8() {
; CHECK-LABEL: .8b @alloca_i8(
; CHECK: 	.reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 1 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][1];
; CHECK: 	ld.private.8b	 [[R8_B0]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	return [[R8_B0]];
  %1 = alloca i8, align 1, addrspace(4)
  %2 = load i8, ptr addrspace(4) %1
  ret i8 %2
}

define i16 @alloca_i16() {
; CHECK-LABEL: .16b @alloca_i16(
; CHECK: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 2 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][2];
; CHECK: 	ld.private.16b	 [[R16_H0]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	return [[R16_H0]];
  %1 = alloca i16, align 2, addrspace(4)
  %2 = load i16, ptr addrspace(4) %1
  ret i16 %2
}

define i32 @alloca_i32() {
; CHECK-LABEL: .32b @alloca_i32(
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 4 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][4];
; CHECK: 	ld.private.32b	 [[R32_W0]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	return [[R32_W0]];
  %1 = alloca i32, align 4, addrspace(4)
  %2 = load i32, ptr addrspace(4) %1
  ret i32 %2
}

define i32 @alloca_i32_align32() {
; CHECK-LABEL: .32b @alloca_i32_align32(
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 32 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][4];
; CHECK: 	ld.private.32b	 [[R32_W0]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	return [[R32_W0]];
  %1 = alloca i32, align 32, addrspace(4)
  %2 = load i32, ptr addrspace(4) %1
  ret i32 %2
}

define i32 @alloca_i32_default_align() {
; CHECK-LABEL: .32b @alloca_i32_default_align(
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 4 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][4];
; CHECK: 	ld.private.32b	 [[R32_W0]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	return [[R32_W0]];
  %1 = alloca i32, addrspace(4)
  %2 = load i32, ptr addrspace(4) %1
  ret i32 %2
}

define i32 @array_alloca() {
; CHECK-LABEL: .32b @array_alloca(
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 16 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][12];
; CHECK: 	ld.private.32b	 [[R32_W0]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	return [[R32_W0]];
  %1 = alloca [3 x i32], align 16, addrspace(4)
  %2 = load i32, ptr addrspace(4) %1
  ret i32 %2
}

define i32 @array_alloca_var_imm() {
; CHECK-LABEL: .32b @array_alloca_var_imm(
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 16 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][12];
; CHECK: 	ld.private.32b	 [[R32_W0]], [[[PRIVATE_R0]] + 4];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + 4], [[R32_W0]];
; CHECK-NEXT: 	return [[R32_W0]];
  %1 = alloca [3 x i32], align 16, addrspace(4)
  %2 = getelementptr [3 x i32], ptr addrspace(4) %1, i32 0, i32 1
  %3 = load i32, ptr addrspace(4) %2
  store i32 %3, ptr addrspace(4) %2
  ret i32 %3
}

define i32 @array_alloca_var_reg(i32 %idx) {
; CHECK-LABEL: .32b @array_alloca_var_reg(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]], [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 16 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][12];
; CHECK: 	shl.32b 	[[R32_W1]], [[R32_W0]], 2;
; CHECK-NEXT: 	ld.private.32b	 [[R32_W2]], [[[PRIVATE_R0]] + [[R32_W1]]];
; CHECK-NEXT: 	st.private.32b	 [[[PRIVATE_R0]] + [[R32_W1]]], [[R32_W2]];
; CHECK-NEXT: 	return [[R32_W2]];
  %1 = alloca [3 x i32], align 16, addrspace(4)
  %2 = getelementptr [3 x i32], ptr addrspace(4) %1, i32 0, i32 %idx
  %3 = load i32, ptr addrspace(4) %2
  store i32 %3, ptr addrspace(4) %2
  ret i32 %3
}

define ptr addrspace(4) @addrspace0() {
; CHECK-LABEL: .32b @addrspace0(
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 8 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][4];
; CHECK: 	ld.private.32b	 [[R32_W0]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	return [[R32_W0]];
  %1 = alloca ptr addrspace(4), align 8, addrspace(4)
  %2 = load ptr addrspace(4), ptr addrspace(4) %1
  ret ptr addrspace(4) %2
}

define ptr addrspace(1) @addrspace1() {
; CHECK-LABEL: .64b @addrspace1(
; CHECK: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 8 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][8];
; CHECK: 	ld.private.64b	 [[R64_D0]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	return [[R64_D0]];
  %1 = alloca ptr addrspace(1), align 8, addrspace(4)
  %2 = load ptr addrspace (1), ptr addrspace(4) %1
  ret ptr addrspace(1) %2
}

define ptr addrspace(2) @addrspace2() {
; CHECK-LABEL: .64b @addrspace2(
; CHECK: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 8 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][8];
; CHECK: 	ld.private.64b	 [[R64_D0]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	return [[R64_D0]];
  %1 = alloca ptr addrspace(2), align 8, addrspace(4)
  %2 = load ptr addrspace (2), ptr addrspace(4) %1
  ret ptr addrspace(2) %2
}

define ptr addrspace(3) @addrspace3() {
; CHECK-LABEL: .32b @addrspace3(
; CHECK: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 4 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][4];
; CHECK: 	ld.private.32b	 [[R32_W0]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	return [[R32_W0]];
  %1 = alloca ptr addrspace(3), align 4, addrspace(4)
  %2 = load ptr addrspace (3), ptr addrspace(4) %1
  ret ptr addrspace(3) %2
}

define ptr @addrspace4() {
; CHECK-LABEL: .64b @addrspace4(
; CHECK: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 8 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][8];
; CHECK: 	ld.private.64b	 [[R64_D0]], [[[PRIVATE_R0]]];
; CHECK-NEXT: 	return [[R64_D0]];
  %1 = alloca ptr, align 8, addrspace(4)
  %2 = load ptr, ptr addrspace(4) %1
  ret ptr %2
}

declare void @llvm.lifetime.start.p0(i64, ptr addrspace(4))
declare void @llvm.lifetime.end.p0(i64, ptr addrspace(4))

define void @alloca_vec(i8 %x, i32 %idx1, i32 %idx2) {
; CHECK-LABEL: void @alloca_vec(
; CHECK-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .8b [[R8_B1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.private .align 4 [[PRIVATE_R0:@[-a-zA-Z$._0-9]+]][32];
; CHECK: 	mov.8b 	[[R8_B1]], 0;
; CHECK-NEXT: 	st.private.8b	 [[[PRIVATE_R0]]], [[R8_B1]];
; CHECK-NEXT: 	st.private.8b	 [[[PRIVATE_R0]]], [[R8_B1]];
; CHECK-NEXT: 	return;
  %1 = alloca <4 x i64>, align 4, addrspace(4)
  %2 = alloca <4 x i64>, align 4, addrspace(4)
  call void @llvm.lifetime.start.p0(i64 4, ptr addrspace(4) nonnull %1)
  store i8 0, ptr addrspace(4) %1
  call void @llvm.lifetime.end.p0(i64 4, ptr addrspace(4) nonnull %1)
  call void @llvm.lifetime.start.p0(i64 4, ptr addrspace(4) nonnull %2)
  store i8 0, ptr addrspace(4) %2
  call void @llvm.lifetime.end.p0(i64 4, ptr addrspace(4) nonnull %2)
  ret void
}

declare void @stack.user(ptr addrspace(4) %stack)

define void @alloca_dead(i8 %x, i32 %idx1, i32 %idx2) {
  %dead0 = alloca i32, align 4, addrspace(4)
  %live0 = alloca i32, align 4, addrspace(4)
  %dead1 = alloca i32, align 4, addrspace(4)
  %live1 = alloca i32, align 4, addrspace(4)

  call void @llvm.lifetime.start.p0(i64 4, ptr addrspace(4) nonnull %dead0)
  call void @llvm.lifetime.start.p0(i64 4, ptr addrspace(4) nonnull %live0)
  call void @llvm.lifetime.start.p0(i64 4, ptr addrspace(4) nonnull %live1)

  call void @stack.user(ptr addrspace(4) %dead0)

  call void @llvm.lifetime.end.p0(i64 4, ptr addrspace(4) nonnull %dead0)
  call void @llvm.lifetime.start.p0(i64 4, ptr addrspace(4) nonnull %dead1)

  call void @stack.user(ptr addrspace(4) %live0)
  call void @stack.user(ptr addrspace(4) %live1)
  call void @stack.user(ptr addrspace(4) %dead1)

  call void @llvm.lifetime.end.p0(i64 4, ptr addrspace(4) nonnull %live0)
  call void @llvm.lifetime.end.p0(i64 4, ptr addrspace(4) nonnull %live1)
  call void @llvm.lifetime.end.p0(i64 4, ptr addrspace(4) nonnull %dead1)

  ret void
}
