; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs

; SEL-LABEL: @test_sel_i16rr
define i16 @test_sel_i16rr(i16 %a, i16 %b) {
; CHECK-LABEL: .16b @test_sel_i16rr(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.16b 	[[P_P0]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	sel.16b 	[[R16_H2]], [[R16_H0]], [[R16_H1]], [[P_P0]];
; CHECK-NEXT: 	return [[R16_H2]];
  %cmp = icmp eq i16 %a, %b
  %sel = select i1 %cmp, i16 %a, i16 %b
  ret i16 %sel
}

; SEL-LABEL: @test_sel_i16ri
define i16 @test_sel_i16ri(i16 %a, i16 %b) {
; CHECK-LABEL: .16b @test_sel_i16ri(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.16b 	[[P_P0]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	sel.16b 	[[R16_H2]], [[R16_H0]], 5, [[P_P0]];
; CHECK-NEXT: 	return [[R16_H2]];
  %cmp = icmp eq i16 %a, %b
  %sel = select i1 %cmp, i16 %a, i16 5
  ret i16 %sel
}

; SEL-LABEL: @test_sel_i16ir
define i16 @test_sel_i16ir(i16 %a, i16 %b) {
; CHECK-LABEL: .16b @test_sel_i16ir(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.16b 	[[P_P0]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	sel.16b 	[[R16_H2]], 5, [[R16_H0]], [[P_P0]];
; CHECK-NEXT: 	return [[R16_H2]];
  %cmp = icmp eq i16 %a, %b
  %sel = select i1 %cmp, i16 5, i16 %a
  ret i16 %sel
}

; FIXME: Retain two immediate sources for minimal code sequence.
; SEL-LABEL: @test_sel_i16ii
define i16 @test_sel_i16ii(i16 %a, i16 %b) {
; CHECK-LABEL: .16b @test_sel_i16ii(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]], [[R16_H3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.16b 	[[P_P0]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	sel.16b 	[[R16_H2]], -1, 0, [[P_P0]];
; CHECK-NEXT: 	iadd.16b 	[[R16_H3]], [[R16_H2]], 6;
; CHECK-NEXT: 	return [[R16_H3]];
  %cmp = icmp eq i16 %a, %b
  %sel = select i1 %cmp, i16 5, i16 6
  ret i16 %sel
}

; SEL-LABEL: @test_sel_i32rr
define i32 @test_sel_i32rr(i32 %a, i32 %b) {
; CHECK-LABEL: .32b @test_sel_i32rr(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.32b 	[[P_P0]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	sel.32b 	[[R32_W2]], [[R32_W0]], [[R32_W1]], [[P_P0]];
; CHECK-NEXT: 	return [[R32_W2]];
  %cmp = icmp eq i32 %a, %b
  %sel = select i1 %cmp, i32 %a, i32 %b
  ret i32 %sel
}

; SEL-LABEL: @test_sel_i32ri
define i32 @test_sel_i32ri(i32 %a, i32 %b) {
; CHECK-LABEL: .32b @test_sel_i32ri(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.32b 	[[P_P0]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	sel.32b 	[[R32_W2]], [[R32_W0]], 5, [[P_P0]];
; CHECK-NEXT: 	return [[R32_W2]];
  %cmp = icmp eq i32 %a, %b
  %sel = select i1 %cmp, i32 %a, i32 5
  ret i32 %sel
}

; SEL-LABEL: @test_sel_i32ir
define i32 @test_sel_i32ir(i32 %a, i32 %b) {
; CHECK-LABEL: .32b @test_sel_i32ir(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.32b 	[[P_P0]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	sel.32b 	[[R32_W2]], 5, [[R32_W0]], [[P_P0]];
; CHECK-NEXT: 	return [[R32_W2]];
  %cmp = icmp eq i32 %a, %b
  %sel = select i1 %cmp, i32 5, i32 %a
  ret i32 %sel
}

; FIXME: Retain the selection to keep the original semnatic.
; SEL-LABEL: @test_sel_i32ii
define i32 @test_sel_i32ii(i32 %a, i32 %b) {
; CHECK-LABEL: .32b @test_sel_i32ii(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]], [[R32_W3:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.32b 	[[R32_W2]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	iadd.32b 	[[R32_W3]], [[R32_W2]], 6;
; CHECK-NEXT: 	return [[R32_W3]];
  %cmp = icmp eq i32 %a, %b
  %sel = select i1 %cmp, i32 5, i32 6
  ret i32 %sel
}

; SEL-LABEL: @test_sel_i64rr
define i64 @test_sel_i64rr(i64 %a, i64 %b) {
; CHECK-LABEL: .64b @test_sel_i64rr(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.64b 	[[P_P0]], [[R64_D0]], [[R64_D1]];
; CHECK-NEXT: 	sel.64b 	[[R64_D2]], [[R64_D0]], [[R64_D1]], [[P_P0]];
; CHECK-NEXT: 	return [[R64_D2]];
  %cmp = icmp eq i64 %a, %b
  %sel = select i1 %cmp, i64 %a, i64 %b
  ret i64 %sel
}

; SEL-LABEL: @test_sel_i64ri
define i64 @test_sel_i64ri(i64 %a, i64 %b) {
; CHECK-LABEL: .64b @test_sel_i64ri(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.64b 	[[P_P0]], [[R64_D0]], [[R64_D1]];
; CHECK-NEXT: 	sel.64b 	[[R64_D2]], [[R64_D0]], 5, [[P_P0]];
; CHECK-NEXT: 	return [[R64_D2]];
  %cmp = icmp eq i64 %a, %b
  %sel = select i1 %cmp, i64 %a, i64 5
  ret i64 %sel
}

; SEL-LABEL: @test_sel_i64ir
define i64 @test_sel_i64ir(i64 %a, i64 %b) {
; CHECK-LABEL: .64b @test_sel_i64ir(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.64b 	[[P_P0]], [[R64_D0]], [[R64_D1]];
; CHECK-NEXT: 	sel.64b 	[[R64_D2]], 5, [[R64_D0]], [[P_P0]];
; CHECK-NEXT: 	return [[R64_D2]];
  %cmp = icmp eq i64 %a, %b
  %sel = select i1 %cmp, i64 5, i64 %a
  ret i64 %sel
}

; FIXME: Retain two immediate sources for minimal code sequence.
; SEL-LABEL: @test_sel_i64ii
define i64 @test_sel_i64ii(i64 %a, i64 %b) {
; CHECK-LABEL: .64b @test_sel_i64ii(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]], [[R64_D3:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.64b 	[[P_P0]], [[R64_D0]], [[R64_D1]];
; CHECK-NEXT: 	sel.64b 	[[R64_D2]], -1, 0, [[P_P0]];
; CHECK-NEXT: 	iadd.64b 	[[R64_D3]], [[R64_D2]], 6;
; CHECK-NEXT: 	return [[R64_D3]];
  %cmp = icmp eq i64 %a, %b
  %sel = select i1 %cmp, i64 5, i64 6
  ret i64 %sel
}

; SEL-LABEL: @test_sel_f16rr
define half @test_sel_f16rr(half %a, half %b) {
; CHECK-LABEL: .16b @test_sel_f16rr(
; CHECK-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_H2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fcmp.eq.hf 	[[P_P0]], [[R16_H0]], [[R16_H1]];
; CHECK-NEXT: 	sel.16b 	[[R16_H2]], [[R16_H0]], [[R16_H1]], [[P_P0]];
; CHECK-NEXT: 	return [[R16_H2]];
  %cmp = fcmp oeq half %a, %b
  %sel = select i1 %cmp, half %a, half %b
  ret half %sel
}

; SEL-LABEL: @test_sel_f16ri
define half @test_sel_f16ri(half %a, half %b) {
  %cmp = fcmp oeq half %a, %b
  %sel = select i1 %cmp, half %a, half 0xH3C00
  ret half %sel
}

; SEL-LABEL: @test_sel_f16ir
define half @test_sel_f16ir(half %a, half %b) {
  %cmp = fcmp oeq half %a, %b
  %sel = select i1 %cmp, half 0xH3C00, half %a
  ret half %sel
}

; SEL-LABEL: @test_sel_f16ii
define half @test_sel_f16ii(half %a, half %b) {
  %cmp = fcmp oeq half %a, %b
  %sel = select i1 %cmp, half 0xH3C00, half 0xH4A00
  ret half %sel
}

; SEL-LABEL: @test_sel_f32rr
define float @test_sel_f32rr(float %a, float %b) {
; CHECK-LABEL: .32b @test_sel_f32rr(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fcmp.eq.f 	[[P_P0]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	sel.32b 	[[R32_W2]], [[R32_W0]], [[R32_W1]], [[P_P0]];
; CHECK-NEXT: 	return [[R32_W2]];
  %cmp = fcmp oeq float %a, %b
  %sel = select i1 %cmp, float %a, float %b
  ret float %sel
}

; SEL-LABEL: @test_sel_f32ri
define float @test_sel_f32ri(float %a, float %b) {
  %cmp = fcmp oeq float %a, %b
  %sel = select i1 %cmp, float %a, float 5.000000e-01
  ret float %sel
}

; SEL-LABEL: @test_sel_f32ir
define float @test_sel_f32ir(float %a, float %b) {
  %cmp = fcmp oeq float %a, %b
  %sel = select i1 %cmp, float 5.000000e-01, float %a
  ret float %sel
}

; SEL-LABEL: @test_sel_f32ii
define float @test_sel_f32ii(float %a, float %b) {
  %cmp = fcmp oeq float %a, %b
  %sel = select i1 %cmp, float 5.000000e-01, float 2.000000e+00
  ret float %sel
}

; SEL-LABEL: @test_sel_f64rr
define double @test_sel_f64rr(double %a, double %b) {
; CHECK-LABEL: .64b @test_sel_f64rr(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	fcmp.eq.df 	[[P_P0]], [[R64_D0]], [[R64_D1]];
; CHECK-NEXT: 	sel.64b 	[[R64_D2]], [[R64_D0]], [[R64_D1]], [[P_P0]];
; CHECK-NEXT: 	return [[R64_D2]];
  %cmp = fcmp oeq double %a, %b
  %sel = select i1 %cmp, double %a, double %b
  ret double %sel
}

; SEL-LABEL: @test_sel_f64ri
define double @test_sel_f64ri(double %a, double %b) {
  %cmp = fcmp oeq double %a, %b
  %sel = select i1 %cmp, double %a, double 0x7FF0000000000000
  ret double %sel
}

; SEL-LABEL: @test_sel_f64ir
define double @test_sel_f64ir(double %a, double %b) {
  %cmp = fcmp oeq double %a, %b
  %sel = select i1 %cmp, double 0x7FF0000000000000, double %a
  ret double %sel
}

; SEL-LABEL: @test_sel_f64ii
define double @test_sel_f64ii(double %a, double %b) {
  %cmp = fcmp oeq double %a, %b
  %sel = select i1 %cmp, double 0x7FF0000000000000, double 0x8FF0000000000000
  ret double %sel
}

; SEL-LABEL: @test_sel_p0rr
define ptr addrspace(4) @test_sel_p0rr(ptr addrspace(4) %a, ptr addrspace(4) %b) {
; CHECK-LABEL: .32b @test_sel_p0rr(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.32b 	[[P_P0]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	sel.32b 	[[R32_W2]], [[R32_W0]], [[R32_W1]], [[P_P0]];
; CHECK-NEXT: 	return [[R32_W2]];
  %cmp = icmp eq ptr addrspace(4) %a, %b
  %sel = select i1 %cmp, ptr addrspace(4) %a, ptr addrspace(4) %b
  ret ptr addrspace(4) %sel
}

; SEL-LABEL: @test_sel_p1rr
define ptr addrspace(1) @test_sel_p1rr(ptr addrspace(1) %a, ptr addrspace(1) %b) {
; CHECK-LABEL: .64b @test_sel_p1rr(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.64b 	[[P_P0]], [[R64_D0]], [[R64_D1]];
; CHECK-NEXT: 	sel.64b 	[[R64_D2]], [[R64_D0]], [[R64_D1]], [[P_P0]];
; CHECK-NEXT: 	return [[R64_D2]];
  %cmp = icmp eq ptr addrspace(1) %a, %b
  %sel = select i1 %cmp, ptr addrspace(1) %a, ptr addrspace(1) %b
  ret ptr addrspace(1) %sel
}

; SEL-LABEL: @test_sel_p2rr
define ptr addrspace(2) @test_sel_p2rr(ptr addrspace(2) %a, ptr addrspace(2) %b) {
; CHECK-LABEL: .64b @test_sel_p2rr(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.64b 	[[P_P0]], [[R64_D0]], [[R64_D1]];
; CHECK-NEXT: 	sel.64b 	[[R64_D2]], [[R64_D0]], [[R64_D1]], [[P_P0]];
; CHECK-NEXT: 	return [[R64_D2]];
  %cmp = icmp eq ptr addrspace(2) %a, %b
  %sel = select i1 %cmp, ptr addrspace(2) %a, ptr addrspace(2) %b
  ret ptr addrspace(2) %sel
}

; SEL-LABEL: @test_sel_p3rr
define ptr addrspace(3) @test_sel_p3rr(ptr addrspace(3) %a, ptr addrspace(3) %b) {
; CHECK-LABEL: .32b @test_sel_p3rr(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.32b 	[[P_P0]], [[R32_W0]], [[R32_W1]];
; CHECK-NEXT: 	sel.32b 	[[R32_W2]], [[R32_W0]], [[R32_W1]], [[P_P0]];
; CHECK-NEXT: 	return [[R32_W2]];
  %cmp = icmp eq ptr addrspace(3) %a, %b
  %sel = select i1 %cmp, ptr addrspace(3) %a, ptr addrspace(3) %b
  ret ptr addrspace(3) %sel
}

; SEL-LABEL: @test_sel_p4rr
define ptr @test_sel_p4rr(ptr %a, ptr %b) {
; CHECK-LABEL: .64b @test_sel_p4rr(
; CHECK-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_D2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.pred [[P_P0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ucmp.eq.64b 	[[P_P0]], [[R64_D0]], [[R64_D1]];
; CHECK-NEXT: 	sel.64b 	[[R64_D2]], [[R64_D0]], [[R64_D1]], [[P_P0]];
; CHECK-NEXT: 	return [[R64_D2]];
  %cmp = icmp eq ptr %a, %b
  %sel = select i1 %cmp, ptr %a, ptr %b
  ret ptr %sel
}
