; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -march=pisa -verify-machineinstrs -o - | FileCheck %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

define <7 x i32> @test_add_i32_7(<7 x i32> %arg0 ,<7 x i32> %arg1) {
; O0-LABEL: .v7.32b @test_add_i32_7(
; O0-SAME: .reg .v7.32b [[VR7_32_V7W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v7.32b [[VR7_32_V7W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v7.32b %v7w<2~9>;
; O0-NEXT: 	.reg .32b %w<0~21>;
; O0: 	mov.32b 	%w0, [[VR7_32_V7W0]].x;
; O0-NEXT: 	mov.32b 	%w1, [[VR7_32_V7W0]].y;
; O0-NEXT: 	mov.32b 	%w2, [[VR7_32_V7W0]].z;
; O0-NEXT: 	mov.32b 	%w3, [[VR7_32_V7W0]].w;
; O0-NEXT: 	extract.4.32b 	%w4, [[VR7_32_V7W0]];
; O0-NEXT: 	extract.5.32b 	%w5, [[VR7_32_V7W0]];
; O0-NEXT: 	extract.6.32b 	%w6, [[VR7_32_V7W0]];
; O0-NEXT: 	mov.32b 	%w7, [[VR7_32_V7W1]].x;
; O0-NEXT: 	mov.32b 	%w8, [[VR7_32_V7W1]].y;
; O0-NEXT: 	mov.32b 	%w9, [[VR7_32_V7W1]].z;
; O0-NEXT: 	mov.32b 	%w10, [[VR7_32_V7W1]].w;
; O0-NEXT: 	extract.4.32b 	%w11, [[VR7_32_V7W1]];
; O0-NEXT: 	extract.5.32b 	%w12, [[VR7_32_V7W1]];
; O0-NEXT: 	extract.6.32b 	%w13, [[VR7_32_V7W1]];
; O0-NEXT: 	iadd.32b 	%w14, %w0, %w7;
; O0-NEXT: 	iadd.32b 	%w15, %w1, %w8;
; O0-NEXT: 	iadd.32b 	%w16, %w2, %w9;
; O0-NEXT: 	iadd.32b 	%w17, %w3, %w10;
; O0-NEXT: 	iadd.32b 	%w18, %w4, %w11;
; O0-NEXT: 	iadd.32b 	%w19, %w5, %w12;
; O0-NEXT: 	iadd.32b 	%w20, %w6, %w13;
; O0-NEXT: 	insert.0.32b 	%v7w2, %w14;
; O0-NEXT: 	extract.0.v7.32b 	%v7w3, %v7w2;
; O0-NEXT: 	insert.1.32b 	%v7w3, %w15;
; O0-NEXT: 	extract.0.v7.32b 	%v7w4, %v7w3;
; O0-NEXT: 	insert.2.32b 	%v7w4, %w16;
; O0-NEXT: 	extract.0.v7.32b 	%v7w5, %v7w4;
; O0-NEXT: 	insert.3.32b 	%v7w5, %w17;
; O0-NEXT: 	extract.0.v7.32b 	%v7w6, %v7w5;
; O0-NEXT: 	insert.4.32b 	%v7w6, %w18;
; O0-NEXT: 	extract.0.v7.32b 	%v7w7, %v7w6;
; O0-NEXT: 	insert.5.32b 	%v7w7, %w19;
; O0-NEXT: 	extract.0.v7.32b 	%v7w8, %v7w7;
; O0-NEXT: 	insert.6.32b 	%v7w8, %w20;
; O0-NEXT: 	return %v7w8;
;
; CHECK-LABEL: .v7.32b @test_add_i32_7(
; CHECK-SAME: .reg .v7.32b [[VR7_32_V7W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v7.32b [[VR7_32_V7W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v7.32b [[VR7_32_V7W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .32b %w<0~13>;
; CHECK: 	extract.4.32b 	%w0, [[VR7_32_V7W0]];
; CHECK-NEXT: 	extract.5.32b 	%w1, [[VR7_32_V7W0]];
; CHECK-NEXT: 	extract.6.32b 	%w2, [[VR7_32_V7W0]];
; CHECK-NEXT: 	extract.4.32b 	%w3, [[VR7_32_V7W1]];
; CHECK-NEXT: 	extract.5.32b 	%w4, [[VR7_32_V7W1]];
; CHECK-NEXT: 	extract.6.32b 	%w5, [[VR7_32_V7W1]];
; CHECK-NEXT: 	iadd.32b 	%w6, [[VR7_32_V7W0]].x, [[VR7_32_V7W1]].x;
; CHECK-NEXT: 	iadd.32b 	%w7, [[VR7_32_V7W0]].y, [[VR7_32_V7W1]].y;
; CHECK-NEXT: 	iadd.32b 	%w8, [[VR7_32_V7W0]].z, [[VR7_32_V7W1]].z;
; CHECK-NEXT: 	iadd.32b 	%w9, [[VR7_32_V7W0]].w, [[VR7_32_V7W1]].w;
; CHECK-NEXT: 	iadd.32b 	%w10, %w0, %w3;
; CHECK-NEXT: 	iadd.32b 	%w11, %w1, %w4;
; CHECK-NEXT: 	iadd.32b 	%w12, %w2, %w5;
; CHECK-NEXT: 	insert.0.32b 	[[VR7_32_V7W2]], %w6;
; CHECK-NEXT: 	insert.1.32b 	[[VR7_32_V7W2]], %w7;
; CHECK-NEXT: 	insert.2.32b 	[[VR7_32_V7W2]], %w8;
; CHECK-NEXT: 	insert.3.32b 	[[VR7_32_V7W2]], %w9;
; CHECK-NEXT: 	insert.4.32b 	[[VR7_32_V7W2]], %w10;
; CHECK-NEXT: 	insert.5.32b 	[[VR7_32_V7W2]], %w11;
; CHECK-NEXT: 	insert.6.32b 	[[VR7_32_V7W2]], %w12;
; CHECK-NEXT: 	return [[VR7_32_V7W2]];
  %res = add <7 x i32> %arg0, %arg1
  ret <7 x i32> %res
}

define <8 x i32> @test_add_i32_8(<8 x i32> %arg0 ,<8 x i32> %arg1) {
; O0-LABEL: .v8.32b @test_add_i32_8(
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v4.32b %v4w<0~12>;
; O0-NEXT: 	.reg .32b %w<0~24>;
; O0: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; O0-NEXT: 	mov.32b 	%w0, %v4w0.x;
; O0-NEXT: 	mov.32b 	%w1, %v4w0.y;
; O0-NEXT: 	mov.32b 	%w2, %v4w0.z;
; O0-NEXT: 	mov.32b 	%w3, %v4w0.w;
; O0-NEXT: 	mov.32b 	%w4, %v4w2.x;
; O0-NEXT: 	mov.32b 	%w5, %v4w2.y;
; O0-NEXT: 	mov.32b 	%w6, %v4w2.z;
; O0-NEXT: 	mov.32b 	%w7, %v4w2.w;
; O0-NEXT: 	iadd.32b 	%w8, %w0, %w4;
; O0-NEXT: 	iadd.32b 	%w9, %w1, %w5;
; O0-NEXT: 	iadd.32b 	%w10, %w2, %w6;
; O0-NEXT: 	iadd.32b 	%w11, %w3, %w7;
; O0-NEXT: 	mov.32b 	%v4w4.x, %w8;
; O0-NEXT: 	mov.128b 	%v4w5.xyzw, %v4w4.xyzw;
; O0-NEXT: 	mov.32b 	%v4w5.y, %w9;
; O0-NEXT: 	mov.128b 	%v4w6.xyzw, %v4w5.xyzw;
; O0-NEXT: 	mov.32b 	%v4w6.z, %w10;
; O0-NEXT: 	mov.128b 	%v4w7.xyzw, %v4w6.xyzw;
; O0-NEXT: 	mov.32b 	%v4w7.w, %w11;
; O0-NEXT: 	mov.32b 	%w12, %v4w1.x;
; O0-NEXT: 	mov.32b 	%w13, %v4w1.y;
; O0-NEXT: 	mov.32b 	%w14, %v4w1.z;
; O0-NEXT: 	mov.32b 	%w15, %v4w1.w;
; O0-NEXT: 	mov.32b 	%w16, %v4w3.x;
; O0-NEXT: 	mov.32b 	%w17, %v4w3.y;
; O0-NEXT: 	mov.32b 	%w18, %v4w3.z;
; O0-NEXT: 	mov.32b 	%w19, %v4w3.w;
; O0-NEXT: 	iadd.32b 	%w20, %w12, %w16;
; O0-NEXT: 	iadd.32b 	%w21, %w13, %w17;
; O0-NEXT: 	iadd.32b 	%w22, %w14, %w18;
; O0-NEXT: 	iadd.32b 	%w23, %w15, %w19;
; O0-NEXT: 	mov.32b 	%v4w8.x, %w20;
; O0-NEXT: 	mov.128b 	%v4w9.xyzw, %v4w8.xyzw;
; O0-NEXT: 	mov.32b 	%v4w9.y, %w21;
; O0-NEXT: 	mov.128b 	%v4w10.xyzw, %v4w9.xyzw;
; O0-NEXT: 	mov.32b 	%v4w10.z, %w22;
; O0-NEXT: 	mov.128b 	%v4w11.xyzw, %v4w10.xyzw;
; O0-NEXT: 	mov.32b 	%v4w11.w, %w23;
; O0-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W2]], %v4w7;
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W3]], [[VR8_32_V8W2]];
; O0-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W3]], %v4w11;
; O0-NEXT: 	return [[VR8_32_V8W3]];
;
; CHECK-LABEL: .v8.32b @test_add_i32_8(
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.32b %v4w<0~6>;
; CHECK: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; CHECK-NEXT: 	iadd.32b 	%v4w4.x, %v4w0.x, %v4w2.x;
; CHECK-NEXT: 	iadd.32b 	%v4w4.y, %v4w0.y, %v4w2.y;
; CHECK-NEXT: 	iadd.32b 	%v4w4.z, %v4w0.z, %v4w2.z;
; CHECK-NEXT: 	iadd.32b 	%v4w4.w, %v4w0.w, %v4w2.w;
; CHECK-NEXT: 	iadd.32b 	%v4w5.x, %v4w1.x, %v4w3.x;
; CHECK-NEXT: 	iadd.32b 	%v4w5.y, %v4w1.y, %v4w3.y;
; CHECK-NEXT: 	iadd.32b 	%v4w5.z, %v4w1.z, %v4w3.z;
; CHECK-NEXT: 	iadd.32b 	%v4w5.w, %v4w1.w, %v4w3.w;
; CHECK-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W2]], %v4w4;
; CHECK-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W2]], %v4w5;
; CHECK-NEXT: 	return [[VR8_32_V8W2]];
  %res = add <8 x i32> %arg0, %arg1
  ret <8 x i32> %res
}

define <8 x i32> @test_mul_i32_8(<8 x i32> %arg0 ,<8 x i32> %arg1) {
; O0-LABEL: .v8.32b @test_mul_i32_8(
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v4.32b %v4w<0~12>;
; O0-NEXT: 	.reg .32b %w<0~24>;
; O0: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; O0-NEXT: 	mov.32b 	%w0, %v4w0.x;
; O0-NEXT: 	mov.32b 	%w1, %v4w0.y;
; O0-NEXT: 	mov.32b 	%w2, %v4w0.z;
; O0-NEXT: 	mov.32b 	%w3, %v4w0.w;
; O0-NEXT: 	mov.32b 	%w4, %v4w2.x;
; O0-NEXT: 	mov.32b 	%w5, %v4w2.y;
; O0-NEXT: 	mov.32b 	%w6, %v4w2.z;
; O0-NEXT: 	mov.32b 	%w7, %v4w2.w;
; O0-NEXT: 	smul.32b 	%w8, %w0, %w4;
; O0-NEXT: 	smul.32b 	%w9, %w1, %w5;
; O0-NEXT: 	smul.32b 	%w10, %w2, %w6;
; O0-NEXT: 	smul.32b 	%w11, %w3, %w7;
; O0-NEXT: 	mov.32b 	%v4w4.x, %w8;
; O0-NEXT: 	mov.128b 	%v4w5.xyzw, %v4w4.xyzw;
; O0-NEXT: 	mov.32b 	%v4w5.y, %w9;
; O0-NEXT: 	mov.128b 	%v4w6.xyzw, %v4w5.xyzw;
; O0-NEXT: 	mov.32b 	%v4w6.z, %w10;
; O0-NEXT: 	mov.128b 	%v4w7.xyzw, %v4w6.xyzw;
; O0-NEXT: 	mov.32b 	%v4w7.w, %w11;
; O0-NEXT: 	mov.32b 	%w12, %v4w1.x;
; O0-NEXT: 	mov.32b 	%w13, %v4w1.y;
; O0-NEXT: 	mov.32b 	%w14, %v4w1.z;
; O0-NEXT: 	mov.32b 	%w15, %v4w1.w;
; O0-NEXT: 	mov.32b 	%w16, %v4w3.x;
; O0-NEXT: 	mov.32b 	%w17, %v4w3.y;
; O0-NEXT: 	mov.32b 	%w18, %v4w3.z;
; O0-NEXT: 	mov.32b 	%w19, %v4w3.w;
; O0-NEXT: 	smul.32b 	%w20, %w12, %w16;
; O0-NEXT: 	smul.32b 	%w21, %w13, %w17;
; O0-NEXT: 	smul.32b 	%w22, %w14, %w18;
; O0-NEXT: 	smul.32b 	%w23, %w15, %w19;
; O0-NEXT: 	mov.32b 	%v4w8.x, %w20;
; O0-NEXT: 	mov.128b 	%v4w9.xyzw, %v4w8.xyzw;
; O0-NEXT: 	mov.32b 	%v4w9.y, %w21;
; O0-NEXT: 	mov.128b 	%v4w10.xyzw, %v4w9.xyzw;
; O0-NEXT: 	mov.32b 	%v4w10.z, %w22;
; O0-NEXT: 	mov.128b 	%v4w11.xyzw, %v4w10.xyzw;
; O0-NEXT: 	mov.32b 	%v4w11.w, %w23;
; O0-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W2]], %v4w7;
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W3]], [[VR8_32_V8W2]];
; O0-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W3]], %v4w11;
; O0-NEXT: 	return [[VR8_32_V8W3]];
;
; CHECK-LABEL: .v8.32b @test_mul_i32_8(
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.32b %v4w<0~6>;
; CHECK: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; CHECK-NEXT: 	smul.32b 	%v4w4.x, %v4w0.x, %v4w2.x;
; CHECK-NEXT: 	smul.32b 	%v4w4.y, %v4w0.y, %v4w2.y;
; CHECK-NEXT: 	smul.32b 	%v4w4.z, %v4w0.z, %v4w2.z;
; CHECK-NEXT: 	smul.32b 	%v4w4.w, %v4w0.w, %v4w2.w;
; CHECK-NEXT: 	smul.32b 	%v4w5.x, %v4w1.x, %v4w3.x;
; CHECK-NEXT: 	smul.32b 	%v4w5.y, %v4w1.y, %v4w3.y;
; CHECK-NEXT: 	smul.32b 	%v4w5.z, %v4w1.z, %v4w3.z;
; CHECK-NEXT: 	smul.32b 	%v4w5.w, %v4w1.w, %v4w3.w;
; CHECK-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W2]], %v4w4;
; CHECK-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W2]], %v4w5;
; CHECK-NEXT: 	return [[VR8_32_V8W2]];
  %res = mul <8 x i32> %arg0, %arg1
  ret <8 x i32> %res
}

define <9 x i32> @test_xor_i32_9(<9 x i32> %arg0, <9 x i32> %arg1) {
; O0-LABEL: void @test_xor_i32_9(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b %w<3~30>;
; O0-NEXT: 	.reg .v8.32b %v8w<0~10>;
; O0: 	ld.private.v8.32b	 %v8w0, [[[R32_W0]]];
; O0-NEXT: 	ld.private.32b	 %w3, [[[R32_W0]] + 32];
; O0-NEXT: 	mov.32b 	%w4, %v8w0.x;
; O0-NEXT: 	mov.32b 	%w5, %v8w0.y;
; O0-NEXT: 	mov.32b 	%w6, %v8w0.z;
; O0-NEXT: 	mov.32b 	%w7, %v8w0.w;
; O0-NEXT: 	extract.4.32b 	%w8, %v8w0;
; O0-NEXT: 	extract.5.32b 	%w9, %v8w0;
; O0-NEXT: 	extract.6.32b 	%w10, %v8w0;
; O0-NEXT: 	extract.7.32b 	%w11, %v8w0;
; O0-NEXT: 	ld.private.v8.32b	 %v8w1, [[[R32_W1]]];
; O0-NEXT: 	ld.private.32b	 %w12, [[[R32_W1]] + 32];
; O0-NEXT: 	mov.32b 	%w13, %v8w1.x;
; O0-NEXT: 	mov.32b 	%w14, %v8w1.y;
; O0-NEXT: 	mov.32b 	%w15, %v8w1.z;
; O0-NEXT: 	mov.32b 	%w16, %v8w1.w;
; O0-NEXT: 	extract.4.32b 	%w17, %v8w1;
; O0-NEXT: 	extract.5.32b 	%w18, %v8w1;
; O0-NEXT: 	extract.6.32b 	%w19, %v8w1;
; O0-NEXT: 	extract.7.32b 	%w20, %v8w1;
; O0-NEXT: 	xor.32b 	%w21, %w4, %w13;
; O0-NEXT: 	xor.32b 	%w22, %w5, %w14;
; O0-NEXT: 	xor.32b 	%w23, %w6, %w15;
; O0-NEXT: 	xor.32b 	%w24, %w7, %w16;
; O0-NEXT: 	xor.32b 	%w25, %w8, %w17;
; O0-NEXT: 	xor.32b 	%w26, %w9, %w18;
; O0-NEXT: 	xor.32b 	%w27, %w10, %w19;
; O0-NEXT: 	xor.32b 	%w28, %w11, %w20;
; O0-NEXT: 	xor.32b 	%w29, %w3, %w12;
; O0-NEXT: 	insert.0.32b 	%v8w2, %w21;
; O0-NEXT: 	extract.0.v8.32b 	%v8w3, %v8w2;
; O0-NEXT: 	insert.1.32b 	%v8w3, %w22;
; O0-NEXT: 	extract.0.v8.32b 	%v8w4, %v8w3;
; O0-NEXT: 	insert.2.32b 	%v8w4, %w23;
; O0-NEXT: 	extract.0.v8.32b 	%v8w5, %v8w4;
; O0-NEXT: 	insert.3.32b 	%v8w5, %w24;
; O0-NEXT: 	extract.0.v8.32b 	%v8w6, %v8w5;
; O0-NEXT: 	insert.4.32b 	%v8w6, %w25;
; O0-NEXT: 	extract.0.v8.32b 	%v8w7, %v8w6;
; O0-NEXT: 	insert.5.32b 	%v8w7, %w26;
; O0-NEXT: 	extract.0.v8.32b 	%v8w8, %v8w7;
; O0-NEXT: 	insert.6.32b 	%v8w8, %w27;
; O0-NEXT: 	extract.0.v8.32b 	%v8w9, %v8w8;
; O0-NEXT: 	insert.7.32b 	%v8w9, %w28;
; O0-NEXT: 	st.private.v8.32b	 [[[R32_W2]]], %v8w9;
; O0-NEXT: 	st.private.32b	 [[[R32_W2]] + 32], %w29;
; O0-NEXT: 	return;
;
; CHECK-LABEL: void @test_xor_i32_9(
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W2:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b %w<3~22>;
; CHECK-NEXT: 	.reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]];
; CHECK: 	ld.private.v8.32b	 [[VR8_32_V8W0]], [[[R32_W0]]];
; CHECK-NEXT: 	ld.private.32b	 %w3, [[[R32_W0]] + 32];
; CHECK-NEXT: 	extract.4.32b 	%w4, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.5.32b 	%w5, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.6.32b 	%w6, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.7.32b 	%w7, [[VR8_32_V8W0]];
; CHECK-NEXT: 	ld.private.v8.32b	 [[VR8_32_V8W1]], [[[R32_W1]]];
; CHECK-NEXT: 	ld.private.32b	 %w8, [[[R32_W1]] + 32];
; CHECK-NEXT: 	extract.4.32b 	%w9, [[VR8_32_V8W1]];
; CHECK-NEXT: 	extract.5.32b 	%w10, [[VR8_32_V8W1]];
; CHECK-NEXT: 	extract.6.32b 	%w11, [[VR8_32_V8W1]];
; CHECK-NEXT: 	extract.7.32b 	%w12, [[VR8_32_V8W1]];
; CHECK-NEXT: 	xor.32b 	%w13, [[VR8_32_V8W0]].x, [[VR8_32_V8W1]].x;
; CHECK-NEXT: 	xor.32b 	%w14, [[VR8_32_V8W0]].y, [[VR8_32_V8W1]].y;
; CHECK-NEXT: 	xor.32b 	%w15, [[VR8_32_V8W0]].z, [[VR8_32_V8W1]].z;
; CHECK-NEXT: 	xor.32b 	%w16, [[VR8_32_V8W0]].w, [[VR8_32_V8W1]].w;
; CHECK-NEXT: 	xor.32b 	%w17, %w4, %w9;
; CHECK-NEXT: 	xor.32b 	%w18, %w5, %w10;
; CHECK-NEXT: 	xor.32b 	%w19, %w6, %w11;
; CHECK-NEXT: 	xor.32b 	%w20, %w7, %w12;
; CHECK-NEXT: 	xor.32b 	%w21, %w3, %w8;
; CHECK-NEXT: 	insert.0.32b 	[[VR8_32_V8W2]], %w13;
; CHECK-NEXT: 	insert.1.32b 	[[VR8_32_V8W2]], %w14;
; CHECK-NEXT: 	insert.2.32b 	[[VR8_32_V8W2]], %w15;
; CHECK-NEXT: 	insert.3.32b 	[[VR8_32_V8W2]], %w16;
; CHECK-NEXT: 	insert.4.32b 	[[VR8_32_V8W2]], %w17;
; CHECK-NEXT: 	insert.5.32b 	[[VR8_32_V8W2]], %w18;
; CHECK-NEXT: 	insert.6.32b 	[[VR8_32_V8W2]], %w19;
; CHECK-NEXT: 	insert.7.32b 	[[VR8_32_V8W2]], %w20;
; CHECK-NEXT: 	st.private.v8.32b	 [[[R32_W2]]], [[VR8_32_V8W2]];
; CHECK-NEXT: 	st.private.32b	 [[[R32_W2]] + 32], %w21;
; CHECK-NEXT: 	return;
  %res = xor <9 x i32> %arg0, %arg1

  ret <9 x i32> %res
}

define <8 x i32> @test_sub_i32_8(<8 x i32> %arg0 ,<8 x i32> %arg1, ptr addrspace(4) noundef %0) {
; O0-LABEL: .v8.32b @test_sub_i32_8(
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<1~25>;
; O0-NEXT: 	.reg .v4.32b %v4w<0~12>;
; O0: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; O0-NEXT: 	mov.32b 	%w1, %v4w0.x;
; O0-NEXT: 	mov.32b 	%w2, %v4w0.y;
; O0-NEXT: 	mov.32b 	%w3, %v4w0.z;
; O0-NEXT: 	mov.32b 	%w4, %v4w0.w;
; O0-NEXT: 	mov.32b 	%w5, %v4w2.x;
; O0-NEXT: 	mov.32b 	%w6, %v4w2.y;
; O0-NEXT: 	mov.32b 	%w7, %v4w2.z;
; O0-NEXT: 	mov.32b 	%w8, %v4w2.w;
; O0-NEXT: 	isub.32b 	%w9, %w1, %w5;
; O0-NEXT: 	isub.32b 	%w10, %w2, %w6;
; O0-NEXT: 	isub.32b 	%w11, %w3, %w7;
; O0-NEXT: 	isub.32b 	%w12, %w4, %w8;
; O0-NEXT: 	mov.32b 	%v4w4.x, %w9;
; O0-NEXT: 	mov.128b 	%v4w5.xyzw, %v4w4.xyzw;
; O0-NEXT: 	mov.32b 	%v4w5.y, %w10;
; O0-NEXT: 	mov.128b 	%v4w6.xyzw, %v4w5.xyzw;
; O0-NEXT: 	mov.32b 	%v4w6.z, %w11;
; O0-NEXT: 	mov.128b 	%v4w7.xyzw, %v4w6.xyzw;
; O0-NEXT: 	mov.32b 	%v4w7.w, %w12;
; O0-NEXT: 	mov.32b 	%w13, %v4w1.x;
; O0-NEXT: 	mov.32b 	%w14, %v4w1.y;
; O0-NEXT: 	mov.32b 	%w15, %v4w1.z;
; O0-NEXT: 	mov.32b 	%w16, %v4w1.w;
; O0-NEXT: 	mov.32b 	%w17, %v4w3.x;
; O0-NEXT: 	mov.32b 	%w18, %v4w3.y;
; O0-NEXT: 	mov.32b 	%w19, %v4w3.z;
; O0-NEXT: 	mov.32b 	%w20, %v4w3.w;
; O0-NEXT: 	isub.32b 	%w21, %w13, %w17;
; O0-NEXT: 	isub.32b 	%w22, %w14, %w18;
; O0-NEXT: 	isub.32b 	%w23, %w15, %w19;
; O0-NEXT: 	isub.32b 	%w24, %w16, %w20;
; O0-NEXT: 	mov.32b 	%v4w8.x, %w21;
; O0-NEXT: 	mov.128b 	%v4w9.xyzw, %v4w8.xyzw;
; O0-NEXT: 	mov.32b 	%v4w9.y, %w22;
; O0-NEXT: 	mov.128b 	%v4w10.xyzw, %v4w9.xyzw;
; O0-NEXT: 	mov.32b 	%v4w10.z, %w23;
; O0-NEXT: 	mov.128b 	%v4w11.xyzw, %v4w10.xyzw;
; O0-NEXT: 	mov.32b 	%v4w11.w, %w24;
; O0-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W2]], %v4w7;
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W3]], [[VR8_32_V8W2]];
; O0-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W3]], %v4w11;
; O0-NEXT: 	st.private.v8.32b	 [[[R32_W0]]], [[VR8_32_V8W3]];
; O0-NEXT: 	return [[VR8_32_V8W3]];
;
; CHECK-LABEL: .v8.32b @test_sub_i32_8(
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.32b %v4w<0~6>;
; CHECK: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; CHECK-NEXT: 	isub.32b 	%v4w4.x, %v4w0.x, %v4w2.x;
; CHECK-NEXT: 	isub.32b 	%v4w4.y, %v4w0.y, %v4w2.y;
; CHECK-NEXT: 	isub.32b 	%v4w4.z, %v4w0.z, %v4w2.z;
; CHECK-NEXT: 	isub.32b 	%v4w4.w, %v4w0.w, %v4w2.w;
; CHECK-NEXT: 	isub.32b 	%v4w5.x, %v4w1.x, %v4w3.x;
; CHECK-NEXT: 	isub.32b 	%v4w5.y, %v4w1.y, %v4w3.y;
; CHECK-NEXT: 	isub.32b 	%v4w5.z, %v4w1.z, %v4w3.z;
; CHECK-NEXT: 	isub.32b 	%v4w5.w, %v4w1.w, %v4w3.w;
; CHECK-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W2]], %v4w4;
; CHECK-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W2]], %v4w5;
; CHECK-NEXT: 	st.private.v8.32b	 [[[R32_W0]]], [[VR8_32_V8W2]];
; CHECK-NEXT: 	return [[VR8_32_V8W2]];
  %res = sub <8 x i32> %arg0, %arg1
  store <8 x i32> %res, ptr addrspace(4) %0, align 4
  ret <8 x i32> %res
}

define <8 x i32> @test_smad_i32_8(<8 x i32> %arg0 ,<8 x i32> %arg1, <8 x i32> %arg2, <8 x i32> %arg3) {
; O0-LABEL: .v8.32b @test_smad_i32_8(
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W3:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v8.32b [[VR8_32_V8W4:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W5:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v4.32b %v4w<0~16>;
; O0-NEXT: 	.reg .32b %w<0~48>;
; O0: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; O0-NEXT: 	mov.32b 	%w0, %v4w0.x;
; O0-NEXT: 	mov.32b 	%w1, %v4w0.y;
; O0-NEXT: 	mov.32b 	%w2, %v4w0.z;
; O0-NEXT: 	mov.32b 	%w3, %v4w0.w;
; O0-NEXT: 	mov.32b 	%w4, %v4w2.x;
; O0-NEXT: 	mov.32b 	%w5, %v4w2.y;
; O0-NEXT: 	mov.32b 	%w6, %v4w2.z;
; O0-NEXT: 	mov.32b 	%w7, %v4w2.w;
; O0-NEXT: 	mov.32b 	%w8, %v4w1.x;
; O0-NEXT: 	mov.32b 	%w9, %v4w1.y;
; O0-NEXT: 	mov.32b 	%w10, %v4w1.z;
; O0-NEXT: 	mov.32b 	%w11, %v4w1.w;
; O0-NEXT: 	mov.32b 	%w12, %v4w3.x;
; O0-NEXT: 	mov.32b 	%w13, %v4w3.y;
; O0-NEXT: 	mov.32b 	%w14, %v4w3.z;
; O0-NEXT: 	mov.32b 	%w15, %v4w3.w;
; O0-NEXT: 	extract.0.v4.32b 	%v4w4, [[VR8_32_V8W2]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w5, [[VR8_32_V8W2]];
; O0-NEXT: 	mov.32b 	%w16, %v4w4.x;
; O0-NEXT: 	mov.32b 	%w17, %v4w4.y;
; O0-NEXT: 	mov.32b 	%w18, %v4w4.z;
; O0-NEXT: 	mov.32b 	%w19, %v4w4.w;
; O0-NEXT: 	smad.32b 	%w20, %w0, %w4, %w16;
; O0-NEXT: 	smad.32b 	%w21, %w1, %w5, %w17;
; O0-NEXT: 	smad.32b 	%w22, %w2, %w6, %w18;
; O0-NEXT: 	smad.32b 	%w23, %w3, %w7, %w19;
; O0-NEXT: 	mov.32b 	%w24, %v4w5.x;
; O0-NEXT: 	mov.32b 	%w25, %v4w5.y;
; O0-NEXT: 	mov.32b 	%w26, %v4w5.z;
; O0-NEXT: 	mov.32b 	%w27, %v4w5.w;
; O0-NEXT: 	smad.32b 	%w28, %w8, %w12, %w24;
; O0-NEXT: 	smad.32b 	%w29, %w9, %w13, %w25;
; O0-NEXT: 	smad.32b 	%w30, %w10, %w14, %w26;
; O0-NEXT: 	smad.32b 	%w31, %w11, %w15, %w27;
; O0-NEXT: 	extract.0.v4.32b 	%v4w6, [[VR8_32_V8W3]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w7, [[VR8_32_V8W3]];
; O0-NEXT: 	mov.32b 	%w32, %v4w6.x;
; O0-NEXT: 	mov.32b 	%w33, %v4w6.y;
; O0-NEXT: 	mov.32b 	%w34, %v4w6.z;
; O0-NEXT: 	mov.32b 	%w35, %v4w6.w;
; O0-NEXT: 	smul.32b 	%w36, %w20, %w32;
; O0-NEXT: 	smul.32b 	%w37, %w21, %w33;
; O0-NEXT: 	smul.32b 	%w38, %w22, %w34;
; O0-NEXT: 	smul.32b 	%w39, %w23, %w35;
; O0-NEXT: 	mov.32b 	%v4w8.x, %w36;
; O0-NEXT: 	mov.128b 	%v4w9.xyzw, %v4w8.xyzw;
; O0-NEXT: 	mov.32b 	%v4w9.y, %w37;
; O0-NEXT: 	mov.128b 	%v4w10.xyzw, %v4w9.xyzw;
; O0-NEXT: 	mov.32b 	%v4w10.z, %w38;
; O0-NEXT: 	mov.128b 	%v4w11.xyzw, %v4w10.xyzw;
; O0-NEXT: 	mov.32b 	%v4w11.w, %w39;
; O0-NEXT: 	mov.32b 	%w40, %v4w7.x;
; O0-NEXT: 	mov.32b 	%w41, %v4w7.y;
; O0-NEXT: 	mov.32b 	%w42, %v4w7.z;
; O0-NEXT: 	mov.32b 	%w43, %v4w7.w;
; O0-NEXT: 	smul.32b 	%w44, %w28, %w40;
; O0-NEXT: 	smul.32b 	%w45, %w29, %w41;
; O0-NEXT: 	smul.32b 	%w46, %w30, %w42;
; O0-NEXT: 	smul.32b 	%w47, %w31, %w43;
; O0-NEXT: 	mov.32b 	%v4w12.x, %w44;
; O0-NEXT: 	mov.128b 	%v4w13.xyzw, %v4w12.xyzw;
; O0-NEXT: 	mov.32b 	%v4w13.y, %w45;
; O0-NEXT: 	mov.128b 	%v4w14.xyzw, %v4w13.xyzw;
; O0-NEXT: 	mov.32b 	%v4w14.z, %w46;
; O0-NEXT: 	mov.128b 	%v4w15.xyzw, %v4w14.xyzw;
; O0-NEXT: 	mov.32b 	%v4w15.w, %w47;
; O0-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W4]], %v4w11;
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W5]], [[VR8_32_V8W4]];
; O0-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W5]], %v4w15;
; O0-NEXT: 	return [[VR8_32_V8W5]];
;
; CHECK-LABEL: .v8.32b @test_smad_i32_8(
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W3:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v8.32b [[VR8_32_V8W4:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.32b %v4w<0~10>;
; CHECK-NEXT: 	.reg .32b %w<0~8>;
; CHECK: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; CHECK-NEXT: 	extract.0.v4.32b 	%v4w4, [[VR8_32_V8W2]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w5, [[VR8_32_V8W2]];
; CHECK-NEXT: 	smad.32b 	%w0, %v4w0.x, %v4w2.x, %v4w4.x;
; CHECK-NEXT: 	smad.32b 	%w1, %v4w0.y, %v4w2.y, %v4w4.y;
; CHECK-NEXT: 	smad.32b 	%w2, %v4w0.z, %v4w2.z, %v4w4.z;
; CHECK-NEXT: 	smad.32b 	%w3, %v4w0.w, %v4w2.w, %v4w4.w;
; CHECK-NEXT: 	smad.32b 	%w4, %v4w1.x, %v4w3.x, %v4w5.x;
; CHECK-NEXT: 	smad.32b 	%w5, %v4w1.y, %v4w3.y, %v4w5.y;
; CHECK-NEXT: 	smad.32b 	%w6, %v4w1.z, %v4w3.z, %v4w5.z;
; CHECK-NEXT: 	smad.32b 	%w7, %v4w1.w, %v4w3.w, %v4w5.w;
; CHECK-NEXT: 	extract.0.v4.32b 	%v4w6, [[VR8_32_V8W3]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w7, [[VR8_32_V8W3]];
; CHECK-NEXT: 	smul.32b 	%v4w8.x, %w0, %v4w6.x;
; CHECK-NEXT: 	smul.32b 	%v4w8.y, %w1, %v4w6.y;
; CHECK-NEXT: 	smul.32b 	%v4w8.z, %w2, %v4w6.z;
; CHECK-NEXT: 	smul.32b 	%v4w8.w, %w3, %v4w6.w;
; CHECK-NEXT: 	smul.32b 	%v4w9.x, %w4, %v4w7.x;
; CHECK-NEXT: 	smul.32b 	%v4w9.y, %w5, %v4w7.y;
; CHECK-NEXT: 	smul.32b 	%v4w9.z, %w6, %v4w7.z;
; CHECK-NEXT: 	smul.32b 	%v4w9.w, %w7, %v4w7.w;
; CHECK-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W4]], %v4w8;
; CHECK-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W4]], %v4w9;
; CHECK-NEXT: 	return [[VR8_32_V8W4]];
  %1 = mul <8 x i32> %arg0, %arg1
  %2 = add <8 x i32> %1, %arg2
  %3 = mul <8 x i32> %2, %arg3
  ret <8 x i32> %3
}
define <8 x i64> @test_zext_i32_8(<8 x i32>%arg0) {
; O0-LABEL: .v16.32b @test_zext_i32_8(
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .32b %w<0~8>;
; O0-NEXT: 	.reg .64b %d<0~8>;
; O0-NEXT: 	.reg .v2.32b %v2w<0~8>;
; O0-NEXT: 	.reg .v16.32b %v16w<0~8>;
; O0: 	extract.0.v4.32b 	[[VR4_32_V4W0]], [[VR8_32_V8W0]];
; O0-NEXT: 	extract.4.v4.32b 	[[VR4_32_V4W1]], [[VR8_32_V8W0]];
; O0-NEXT: 	mov.32b 	%w0, [[VR4_32_V4W0]].x;
; O0-NEXT: 	mov.32b 	%w1, [[VR4_32_V4W0]].y;
; O0-NEXT: 	mov.32b 	%w2, [[VR4_32_V4W0]].z;
; O0-NEXT: 	mov.32b 	%w3, [[VR4_32_V4W0]].w;
; O0-NEXT: 	zext.64b.32b 	%d0, %w0;
; O0-NEXT: 	zext.64b.32b 	%d1, %w1;
; O0-NEXT: 	zext.64b.32b 	%d2, %w2;
; O0-NEXT: 	zext.64b.32b 	%d3, %w3;
; O0-NEXT: 	mov.32b 	%w4, [[VR4_32_V4W1]].x;
; O0-NEXT: 	mov.32b 	%w5, [[VR4_32_V4W1]].y;
; O0-NEXT: 	mov.32b 	%w6, [[VR4_32_V4W1]].z;
; O0-NEXT: 	mov.32b 	%w7, [[VR4_32_V4W1]].w;
; O0-NEXT: 	zext.64b.32b 	%d4, %w4;
; O0-NEXT: 	zext.64b.32b 	%d5, %w5;
; O0-NEXT: 	zext.64b.32b 	%d6, %w6;
; O0-NEXT: 	zext.64b.32b 	%d7, %w7;
; O0-NEXT: 	mov.64b 	%v2w0.xy, %d0;
; O0-NEXT: 	mov.64b 	%v2w1.xy, %d1;
; O0-NEXT: 	mov.64b 	%v2w2.xy, %d2;
; O0-NEXT: 	mov.64b 	%v2w3.xy, %d3;
; O0-NEXT: 	mov.64b 	%v2w4.xy, %d4;
; O0-NEXT: 	mov.64b 	%v2w5.xy, %d5;
; O0-NEXT: 	mov.64b 	%v2w6.xy, %d6;
; O0-NEXT: 	mov.64b 	%v2w7.xy, %d7;
; O0-NEXT: 	insert.0.v2.32b 	%v16w0, %v2w0;
; O0-NEXT: 	extract.0.v16.32b 	%v16w1, %v16w0;
; O0-NEXT: 	insert.2.v2.32b 	%v16w1, %v2w1;
; O0-NEXT: 	extract.0.v16.32b 	%v16w2, %v16w1;
; O0-NEXT: 	insert.4.v2.32b 	%v16w2, %v2w2;
; O0-NEXT: 	extract.0.v16.32b 	%v16w3, %v16w2;
; O0-NEXT: 	insert.6.v2.32b 	%v16w3, %v2w3;
; O0-NEXT: 	extract.0.v16.32b 	%v16w4, %v16w3;
; O0-NEXT: 	insert.8.v2.32b 	%v16w4, %v2w4;
; O0-NEXT: 	extract.0.v16.32b 	%v16w5, %v16w4;
; O0-NEXT: 	insert.10.v2.32b 	%v16w5, %v2w5;
; O0-NEXT: 	extract.0.v16.32b 	%v16w6, %v16w5;
; O0-NEXT: 	insert.12.v2.32b 	%v16w6, %v2w6;
; O0-NEXT: 	extract.0.v16.32b 	%v16w7, %v16w6;
; O0-NEXT: 	insert.14.v2.32b 	%v16w7, %v2w7;
; O0-NEXT: 	return %v16w7;
;
; CHECK-LABEL: .v16.32b @test_zext_i32_8(
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .64b %d<0~8>;
; CHECK-NEXT: 	.reg .v2.32b %v2w<0~8>;
; CHECK-NEXT: 	.reg .v16.32b [[VR16_32_V16W0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	extract.0.v4.32b 	[[VR4_32_V4W0]], [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.4.v4.32b 	[[VR4_32_V4W1]], [[VR8_32_V8W0]];
; CHECK-NEXT: 	zext.64b.32b 	%d0, [[VR4_32_V4W0]].x;
; CHECK-NEXT: 	zext.64b.32b 	%d1, [[VR4_32_V4W0]].y;
; CHECK-NEXT: 	zext.64b.32b 	%d2, [[VR4_32_V4W0]].z;
; CHECK-NEXT: 	zext.64b.32b 	%d3, [[VR4_32_V4W0]].w;
; CHECK-NEXT: 	zext.64b.32b 	%d4, [[VR4_32_V4W1]].x;
; CHECK-NEXT: 	zext.64b.32b 	%d5, [[VR4_32_V4W1]].y;
; CHECK-NEXT: 	zext.64b.32b 	%d6, [[VR4_32_V4W1]].z;
; CHECK-NEXT: 	zext.64b.32b 	%d7, [[VR4_32_V4W1]].w;
; CHECK-NEXT: 	mov.64b 	%v2w0.xy, %d0;
; CHECK-NEXT: 	mov.64b 	%v2w1.xy, %d1;
; CHECK-NEXT: 	mov.64b 	%v2w2.xy, %d2;
; CHECK-NEXT: 	mov.64b 	%v2w3.xy, %d3;
; CHECK-NEXT: 	mov.64b 	%v2w4.xy, %d4;
; CHECK-NEXT: 	mov.64b 	%v2w5.xy, %d5;
; CHECK-NEXT: 	mov.64b 	%v2w6.xy, %d6;
; CHECK-NEXT: 	mov.64b 	%v2w7.xy, %d7;
; CHECK-NEXT: 	insert.0.v2.32b 	[[VR16_32_V16W0]], %v2w0;
; CHECK-NEXT: 	insert.2.v2.32b 	[[VR16_32_V16W0]], %v2w1;
; CHECK-NEXT: 	insert.4.v2.32b 	[[VR16_32_V16W0]], %v2w2;
; CHECK-NEXT: 	insert.6.v2.32b 	[[VR16_32_V16W0]], %v2w3;
; CHECK-NEXT: 	insert.8.v2.32b 	[[VR16_32_V16W0]], %v2w4;
; CHECK-NEXT: 	insert.10.v2.32b 	[[VR16_32_V16W0]], %v2w5;
; CHECK-NEXT: 	insert.12.v2.32b 	[[VR16_32_V16W0]], %v2w6;
; CHECK-NEXT: 	insert.14.v2.32b 	[[VR16_32_V16W0]], %v2w7;
; CHECK-NEXT: 	return [[VR16_32_V16W0]];
  %res = zext <8 x i32> %arg0 to <8 x i64>
  ret <8 x i64> %res
}

define <8 x i32> @test_trunc_i32_8(<8 x i64> %arg0) {
; O0-LABEL: .v8.32b @test_trunc_i32_8(
; O0-SAME: .reg .v16.32b [[VR16_32_V16W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v2.32b %v2w<0~8>;
; O0-NEXT: 	.reg .64b %d<0~8>;
; O0-NEXT: 	.reg .32b %w<0~8>;
; O0-NEXT: 	.reg .v4.32b %v4w<0~8>;
; O0-NEXT: 	.reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]];
; O0: 	extract.0.v2.32b 	%v2w0, [[VR16_32_V16W0]];
; O0-NEXT: 	extract.2.v2.32b 	%v2w1, [[VR16_32_V16W0]];
; O0-NEXT: 	extract.4.v2.32b 	%v2w2, [[VR16_32_V16W0]];
; O0-NEXT: 	extract.6.v2.32b 	%v2w3, [[VR16_32_V16W0]];
; O0-NEXT: 	extract.8.v2.32b 	%v2w4, [[VR16_32_V16W0]];
; O0-NEXT: 	extract.10.v2.32b 	%v2w5, [[VR16_32_V16W0]];
; O0-NEXT: 	extract.12.v2.32b 	%v2w6, [[VR16_32_V16W0]];
; O0-NEXT: 	extract.14.v2.32b 	%v2w7, [[VR16_32_V16W0]];
; O0-NEXT: 	mov.64b 	%d0, %v2w0.xy;
; O0-NEXT: 	mov.64b 	%d1, %v2w1.xy;
; O0-NEXT: 	mov.64b 	%d2, %v2w2.xy;
; O0-NEXT: 	mov.64b 	%d3, %v2w3.xy;
; O0-NEXT: 	mov.64b 	%d4, %v2w4.xy;
; O0-NEXT: 	mov.64b 	%d5, %v2w5.xy;
; O0-NEXT: 	mov.64b 	%d6, %v2w6.xy;
; O0-NEXT: 	mov.64b 	%d7, %v2w7.xy;
; O0-NEXT: 	trunc.32b.64b 	%w0, %d0;
; O0-NEXT: 	trunc.32b.64b 	%w1, %d1;
; O0-NEXT: 	trunc.32b.64b 	%w2, %d2;
; O0-NEXT: 	trunc.32b.64b 	%w3, %d3;
; O0-NEXT: 	mov.32b 	%v4w0.x, %w0;
; O0-NEXT: 	mov.128b 	%v4w1.xyzw, %v4w0.xyzw;
; O0-NEXT: 	mov.32b 	%v4w1.y, %w1;
; O0-NEXT: 	mov.128b 	%v4w2.xyzw, %v4w1.xyzw;
; O0-NEXT: 	mov.32b 	%v4w2.z, %w2;
; O0-NEXT: 	mov.128b 	%v4w3.xyzw, %v4w2.xyzw;
; O0-NEXT: 	mov.32b 	%v4w3.w, %w3;
; O0-NEXT: 	trunc.32b.64b 	%w4, %d4;
; O0-NEXT: 	trunc.32b.64b 	%w5, %d5;
; O0-NEXT: 	trunc.32b.64b 	%w6, %d6;
; O0-NEXT: 	trunc.32b.64b 	%w7, %d7;
; O0-NEXT: 	mov.32b 	%v4w4.x, %w4;
; O0-NEXT: 	mov.128b 	%v4w5.xyzw, %v4w4.xyzw;
; O0-NEXT: 	mov.32b 	%v4w5.y, %w5;
; O0-NEXT: 	mov.128b 	%v4w6.xyzw, %v4w5.xyzw;
; O0-NEXT: 	mov.32b 	%v4w6.z, %w6;
; O0-NEXT: 	mov.128b 	%v4w7.xyzw, %v4w6.xyzw;
; O0-NEXT: 	mov.32b 	%v4w7.w, %w7;
; O0-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W0]], %v4w3;
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W1]], [[VR8_32_V8W0]];
; O0-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W1]], %v4w7;
; O0-NEXT: 	return [[VR8_32_V8W1]];
;
; CHECK-LABEL: .v8.32b @test_trunc_i32_8(
; CHECK-SAME: .reg .v16.32b [[VR16_32_V16W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v2.32b %v2w<0~8>;
; CHECK-NEXT: 	.reg .64b %d<0~8>;
; CHECK-NEXT: 	.reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]];
; CHECK: 	extract.0.v2.32b 	%v2w0, [[VR16_32_V16W0]];
; CHECK-NEXT: 	extract.2.v2.32b 	%v2w1, [[VR16_32_V16W0]];
; CHECK-NEXT: 	extract.4.v2.32b 	%v2w2, [[VR16_32_V16W0]];
; CHECK-NEXT: 	extract.6.v2.32b 	%v2w3, [[VR16_32_V16W0]];
; CHECK-NEXT: 	extract.8.v2.32b 	%v2w4, [[VR16_32_V16W0]];
; CHECK-NEXT: 	extract.10.v2.32b 	%v2w5, [[VR16_32_V16W0]];
; CHECK-NEXT: 	extract.12.v2.32b 	%v2w6, [[VR16_32_V16W0]];
; CHECK-NEXT: 	extract.14.v2.32b 	%v2w7, [[VR16_32_V16W0]];
; CHECK-NEXT: 	mov.64b 	%d0, %v2w0.xy;
; CHECK-NEXT: 	mov.64b 	%d1, %v2w1.xy;
; CHECK-NEXT: 	mov.64b 	%d2, %v2w2.xy;
; CHECK-NEXT: 	mov.64b 	%d3, %v2w3.xy;
; CHECK-NEXT: 	mov.64b 	%d4, %v2w4.xy;
; CHECK-NEXT: 	mov.64b 	%d5, %v2w5.xy;
; CHECK-NEXT: 	mov.64b 	%d6, %v2w6.xy;
; CHECK-NEXT: 	mov.64b 	%d7, %v2w7.xy;
; CHECK-NEXT: 	trunc.32b.64b 	[[VR4_32_V4W0]].x, %d0;
; CHECK-NEXT: 	trunc.32b.64b 	[[VR4_32_V4W0]].y, %d1;
; CHECK-NEXT: 	trunc.32b.64b 	[[VR4_32_V4W0]].z, %d2;
; CHECK-NEXT: 	trunc.32b.64b 	[[VR4_32_V4W0]].w, %d3;
; CHECK-NEXT: 	trunc.32b.64b 	[[VR4_32_V4W1]].x, %d4;
; CHECK-NEXT: 	trunc.32b.64b 	[[VR4_32_V4W1]].y, %d5;
; CHECK-NEXT: 	trunc.32b.64b 	[[VR4_32_V4W1]].z, %d6;
; CHECK-NEXT: 	trunc.32b.64b 	[[VR4_32_V4W1]].w, %d7;
; CHECK-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W0]], [[VR4_32_V4W0]];
; CHECK-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W0]], [[VR4_32_V4W1]];
; CHECK-NEXT: 	return [[VR8_32_V8W0]];
  %res = trunc <8 x i64> %arg0 to <8 x i32>
  ret <8 x i32> %res
}

define <8 x float> @test_fneg_float_8(<8 x float> %arg0) {
; O0-LABEL: .v8.32b @test_fneg_float_8(
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v4.32b %v4w<0~10>;
; O0-NEXT: 	.reg .32b %w<0~16>;
; O0: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; O0-NEXT: 	mov.32b 	%w0, %v4w0.x;
; O0-NEXT: 	mov.32b 	%w1, %v4w0.y;
; O0-NEXT: 	mov.32b 	%w2, %v4w0.z;
; O0-NEXT: 	mov.32b 	%w3, %v4w0.w;
; O0-NEXT: 	fneg.f 	%w4, %w0;
; O0-NEXT: 	fneg.f 	%w5, %w1;
; O0-NEXT: 	fneg.f 	%w6, %w2;
; O0-NEXT: 	fneg.f 	%w7, %w3;
; O0-NEXT: 	mov.32b 	%v4w2.x, %w4;
; O0-NEXT: 	mov.128b 	%v4w3.xyzw, %v4w2.xyzw;
; O0-NEXT: 	mov.32b 	%v4w3.y, %w5;
; O0-NEXT: 	mov.128b 	%v4w4.xyzw, %v4w3.xyzw;
; O0-NEXT: 	mov.32b 	%v4w4.z, %w6;
; O0-NEXT: 	mov.128b 	%v4w5.xyzw, %v4w4.xyzw;
; O0-NEXT: 	mov.32b 	%v4w5.w, %w7;
; O0-NEXT: 	mov.32b 	%w8, %v4w1.x;
; O0-NEXT: 	mov.32b 	%w9, %v4w1.y;
; O0-NEXT: 	mov.32b 	%w10, %v4w1.z;
; O0-NEXT: 	mov.32b 	%w11, %v4w1.w;
; O0-NEXT: 	fneg.f 	%w12, %w8;
; O0-NEXT: 	fneg.f 	%w13, %w9;
; O0-NEXT: 	fneg.f 	%w14, %w10;
; O0-NEXT: 	fneg.f 	%w15, %w11;
; O0-NEXT: 	mov.32b 	%v4w6.x, %w12;
; O0-NEXT: 	mov.128b 	%v4w7.xyzw, %v4w6.xyzw;
; O0-NEXT: 	mov.32b 	%v4w7.y, %w13;
; O0-NEXT: 	mov.128b 	%v4w8.xyzw, %v4w7.xyzw;
; O0-NEXT: 	mov.32b 	%v4w8.z, %w14;
; O0-NEXT: 	mov.128b 	%v4w9.xyzw, %v4w8.xyzw;
; O0-NEXT: 	mov.32b 	%v4w9.w, %w15;
; O0-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W1]], %v4w5;
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W2]], [[VR8_32_V8W1]];
; O0-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W2]], %v4w9;
; O0-NEXT: 	return [[VR8_32_V8W2]];
;
; CHECK-LABEL: .v8.32b @test_fneg_float_8(
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.32b [[VR4_32_V4W0:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W1:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W2:%[-a-zA-Z$._0-9]+]], [[VR4_32_V4W3:%[-a-zA-Z$._0-9]+]];
; CHECK: 	extract.0.v4.32b 	[[VR4_32_V4W0]], [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.4.v4.32b 	[[VR4_32_V4W1]], [[VR8_32_V8W0]];
; CHECK-NEXT: 	fneg.f 	[[VR4_32_V4W2]].x, [[VR4_32_V4W0]].x;
; CHECK-NEXT: 	fneg.f 	[[VR4_32_V4W2]].y, [[VR4_32_V4W0]].y;
; CHECK-NEXT: 	fneg.f 	[[VR4_32_V4W2]].z, [[VR4_32_V4W0]].z;
; CHECK-NEXT: 	fneg.f 	[[VR4_32_V4W2]].w, [[VR4_32_V4W0]].w;
; CHECK-NEXT: 	fneg.f 	[[VR4_32_V4W3]].x, [[VR4_32_V4W1]].x;
; CHECK-NEXT: 	fneg.f 	[[VR4_32_V4W3]].y, [[VR4_32_V4W1]].y;
; CHECK-NEXT: 	fneg.f 	[[VR4_32_V4W3]].z, [[VR4_32_V4W1]].z;
; CHECK-NEXT: 	fneg.f 	[[VR4_32_V4W3]].w, [[VR4_32_V4W1]].w;
; CHECK-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W1]], [[VR4_32_V4W2]];
; CHECK-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W1]], [[VR4_32_V4W3]];
; CHECK-NEXT: 	return [[VR8_32_V8W1]];
  %res = fneg <8 x float> %arg0
  ret <8 x float> %res
}


define <8 x float> @test_fadd_float_8(<8 x float> %arg0 ,<8 x float> %arg1) {
; O0-LABEL: .v8.32b @test_fadd_float_8(
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v4.32b %v4w<0~12>;
; O0-NEXT: 	.reg .32b %w<0~24>;
; O0: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; O0-NEXT: 	mov.32b 	%w0, %v4w0.x;
; O0-NEXT: 	mov.32b 	%w1, %v4w0.y;
; O0-NEXT: 	mov.32b 	%w2, %v4w0.z;
; O0-NEXT: 	mov.32b 	%w3, %v4w0.w;
; O0-NEXT: 	mov.32b 	%w4, %v4w2.x;
; O0-NEXT: 	mov.32b 	%w5, %v4w2.y;
; O0-NEXT: 	mov.32b 	%w6, %v4w2.z;
; O0-NEXT: 	mov.32b 	%w7, %v4w2.w;
; O0-NEXT: 	fadd.f 	%w8, %w0, %w4;
; O0-NEXT: 	fadd.f 	%w9, %w1, %w5;
; O0-NEXT: 	fadd.f 	%w10, %w2, %w6;
; O0-NEXT: 	fadd.f 	%w11, %w3, %w7;
; O0-NEXT: 	mov.32b 	%v4w4.x, %w8;
; O0-NEXT: 	mov.128b 	%v4w5.xyzw, %v4w4.xyzw;
; O0-NEXT: 	mov.32b 	%v4w5.y, %w9;
; O0-NEXT: 	mov.128b 	%v4w6.xyzw, %v4w5.xyzw;
; O0-NEXT: 	mov.32b 	%v4w6.z, %w10;
; O0-NEXT: 	mov.128b 	%v4w7.xyzw, %v4w6.xyzw;
; O0-NEXT: 	mov.32b 	%v4w7.w, %w11;
; O0-NEXT: 	mov.32b 	%w12, %v4w1.x;
; O0-NEXT: 	mov.32b 	%w13, %v4w1.y;
; O0-NEXT: 	mov.32b 	%w14, %v4w1.z;
; O0-NEXT: 	mov.32b 	%w15, %v4w1.w;
; O0-NEXT: 	mov.32b 	%w16, %v4w3.x;
; O0-NEXT: 	mov.32b 	%w17, %v4w3.y;
; O0-NEXT: 	mov.32b 	%w18, %v4w3.z;
; O0-NEXT: 	mov.32b 	%w19, %v4w3.w;
; O0-NEXT: 	fadd.f 	%w20, %w12, %w16;
; O0-NEXT: 	fadd.f 	%w21, %w13, %w17;
; O0-NEXT: 	fadd.f 	%w22, %w14, %w18;
; O0-NEXT: 	fadd.f 	%w23, %w15, %w19;
; O0-NEXT: 	mov.32b 	%v4w8.x, %w20;
; O0-NEXT: 	mov.128b 	%v4w9.xyzw, %v4w8.xyzw;
; O0-NEXT: 	mov.32b 	%v4w9.y, %w21;
; O0-NEXT: 	mov.128b 	%v4w10.xyzw, %v4w9.xyzw;
; O0-NEXT: 	mov.32b 	%v4w10.z, %w22;
; O0-NEXT: 	mov.128b 	%v4w11.xyzw, %v4w10.xyzw;
; O0-NEXT: 	mov.32b 	%v4w11.w, %w23;
; O0-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W2]], %v4w7;
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W3]], [[VR8_32_V8W2]];
; O0-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W3]], %v4w11;
; O0-NEXT: 	return [[VR8_32_V8W3]];
;
; CHECK-LABEL: .v8.32b @test_fadd_float_8(
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.32b %v4w<0~6>;
; CHECK: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; CHECK-NEXT: 	fadd.f 	%v4w4.x, %v4w0.x, %v4w2.x;
; CHECK-NEXT: 	fadd.f 	%v4w4.y, %v4w0.y, %v4w2.y;
; CHECK-NEXT: 	fadd.f 	%v4w4.z, %v4w0.z, %v4w2.z;
; CHECK-NEXT: 	fadd.f 	%v4w4.w, %v4w0.w, %v4w2.w;
; CHECK-NEXT: 	fadd.f 	%v4w5.x, %v4w1.x, %v4w3.x;
; CHECK-NEXT: 	fadd.f 	%v4w5.y, %v4w1.y, %v4w3.y;
; CHECK-NEXT: 	fadd.f 	%v4w5.z, %v4w1.z, %v4w3.z;
; CHECK-NEXT: 	fadd.f 	%v4w5.w, %v4w1.w, %v4w3.w;
; CHECK-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W2]], %v4w4;
; CHECK-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W2]], %v4w5;
; CHECK-NEXT: 	return [[VR8_32_V8W2]];
  %res = fadd <8 x float> %arg0, %arg1
  ret <8 x float> %res
}

define <8 x i32> @test_shl_i32_8(<8 x i32> %arg0 ,<8 x i32> %arg1) {
; O0-LABEL: .v8.32b @test_shl_i32_8(
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v4.32b %v4w<0~12>;
; O0-NEXT: 	.reg .32b %w<0~24>;
; O0: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; O0-NEXT: 	mov.32b 	%w0, %v4w0.x;
; O0-NEXT: 	mov.32b 	%w1, %v4w0.y;
; O0-NEXT: 	mov.32b 	%w2, %v4w0.z;
; O0-NEXT: 	mov.32b 	%w3, %v4w0.w;
; O0-NEXT: 	mov.32b 	%w4, %v4w2.x;
; O0-NEXT: 	mov.32b 	%w5, %v4w2.y;
; O0-NEXT: 	mov.32b 	%w6, %v4w2.z;
; O0-NEXT: 	mov.32b 	%w7, %v4w2.w;
; O0-NEXT: 	shl.32b 	%w8, %w0, %w4;
; O0-NEXT: 	shl.32b 	%w9, %w1, %w5;
; O0-NEXT: 	shl.32b 	%w10, %w2, %w6;
; O0-NEXT: 	shl.32b 	%w11, %w3, %w7;
; O0-NEXT: 	mov.32b 	%v4w4.x, %w8;
; O0-NEXT: 	mov.128b 	%v4w5.xyzw, %v4w4.xyzw;
; O0-NEXT: 	mov.32b 	%v4w5.y, %w9;
; O0-NEXT: 	mov.128b 	%v4w6.xyzw, %v4w5.xyzw;
; O0-NEXT: 	mov.32b 	%v4w6.z, %w10;
; O0-NEXT: 	mov.128b 	%v4w7.xyzw, %v4w6.xyzw;
; O0-NEXT: 	mov.32b 	%v4w7.w, %w11;
; O0-NEXT: 	mov.32b 	%w12, %v4w1.x;
; O0-NEXT: 	mov.32b 	%w13, %v4w1.y;
; O0-NEXT: 	mov.32b 	%w14, %v4w1.z;
; O0-NEXT: 	mov.32b 	%w15, %v4w1.w;
; O0-NEXT: 	mov.32b 	%w16, %v4w3.x;
; O0-NEXT: 	mov.32b 	%w17, %v4w3.y;
; O0-NEXT: 	mov.32b 	%w18, %v4w3.z;
; O0-NEXT: 	mov.32b 	%w19, %v4w3.w;
; O0-NEXT: 	shl.32b 	%w20, %w12, %w16;
; O0-NEXT: 	shl.32b 	%w21, %w13, %w17;
; O0-NEXT: 	shl.32b 	%w22, %w14, %w18;
; O0-NEXT: 	shl.32b 	%w23, %w15, %w19;
; O0-NEXT: 	mov.32b 	%v4w8.x, %w20;
; O0-NEXT: 	mov.128b 	%v4w9.xyzw, %v4w8.xyzw;
; O0-NEXT: 	mov.32b 	%v4w9.y, %w21;
; O0-NEXT: 	mov.128b 	%v4w10.xyzw, %v4w9.xyzw;
; O0-NEXT: 	mov.32b 	%v4w10.z, %w22;
; O0-NEXT: 	mov.128b 	%v4w11.xyzw, %v4w10.xyzw;
; O0-NEXT: 	mov.32b 	%v4w11.w, %w23;
; O0-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W2]], %v4w7;
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W3]], [[VR8_32_V8W2]];
; O0-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W3]], %v4w11;
; O0-NEXT: 	return [[VR8_32_V8W3]];
;
; CHECK-LABEL: .v8.32b @test_shl_i32_8(
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.32b %v4w<0~6>;
; CHECK: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; CHECK-NEXT: 	shl.32b 	%v4w4.x, %v4w0.x, %v4w2.x;
; CHECK-NEXT: 	shl.32b 	%v4w4.y, %v4w0.y, %v4w2.y;
; CHECK-NEXT: 	shl.32b 	%v4w4.z, %v4w0.z, %v4w2.z;
; CHECK-NEXT: 	shl.32b 	%v4w4.w, %v4w0.w, %v4w2.w;
; CHECK-NEXT: 	shl.32b 	%v4w5.x, %v4w1.x, %v4w3.x;
; CHECK-NEXT: 	shl.32b 	%v4w5.y, %v4w1.y, %v4w3.y;
; CHECK-NEXT: 	shl.32b 	%v4w5.z, %v4w1.z, %v4w3.z;
; CHECK-NEXT: 	shl.32b 	%v4w5.w, %v4w1.w, %v4w3.w;
; CHECK-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W2]], %v4w4;
; CHECK-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W2]], %v4w5;
; CHECK-NEXT: 	return [[VR8_32_V8W2]];
  %res = shl <8 x i32> %arg0, %arg1
  ret <8 x i32> %res
}

define <8 x i32> @test_xor_i32_8(<8 x i32> %arg0 ,<8 x i32> %arg1) {
; O0-LABEL: .v8.32b @test_xor_i32_8(
; O0-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]], [[VR8_32_V8W3:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v4.32b %v4w<0~12>;
; O0-NEXT: 	.reg .32b %w<0~24>;
; O0: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; O0-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; O0-NEXT: 	mov.32b 	%w0, %v4w0.x;
; O0-NEXT: 	mov.32b 	%w1, %v4w0.y;
; O0-NEXT: 	mov.32b 	%w2, %v4w0.z;
; O0-NEXT: 	mov.32b 	%w3, %v4w0.w;
; O0-NEXT: 	mov.32b 	%w4, %v4w2.x;
; O0-NEXT: 	mov.32b 	%w5, %v4w2.y;
; O0-NEXT: 	mov.32b 	%w6, %v4w2.z;
; O0-NEXT: 	mov.32b 	%w7, %v4w2.w;
; O0-NEXT: 	xor.32b 	%w8, %w0, %w4;
; O0-NEXT: 	xor.32b 	%w9, %w1, %w5;
; O0-NEXT: 	xor.32b 	%w10, %w2, %w6;
; O0-NEXT: 	xor.32b 	%w11, %w3, %w7;
; O0-NEXT: 	mov.32b 	%v4w4.x, %w8;
; O0-NEXT: 	mov.128b 	%v4w5.xyzw, %v4w4.xyzw;
; O0-NEXT: 	mov.32b 	%v4w5.y, %w9;
; O0-NEXT: 	mov.128b 	%v4w6.xyzw, %v4w5.xyzw;
; O0-NEXT: 	mov.32b 	%v4w6.z, %w10;
; O0-NEXT: 	mov.128b 	%v4w7.xyzw, %v4w6.xyzw;
; O0-NEXT: 	mov.32b 	%v4w7.w, %w11;
; O0-NEXT: 	mov.32b 	%w12, %v4w1.x;
; O0-NEXT: 	mov.32b 	%w13, %v4w1.y;
; O0-NEXT: 	mov.32b 	%w14, %v4w1.z;
; O0-NEXT: 	mov.32b 	%w15, %v4w1.w;
; O0-NEXT: 	mov.32b 	%w16, %v4w3.x;
; O0-NEXT: 	mov.32b 	%w17, %v4w3.y;
; O0-NEXT: 	mov.32b 	%w18, %v4w3.z;
; O0-NEXT: 	mov.32b 	%w19, %v4w3.w;
; O0-NEXT: 	xor.32b 	%w20, %w12, %w16;
; O0-NEXT: 	xor.32b 	%w21, %w13, %w17;
; O0-NEXT: 	xor.32b 	%w22, %w14, %w18;
; O0-NEXT: 	xor.32b 	%w23, %w15, %w19;
; O0-NEXT: 	mov.32b 	%v4w8.x, %w20;
; O0-NEXT: 	mov.128b 	%v4w9.xyzw, %v4w8.xyzw;
; O0-NEXT: 	mov.32b 	%v4w9.y, %w21;
; O0-NEXT: 	mov.128b 	%v4w10.xyzw, %v4w9.xyzw;
; O0-NEXT: 	mov.32b 	%v4w10.z, %w22;
; O0-NEXT: 	mov.128b 	%v4w11.xyzw, %v4w10.xyzw;
; O0-NEXT: 	mov.32b 	%v4w11.w, %w23;
; O0-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W2]], %v4w7;
; O0-NEXT: 	extract.0.v8.32b 	[[VR8_32_V8W3]], [[VR8_32_V8W2]];
; O0-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W3]], %v4w11;
; O0-NEXT: 	return [[VR8_32_V8W3]];
;
; CHECK-LABEL: .v8.32b @test_xor_i32_8(
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v8.32b [[VR8_32_V8W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v8.32b [[VR8_32_V8W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.32b %v4w<0~6>;
; CHECK: 	extract.0.v4.32b 	%v4w0, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR8_32_V8W0]];
; CHECK-NEXT: 	extract.0.v4.32b 	%v4w2, [[VR8_32_V8W1]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w3, [[VR8_32_V8W1]];
; CHECK-NEXT: 	xor.32b 	%v4w4.x, %v4w0.x, %v4w2.x;
; CHECK-NEXT: 	xor.32b 	%v4w4.y, %v4w0.y, %v4w2.y;
; CHECK-NEXT: 	xor.32b 	%v4w4.z, %v4w0.z, %v4w2.z;
; CHECK-NEXT: 	xor.32b 	%v4w4.w, %v4w0.w, %v4w2.w;
; CHECK-NEXT: 	xor.32b 	%v4w5.x, %v4w1.x, %v4w3.x;
; CHECK-NEXT: 	xor.32b 	%v4w5.y, %v4w1.y, %v4w3.y;
; CHECK-NEXT: 	xor.32b 	%v4w5.z, %v4w1.z, %v4w3.z;
; CHECK-NEXT: 	xor.32b 	%v4w5.w, %v4w1.w, %v4w3.w;
; CHECK-NEXT: 	insert.0.v4.32b 	[[VR8_32_V8W2]], %v4w4;
; CHECK-NEXT: 	insert.4.v4.32b 	[[VR8_32_V8W2]], %v4w5;
; CHECK-NEXT: 	return [[VR8_32_V8W2]];
  %res = xor <8 x i32> %arg0, %arg1
  ret <8 x i32> %res
}


define <16 x i32> @test_xor_i32_16(<16 x i32> %arg0 ,<16 x i32> %arg1) {
; O0-LABEL: .v16.32b @test_xor_i32_16(
; O0-SAME: .reg .v16.32b [[VR16_32_V16W0:%[-a-zA-Z$._0-9]+]]
; O0-SAME: .reg .v16.32b [[VR16_32_V16W1:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .v16.32b [[VR16_32_V16W2:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W3:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W4:%[-a-zA-Z$._0-9]+]], [[VR16_32_V16W5:%[-a-zA-Z$._0-9]+]];
; O0-NEXT: 	.reg .v4.32b %v4w<0~24>;
; O0-NEXT: 	.reg .32b %w<0~48>;
; O0: 	extract.0.v4.32b 	%v4w0, [[VR16_32_V16W0]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR16_32_V16W0]];
; O0-NEXT: 	extract.8.v4.32b 	%v4w2, [[VR16_32_V16W0]];
; O0-NEXT: 	extract.12.v4.32b 	%v4w3, [[VR16_32_V16W0]];
; O0-NEXT: 	extract.0.v4.32b 	%v4w4, [[VR16_32_V16W1]];
; O0-NEXT: 	extract.4.v4.32b 	%v4w5, [[VR16_32_V16W1]];
; O0-NEXT: 	extract.8.v4.32b 	%v4w6, [[VR16_32_V16W1]];
; O0-NEXT: 	extract.12.v4.32b 	%v4w7, [[VR16_32_V16W1]];
; O0-NEXT: 	mov.32b 	%w0, %v4w0.x;
; O0-NEXT: 	mov.32b 	%w1, %v4w0.y;
; O0-NEXT: 	mov.32b 	%w2, %v4w0.z;
; O0-NEXT: 	mov.32b 	%w3, %v4w0.w;
; O0-NEXT: 	mov.32b 	%w4, %v4w4.x;
; O0-NEXT: 	mov.32b 	%w5, %v4w4.y;
; O0-NEXT: 	mov.32b 	%w6, %v4w4.z;
; O0-NEXT: 	mov.32b 	%w7, %v4w4.w;
; O0-NEXT: 	xor.32b 	%w8, %w0, %w4;
; O0-NEXT: 	xor.32b 	%w9, %w1, %w5;
; O0-NEXT: 	xor.32b 	%w10, %w2, %w6;
; O0-NEXT: 	xor.32b 	%w11, %w3, %w7;
; O0-NEXT: 	mov.32b 	%v4w8.x, %w8;
; O0-NEXT: 	mov.128b 	%v4w9.xyzw, %v4w8.xyzw;
; O0-NEXT: 	mov.32b 	%v4w9.y, %w9;
; O0-NEXT: 	mov.128b 	%v4w10.xyzw, %v4w9.xyzw;
; O0-NEXT: 	mov.32b 	%v4w10.z, %w10;
; O0-NEXT: 	mov.128b 	%v4w11.xyzw, %v4w10.xyzw;
; O0-NEXT: 	mov.32b 	%v4w11.w, %w11;
; O0-NEXT: 	mov.32b 	%w12, %v4w1.x;
; O0-NEXT: 	mov.32b 	%w13, %v4w1.y;
; O0-NEXT: 	mov.32b 	%w14, %v4w1.z;
; O0-NEXT: 	mov.32b 	%w15, %v4w1.w;
; O0-NEXT: 	mov.32b 	%w16, %v4w5.x;
; O0-NEXT: 	mov.32b 	%w17, %v4w5.y;
; O0-NEXT: 	mov.32b 	%w18, %v4w5.z;
; O0-NEXT: 	mov.32b 	%w19, %v4w5.w;
; O0-NEXT: 	xor.32b 	%w20, %w12, %w16;
; O0-NEXT: 	xor.32b 	%w21, %w13, %w17;
; O0-NEXT: 	xor.32b 	%w22, %w14, %w18;
; O0-NEXT: 	xor.32b 	%w23, %w15, %w19;
; O0-NEXT: 	mov.32b 	%v4w12.x, %w20;
; O0-NEXT: 	mov.128b 	%v4w13.xyzw, %v4w12.xyzw;
; O0-NEXT: 	mov.32b 	%v4w13.y, %w21;
; O0-NEXT: 	mov.128b 	%v4w14.xyzw, %v4w13.xyzw;
; O0-NEXT: 	mov.32b 	%v4w14.z, %w22;
; O0-NEXT: 	mov.128b 	%v4w15.xyzw, %v4w14.xyzw;
; O0-NEXT: 	mov.32b 	%v4w15.w, %w23;
; O0-NEXT: 	mov.32b 	%w24, %v4w2.x;
; O0-NEXT: 	mov.32b 	%w25, %v4w2.y;
; O0-NEXT: 	mov.32b 	%w26, %v4w2.z;
; O0-NEXT: 	mov.32b 	%w27, %v4w2.w;
; O0-NEXT: 	mov.32b 	%w28, %v4w6.x;
; O0-NEXT: 	mov.32b 	%w29, %v4w6.y;
; O0-NEXT: 	mov.32b 	%w30, %v4w6.z;
; O0-NEXT: 	mov.32b 	%w31, %v4w6.w;
; O0-NEXT: 	xor.32b 	%w32, %w24, %w28;
; O0-NEXT: 	xor.32b 	%w33, %w25, %w29;
; O0-NEXT: 	xor.32b 	%w34, %w26, %w30;
; O0-NEXT: 	xor.32b 	%w35, %w27, %w31;
; O0-NEXT: 	mov.32b 	%v4w16.x, %w32;
; O0-NEXT: 	mov.128b 	%v4w17.xyzw, %v4w16.xyzw;
; O0-NEXT: 	mov.32b 	%v4w17.y, %w33;
; O0-NEXT: 	mov.128b 	%v4w18.xyzw, %v4w17.xyzw;
; O0-NEXT: 	mov.32b 	%v4w18.z, %w34;
; O0-NEXT: 	mov.128b 	%v4w19.xyzw, %v4w18.xyzw;
; O0-NEXT: 	mov.32b 	%v4w19.w, %w35;
; O0-NEXT: 	mov.32b 	%w36, %v4w3.x;
; O0-NEXT: 	mov.32b 	%w37, %v4w3.y;
; O0-NEXT: 	mov.32b 	%w38, %v4w3.z;
; O0-NEXT: 	mov.32b 	%w39, %v4w3.w;
; O0-NEXT: 	mov.32b 	%w40, %v4w7.x;
; O0-NEXT: 	mov.32b 	%w41, %v4w7.y;
; O0-NEXT: 	mov.32b 	%w42, %v4w7.z;
; O0-NEXT: 	mov.32b 	%w43, %v4w7.w;
; O0-NEXT: 	xor.32b 	%w44, %w36, %w40;
; O0-NEXT: 	xor.32b 	%w45, %w37, %w41;
; O0-NEXT: 	xor.32b 	%w46, %w38, %w42;
; O0-NEXT: 	xor.32b 	%w47, %w39, %w43;
; O0-NEXT: 	mov.32b 	%v4w20.x, %w44;
; O0-NEXT: 	mov.128b 	%v4w21.xyzw, %v4w20.xyzw;
; O0-NEXT: 	mov.32b 	%v4w21.y, %w45;
; O0-NEXT: 	mov.128b 	%v4w22.xyzw, %v4w21.xyzw;
; O0-NEXT: 	mov.32b 	%v4w22.z, %w46;
; O0-NEXT: 	mov.128b 	%v4w23.xyzw, %v4w22.xyzw;
; O0-NEXT: 	mov.32b 	%v4w23.w, %w47;
; O0-NEXT: 	insert.0.v4.32b 	[[VR16_32_V16W2]], %v4w11;
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W3]], [[VR16_32_V16W2]];
; O0-NEXT: 	insert.4.v4.32b 	[[VR16_32_V16W3]], %v4w15;
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W4]], [[VR16_32_V16W3]];
; O0-NEXT: 	insert.8.v4.32b 	[[VR16_32_V16W4]], %v4w19;
; O0-NEXT: 	extract.0.v16.32b 	[[VR16_32_V16W5]], [[VR16_32_V16W4]];
; O0-NEXT: 	insert.12.v4.32b 	[[VR16_32_V16W5]], %v4w23;
; O0-NEXT: 	return [[VR16_32_V16W5]];
;
; CHECK-LABEL: .v16.32b @test_xor_i32_16(
; CHECK-SAME: .reg .v16.32b [[VR16_32_V16W0:%[-a-zA-Z$._0-9]+]]
; CHECK-SAME: .reg .v16.32b [[VR16_32_V16W1:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .v16.32b [[VR16_32_V16W2:%[-a-zA-Z$._0-9]+]];
; CHECK-NEXT: 	.reg .v4.32b %v4w<0~12>;
; CHECK: 	extract.0.v4.32b 	%v4w0, [[VR16_32_V16W0]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w1, [[VR16_32_V16W0]];
; CHECK-NEXT: 	extract.8.v4.32b 	%v4w2, [[VR16_32_V16W0]];
; CHECK-NEXT: 	extract.12.v4.32b 	%v4w3, [[VR16_32_V16W0]];
; CHECK-NEXT: 	extract.0.v4.32b 	%v4w4, [[VR16_32_V16W1]];
; CHECK-NEXT: 	extract.4.v4.32b 	%v4w5, [[VR16_32_V16W1]];
; CHECK-NEXT: 	extract.8.v4.32b 	%v4w6, [[VR16_32_V16W1]];
; CHECK-NEXT: 	extract.12.v4.32b 	%v4w7, [[VR16_32_V16W1]];
; CHECK-NEXT: 	xor.32b 	%v4w8.x, %v4w0.x, %v4w4.x;
; CHECK-NEXT: 	xor.32b 	%v4w8.y, %v4w0.y, %v4w4.y;
; CHECK-NEXT: 	xor.32b 	%v4w8.z, %v4w0.z, %v4w4.z;
; CHECK-NEXT: 	xor.32b 	%v4w8.w, %v4w0.w, %v4w4.w;
; CHECK-NEXT: 	xor.32b 	%v4w9.x, %v4w1.x, %v4w5.x;
; CHECK-NEXT: 	xor.32b 	%v4w9.y, %v4w1.y, %v4w5.y;
; CHECK-NEXT: 	xor.32b 	%v4w9.z, %v4w1.z, %v4w5.z;
; CHECK-NEXT: 	xor.32b 	%v4w9.w, %v4w1.w, %v4w5.w;
; CHECK-NEXT: 	xor.32b 	%v4w10.x, %v4w2.x, %v4w6.x;
; CHECK-NEXT: 	xor.32b 	%v4w10.y, %v4w2.y, %v4w6.y;
; CHECK-NEXT: 	xor.32b 	%v4w10.z, %v4w2.z, %v4w6.z;
; CHECK-NEXT: 	xor.32b 	%v4w10.w, %v4w2.w, %v4w6.w;
; CHECK-NEXT: 	xor.32b 	%v4w11.x, %v4w3.x, %v4w7.x;
; CHECK-NEXT: 	xor.32b 	%v4w11.y, %v4w3.y, %v4w7.y;
; CHECK-NEXT: 	xor.32b 	%v4w11.z, %v4w3.z, %v4w7.z;
; CHECK-NEXT: 	xor.32b 	%v4w11.w, %v4w3.w, %v4w7.w;
; CHECK-NEXT: 	insert.0.v4.32b 	[[VR16_32_V16W2]], %v4w8;
; CHECK-NEXT: 	insert.4.v4.32b 	[[VR16_32_V16W2]], %v4w9;
; CHECK-NEXT: 	insert.8.v4.32b 	[[VR16_32_V16W2]], %v4w10;
; CHECK-NEXT: 	insert.12.v4.32b 	[[VR16_32_V16W2]], %v4w11;
; CHECK-NEXT: 	return [[VR16_32_V16W2]];
  %res = xor <16 x i32> %arg0, %arg1
  ret <16 x i32> %res
}
