; NOTE: Assertions have been autogenerated by utils/update_pisa_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=pisa -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -march=pisa -O0 -verify-machineinstrs | FileCheck --check-prefix=O0 %s

define half @test_hf_to_s8(i8 %a) {
; O0-LABEL: .16b @test_hf_to_s8(
; O0-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.s8.dsat 	[[R16_H0]], [[R8_B0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_s8(
; CHECK-SAME: .reg .8b [[R8_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.s8.dsat 	[[R16_R1]], [[R8_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.sitofp.f16.i8(i8 %a, i8 -1, i1 1)
  ret half %res
}

define bfloat @test_bf_to_s8(i8 %a) {
; O0-LABEL: .16b @test_bf_to_s8(
; O0-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.bf.s8.dsat 	[[R16_H0]], [[R8_B0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_bf_to_s8(
; CHECK-SAME: .reg .8b [[R8_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.bf.s8.dsat 	[[R16_R1]], [[R8_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call bfloat @llvm.pisa.sitofp.bf16.i8(i8 %a, i8 -1, i1 1)
  ret bfloat %res
}

define float @test_f32_to_s8(i8 %a) {
; O0-LABEL: .32b @test_f32_to_s8(
; O0-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.f.s8.dsat 	[[R32_W0]], [[R8_B0]];
; O0-NEXT: 	return [[R32_W0]];
;
; CHECK-LABEL: .32b @test_f32_to_s8(
; CHECK-SAME: .reg .8b [[R8_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.f.s8.dsat 	[[R32_R1]], [[R8_R0]];
; CHECK-NEXT: 	return [[R32_R1]];
  %res = call float @llvm.pisa.sitofp.f32.i8(i8 %a, i8 -1, i1 1)
  ret float %res
}

define double @test_f64_to_s8(i8 %a) {
; O0-LABEL: .64b @test_f64_to_s8(
; O0-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.df.s8.dsat 	[[R64_D0]], [[R8_B0]];
; O0-NEXT: 	return [[R64_D0]];
;
; CHECK-LABEL: .64b @test_f64_to_s8(
; CHECK-SAME: .reg .8b [[R8_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.df.s8.dsat 	[[R64_R1]], [[R8_R0]];
; CHECK-NEXT: 	return [[R64_R1]];
  %res = call double @llvm.pisa.sitofp.f64.i8(i8 %a, i8 -1, i1 1)
  ret double %res
}

define half @test_hf_to_s16(i16 %a) {
; O0-LABEL: .16b @test_hf_to_s16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.s16.dsat 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
;
; CHECK-LABEL: .16b @test_hf_to_s16(
; CHECK-SAME: .reg .16b [[R16_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.s16.dsat 	[[R16_R1]], [[R16_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.sitofp.f16.i16(i16 %a, i8 -1, i1 1)
  ret half %res
}

define bfloat @test_bf_to_s16(i16 %a) {
; O0-LABEL: .16b @test_bf_to_s16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.bf.s16.dsat 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
;
; CHECK-LABEL: .16b @test_bf_to_s16(
; CHECK-SAME: .reg .16b [[R16_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.bf.s16.dsat 	[[R16_R1]], [[R16_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call bfloat @llvm.pisa.sitofp.bf16.i16(i16 %a, i8 -1, i1 1)
  ret bfloat %res
}

define float @test_f32_to_s16(i16 %a) {
; O0-LABEL: .32b @test_f32_to_s16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.f.s16.dsat 	[[R32_W0]], [[R16_H0]];
; O0-NEXT: 	return [[R32_W0]];
;
; CHECK-LABEL: .32b @test_f32_to_s16(
; CHECK-SAME: .reg .16b [[R16_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.f.s16.dsat 	[[R32_R1]], [[R16_R0]];
; CHECK-NEXT: 	return [[R32_R1]];
  %res = call float @llvm.pisa.sitofp.f32.i16(i16 %a, i8 -1, i1 1)
  ret float %res
}

define double @test_f64_to_s16(i16 %a) {
; O0-LABEL: .64b @test_f64_to_s16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.df.s16.dsat 	[[R64_D0]], [[R16_H0]];
; O0-NEXT: 	return [[R64_D0]];
;
; CHECK-LABEL: .64b @test_f64_to_s16(
; CHECK-SAME: .reg .16b [[R16_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.df.s16.dsat 	[[R64_R1]], [[R16_R0]];
; CHECK-NEXT: 	return [[R64_R1]];
  %res = call double @llvm.pisa.sitofp.f64.i16(i16 %a, i8 -1, i1 1)
  ret double %res
}

define half @test_hf_to_s32(i32 %a) {
; O0-LABEL: .16b @test_hf_to_s32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.s32.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_s32(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.s32.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.sitofp.f16.i32(i32 %a, i8 -1, i1 1)
  ret half %res
}

define bfloat @test_bf_to_s32(i32 %a) {
; O0-LABEL: .16b @test_bf_to_s32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.bf.s32.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_bf_to_s32(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.bf.s32.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call bfloat @llvm.pisa.sitofp.bf16.i32(i32 %a, i8 -1, i1 1)
  ret bfloat %res
}

define float @test_f32_to_s32(i32 %a) {
; O0-LABEL: .32b @test_f32_to_s32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.f.s32.dsat 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	return [[R32_W1]];
;
; CHECK-LABEL: .32b @test_f32_to_s32(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.f.s32.dsat 	[[R32_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R32_R1]];
  %res = call float @llvm.pisa.sitofp.f32.i32(i32 %a, i8 -1, i1 1)
  ret float %res
}

define double @test_f64_to_s32(i32 %a) {
; O0-LABEL: .64b @test_f64_to_s32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.df.s32.dsat 	[[R64_D0]], [[R32_W0]];
; O0-NEXT: 	return [[R64_D0]];
;
; CHECK-LABEL: .64b @test_f64_to_s32(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.df.s32.dsat 	[[R64_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R64_R1]];
  %res = call double @llvm.pisa.sitofp.f64.i32(i32 %a, i8 -1, i1 1)
  ret double %res
}

define half @test_hf_to_s64(i64 %a) {
; O0-LABEL: .16b @test_hf_to_s64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.s64.dsat 	[[R16_H0]], [[R64_D0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_s64(
; CHECK-SAME: .reg .64b [[R64_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.s64.dsat 	[[R16_R1]], [[R64_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.sitofp.f16.i64(i64 %a, i8 -1, i1 1)
  ret half %res
}

define bfloat @test_bf_to_s64(i64 %a) {
; O0-LABEL: .16b @test_bf_to_s64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.bf.s64.dsat 	[[R16_H0]], [[R64_D0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_bf_to_s64(
; CHECK-SAME: .reg .64b [[R64_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.bf.s64.dsat 	[[R16_R1]], [[R64_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call bfloat @llvm.pisa.sitofp.bf16.i64(i64 %a, i8 -1, i1 1)
  ret bfloat %res
}

define float @test_f32_to_s64(i64 %a) {
; O0-LABEL: .32b @test_f32_to_s64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.f.s64.dsat 	[[R32_W0]], [[R64_D0]];
; O0-NEXT: 	return [[R32_W0]];
;
; CHECK-LABEL: .32b @test_f32_to_s64(
; CHECK-SAME: .reg .64b [[R64_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.f.s64.dsat 	[[R32_R1]], [[R64_R0]];
; CHECK-NEXT: 	return [[R32_R1]];
  %res = call float @llvm.pisa.sitofp.f32.i64(i64 %a, i8 -1, i1 1)
  ret float %res
}

define double @test_f64_to_s64(i64 %a) {
; O0-LABEL: .64b @test_f64_to_s64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.df.s64.dsat 	[[R64_D1]], [[R64_D0]];
; O0-NEXT: 	return [[R64_D1]];
;
; CHECK-LABEL: .64b @test_f64_to_s64(
; CHECK-SAME: .reg .64b [[R64_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.df.s64.dsat 	[[R64_R1]], [[R64_R0]];
; CHECK-NEXT: 	return [[R64_R1]];
  %res = call double @llvm.pisa.sitofp.f64.i64(i64 %a, i8 -1, i1 1)
  ret double %res
}


define half @test_hf_to_u8(i8 %a) {
; O0-LABEL: .16b @test_hf_to_u8(
; O0-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.u8.dsat 	[[R16_H0]], [[R8_B0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_u8(
; CHECK-SAME: .reg .8b [[R8_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.u8.dsat 	[[R16_R1]], [[R8_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.uitofp.f16.i8(i8 %a, i8 -1, i1 1)
  ret half %res
}

define bfloat @test_bf_to_u8(i8 %a) {
; O0-LABEL: .16b @test_bf_to_u8(
; O0-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.bf.u8.dsat 	[[R16_H0]], [[R8_B0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_bf_to_u8(
; CHECK-SAME: .reg .8b [[R8_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.bf.u8.dsat 	[[R16_R1]], [[R8_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call bfloat @llvm.pisa.uitofp.bf16.i8(i8 %a, i8 -1, i1 1)
  ret bfloat %res
}

define float @test_f32_to_u8(i8 %a) {
; O0-LABEL: .32b @test_f32_to_u8(
; O0-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.f.u8.dsat 	[[R32_W0]], [[R8_B0]];
; O0-NEXT: 	return [[R32_W0]];
;
; CHECK-LABEL: .32b @test_f32_to_u8(
; CHECK-SAME: .reg .8b [[R8_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.f.u8.dsat 	[[R32_R1]], [[R8_R0]];
; CHECK-NEXT: 	return [[R32_R1]];
  %res = call float @llvm.pisa.uitofp.f32.i8(i8 %a, i8 -1, i1 1)
  ret float %res
}

define double @test_f64_to_u8(i8 %a) {
; O0-LABEL: .64b @test_f64_to_u8(
; O0-SAME: .reg .8b [[R8_B0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.df.u8.dsat 	[[R64_D0]], [[R8_B0]];
; O0-NEXT: 	return [[R64_D0]];
;
; CHECK-LABEL: .64b @test_f64_to_u8(
; CHECK-SAME: .reg .8b [[R8_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.df.u8.dsat 	[[R64_R1]], [[R8_R0]];
; CHECK-NEXT: 	return [[R64_R1]];
  %res = call double @llvm.pisa.uitofp.f64.i8(i8 %a, i8 -1, i1 1)
  ret double %res
}

define half @test_hf_to_u16(i16 %a) {
; O0-LABEL: .16b @test_hf_to_u16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.u16.dsat 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
;
; CHECK-LABEL: .16b @test_hf_to_u16(
; CHECK-SAME: .reg .16b [[R16_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.u16.dsat 	[[R16_R1]], [[R16_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.uitofp.f16.i16(i16 %a, i8 -1, i1 1)
  ret half %res
}

define bfloat @test_bf_to_u16(i16 %a) {
; O0-LABEL: .16b @test_bf_to_u16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H1:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.bf.u16.dsat 	[[R16_H1]], [[R16_H0]];
; O0-NEXT: 	return [[R16_H1]];
;
; CHECK-LABEL: .16b @test_bf_to_u16(
; CHECK-SAME: .reg .16b [[R16_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.bf.u16.dsat 	[[R16_R1]], [[R16_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call bfloat @llvm.pisa.uitofp.bf16.i16(i16 %a, i8 -1, i1 1)
  ret bfloat %res
}

define float @test_f32_to_u16(i16 %a) {
; O0-LABEL: .32b @test_f32_to_u16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.f.u16.dsat 	[[R32_W0]], [[R16_H0]];
; O0-NEXT: 	return [[R32_W0]];
;
; CHECK-LABEL: .32b @test_f32_to_u16(
; CHECK-SAME: .reg .16b [[R16_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.f.u16.dsat 	[[R32_R1]], [[R16_R0]];
; CHECK-NEXT: 	return [[R32_R1]];
  %res = call float @llvm.pisa.uitofp.f32.i16(i16 %a, i8 -1, i1 1)
  ret float %res
}

define double @test_f64_to_u16(i16 %a) {
; O0-LABEL: .64b @test_f64_to_u16(
; O0-SAME: .reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.df.u16.dsat 	[[R64_D0]], [[R16_H0]];
; O0-NEXT: 	return [[R64_D0]];
;
; CHECK-LABEL: .64b @test_f64_to_u16(
; CHECK-SAME: .reg .16b [[R16_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.df.u16.dsat 	[[R64_R1]], [[R16_R0]];
; CHECK-NEXT: 	return [[R64_R1]];
  %res = call double @llvm.pisa.uitofp.f64.i16(i16 %a, i8 -1, i1 1)
  ret double %res
}

define half @test_hf_to_u32(i32 %a) {
; O0-LABEL: .16b @test_hf_to_u32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.u32.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_u32(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.u32.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.uitofp.f16.i32(i32 %a, i8 -1, i1 1)
  ret half %res
}

define bfloat @test_bf_to_u32(i32 %a) {
; O0-LABEL: .16b @test_bf_to_u32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.bf.u32.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_bf_to_u32(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.bf.u32.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call bfloat @llvm.pisa.uitofp.bf16.i32(i32 %a, i8 -1, i1 1)
  ret bfloat %res
}

define float @test_f32_to_u32(i32 %a) {
; O0-LABEL: .32b @test_f32_to_u32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.f.u32.dsat 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	return [[R32_W1]];
;
; CHECK-LABEL: .32b @test_f32_to_u32(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.f.u32.dsat 	[[R32_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R32_R1]];
  %res = call float @llvm.pisa.uitofp.f32.i32(i32 %a, i8 -1, i1 1)
  ret float %res
}

define double @test_f64_to_u32(i32 %a) {
; O0-LABEL: .64b @test_f64_to_u32(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.df.u32.dsat 	[[R64_D0]], [[R32_W0]];
; O0-NEXT: 	return [[R64_D0]];
;
; CHECK-LABEL: .64b @test_f64_to_u32(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.df.u32.dsat 	[[R64_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R64_R1]];
  %res = call double @llvm.pisa.uitofp.f64.i32(i32 %a, i8 -1, i1 1)
  ret double %res
}

define half @test_hf_to_u64(i64 %a) {
; O0-LABEL: .16b @test_hf_to_u64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.u64.dsat 	[[R16_H0]], [[R64_D0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_u64(
; CHECK-SAME: .reg .64b [[R64_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.u64.dsat 	[[R16_R1]], [[R64_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.uitofp.f16.i64(i64 %a, i8 -1, i1 1)
  ret half %res
}

define bfloat @test_bf_to_u64(i64 %a) {
; O0-LABEL: .16b @test_bf_to_u64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.bf.u64.dsat 	[[R16_H0]], [[R64_D0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_bf_to_u64(
; CHECK-SAME: .reg .64b [[R64_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.bf.u64.dsat 	[[R16_R1]], [[R64_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call bfloat @llvm.pisa.uitofp.bf16.i64(i64 %a, i8 -1, i1 1)
  ret bfloat %res
}

define float @test_f32_to_u64(i64 %a) {
; O0-LABEL: .32b @test_f32_to_u64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.f.u64.dsat 	[[R32_W0]], [[R64_D0]];
; O0-NEXT: 	return [[R32_W0]];
;
; CHECK-LABEL: .32b @test_f32_to_u64(
; CHECK-SAME: .reg .64b [[R64_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.f.u64.dsat 	[[R32_R1]], [[R64_R0]];
; CHECK-NEXT: 	return [[R32_R1]];
  %res = call float @llvm.pisa.uitofp.f32.i64(i64 %a, i8 -1, i1 1)
  ret float %res
}

define double @test_f64_to_u64(i64 %a) {
; O0-LABEL: .64b @test_f64_to_u64(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.df.u64.dsat 	[[R64_D1]], [[R64_D0]];
; O0-NEXT: 	return [[R64_D1]];
;
; CHECK-LABEL: .64b @test_f64_to_u64(
; CHECK-SAME: .reg .64b [[R64_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.df.u64.dsat 	[[R64_R1]], [[R64_R0]];
; CHECK-NEXT: 	return [[R64_R1]];
  %res = call double @llvm.pisa.uitofp.f64.i64(i64 %a, i8 -1, i1 1)
  ret double %res
}

define half @test_hf_to_s32_rtz(i32 %a) {
; O0-LABEL: .16b @test_hf_to_s32_rtz(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.s32.rz.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_s32_rtz(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.s32.rz.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.sitofp.f16.i32(i32 %a, i8 0, i1 1)
  ret half %res
}

define half @test_hf_to_s32_rne(i32 %a) {
; O0-LABEL: .16b @test_hf_to_s32_rne(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.s32.re.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_s32_rne(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.s32.re.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.sitofp.f16.i32(i32 %a, i8 1, i1 1)
  ret half %res
}

define half @test_hf_to_s32_rtp(i32 %a) {
; O0-LABEL: .16b @test_hf_to_s32_rtp(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.s32.ru.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_s32_rtp(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.s32.ru.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.sitofp.f16.i32(i32 %a, i8 2, i1 1)
  ret half %res
}

define half @test_hf_to_s32_rtn(i32 %a) {
; O0-LABEL: .16b @test_hf_to_s32_rtn(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.s32.rd.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_s32_rtn(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.s32.rd.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.sitofp.f16.i32(i32 %a, i8 3, i1 1)
  ret half %res
}

define bfloat @test_bf_to_s32_rtz(i32 %a) {
; O0-LABEL: .16b @test_bf_to_s32_rtz(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.bf.s32.rz.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_bf_to_s32_rtz(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.bf.s32.rz.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call bfloat @llvm.pisa.sitofp.bf16.i32(i32 %a, i8 0, i1 1)
  ret bfloat %res
}

define float @test_f32_to_s32_rtz(i32 %a) {
; O0-LABEL: .32b @test_f32_to_s32_rtz(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.f.s32.rz.dsat 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	return [[R32_W1]];
;
; CHECK-LABEL: .32b @test_f32_to_s32_rtz(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.f.s32.rz.dsat 	[[R32_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R32_R1]];
  %res = call float @llvm.pisa.sitofp.f32.i32(i32 %a, i8 0, i1 1)
  ret float %res
}

define double @test_f64_to_s32_rtz(i32 %a) {
; O0-LABEL: .64b @test_f64_to_s32_rtz(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.df.s32.rz.dsat 	[[R64_D0]], [[R32_W0]];
; O0-NEXT: 	return [[R64_D0]];
;
; CHECK-LABEL: .64b @test_f64_to_s32_rtz(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.df.s32.rz.dsat 	[[R64_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R64_R1]];
  %res = call double @llvm.pisa.sitofp.f64.i32(i32 %a, i8 0, i1 1)
  ret double %res
}

define float @test_f32_to_s64_rtz(i64 %a) {
; O0-LABEL: .32b @test_f32_to_s64_rtz(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.f.s64.rz.dsat 	[[R32_W0]], [[R64_D0]];
; O0-NEXT: 	return [[R32_W0]];
;
; CHECK-LABEL: .32b @test_f32_to_s64_rtz(
; CHECK-SAME: .reg .64b [[R64_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.f.s64.rz.dsat 	[[R32_R1]], [[R64_R0]];
; CHECK-NEXT: 	return [[R32_R1]];
  %res = call float @llvm.pisa.sitofp.f32.i64(i64 %a, i8 0, i1 1)
  ret float %res
}

define double @test_f64_to_s64_rtz(i64 %a) {
; O0-LABEL: .64b @test_f64_to_s64_rtz(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.df.s64.rz.dsat 	[[R64_D1]], [[R64_D0]];
; O0-NEXT: 	return [[R64_D1]];
;
; CHECK-LABEL: .64b @test_f64_to_s64_rtz(
; CHECK-SAME: .reg .64b [[R64_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.df.s64.rz.dsat 	[[R64_R1]], [[R64_R0]];
; CHECK-NEXT: 	return [[R64_R1]];
  %res = call double @llvm.pisa.sitofp.f64.i64(i64 %a, i8 0, i1 1)
  ret double %res
}

define half @test_hf_to_u32_rtz(i32 %a) {
; O0-LABEL: .16b @test_hf_to_u32_rtz(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.u32.rz.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_u32_rtz(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.u32.rz.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.uitofp.f16.i32(i32 %a, i8 0, i1 1)
  ret half %res
}

define half @test_hf_to_u32_rne(i32 %a) {
; O0-LABEL: .16b @test_hf_to_u32_rne(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.u32.re.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_u32_rne(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.u32.re.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.uitofp.f16.i32(i32 %a, i8 1, i1 1)
  ret half %res
}

define half @test_hf_to_u32_rtp(i32 %a) {
; O0-LABEL: .16b @test_hf_to_u32_rtp(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.u32.ru.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_u32_rtp(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.u32.ru.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.uitofp.f16.i32(i32 %a, i8 2, i1 1)
  ret half %res
}

define half @test_hf_to_u32_rtn(i32 %a) {
; O0-LABEL: .16b @test_hf_to_u32_rtn(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.hf.u32.rd.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_hf_to_u32_rtn(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.hf.u32.rd.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call half @llvm.pisa.uitofp.f16.i32(i32 %a, i8 3, i1 1)
  ret half %res
}

define bfloat @test_bf_to_u32_rtz(i32 %a) {
; O0-LABEL: .16b @test_bf_to_u32_rtz(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .16b [[R16_H0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.bf.u32.rz.dsat 	[[R16_H0]], [[R32_W0]];
; O0-NEXT: 	return [[R16_H0]];
;
; CHECK-LABEL: .16b @test_bf_to_u32_rtz(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .16b [[R16_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.bf.u32.rz.dsat 	[[R16_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R16_R1]];
  %res = call bfloat @llvm.pisa.uitofp.bf16.i32(i32 %a, i8 0, i1 1)
  ret bfloat %res
}

define float @test_f32_to_u32_rtz(i32 %a) {
; O0-LABEL: .32b @test_f32_to_u32_rtz(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W1:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.f.u32.rz.dsat 	[[R32_W1]], [[R32_W0]];
; O0-NEXT: 	return [[R32_W1]];
;
; CHECK-LABEL: .32b @test_f32_to_u32_rtz(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.f.u32.rz.dsat 	[[R32_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R32_R1]];
  %res = call float @llvm.pisa.uitofp.f32.i32(i32 %a, i8 0, i1 1)
  ret float %res
}

define double @test_f64_to_u32_rtz(i32 %a) {
; O0-LABEL: .64b @test_f64_to_u32_rtz(
; O0-SAME: .reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.df.u32.rz.dsat 	[[R64_D0]], [[R32_W0]];
; O0-NEXT: 	return [[R64_D0]];
;
; CHECK-LABEL: .64b @test_f64_to_u32_rtz(
; CHECK-SAME: .reg .32b [[R32_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.df.u32.rz.dsat 	[[R64_R1]], [[R32_R0]];
; CHECK-NEXT: 	return [[R64_R1]];
  %res = call double @llvm.pisa.uitofp.f64.i32(i32 %a, i8 0, i1 1)
  ret double %res
}

define float @test_f32_to_u64_rtz(i64 %a) {
; O0-LABEL: .32b @test_f32_to_u64_rtz(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .32b [[R32_W0:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.f.u64.rz.dsat 	[[R32_W0]], [[R64_D0]];
; O0-NEXT: 	return [[R32_W0]];
;
; CHECK-LABEL: .32b @test_f32_to_u64_rtz(
; CHECK-SAME: .reg .64b [[R64_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .32b [[R32_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.f.u64.rz.dsat 	[[R32_R1]], [[R64_R0]];
; CHECK-NEXT: 	return [[R32_R1]];
  %res = call float @llvm.pisa.uitofp.f32.i64(i64 %a, i8 0, i1 1)
  ret float %res
}

define double @test_f64_to_u64_rtz(i64 %a) {
; O0-LABEL: .64b @test_f64_to_u64_rtz(
; O0-SAME: .reg .64b [[R64_D0:%[-a-zA-Z$._0-9]+]]
; O0: 	.reg .64b [[R64_D1:%[-a-zA-Z$._0-9]+]];
; O0: 	i2f.df.u64.rz.dsat 	[[R64_D1]], [[R64_D0]];
; O0-NEXT: 	return [[R64_D1]];
;
; CHECK-LABEL: .64b @test_f64_to_u64_rtz(
; CHECK-SAME: .reg .64b [[R64_R0:%[-a-zA-Z$._0-9]+]]
; CHECK: 	.reg .64b [[R64_R1:%[-a-zA-Z$._0-9]+]];
; CHECK: 	i2f.df.u64.rz.dsat 	[[R64_R1]], [[R64_R0]];
; CHECK-NEXT: 	return [[R64_R1]];
  %res = call double @llvm.pisa.uitofp.f64.i64(i64 %a, i8 0, i1 1)
  ret double %res
}
